### PR TITLE
octave: vendor qscintilla2 for qt@5.7

### PR DESCRIPTION
**Pull request by dakcarto**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

See: https://github.com/Homebrew/homebrew-core/pull/10171

### CODE REVIEW

**Comment by dakcarto** [comment]
Failures seem to be false negatives.

```
==> Retrying download
Resource: qscintilla2
==> Downloading https://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz
==> Downloading from https://svwh.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz
Warning: Resource qscintilla2 reports different SHA256: 16be30577bc178470936c458551f2512cc068aff6e7a7de6ed244e28c045f6ec
Downloaded to: /home/travis/.cache/Homebrew/octave--qscintilla2-2.10.tar.gz
SHA256: 0fa26e565c169723e288b52de47a0cb6d838450b26d404726330adde3147eb4a
```
and
```
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/gnuplot-5.0.5.tar.gz
==> Verifying gnuplot-5.0.5.tar.gz checksum
Error: SHA256 mismatch
Expected: 25f3e0bf192e01115c580f278c3725d7a569eb848786e12b455a3fda70312053
Actual: 0fa26e565c169723e288b52de47a0cb6d838450b26d404726330adde3147eb4a
```

The SHA256 in both formulae are correct. Problems with SourceForge? Downloads page seems to load twice.

**Comment by ilovezfs** [comment]
I assume you mean false positives.

**Comment by dakcarto** [comment]
Yes, if positive means failure. Either way it is an incorrect error.

**Comment by dakcarto** [comment]
Also, note the Actual SHA256 is the same (from different checking systems):
0fa26e565c169723e288b52de47a0cb6d838450b26d404726330adde3147eb4a

Guessing that is some HTTP response, instead of a download archive.

**Comment by dakcarto** [comment]
@ilovezfs I see your point, I think. The error is correct, just indicates something amiss with upstream archive source.

**Comment by ilovezfs** [comment]
Yeah, 16be30577bc178470936c458551f2512cc068aff6e7a7de6ed244e28c045f6ec appears to be correct. Note that https://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz will request a mirror, so we sometimes get burned by a bad mirror/redirect/whatever.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
added silly commit to retrigger CI

**Comment by jonchang** [comment]
I like `git commit --allow-empty` to avoid having to undo my changes later :smile:

**Comment by dakcarto** [comment]
Ugh, same issue again (at least on Jenkins):
```
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/gnuplot-5.0.5.tar.gz
==> Verifying gnuplot-5.0.5.tar.gz checksum
Error: SHA256 mismatch
Expected: 25f3e0bf192e01115c580f278c3725d7a569eb848786e12b455a3fda70312053
Actual: 0fa26e565c169723e288b52de47a0cb6d838450b26d404726330adde3147eb4a
Archive: /Users/brew/Library/Caches/Homebrew/gnuplot-5.0.5.tar.gz
```

Seems to be using a pre-populated (and flawed) cache. Can that be cleared?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@sjackman is there a bug in Linuxbrew's test-bot? On CircleCI and Travis
```
==> brew bottle --verbose --json homebrew/science/octave
Error: Formula not installed or up-to-date: homebrew/science/octave
==> FAILED
```

**Comment by iMichka** [comment]
Same error as in #5192, see the discussion there

**Comment by ilovezfs** [comment]
@iMichka ok but octave built fine on linux just the other day.

**Comment by sjackman** [comment]
I think there's a bug in `brew` if both `linuxbrew/xorg/xorg` and `xorg` end up in the dependencies, it gets confused.

**Comment by sjackman** [comment]
Since octave depends on `gl2ps: OpenGL to PostScript printing library`, which depends on `:x11`, the hack work around is
```ruby
depends_on :x11 unless OS.linux?
```
It'd be great to fix the bug in `brew` though.

**Comment by sjackman** [comment]
@maxim-belkin I have a theory that in `linuxbrew/xorg/mesa` changing `depends_on "xorg"` to `depends_on :x11` would resolve this weird dependency duplicate bug.

**Comment by maxim-belkin** [comment]
@sjackman so.... let's change this! :)

**Comment by ilovezfs** [comment]
@sjackman are you suggesting this is a new bug that was introduced recently? As you know, a Linux octave bottle was built successfully on the 25th of February.

**Comment by maxim-belkin** [comment]
> As you know, a Linux octave bottle was built successfully on the 25th of February.

That was probably a glitch :D

**Comment by sjackman** [comment]
@ilovezfs I started seeing this bug in the last two weeks (roughly).

**Comment by ilovezfs** [comment]
@sjackman seems the `depends_on :x11 unless OS.linux?` doesn't help

**Comment by maxim-belkin** [comment]
@ilovezfs what @sjackman was suggesting is to change the dependency on `xorg` in `mesa` formula to `depends_on :x11`, not what you've tried

**Comment by ilovezfs** [comment]
OK. I think we're going to have to move on here without a Linux bottle since the pyqt5 PR in core is blocked on this.

**Comment by maxim-belkin** [comment]
Linuxbrew/homebrew-xorg#277

**Comment by sjackman** [comment]
Both `linuxbrew/xorg/xorg` and `xorg` and `linuxbrew/xorg/mesa` and `mesa` appear in the dependencies list. https://travis-ci.org/Homebrew/homebrew-science/builds/208593580#L1619
I think that situation needs to be figured out. If it's not resolved in `brew`, then a possible fix is to change every `"xorg"` to `:x11` and every `mesa` to `linuxbrew/xorg/mesa` in the repo `linuxbrew/xorg`.

**Comment by dakcarto** [comment]
@ilovezfs wrote:
> OK. I think we're going to have to move on here without a Linux bottle since the pyqt5 PR in core is blocked on this.
👍 

@sjackman, @maxim-belkin, what's your recommended path forward here?

**Comment by maxim-belkin** [comment]
we've merged the fix for `mesa` formula, so one could try a rebuild 😁

**Comment by sjackman** [comment]
I think it may also require changing
```ruby
depends_on "mesa"
```
to
```ruby
depends_on "linuxbrew/xorg/mesa"
```
in both `glu.rb` and `xdriinfo.rb`

**Comment by sjackman** [comment]
💚 Yeah, happy green light!

**Comment by ilovezfs** [comment]
Shipped! Thank you, @dakcarto (and @maxim-belkin and @sjackman)

**Pull request closed without merging**
