### PR TITLE
bamtools 2.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Revisions will be needed for the following formula:
augustus, reapr, sga

**Comment by ilovezfs** [comment]
Looks like `reapr` is already broken so the revision bump is going to mess this PR up.

**Comment by ilovezfs** [comment]
@sjackman :penguin:

**Pull request closed without merging**
