### PR TITLE
opencascade 7.0.0

### PR DESCRIPTION
**Pull request by quantumsteve**
This updates the opencascade formula to version 7.0.0. Updating the version number in the current url redirects to a login-page (see #3155). How has this issue been addressed in other formulas? Can homebrew host the source files? Currently I have it downloading the tarball from Arch Linux. 

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by ianrrees** [comment]
Just wanted to confirm that this worked great for me on OS 10.11.5.  Would be great to get it pulled in to homebrew-science!  Thanks!

**Comment by dpo** [comment]
@quantumsteve Could you hold off on bumping `dealii`? PETSc was updated recently, and it doesn't build any more (see #3730).

**Comment by quantumsteve** [comment]
@dpo I removed the revision bump on `dealii`

**Comment by dpo** [comment]
Thanks. `opencascade` builds but `gmsh` doesn't.

**Comment by quantumsteve** [comment]
The current master branch of gmsh successfully builds with OpenCascade 7.0. The simplest workaround is to change gmsh to build against oce, which is based on OpenCascade 6.8.

**Comment by dpo** [comment]
I'll ping @schoeps, who's been updating `gmsh`, for his opinion.

**Comment by schoeps** [comment]
I would prefer to backport the changes. It's quite confusing for the users if we change the dependencies back and forth. However, I cannot do the changes before next week.

**Comment by dpo** [comment]
That was also my impression. No rush. Thanks!

**Comment by schoeps** [comment]
You can find an update for gmsh.rb (12.12.0) here: https://gist.github.com/schoeps/3a8b758c007629febd89948c0a856bd9

I disabled the Salome features since they did not work for me with 12.12.0. I guess we can switch them on when 12.12.1 is ready since HEAD is working fine.

**Comment by dpo** [comment]
@quantumsteve Would you mind including @schoeps's changes into your PR? The patched formula builds for me, though not `--with-petsc`.

**Comment by schoeps** [comment]
@dpo Same problem with petsc here but patching was not so obvious and it will be fixed in the next release anyhow....

**Comment by quantumsteve** [comment]
@schoeps I had to change `stable do` to `if build.stable?` in order to disable Salome and successfully build gmsh.

@dpo The audit warnings from gmsh are fixed.

**Comment by dpo** [comment]
@quantumsteve `gmsh` was just updated. Would you mind rebasing and removing `gmsh` from this PR? Sorry for the hassle and the long wait.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Many thanks for your patience!

**Pull request closed without merging**
