### PR TITLE
augustus 3.3

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI
```
==> brew linkage --test homebrew/science/augustus
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Missing libraries:
  libbamtools.so.2.4.0
No unwanted system libraries
```
https://travis-ci.org/Homebrew/homebrew-science/builds/268174243#L3163

**Comment by sjackman** [comment]
`bamtools` provides `libbamtools.so.2.4.1` not `libbamtools.so.2.4.0`

**Comment by sjackman** [comment]
The bundled binary executables are linked against `libbamtools.so.2.4.0`.
```
auxprogs/bam2hints/bam2hints
auxprogs/filterBam/src/filterBam
bin/bam2hints
bin/filterBam
```

**Comment by tseemann** [comment]
```
% find . -name Makefile -exec grep -H -i bamtools {} \;

./filterBam/src/Makefile:BAMTOOLS = /usr/include/bamtools
./filterBam/src/Makefile:INCLUDES = -I$(BAMTOOLS) -Iheaders -I./bamtools
./filterBam/src/Makefile:LIBS = -lbamtools -lz
./filterBam/src/Makefile:       @if [ -z "${BAMTOOLS}" ]; then \
./filterBam/src/Makefile:               echo '[Makefile]: $${BAMTOOLS} has not been set.'; \
./filterBam/src/Makefile:       elif [ "${BAMTOOLS}" ]; then \
./filterBam/src/Makefile:               echo "filterBam compiled with BAMTOOLS=${BAMTOOLS}"; \
./bam2hints/Makefile:#  b) libbamtools.a and lz library are used during the linking process
./bam2hints/Makefile:INCLUDES = /usr/include/bamtools
./bam2hints/Makefile:LIBS = -lbamtools -lz
```

**Comment by sjackman** [comment]
The magic of `superenv` should add the necessary `-I` and `-L` options for `bamtools`. This formula does need to delete the precompiled binary executables and rebuild them.

**Pull request closed without merging**
