### PR TITLE
masurca 3.1.3

### PR DESCRIPTION
**Pull request by sjackman**
masurca 3.1.3 does not build on Mac OS, which is missing the required function mremap.

```
sort.cc:62:75: error: 'mremap' was not declared in this scope
         void*  new_ptr  = mremap(fd.ptr, fd.size, new_size, MREMAP_MAYMOVE);
```

### CODE REVIEW

**Comment by sjackman** [comment]
```
tar xzf /home/ubuntu/.cache/Homebrew/masurca-3.1.3.tar.gz
tar: Removing leading `/' from member names
==> ./install.sh
....
Error: No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/include/jellyfish-2.1.3
==> FAILED
```

**Comment by ilovezfs** [comment]
Yeah the jobs and bottles get deleted after like a week. As you can see it's gone: https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5126/

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@tseemann you should be able to pull now.

**Comment by tseemann** [comment]
@ilovezfs It's been 4 days, is that too late again?
```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/3802
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-science/pull/3802.patch
==> Applying patch
Applying: masurca 3.1.3
==> Patch closes issue #3802
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-3802
```

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Audit warnings, but otherwise succeeded.
```
==> brew audit homebrew/science/masurca
Error: 1 problem in 1 formula
homebrew/science/masurca:
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/fix_unitigs.sh
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/run_ECR.sh
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/MasurcaConf.pm
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/MasurcaCommon.pm
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/MasurcaCelera.pm
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/MasurcaSoap.pm
      /home/linuxbrew/.linuxbrew/Cellar/masurca/3.1.3/bin/MasurcaSuperReads.pm
==> FAILED
```

**Comment by sjackman** [comment]
Merged!

**Pull request closed without merging**
