### PR TITLE
quicktree 2.0

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
I don't understand what happened? 
Some other packaged called `phlawd` is in my build failure?

```
Error Message

failed: brew test --verbose phlawd
Stacktrace

        Testing homebrew/science/phlawd
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170409-64441-1vfk7a9.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/phlawd.rb --verbose
==> /usr/local/Cellar/phlawd/3.4a_2/bin/PHLAWD
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/phlawd/3.4a_2/bin/PHLAWD
  Reason: image not found
Error: homebrew/science/phlawd: failed
<0> expected but was
<nil>.
```

**Comment by ilovezfs** [comment]
Yes, reverse dependencies are tested by test-bot.

```
$ brew deps phlawd
mafft
muscle
openssl
quicktree
readline
sqlite
wget
```

```
$ brew uses quicktree
homebrew/science/phlawd
```

**Comment by ilovezfs** [comment]
If you rebase and force push, it should be fixed now.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@ilovezfs @jonchang thanks!  i no longer have homebrew-science access, plus `brew --pull` never works properly for me anyway, so if you could merge this that would be great.

**Comment by jonchang** [comment]
Merged. Thanks @tseemann.

**Pull request closed without merging**
