### PR TITLE
nco: revision for gsl

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> ==> Downloading https://downloads.sourceforge.net/project/nco/nco-4.6.7.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/nco-4.6.7.tar.gz
==> Verifying nco-4.6.7.tar.gz checksum
Error: SHA256 mismatch
Expected: 6b9297093e38e29a7b44f263f67aa0e728052d947338bbb1f6fc2a4cc4b910c6
Actual: 2fe2dabf14a60bface694307cbe719df57103682b715348e9d77bfe8d31487f3
Archive: /Users/brew/Library/Caches/Homebrew/nco-4.6.7.tar.gz

**Comment by iMichka** [comment]
I sent an email to their mailing list.

**Comment by iMichka** [comment]
Reported on their issue tracker too: https://github.com/nco/nco/issues/59

**Comment by czender** [comment]
The "Actual" SHA256 above is the correct NCO 4.6.7 source code. Sorry for the trouble.

**Comment by iMichka** [comment]
@czender Thanks for the fast answer. I updated the sha sum.

**Comment by iMichka** [comment]
Done that:
> * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.

Ignoring Linux build error. We need an `antlr@2` Linux bottle first.

**Pull request closed without merging**
