### PR TITLE
tabix (modernize + test)

### PR DESCRIPTION
**Pull request by tseemann**

### CODE REVIEW

**Comment by tseemann** [comment]
```
        ==> Installing tabix from homebrew/homebrew-science
==> Downloading https://downloads.sourceforge.net/project/samtools/tabix/tabix-0.2.6.tar.bz2
Already downloaded: /Library/Caches/Homebrew/tabix-0.2.6.tar.bz2
==> Verifying tabix-0.2.6.tar.bz2 checksum
tar xf /Library/Caches/Homebrew/tabix-0.2.6.tar.bz2
==> make
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  bgzf.c -o bgzf.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  kstring.c -o kstring.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  knetfile.c -o knetfile.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  index.c -o index.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  bedidx.c -o bedidx.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  main.c -o main.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE -DBGZF_CACHE  bgzip.c -o bgzip.o
gcc -g -Wall -O2 -fPIC  -o bgzip bgzip.o bgzf.o knetfile.o -lz
ar -csru libtabix.a bgzf.o kstring.o knetfile.o index.o bedidx.o
gcc -g -Wall -O2 -fPIC  -o tabix main.o -L. -ltabix -lm  -lz
Error: No such file or directory - gzip
```

**Comment by andrewjpage** [comment]
How about deleting it altogether or making it just have a dependancy on htslib?   The reapr dependancy should be fixable.

**Comment by tseemann** [comment]
I hadn't considered just making 'tabix' depend on 'htslib' and that's it.
Will ask on Issues page.

**Comment by tseemann** [comment]
I'm closing this, it is defunct.

**Pull request closed without merging**
