### PR TITLE
xraylib: remove make check

### PR DESCRIPTION
**Pull request by tschoonj**
it fails on El Capitan for ruby, perl and python due to SIP...

### CODE REVIEW

**Comment by dpo** [comment]
If the check fails, isn't that indicative of a problem with the software?

**Comment by tschoonj** [comment]
Nope it's indicative of SIP :smile: 

The tests rely on the use of `DYLD_LIBRARY_PATH` in order to find libraries that were compiled. However, SIP doesn't allow this variable to be processed by executable residing in `/usr/bin`, including the system ruby, perl, python and others... Fortunately the installed software works fine since it relies on hardcoded paths to the libraries.

**Comment by dpo** [comment]
Ok. Please bump the revision number.

**Comment by tschoonj** [comment]
No need for that in this case I think. This only affects people who provided certain options when installing xraylib. There is no need for people with a successful installation to update.

**Comment by tschoonj** [comment]
@dpo Could you please merge this one in? Thanks!

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
