### PR TITLE
opencv: Add Python3 module

### PR DESCRIPTION
**Pull request by davll**
The PR enables opencv to build Python 3 binding

### CODE REVIEW

**Comment by iml** [comment]
Is this for the `devel` version? I don't see these these options in CMakeLists.
```
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON2_EXECUTABLE
    PYTHON2_INCLUDE_DIR
    PYTHON2_LIBRARY
    PYTHON3_EXECUTABLE
    PYTHON3_INCLUDE_DIR
    PYTHON3_LIBRARY

**Comment by davll** [comment]
Yep, these options are for OpenCV 3.x (devel) version.

**Comment by iml** [comment]
Then this needs to be updated so a) it actually works under devel, which has since been added, and b) doesn't impact the existing python2 bindings in stable.

**Comment by dpo** [comment]
Closing as `opencv3` now has optional Python 3 bindings.

**Pull request closed without merging**
