### PR TITLE
tamarin-prover 1.2.2

### PR DESCRIPTION
**Pull request by lordqwerty**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
I relaunched the mac build, it failed due to a problem on our side.
The linux build fails with:

> Invalid argument `install --flag tamarin-prover:threaded'
File does not exist or is not a regular file `-j1'

**Comment by lordqwerty** [comment]
Can someone please confirm the fail is a result of the CI? All passes on Linux.

**Comment by iMichka** [comment]
Yes, we have a CI bug. Once https://github.com/Homebrew/brew/pull/2718 is merged, I'll re-trigger a build here.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@lordqwerty The bot ran and you have this error:
> homebrew/science/tamarin-prover:
  * C: 33: col 122: Trailing whitespace detected.

Could you remove the whitespace, amend your commit, and force-push your changes to your branch? Thanks.

**Comment by lordqwerty** [comment]
now resolved. Many thanks for your assistance.

**Comment by iMichka** [comment]
@lordqwerty Thanks for your contribution!

**Pull request closed without merging**
