### PR TITLE
bowtie2 2.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
1.00s==> brew audit homebrew/science/bowtie2
Error: 1 problem in 1 formula
homebrew/science/bowtie2:
  * fully scope test system calls e.g. system "#{bin}/bowtie2-build"
==> FAILED
```
https://travis-ci.org/Homebrew/homebrew-science/builds/186293172#L1603

**Comment by sjackman** [comment]
```
Error running:
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/bam2fastx --all ./tophat_out/tmp/left_kept_reads.bam|/home/linuxbrew/.linuxbrew/bin/bowtie2 -k 20 -D 15 -R 2 -N 0 -L 20 -i S,1,1.25 --gbar 4 --mp 6,2 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-14,0 -p 1 --sam-no-hd -x /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref -|/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/fix_map_ordering --bowtie2-min-score 15 --read-mismatches 2 --read-gap-length 2 --read-edit-dist 2 --read-realign-edit-dist 3 --index-outfile ./tophat_out/tmp/left_kept_reads.mapped.bam.index --sam-header ./tophat_out/tmp/test_ref_genome.bwt.samheader.sam - ./tophat_out/tmp/left_kept_reads.mapped.bam ./tophat_out/tmp/left_kept_reads_unmapped.bam
Error: homebrew/science/tophat: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/tophat -r 20 /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_1.fq /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_2.fq
```
https://travis-ci.org/Homebrew/homebrew-science/builds/186293172#L2614

**Comment by ilovezfs** [comment]
@sjackman tophat test seems to have been failing ever since https://github.com/BenLangmead/bowtie2/commit/d6d4a1deae4535408129c5e9c5d49c1d390e23c5.

**Comment by sjackman** [comment]
@BenLangmead Hi, Ben. Do you have any insight as to why TopHat 2.1.1 fails with Bowtie 2.3.0 in this CI test?
https://travis-ci.org/Homebrew/homebrew-science/builds/186293172#L2610

**Comment by BenLangmead** [comment]
We are looking into this now

**Comment by iMichka** [comment]
@BenLangmead any progress on this?

**Comment by BenLangmead** [comment]
Yes, we know what the issue is.  Bowtie 2 2.3.0, unlike earlier versions, will throw an error if it discovers that the input reads file is empty.  That seemed like a innocuous, rare case, but we didn't realize that TopHat depends on Bowtie 2 not failing; TopHat intentionally runs Bowtie 2 with an empty read file in order to get SAM headers that it later prepends to another SAM file.

So that's the issue -- it won't be fixed on the TopHat side anytime soon so we're planning to fix it in the next Bowtie 2 release, which I expect in March.

**Comment by iMichka** [comment]
Thanks for the quick answer. So there is not quickfix for this? A temporary patch would be welcome, so that we could get this version upgrade merged the time being.

**Comment by BenLangmead** [comment]
Let me defer that to @ch4rr0

**Comment by ch4rr0** [comment]
I committed a change to resolve the issue to the master branch. There were a few commits made prior, but they should not impact CI checks.

**Comment by sjackman** [comment]
@ch4rr0 Can you point us to the particular commit on GitHub that resolves this issue? We'll cherry-pick that one commit as a patch against bowtie2 2.3.0.

**Comment by ch4rr0** [comment]
https://github.com/BenLangmead/bowtie2/commit/2e9b9601489189d0795d8a57df90e319762263d2

**Comment by sjackman** [comment]
Thanks!

**Comment by ilovezfs** [comment]
Good news: We now have :green_apple: on Jenkins.

Bad news: Circle CI failed due to a broken tophat bottle:
```
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2: 49 files, 41.3M
==> brew linkage --test tophat
Missing libraries:
  libboost_system-mt.so.1.62.0
  libboost_thread-mt.so.1.62.0
==> FAILED
==> brew test --verbose tophat
Testing homebrew/science/tophat
==> /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/tophat -r 20 /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_1.fq /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_2.fq
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/tophat/test.01.tophat:
2017-02-17 18:59:29 +0000

/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/tophat
-r
20
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_1.fq
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_2.fq


[2017-02-17 18:59:30] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2017-02-17 18:59:30] Checking for Bowtie
		  Bowtie version:	 2.2.9.0
[2017-02-17 18:59:30] Checking for Bowtie index files (genome)..
	Found both Bowtie1 and Bowtie2 indexes.
[2017-02-17 18:59:30] Checking for reference FASTA file
[2017-02-17 18:59:30] Generating SAM header for /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref
[2017-02-17 18:59:30] Preparing reads
	 left reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
	right reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
[2017-02-17 18:59:30] Mapping left_kept_reads to genome test_ref with Bowtie2 
[2017-02-17 18:59:30] Mapping left_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-02-17 18:59:30] Mapping left_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-02-17 18:59:30] Mapping left_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-02-17 18:59:30] Mapping right_kept_reads to genome test_ref with Bowtie2 
[2017-02-17 18:59:30] Mapping right_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-02-17 18:59:30] Mapping right_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-02-17 18:59:30] Mapping right_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-02-17 18:59:30] Searching for junctions via segment mapping
	[FAILED]
Error: segment-based junction search failed with err =127
/home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/segment_juncs: error while loading shared libraries: libboost_thread-mt.so.1.62.0: cannot open shared object file: No such file or directory

Error: homebrew/science/tophat: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/bin/tophat -r 20 /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/test_ref /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_1.fq /home/linuxbrew/.linuxbrew/Cellar/tophat/2.1.1_2/share/test_data/reads_2.fq
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1834:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1772:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1772:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-science/tophat.rb:48:in `block in <class:Tophat>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1671:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:884:in `with_logging'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1670:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1664:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by sjackman** [comment]
Do you want to bump `tophat` in this PR to rebuild the Linuxbrew bottle, or merge this PR and then I'll fix the `tophat` bottle in a new PR?

**Comment by ilovezfs** [comment]
@sjackman I did the tophat revision bump first in https://github.com/Homebrew/homebrew-science/pull/5161 and https://github.com/Homebrew/homebrew-science/pull/5162), so we now have :green_apple: on Jenkins and Circle. The Travis failure is the same old trouble we've had for a while building `express` on Travis so can be ignored.

**Pull request closed without merging**
