### PR TITLE
Master

### PR DESCRIPTION
**Pull request by carcus88**
Moved from gtksourceview to gtksourceview3 since PSPP is now built with
GTK3

### CODE REVIEW

**Comment by carcus88** [comment]
Shoot I submitted too soon...

**Comment by dpo** [comment]
Please update #3487 instead of opening a new PR.

**Comment by carcus88** [comment]
Sorry yes I realized that and thats why I closed. Not sure what the workflow is for updating a PR. Sorry about that.

**Comment by dpo** [comment]
Any commit you'll add to the local branch you used to submit your PR will appear in #3487.

**Pull request closed without merging**
