### PR TITLE
pspp 0.11.0

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> homebrew/science/pspp:
>  * Stable: Please use "https://ftp.gnu.org/gnu/pspp/pspp-0.10.2.tar.gz" instead of https://ftpmirror.gnu.org/pspp/pspp-0.10.2.tar.gz.

**Comment by iMichka** [comment]
Blocked on Linux by: `Error: gtk+3 3.22.16 did not build`

See https://github.com/Linuxbrew/homebrew-core/pull/3031

**Comment by ilovezfs** [comment]
@iMichka 0.11.0 is out if you want to refresh this.

**Comment by iMichka** [comment]
Thank. I think we have now a gtk3 bottle on Linux, so this should work.

**Pull request closed without merging**
