### PR TITLE
tensorflow 1.0.1 (new formula)

### PR DESCRIPTION
**Pull request by tnayuki**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [X] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by toru-unity** [comment]
Should I make the test on Linux passed?

**Comment by tnayuki** [comment]
Do I have to make the test passed also on Linux

**Comment by tnayuki** [comment]
Do I have to make the test passed also on Linux?

**Comment by iMichka** [comment]
Hi. Thanks for your contribution. It would be great to get the Linux build working too, especially for a new formula.

Also, did you consider adding support for python3 (though that can also be done later in a second PR).

The error is happening during the bazel build:
> ERROR: /tmp/bazel-20170406-41640-1ikqf7t/src/main/tools/BUILD:28:1: C++ compilation of rule '//src/main/tools:linux-sandbox' failed: gcc-5 failed: error executing command 
  (cd /tmp/bazel_kIGAuq4T/out/execroot/bazel-20170406-41640-1ikqf7t && \
  exec env - \
 PATH=/home/linuxbrew/.linuxbrew/opt/jdk/bin:/home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/unzip/bin:/home/linuxbrew/.linuxbrew/opt/jdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/linuxbrew/.linuxbrew/opt/gcc/bin \
    TMPDIR=/tmp \
  /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5 -U_FORTIFY_SOURCE -fstack-protector -Wall -B/home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/src/main/tools/_objs/linux-sandbox/src/main/tools/linux-sandbox-options.d '-frandom-seed=bazel-out/local-opt/bin/src/main/tools/_objs/linux-sandbox/src/main/tools/linux-sandbox-options.o' -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/tools/linux-sandbox-options.cc -o bazel-out/local-opt/bin/src/main/tools/_objs/linux-sandbox/src/main/tools/linux-sandbox-options.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc-5: The build tool has reset ENV; --env=std required.

**Comment by sjackman** [comment]
Superenv passes build options from `brew` to `shims/super/cc` through environment variables, `HOMEBREW_RUBY_PATH`. If that environment variable is not set when `shims/super/cc` runs, it reports the error message `The build tool has reset ENV; --env=std required.` It's odd that you don't see this error on macOS, but do see it on Linuxbrew. It'd be great to figure out the root cause, but a workaround would be
```ruby
env :std if OS.linux?
```

**Comment by iMichka** [comment]
We should try to get bazel to build on Linux. @tnayuki a PR would be welcome here: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/bazel.rb

**Comment by tnayuki** [comment]
Hi! It seems that the problem will be resolved on the next version of bazel as far as seeing this change.
 
https://github.com/bazelbuild/bazel/commit/6326f98ed84c2e0677b552cd4af808d482e8749c#diff-94b0616c37dae10d1639d83278a05bb6

**Comment by sjackman** [comment]
@tnayuki That commit is not quite enough.

> White listing just `HOMEBREW_RUBY_PATH` isn't sufficient. All environment variables starting with `HOMEBREW_` need to be white listed. The current list is:
```
HOMEBREW_ARCHFLAGS HOMEBREW_CC HOMEBREW_CCCFG HOMEBREW_CC_LOG_PATH HOMEBREW_CELLAR HOMEBREW_DEPENDENCIES HOMEBREW_EXPERIMENTAL_FILTER_FLAGS_ON_DEPS HOMEBREW_FORMULA_PREFIX HOMEBREW_INCLUDE_PATHS HOMEBREW_ISYSTEM_PATHS HOMEBREW_LIBRARY_PATHS HOMEBREW_OPT HOMEBREW_OPTFLAGS HOMEBREW_OPTIMIZATION_LEVEL HOMEBREW_PREFIX HOMEBREW_RPATH_PATHS HOMEBREW_RUBY_PATH HOMEBREW_TEMP
```

**Comment by tnayuki** [comment]
Thanks @sjackman 
So will try to patch when new bazel is released.

**Comment by tnayuki** [comment]
And I added support for python3, @iMichka

**Comment by sjackman** [comment]
@tnayuki Why are you closing and reopening this issue?

**Comment by toru-unity** [comment]
@sjackman Sorry, I'd like to try rebuilding on sierra node to know whether Xcode updated or not on it .

**Comment by tnayuki** [comment]
@sjackman Sorry, I'd like to try rebuilding on sierra node to know whether Xcode updated or not on it .

**Comment by ilovezfs** [comment]
Yes Jenkins has been updated.

**Comment by sjackman** [comment]
> Sorry, I'd like to try rebuilding on sierra node to know whether Xcode updated or not on it .

Does closing and reopening the issue trigger a rebuild on Jenkins? It doesn't on CircleCI or TravisCI.

**Comment by tnayuki** [comment]
@sjackman I think it did on Jenkins. I saw this stackflow...
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by tnayuki** [comment]
By the way, I added python3 support, so please merge if only for macOS as now is OK.
> Also, did you consider adding support for python3 (though that can also be done later in a second PR).

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
TravisCI
```
gcc-5: The build tool has reset ENV; --env=std required.
```
https://travis-ci.org/Homebrew/homebrew-science/builds/224626142#L2212

**Comment by sjackman** [comment]
CircleCI has the same failure.
```
gcc-4.8: The build tool has reset ENV; --env=std required.
```
https://circleci.com/gh/Homebrew/homebrew-science/4275

**Comment by sjackman** [comment]
Without looking into the failure further and figuring out the proper solution to make `--env=super` work, the work around would be:
```ruby
# Work around the error: The build tool has reset ENV; --env=std required.
env :std if OS.linux?
```

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@tnayuki I merged this as-is for now, so that the formula is added. I see there were some updates to tensor flow, a new pull request is welcome if you want to make a version bump :)

@sjackman I skipped the Linux integration here to not delay the merge forever. A second pass can be done by some volunteers later, if somebody needs this.

**Comment by tnayuki** [comment]
> I see there were some updates to tensor flow

Will look
Thanks @iMichka

**Pull request closed without merging**
