### PR TITLE
nonpareil v2.4.01

### PR DESCRIPTION
**Pull request by lmrodriguezr**
Closes #2280.

### CODE REVIEW

**Comment by dunn** [comment]
Looks good but for a nitpick from the bot:
```
        Error: 2 problems in 1 formula
homebrew/science/nonpareil:
 * 5: Trailing whitespace was found
 * 8: Trailing whitespace was found
```

**Comment by dpo** [comment]
Does this also fix #2559?

**Comment by lmrodriguezr** [comment]
This change removes the bottle because it's a different base version, but I don't know if an eventual (new) bottle would have the same problem. Is there a way to (1) add libraries in other packages from within a bottle, or (2) avoid bottle creation?

**Comment by dpo** [comment]
Where is the r package supposed to be installed?

**Comment by lmrodriguezr** [comment]
That's directly controlled by R. This formula requires the r formula, but it could be superseded by another R executable happening first in the PATH. Even if the r formula is being used, it can go to the Cellar or to a folder like `~/Library/R/3.2/library` (if it exists).

This is the line installing the R library: `$(R) CMD INSTALL utils/Nonpareil` (https://github.com/lmrodriguezr/nonpareil/blob/master/Makefile#L45).

**Comment by dpo** [comment]
In that case the r package probably ends up somewhere in r's folder structure or a user folder and there's no reason it should  be part of the `nonpareil` bottle. Perhaps it should be made `:optional`.

**Comment by lmrodriguezr** [comment]
But the nonpareil results are nearly meaningless without the R package, so a regular user experience installing Nonpareil from Homebrew would involve manually downloading the code from github just to install the R package. Alternatively, it would involve using the `--build-from-source` flag, in which case not bottling nonpareil would be a better solution than telling the users to build from source in the formula caveats.

**Comment by sjackman** [comment]
> This change removes the bottle because it's a different base version

Don't remove the bottle lines. Bottles are rebuilt automatically by the BrewTestBot.

**Comment by lmrodriguezr** [comment]
So should I revert the bottle removal and continue the bug discussion over at #2559 ?

**Comment by dpo** [comment]
Yes.

**Pull request closed without merging**
