### PR TITLE
links-scaffolder 1.6.1

### PR DESCRIPTION
**Pull request by warrenlr**
### Have you:
- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [ ] Written a sensible test? (The best test is to compile and run a sample program.)
### Updates to existing formula: have you
- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

Update to the formula, point to the latest stable release (v1.6.1)

### CODE REVIEW

**Comment by warrenlr** [comment]
I am trying to update the sha256 sum for links v1.6.1 but in vain
The digest should have read:

c4fa4f39dbee49c484521a80738758a39dc21b4a594d3e3fcf231d4decfdbe97

Could you edit the formula and re-commit?
my bad.
Rene

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Hi @warrenlr, it looks like there's a new version of links-scaffolder (1.8.3). Also, all new versions of links-scaffolder past 1.6.1 will not work on OS X since the compiled XS extensions for the BloomFilter module were built on Linux. You will need to update the formula to follow the install instructions included in links-scaffolder so that OS X users can get it compiled properly.

**Comment by sjackman** [comment]
Superseded by #4726

**Pull request closed without merging**
