### PR TITLE
Update neuron simulator formula sha256 hash

### PR DESCRIPTION
**Pull request by wvangeit**
### Have you:

- [ x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. We would need an explanation from upstream why the sha256 has changed. This could mean that the source file was modified, which is a potential security breach. Worst-case scenario is that a hacker has modified the file on the server.

**Comment by nrnhines** [comment]
The changes between 
http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/v7.4.rel-1341/nrn-7.4.rel-1351.tar.gz
and
http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/v7.4.rel-1370/nrn-7.4.rel-1370.tar.gz
are bug fixes.

**Comment by iMichka** [comment]
But the file we are downloading is `https://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz`. And that file changed. This is rather ... unexpected.

We should then use the `rel-1370.tar.gz` file. Then the version will be `7.4.rel-1370` when you call `brew info neuron`

**Comment by ilovezfs** [comment]
https://www.neuron.yale.edu/ftp/neuron/versions/v7.4/v7.4.rel-1341/nrn-7.4.rel-1351.tar.gz still has the original checksum.

**Comment by iMichka** [comment]
This is why I would prefer to use:
http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/v7.4.rel-1370/nrn-7.4.rel-1370.tar.gz

which is the new version.

**Comment by wvangeit** [comment]
@iMichka I've updated the branch to point to the url of the specific release

**Comment by iMichka** [comment]
The mac build fails with
```
Examine config.log to see error details. Something wrong with
	PYLIB=-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -llibpython2.7.dylib -ldl  -framework CoreFoundation -R/System/Library/Frameworks/Python.framework/Versions/2.7/lib
or
	PYLIBDIR=/System/Library/Frameworks/Python.framework/Versions/2.7/lib
or
	PYLIBLINK=-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -llibpython2.7.dylib -ldl  -framework CoreFoundation
or
```

**Comment by wvangeit** [comment]
Is there any chance we could investigate the config.log ? (I can't reproduce this error on my machine)

**Comment by iMichka** [comment]
I can reproduce it. I use brewed python; which is the python I have in my PATH.
Here is the config.log file:
https://gist.github.com/iMichka/5f78b0d47455875ba3fb38dfeff7bf20

Seems others already had this problem:
https://www.neuron.yale.edu/phpbb/viewtopic.php?f=2&t=1493

**Comment by wvangeit** [comment]
Do you also have python-config of the brewed python in your path ?
The strange thing is that the configure seems to pick up the system python:
https://gist.github.com/iMichka/5f78b0d47455875ba3fb38dfeff7bf20#file-neuronconfig-log-L4075
https://gist.github.com/iMichka/5f78b0d47455875ba3fb38dfeff7bf20#file-neuronconfig-log-L4078

**Pull request closed without merging**
