### PR TITLE
masurca 3.2.3

### PR DESCRIPTION
**Pull request by wookoouk**

### CODE REVIEW

**Comment by sjackman** [comment]
The preferred commit log message is `masurca 3.2.3`

**Comment by sjackman** [comment]
```
g++-5: internal compiler error: Killed (program cc1plus)
```
https://circleci.com/gh/Homebrew/homebrew-science/6810

That usually means that it exceeded the 4 GB memory limit of CircleCI.
Try adding the following line at the top of `def install` to see if that works around the issue.
```ruby
# Reduce memory usage for CircleCI.
ENV["MAKEFLAGS"] = "-j4" if ENV["CIRCLECI"]
```

See for example
https://github.com/Homebrew/homebrew-science/blob/master/cufflinks.rb#L27

**Comment by sjackman** [comment]
Please update this PR rather than opening a new PR with your changes.

**Comment by wookoouk** [comment]
Sorry, didnt know how to update.

**Comment by sjackman** [comment]
Same problem even with `ENV["MAKEFLAGS"] = "-j4"`.
```
g++-5: internal compiler error: Killed (program cc1plus)
```
https://circleci.com/gh/Homebrew/homebrew-science/6812

I just noticed that the formula had
```ruby
ENV.deparallelize
```
You may want to try adding that back in (and removing (`ENV["MAKEFLAGS"] = "-j4"`).

**Comment by sjackman** [comment]
TravisCI reports…
```
brew linkage --test homebrew/science/masurca
Missing libraries:
  libjellyfish-2.0.so.2
Possible unnecessary dependencies:
  boost
No unwanted system libraries
```
Looks like you need…
```ruby
depends_on "boost" => :build
depends_on "jellyfish"
```

**Comment by sjackman** [comment]
```
brew audit masurca
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/opt/masurca/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/opt/masurca/bin/fix_unitigs.sh
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaConf.pm
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaSuperReads.pm
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaSoap.pm
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/run_ECR.sh
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaCelera.pm
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaPaths.pm
            /home/linuxbrew/.linuxbrew/opt/masurca/bin/MasurcaCommon.pm
```
This problem is preexisting. We'll punt it to another day.

**Comment by sjackman** [comment]
For future PRs, the preferred short commit log message is…
```
masurca 3.2.3
```
Put whatever you like in the detailed comments below.

**Comment by wookoouk** [comment]
Sorry, will do in future, will look into this issue further after the new
year.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Homebrew/science, Martin!

**Comment by sjackman** [comment]
Note that this tap Homebrew/science is being retired at the end of the year. The next release can move to https://github.com/Linuxbrew/homebrew-bio/

**Comment by wookoouk** [comment]
I thought it didn't install on the VM? Why was it merged?

**Comment by sjackman** [comment]
It did install. CI was ❌ because of the `brew audit` failure above. A preexisting failure, but it would be good to fix it. The fix is pretty simple, install into `libexec` rather than `prefix`, then symlink the main executable into `bin`.

**Pull request closed without merging**
