### PR TITLE
[pcl] Fix boost 1.57

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/Homebrew/homebrew-science/issues/1624. Upstream patch https://github.com/PointCloudLibrary/pcl/pull/1062

### CODE REVIEW

**Comment by fran6co** [comment]
It's erroring because it takes too long.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
It doesn't seem to be building `vtk` `--with-qt` because the `sip` dependency isn't taken into account.

**Comment by fran6co** [comment]
Isn't that an issue of vtk?

**Comment by fran6co** [comment]
Weird, it has that option => https://github.com/Homebrew/homebrew-science/blob/master/vtk.rb#L47

**Comment by fran6co** [comment]
It looks like it's using sip even without "--with-python"

**Comment by fran6co** [comment]
What is blocking this PR? The errors in the build are not because of this formula.

**Comment by dpo** [comment]
First we have to resolve the problem.

**Comment by fran6co** [comment]
Found the problem, it's deep into homebrew core... Not sure what is the best course of action so I created an issue over there.

**Comment by jacknagel** [comment]
The only way to work around this currently is to manually `brew install vtk --with-qt` first.

The problem is this code in the vtk formula:

```rb
  if build.with? "qt" or build.with? "qt5"
    if build.with? "python"
      depends_on "sip"
      depends_on "pyqt"
    end
  end
```

This conditional is in the class body, and therefore it is evaluated when the formula file is loaded. The `build` that is available in the class body has no way to know about the build options passed from another formula, e.g. it doesn't know about the `with-qt` being passed in by the pcl formula. It only knows about the contents of ARGV.

This problem has existed since the inception of the project.

Eventually using `build` in the class body will be deprecated, but we need new constructs that don't have this problem (e.g. https://gist.github.com/jacknagel/6731244) first.

**Comment by fran6co** [comment]
Thanks @jacknagel, not sure what would be the best fix for the test system then @dpo.

**Comment by jacknagel** [comment]
I should add that I've been working to make a fix possible for the better part of two years. It has required a lot of internal design changes and careful refactoring, and it is sometimes hard to keep up with other changes that are happening. We'll get there eventually, but I want to be careful not to make the same mistakes again.

**Comment by fran6co** [comment]
Fixed @dpo, added sip and pyqt as a dependencies when building with qt. Couldn't think of a better work around.

**Comment by fran6co** [comment]
Sorry to be a bother, but what is blocking this issue now?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Sorry, just lack of free time.

**Comment by fran6co** [comment]
No prob, I thought that something else was blocking it. Thanks!

**Pull request closed without merging**
