### PR TITLE
dynare: make slicot required for build with Matlab and Octave

### PR DESCRIPTION
**Pull request by houtanb**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by houtanb** [comment]
@ilovezfs it seems as though the travis-ci build failed because it could not download the slicot bottle. See [line 1802](https://travis-ci.org/Homebrew/homebrew-science/builds/242770608#L1802). Circle-ci seems to have a problem with linuxbrew as well...

**Comment by houtanb** [comment]
@ilovezfs also if I want to be able to create linuxbrew bottles for dynare, you said that the circleci test would need to pass, is that correct? I guess this is something I can launch independently of creating a PR?

**Comment by ilovezfs** [comment]
>@ilovezfs it seems as though the travis-ci build failed because it could not download the slicot bottle

That should be fixed now.

**Comment by ilovezfs** [comment]
>@ilovezfs also if I want to be able to create linuxbrew bottles for dynare, you said that the circleci test would need to pass, is that correct? I guess this is something I can launch independently of creating a PR?

No, what I mean is that it's the CircleCI task, not the Travis CI task, that generates a Linux bottle. So if you can get the CircleCI task to pass in a PR, then a Linux bottle will have been created. It still needs to go through a PR though.

**Comment by ilovezfs** [comment]
Note that the CircleCI build is not restarted by closing and reopening the PR. You have to do a force push to retrigger CircleCI for some reason that is a mystery to me.

**Comment by houtanb** [comment]
@ilovezfs These builds two builds fail because Octave mex files linuxbrew require the `-std=c++11` or `-std=gnu++11`compiler options when using `g++`. I don't have the time at the moment to fix this upstream. So, if it's ok with you, we can push this change as is so macOS+Octave dynare users can have access to the mex file that was previously being ignored. The upstream change to the configure scripts to get this to build on homebrew is not yet apparent to me, but I'll get to it at some point down the line.

**Comment by ilovezfs** [comment]
@houtanb sounds good to me. Shipped! :rocket:

**Comment by houtanb** [comment]
@ilovezfs thanks!

**Pull request closed without merging**
