### PR TITLE
openfst 1.6.1

### PR DESCRIPTION
**Pull request by stevenbedrick**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by stevenbedrick** [comment]
The circleci test failure is nothing to do with this recipe, but rather was some sort of error in one of the unrelated CI steps. Not sure what to do about that...

**Comment by jonchang** [comment]
I've restarted the Circle build.

**Comment by jonchang** [comment]
Thanks @stevenbedrick!

**Comment by stevenbedrick** [comment]
Awesome, thanks @jonchang !

**Pull request closed without merging**
