### PR TITLE
Gubbins: v2.0.0

### PR DESCRIPTION
**Pull request by andrewjpage**
Update Gubbins to version 2.0.0

### CODE REVIEW

**Comment by andrewjpage** [comment]
Could someone take a look at this? 
It passes on OSX, but in linuxbrew numpy fails to build so it fails?

**Comment by sjackman** [comment]
Yes, the `numpy` build failure is unfortunately a known issue. #3863 
I'd love some help resolving that issue if you have the time and inclination to look into it.

**Comment by sjackman** [comment]
```
Warning: Nonstandard bump subject: Gubbins: v2.0.0
Warning: Subject should be: gubbins 2.0.0
```

**Comment by sjackman** [comment]
```
Error: gubbins-2.0.0.el_capitan.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles-science/gubbins/view#files
```

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Andrew.

**Pull request closed without merging**
