### PR TITLE
Netcdf 4.3.3.1 (fix)

### PR DESCRIPTION
**Pull request by davydden**
Fix for linuxbrew when compiling with fortran.

### CODE REVIEW

**Comment by dpo** [comment]
Please hold until I've merged #2758 and follow-ups.

**Comment by davydden** [comment]
i think this requirement should be dropped off the audit:
```
Error: 1 problem in 1 formula
homebrew/science/netcdf:
 * Non-libraries were installed to "/usr/local/Cellar/netcdf/4.3.3.1_1/lib"
Installing non-libraries to "lib" is discouraged.
The offending files are:
  /usr/local/Cellar/netcdf/4.3.3.1_1/lib/libnetcdf.settings
```
it is certainly not the best place, but it's not up to us to decide where package developers should install auxilary files which may be required to configure other software which use it.

**Comment by davydden** [comment]
since there are some issues with follow-ups, shall we merge this one?

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Bot is stuck. Restarting.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
@dpo can we merge it? the bot audit error (above) is wrong, IMHO

**Comment by dpo** [comment]
Sorry for the wait. Please rebase.

**Comment by dpo** [comment]
Also need to bump the revision number.

**Pull request closed without merging**
