### PR TITLE
bgt 1.0 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
Flexible genotype query among 30,000+ samples whole-genome 
By Heng Li

### CODE REVIEW

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
```
homebrew/science/bgt:
  * Dependency 'zlib' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * Dependency 'zlib' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * fully scope test system calls e.g. system "#{bin}/bgt"
  * Use pkgshare instead of (share/"bgt")
  * Use pkgshare instead of (share/"bgt")
```

@tseemann can you try to fix this and rebase? Thanks.

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
