### PR TITLE
opencv 2.4.10.1

### PR DESCRIPTION
**Pull request by iml**

### CODE REVIEW

**Comment by cbenhagen** [comment]
@iml are you still working on this? I would love to have 2.4.10.1 in. How can i help? I have some more changes which id rather like to make on top of your work.

**Comment by sjackman** [comment]
@iml I just stumbled on `homebrew/python/numpy`. How about we depend on that?

**Comment by iml** [comment]
Thanks for the reminder. I discussed a while ago depending on homebrew/python modules with @tdsmith and the general rule of thumb is to use Apple-provided modules when available. However, most users will want an up-to-date NumPy and our troubleshooting tends to recommend `homebrew/python/numpy` anyway. So I'll close this out with a default `brewed-numpy` option and see how it goes.

**Comment by iml** [comment]
@cbenhagen Yes, please feel free to submit a PR with any changes now that this is merged. 

Bottled cv2.so is now linked with brewed numpy and python:
```
/usr/local/opt/opencv/lib/python2.7/site-packages/cv2.so:
	/usr/local/lib/python2.7/site-packages/cv2.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_contrib.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_nonfree.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_gpu.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_legacy.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_photo.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_ocl.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_calib3d.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_features2d.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_flann.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_ml.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_video.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_objdetect.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_highgui.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_imgproc.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_core.2.4.dylib (compatibility version 2.4.0, current version 2.4.10)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Pull request closed without merging**
