### PR TITLE
Weighbour 1.2 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
Weighbor is a weighted version of Neighbor Joining that gives significantly less weight to the longer distances in the distance matrix. The weights are based on variances and covariances expected in a simple Jukes-Cantor model. The criterion for which pair is joined is based on a likelihood function on the distances. The resulting trees are less perturbed by adding distant taxa compared to Neighbor Joining, and negative branch lengths are avoided. The method does not suffer from long branch attraction as maximum parsimony and other methods do. The method is much faster than maximum likelihood, usually faster than maximum parsimony, and a lot slower than Neighbor Joining.

### CODE REVIEW

**Comment by tseemann** [comment]
I keep getting this error when I try to brew pull it (this happens on every 2nd/3rd formula I try to merge):

```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/2808
######################################################################## 100.0%
==> Applying patch
Applying: Weighbour 1.2 (new formula)
==> Patch closes issue #2808
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ OS\ X\ 10.10.5) --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-2808
```

**Comment by iml** [comment]
I get the same error.

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
I am closing this because the source code no longer seems to be available!

**Pull request closed without merging**
