### PR TITLE
iqtree: Depends on zlib for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew linkage homebrew/science/iqtree
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/libz.so.1
  /usr/lib/x86_64-linux-gnu/libgomp.so.1
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
==> brew linkage --test homebrew/science/iqtree
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/libz.so.1
  /usr/lib/x86_64-linux-gnu/libgomp.so.1
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No broken dylib links
==> FAILED
```
False positive on `libgomp.so.1`

**Comment by maxim-belkin** [comment]
my only question would be: why "Linux" label is in black??? is it like a "Black label"? 😄

**Comment by ilovezfs** [comment]
probably because it looks a bit like a penguin

**Comment by sjackman** [comment]
🐧 So it does!

**Pull request closed without merging**
