### PR TITLE
symengine 0.2.0 (new formula)

### PR DESCRIPTION
**Pull request by isuruf**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by iMichka** [comment]
@isuruf Thanks for your contribution. Looks like a nice project you have there, with already a lot of contributors and activity. I knew of Sympy, but never really used it myself. I will make sure to advertise symengine to some colleagues, it may interest them.

**Comment by sjackman** [comment]
The build failure with Linuxbrew on Circle CI is
```
-- Found GMP: /home/linuxbrew/.linuxbrew/opt/gmp/lib/libgmp.so  
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find MPC (missing: MPC_LIBRARIES MPC_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMPC.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:244 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/symengine-20170111-38776-1biuy7h/symengine-0.2.0/build/CMakeFiles/CMakeOutput.log".
```

**Comment by iMichka** [comment]
@isuruf we do not display the circle ci build for linux for the moment. This is why no Linux bottles were built. These are not mandatory for the moment, the mac bottles are the most important.

Maybe you could have a look and provide a patch/update, that would be super cool. Just open a new pull request for that, in case you want to provide a fix. Thanks.

**Comment by isuruf** [comment]
I think the circle ci build is an old build that failed. Is this the build, https://circleci.com/gh/Homebrew/homebrew-science/2732 ?
I've force pushed over that commit and fixed the error. What should I do?

Thanks for reviewing and merging the PR.

**Comment by sjackman** [comment]
All three Circle CI builds failed. You can use a Circle Docker image to troubleshoot. Unless you're able to reproduce this build error on your own machine, there's not much to do for now. It looks as though `cmake` needs to be told where to find the `mpc` library.

**Comment by isuruf** [comment]
I sent a PR and then force pushed 3 times to get it right. There should have been 4 Circle CI builds.
The change I made in the last commit was to change the dependency from `mpc` to `libmpc` which is the correct dependency, but I didn't notice that `mpc` was not what I needed because of another libmpc.a lying around in my system.

**Comment by sjackman** [comment]
When I look at https://circleci.com/gh/Homebrew/homebrew-science/tree/pull/4842 I see three failed builds.

**Comment by isuruf** [comment]
Yes, but the latest build is testing, https://github.com/Homebrew/homebrew-science/commit/9a9526c95a16fe4d32e69e161cfb6b4316ea303a instead of 
https://github.com/Homebrew/homebrew-science/pull/4842/commits/a72f706df334ed3ea7e3f3a21fb7c507ffc8e928

From the build log, you can also see that it is installing `mpc` instead of `libmpc`.

There should have been 4 builds. 1 build when I created the PR which failed. 2 force pushes which failed. Last force push didn't build.

**Pull request closed without merging**
