### PR TITLE
anvio: revision for gsl

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
I see two errors in the linux build:

> ==> Downloading https://linuxbrew.bintray.com/bottles-science/diamond-0.9.8.x86_64_linux.bottle.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.1 (Linux; x86_64 Ubuntu 14.04.4 LTS) curl/7.35.0 --fail --silent https://linuxbrew.bintray.com/bottles-science/diamond-0.9.8.x86_64_linux.bottle.tar.gz -C 0 -o /home/ubuntu/.cache/Homebrew/diamond-0.9.8.x86_64_linux.bottle.tar.gz.incomplete
Error: Failed to download resource "diamond"
Download failed: https://linuxbrew.bintray.com/bottles-science/diamond-0.9.8.x86_64_linux.bottle.tar.gz

> numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

**Comment by ozcan** [comment]
Hi @iMichka, Can we merge this? I got some emails asking about gsl error. I recommend them to install from source, but it takes so much time.
Thank you very much,

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Rebuilding the mac bottles. Once they are built we can merge this. There were no Linux bottles here before so we can ignore the Linux build failure for the moment. This can be fixed separately.

**Comment by iMichka** [comment]
@tmozgach I merged this as is, so that the mac users get updated bottles. You will need to open a new pull request if you want to add Linux bottles.

**Comment by sjackman** [comment]
`numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`

Looks like some formula (this formula or one of its dependencies) should
```ruby
depends_on "openblas" unless OS.mac?
```

**Pull request closed without merging**
