### PR TITLE
mothur 1.39.0

### PR DESCRIPTION
**Pull request by HadrienG**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by alexstaj** [comment]
how do we get this going and for linuxbrew too?

**Comment by iMichka** [comment]
Hi. Thanks for your contribution. The Linux build passed, it's the mac build that got stopped. I'll relaunch it.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@HadrienG Thanks for your contribution.

Linux bottles will follow later, our linux bottling CI is down for the moment.

**Comment by sjackman** [comment]
@sjackman 🐧

**Pull request closed without merging**
