### PR TITLE
gmsh 2.9.3

### PR DESCRIPTION
**Pull request by schoeps**
…cairo dependency

### CODE REVIEW

**Comment by iml** [comment]
```
Error: 2 problems in 1 formulae
gmsh:
 * Use build.with? "fltk" instead of build.include? 'with-fltk'
 * 30: Trailing whitespace was found

**Comment by schoeps** [comment]
"brew audit gmsh" without error.

**Comment by dpo** [comment]
Thanks! Please squash commits.

**Comment by schoeps** [comment]
done (and understood :)

**Comment by dpo** [comment]
@BrewStatusBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
