### PR TITLE
omcompiler 1.12.0

### PR DESCRIPTION
**Pull request by SimplyDanny**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by SimplyDanny** [comment]
OMCompiler can be used with two different runtimes that perform the computations in the end. The C runtime is build by default. The C++ runtime has to be build separately. I added the possibility to build the C++ runtime with the option `--with-cppruntime`. If you decide that you need the C++ runtime after the C runtime has already been built and you use `brew reinstall omcompiler --with-cppruntime` in order to do that it is reasonable to use the existing `omc` as this will accelerate the build process considerably. On my machine it is nearly twice as fast. So my idea is to add the line 

    args << "--with-omc=#{prefix}.reinstall/bin/omc" if File.exist?("#{prefix}.reinstall/bin/omc")

to the formula in order to provide the existing `omc` to the `configure` system call. The problem is that `brew audit` does not like the line answering with the message `"#{prefix}/bin" should be "#{bin}"` and `The installation seems to be empty. Please ensure the prefix is set correctly and expected files are installed.`.

Can the existing `omc` be used in another (clean) way or is it just impossible to use it?

**Comment by SimplyDanny** [comment]
Is it necessary to support Linuxbrew, too?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
It would be great but it is not mandatory. Let's skip this for the moment.

**Comment by sjackman** [comment]
The build error on Linux is…
```
checking LAPACK/BLAS flags... configure: error: dgesv or dswap not found
```
https://travis-ci.org/Homebrew/homebrew-science/builds/293791356#L4515

If you wanted to support Linux, try adding…
```ruby

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Note that this tap Homebrew/science is being retired at the end of the year. You may wish to create your own tap to house this and similar formulae. See https://github.com/Homebrew/homebrew-science/issues/6365 and https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

**Comment by sjackman** [comment]
```
/usr/bin/curl --show-error --user-agent Linuxbrew/1.4.0-4-g7b558e0 (Linux; x86_64 Debian GNU/Linux 9.3 (stretch)) curl/7.52.1 --fail --silent -I --output /dev/null https://homebrew.bintray.com/bottles-science/omcompiler-1.12.0.sierra.bottle.tar.gz
Error: omcompiler-1.12.0.sierra.bottle.tar.gz is already published. Please remove it manually from
```
https://bintray.com/homebrew/bottles-science/omcompiler/view#files
https://jenkins.brew.sh/job/Homebrew%20Bottles/18497/console

**Comment by sjackman** [comment]
Deleted the published bottles.

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Homebrew/science, Danny!

**Pull request closed without merging**
