### PR TITLE
petsc: revision bump needed for getdp

### PR DESCRIPTION
**Pull request by ilovezfs**
Trying to build `getdp` against the latest bottle of `petsc` gets you
```
ld: library not found for -lclang_rt.osx
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [getdp] Error 1
make[1]: *** [CMakeFiles/getdp.dir/all] Error 2
make: *** [all] Error 2
```

Trying to run `brew test getdp` with the bottled `getdp` gets you
```
Last 15 lines from /Users/joe/Library/Logs/Homebrew/getdp/01.getdp:
2016-03-30 06:54:47 -0700

/usr/local/Cellar/getdp/2.7.0/bin/getdp
/usr/local/Cellar/getdp/2.7.0/share/doc/getdp/demos/magnet.pro

dyld: Library not loaded: /usr/local/opt/gmsh/lib/libGmsh.2.11.dylib
  Referenced from: /usr/local/Cellar/getdp/2.7.0/bin/getdp
  Reason: image not found
Error: homebrew/science/getdp: failed
Failed executing: /usr/local/Cellar/getdp/2.7.0/bin/getdp /usr/local/Cellar/getdp/2.7.0/share/doc/getdp/demos/magnet.pro
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/getdp.rb:71:in `block in <class:Getdp>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

`getdp` build succeeds if built against a freshly built petsc, and then `brew test getdp` succeeds as well. So we need a revision bump of `petsc` and then of `getdp`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
OK, let's see if these three can build together successfully since they're causing mutual failures.

**Comment by dpo** [comment]
There's already #3465 and #3483.

**Comment by ilovezfs** [comment]
@dpo I know.

**Comment by dpo** [comment]
Please don't duplicate.

**Comment by ilovezfs** [comment]
@dpo I have no interest in "duplicating." CI is going to require that they be shown to build together successfully, not that they be shown to all fail separately, get merged while failing separately, and then hoping maybe the situation magically subsequently resolves itself. This is particularly the case when the entire purpose of the PR is to resolve mutual failures. Whether they're ultimately merged from a single PR or from multiple PRs is entirely beside the point.

**Pull request closed without merging**
