### PR TITLE
opencv3 3.3.0

### PR DESCRIPTION
**Pull request by xzcvczx**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

the processor features are now autodetected in cmake

### CODE REVIEW

**Comment by iMichka** [comment]
The Linux CI has some trouble because the jpeg formula just got updated, and we are rebuilding the different bottles. We may need to delay this slightly, but as soon as we are ready, I will trigger a new build.

Though we are in the process to migrate opencv to core, but that may take some more time, so I do not want to delay the update here (see https://github.com/Homebrew/homebrew-core/pull/15903).
@fxcoudert What do you think?

**Comment by jonchang** [comment]
I've restarted the circle build since we have jpeg bottles now. `visp` will need a revision bump too.

**Comment by fxcoudert** [comment]
`visp` revision PR is there: https://github.com/Homebrew/homebrew-science/pull/6088

**Comment by fxcoudert** [comment]
On the mac side, this is good to go!

**Comment by fxcoudert** [comment]
Thanks @xzcvczx for the pull request!

**Pull request closed without merging**
