### PR TITLE
garli: revision for open-mpi

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
checking for mpi.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
configure: WARNING: unrecognized options: --disable-debug, --disable-silent-rules
==> make install
Making install in src
clang++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT  -DUNIX -DNCL_CONST_FUNCS -DNDEBUG -Wno-uninitialized -O3 -ffast-math -funroll-loops -fstrict-aliasing -c -o adaptation.o adaptation.cpp
clang++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT  -DUNIX -DNCL_CONST_FUNCS -DNDEBUG -Wno-uninitialized -O3 -ffast-math -funroll-loops -fstrict-aliasing -c -o bipartition.o bipartition.cpp
clang++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT  -DUNIX -DNCL_CONST_FUNCS -DNDEBUG -Wno-uninitialized -O3 -ffast-math -funroll-loops -fstrict-aliasing -c -o condlike.o condlike.cpp
clang++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT -I/usr/local/include -I/usr/local/include/ncl -DIGNORE_NXS_ASSERT  -DUNIX -DNCL_CONST_FUNCS -DNDEBUG -Wno-uninitialized -O3 -ffast-math -funroll-loops -fstrict-aliasing -c -o configoptions.o configoptions.cpp
In file included from bipartition.cpp:19:
In file included from ./bipartition.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:702:71: error: invalid operands to binary expression ('const ReconNode' and 'const ReconNode')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2191:13: note: in instantiation of member function 'std::__1::__less<ReconNode, ReconNode>::operator()' requested here
        if (__comp(*--__e2, *__f1))
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2177:5: note: in instantiation of function template specialization 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::__sort<std::__1::__less<ReconNode, ReconNode> >' requested here
    __sort(begin(), end(), base::__sz(), __comp);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2168:5: note: in instantiation of function template specialization 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::sort<std::__1::__less<ReconNode, ReconNode> >' requested here
    sort(__less<value_type>());
    ^
./reconnode.h:208:5: note: in instantiation of member function 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::sort' requested here
                l.sort();
                  ^
./reconnode.h:52:7: note: candidate function not viable: 'this' argument has type 'const ReconNode', but method is not marked const
        bool operator<(const ReconNode &rhs){
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:424:1: note: candidate template ignored: could not match 'pair<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:592:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'const ReconNode'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:996:1: note: candidate template ignored: could not match 'move_iterator<type-parameter-0-0>' against 'const ReconNode'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:1312:1: note: candidate template ignored: could not match '__wrap_iter<type-parameter-0-0>' against 'const ReconNode'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2974:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3032:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3041:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4851:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4916:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4924:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
1 error generated.
make[1]: *** [bipartition.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from adaptation.cpp:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:702:71: error: invalid operands to binary expression ('const ReconNode' and 'const ReconNode')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2191:13: note: in instantiation of member function 'std::__1::__less<ReconNode, ReconNode>::operator()' requested here
        if (__comp(*--__e2, *__f1))
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2177:5: note: in instantiation of function template specialization 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::__sort<std::__1::__less<ReconNode, ReconNode> >' requested here
    __sort(begin(), end(), base::__sz(), __comp);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:2168:5: note: in instantiation of function template specialization 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::sort<std::__1::__less<ReconNode, ReconNode> >' requested here
    sort(__less<value_type>());
    ^
./reconnode.h:208:5: note: in instantiation of member function 'std::__1::list<ReconNode, std::__1::allocator<ReconNode> >::sort' requested here
                l.sort();
                  ^
./reconnode.h:52:7: note: candidate function not viable: 'this' argument has type 'const ReconNode', but method is not marked const
        bool operator<(const ReconNode &rhs){
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:424:1: note: candidate template ignored: could not match 'pair<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:592:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'const ReconNode'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:996:1: note: candidate template ignored: could not match 'move_iterator<type-parameter-0-0>' against 'const ReconNode'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:1312:1: note: candidate template ignored: could not match '__wrap_iter<type-parameter-0-0>' against 'const ReconNode'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2974:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3032:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3041:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'const ReconNode'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4851:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4916:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4924:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const ReconNode'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
1 error generated.
make[1]: *** [adaptation.o] Error 1
make: *** [install-recursive] Error 1
```

**Comment by jonchang** [comment]
I believe #3628 fixes this build error.

**Comment by ilovezfs** [comment]
Closing in favor of #3628.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-science/commit/db92fadf98ff0061c5c98ef103b7d4a982672885

**Pull request closed without merging**
