### PR TITLE
pcl depends on Vtk6, adding version for vtk6

### PR DESCRIPTION
**Pull request by ahundt**
Per these issues:
https://github.com/Homebrew/homebrew-science/issues/3370
https://github.com/mikepurvis/ros-install-osx/issues/32 (external)

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by ahundt** [comment]
Audit results:

```
± brew audit --strict vtk6 --online
==> brew style vtk6

1 file inspected, no offenses detected

==> audit problems
ahundt/science/vtk6:
 * `revision` (line 7) should be put before `head` (line 6)
 * A `test do` test block should be added
 * Formula should have a desc (Description).
 * python modules have explicit framework links
These python extension modules were linked directly to a Python
framework binary. They should be linked with -undefined dynamic_lookup
instead of -lpython or -framework Python.
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkChartsCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonColorPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonComputationalGeometryPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonDataModelPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonExecutionModelPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonMathPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonMiscPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonSystemPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkCommonTransformsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkDomainsChemistryPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersAMRPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersExtractionPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersFlowPathsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGeneralPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGenericPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGeometryPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersHybridPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersHyperTreePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersImagingPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersModelingPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersParallelImagingPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersParallelPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersProgrammablePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersPythonPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSelectionPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSMPPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSourcesPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersStatisticsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersTexturePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkFiltersVerdictPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkGeovisCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingColorPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingFourierPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingGeneralPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingHybridPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingMathPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingMorphologicalPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingSourcesPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingStatisticsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkImagingStencilPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInfovisBoostGraphAlgorithmsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInfovisCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInfovisLayoutPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInteractionImagePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInteractionStylePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkInteractionWidgetsPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOAMRPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOEnSightPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOExodusPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOExportPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOGeometryPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOImagePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOImportPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOInfovisPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOLegacyPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOLSDynaPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOMINCPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOMoviePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIONetCDFPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOParallelPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOParallelXMLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOPLYPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOSQLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOVideoPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOXMLParserPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkIOXMLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkParallelCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingAnnotationPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingContext2DPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingContextOpenGLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingFreeTypePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingGL2PSPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingImagePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingLabelPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingLICPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingLODPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingOpenGLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingQtPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingVolumeOpenGLPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkRenderingVolumePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkViewsContext2DPython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkViewsCorePython.so
  /usr/local/Cellar/vtk6/6.3.0_1/lib/python2.7/site-packages/vtk/vtkViewsInfovisPython.so

Error: 4 problems in 1 formula
```

**Comment by mikepurvis** [comment]
Note that I have to build the formula from source, as the bottle doesn't exist. The bottle SHAs should removed until new bottles can be made for this particular formula.

**Comment by dpo** [comment]
Homebrew/versions is probably a better place for `vtk6`. I should also move `vtk5` there since there's nothing left in Science that depends on it.

**Comment by dpo** [comment]
Please address the audits:
```
* `revision` (line 7) should be put before `head` (line 6)
 * A `test do` test block should be added
 * Formula should have a desc (Description).
```

**Comment by ahundt** [comment]
I don't know enough about vtk to address the test, and it is no different from the current vtk7.rb in that respect.

I made the one change I can at: https://github.com/ahundt/homebrew-science/commit/afca4bcf5fe8df11d9d1c85d742e230023c23baf

Should the bottle lines be commented or deleted for now by me?

**Comment by ahundt** [comment]
Also there are probably quite a few things that depend on vtk6 at the current time

**Comment by ahundt** [comment]
looks like my commit is now pushed on the right branch, not sure why it isn't popping up here https://github.com/ahundt/homebrew-science/tree/vtk6

**Comment by mikepurvis** [comment]
vtk6 needs to be present here in the short term, for PCL if nothing else.

**Comment by dpo** [comment]
Nothing in homebrew/science depends on vtk6 at the time and I'd rather not introduce a dependency for a single formula.

**Comment by ahundt** [comment]
@dpo unfortunately as mentioned in the title pcl depends on vtk 6 (recommended), perhaps the broken dependency is disguised by the bottle? Try `brew install pcl` https://github.com/Homebrew/homebrew-science/blob/master/pcl.rb it will fail. vtk is recommended and pcl only supports 6.x. 

from brew info pcl:
```
homebrew/science/pcl: stable 1.7.2 (bottled), HEAD
Library for 2D/3D image and point cloud processing
http://www.pointclouds.org/
/usr/local/Cellar/pcl/1.7.2 (1,124 files, 119.3M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-science/blob/master/pcl.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: boost ✔, eigen ✔, flann ✔, cminpack ✔, qhull ✔, libusb ✔, sip ✔, pyqt ✔
Recommended: qt ✔, vtk ✘
```

**Comment by ahundt** [comment]
here is the start of a test for vtk6 too:

```
 test do
    (testpath/"test.cpp").write <<-EOS
    #include <vtkPolyData.h>
    #include <vtkVersion.h> // NOTE: without this include, the VTK_[]_VERSION are not defined!
 
    // These functions allow you to output the version defines at compile time
    #define STR(x) STR2(x)
    #define STR2(x) #x
 
    int main(int, char *[])
    {
      #if VTK_MAJOR_VERSION>5 || (VTK_MAJOR_VERSION==5 && VTK_MINOR_VERSION>4)
        #pragma message(STR(VTK_MAJOR_VERSION))
      #endif
 
      return EXIT_SUCCESS;
    }
    EOS

    (testpath/"CMakeLists.txt").write <<-EOS
    cmake_minimum_required(VERSION 2.8)
 
    PROJECT(VersionMacros)
 
    find_package(VTK REQUIRED)
    include(${VTK_USE_FILE})
 
    add_executable(VersionMacros MACOSX_BUNDLE VersionMacros)
 
    if(VTK_LIBRARIES)
      target_link_libraries(VersionMacros ${VTK_LIBRARIES})
    else()
      target_link_libraries(VersionMacros vtkHybrid vtkWidgets)
    endif()
    EOS

  end
```

**Comment by mikepurvis** [comment]
Not to muddy the waters here, but at least some of the issue in all this is the PCL doesn't make particularly frequent releases. The last one was 1.7.2, in September 2014.

But it does seem that PCL's master branch (and the [1.8.0 release candidates](https://github.com/PointCloudLibrary/pcl/tree/pcl-1.8.0rc2)), have support for VTK 7. So this may all get simpler fairly soon.

@dpo Would Homebrew consider moving the release version of PCL forward to the 1.8.0RC tag, given that the current release is unusable? We can always make this change in a ROS tap, but it will suck for users to not have bottles, given that VTK and PCL are both expensive compiles.

**Comment by dpo** [comment]
What I mean is that if `vtk6` is in homebrew/versions, `pcl` can  depend on `homebrew/versions/vtk6` and still have bottles. What's the problem with that?

If you have a `devel` release of `pcl` then it can be built against `vtk` (7) but it won't be bottled until it's stable.

**Comment by tdsmith** [comment]
I'm not sure shifting the maintainership burden to -versions is a good way of dealing with this; -versions doesn't get as much attention as the core tap and I think -science is better-prepared to handle the issues arising from these builds.

**Comment by tdsmith** [comment]
Is there an upstream issue about Python linkage?

**Comment by dpo** [comment]
I would normally agree but because in this case we have no current dependent on VTK6, and a forthcoming release of `pcl` should support VTK7, I don't see a reason to include VTK6 in this tap. VTK issues are difficult to debug. So it's perhaps best to wait or set up a temporary tap until `pcl` supports VTK7.

**Comment by tdsmith** [comment]
> Is there an upstream issue about Python linkage?

http://www.vtk.org/Bug/view.php?id=16068

**Comment by dpo** [comment]
Related to #3401?

**Comment by ahundt** [comment]
@dpo it seems homebrew-versions is not the appropriate place for the vtk6.rb script

https://github.com/Homebrew/brew/issues/61

**Comment by ahundt** [comment]
@dpo @tdsmith Based on discussions in https://github.com/Homebrew/brew/issues/60 I believe the conclusion has been that the most appropriate place for vtk6 is in homebrew-science until the libraries that depend on it can all support vtk7, which at least means pcl. @DomT4 in Homebrew-versions recommends putting the installer in homebrew-science for the same reason in https://github.com/Homebrew/homebrew-versions/pull/1215#issuecomment-222391836. Thus, can the vtk6 formula be merged and kept around until it isn't required?

**Comment by mikepurvis** [comment]
PCL 1.8.0 is finally tagged: https://github.com/PointCloudLibrary/pcl/tree/pcl-1.8.0

If the homebrew-science formula can be updated, then we can hopefully proceed with returning everything to a sane state.

**Pull request closed without merging**
