### PR TITLE
xrmc 6.5.0 (new formula)

### PR DESCRIPTION
**Pull request by tschoonj**
This is a formula for XRMC, a tool for the prediction of X-ray imaging and spectroscopy experiments using Monte Carlo simulations.

The build appears to work fine, but I get the following strange message at the begin:

```
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
```

which is surprising because there is no Fortran compiler required by the Formula: perhaps this is because of the OpenMP requirement?

At the end I get the following message:

```
Warning: xrmc dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

It seems harmless though: the test runs fine...

Please consider this package for inclusion in homebrew-science.

Thanks in advance!

### CODE REVIEW

**Comment by iml** [comment]
I would expect the Fortran message with the `xmi-msim` option but not otherwise. The C++ warning is from GCC and the openmp requirement and can be ignored.

**Comment by tschoonj** [comment]
The Fortran message is quite strange indeed but it appears to be harmless.

Anything else I can do to get the pull request accepted?

**Comment by tschoonj** [comment]
@iml Could you take another look at this please?

Thanks

**Comment by tschoonj** [comment]
@dpo Could you take a look at this please?

Thanks

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Would you mind changing the sha1 to a sha256? You can obtain it with `shasum -a 256`. Thanks!

**Comment by tschoonj** [comment]
done!

**Comment by dpo** [comment]
Ok thanks! It builds fine for me and the tests pass. Please squash your commits.

**Comment by tschoonj** [comment]
squashed and waiting to build

**Comment by dpo** [comment]
Any idea why the build fails on Mountain Lion?
````
detector.cpp: In member function 'int detectorarray::ForcedAcquisition(basesource**, photon*, randmt_t**)':
detector.cpp:187: error: expected '#pragma omp' clause before 'collapse'
detector.cpp: In member function 'int detectorarray::UnforcedAcquisition(basesource**, photon*)':
detector.cpp:279: error: expected '#pragma omp' clause before 'collapse'
````

**Comment by tschoonj** [comment]
yes: it's using llvm-gcc that supports only an old version of the OpenMP standard, which does not support the collapse statement. I thought that the :openmp statement enforced switching to gcc49?

**Comment by dpo** [comment]
`llvm-gcc` probably gets picked up because it supports OpenMP. Perhaps you should add a `fails-with` block to avoid it being picked up. I'm not quite sure why this only happened on Mountain Lion.

**Comment by tschoonj** [comment]
Mountain Lion is the last version that has an Xcode that ships with `llvm-gcc`. I will just list `gcc` as a dependency, which should fix the problem. I will do this tomorrow.

**Comment by dpo** [comment]
The `fails_with :clang` block isn't necessary I think because `needs :openmp` explicitly excludes `:clang`. It just wasn't excluding `:llvm` on Mountain Lion.

**Comment by tschoonj** [comment]
@dpo I have removed the `fails_with :clang` block and squashed all commits into one: could you please pull in this formula? 

Thanks

(PS: also the gnudatalanguage formula should be fine by now)

**Comment by dpo** [comment]
It seems the bottles aren't available. Sorry this is taking a while and I keep getting distracted.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@mikemcquaid I'm having trouble fetching bottles from Bintray:
````
$ brew fetch --force-bottle xrmc.rb
==> Fetching xrmc from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/xrmc-6.5.0.mavericks.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
````
Any idea what might be wrong?

**Comment by mikemcquaid** [comment]
Have you used `brew pull` to publish them?

**Comment by dpo** [comment]
I have and that worked fine:
````
$ brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/1845
######################################################################## 100.0%
==> Applying patch
Applying: xrmc 6.5.0 (new formula)
==> Patch closes issue #1845
Switched to a new branch 'pull-bottle-1845'
######################################################################## 100.0%
==> Applying patch
Applying: xrmc 6.5.0 (new formula)
Applying: xrmc: add 6.5.0 bottle.
First, rewinding head to replay your work on top of it...
Applying: xrmc: add 6.5.0 bottle.
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Updating d219db3..4d24609
Fast-forward
 xrmc.rb | 7 +++++++
 1 file changed, 7 insertions(+)
Deleted branch pull-bottle-1845 (was 4d24609).
==> Patch changed:
 xrmc.rb | 47 +++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 47 insertions(+)
````
My `BINTRAY_USER` and `BINTRAY_KEY` also look correct.

**Comment by mikemcquaid** [comment]
It should say something about publishing files on Bintray.

**Comment by mikemcquaid** [comment]
Your login details do not seem to be correct and/or you need to run `brew update` because the files are not published here: https://bintray.com/homebrew/bottles-science/xrmc/6.5.0/view

**Comment by dpo** [comment]
Oh well when I followed the link you just gave and clicked `Publish`, the bottles became available. Does that have to be done manually?

**Comment by mikemcquaid** [comment]
It's done by `brew pull`. Please `brew update` and make sure that you have exported those variables correctly: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/pull.rb#L160-L180

**Comment by tschoonj** [comment]
Thanks!

**Comment by dpo** [comment]
I `brew update` several times a day. The bottles were uploaded, just not published. It might have been a temporary glitch because I was just able to fetch another bottle (#1918).

**Pull request closed without merging**
