### PR TITLE
rstudio-server: fix linuxbrew linkage error

### PR DESCRIPTION
**Pull request by randy3k**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by randy3k** [comment]
@jonchang 🙏

**Comment by randy3k** [comment]
It seems there was a network issue on Jenkins.

**Comment by randy3k** [comment]
cf https://github.com/Homebrew/homebrew-core/issues/18044

**Comment by ilovezfs** [comment]
I cannot reconstruct the original checksum. Are we sure this wasn't retagged?

**Comment by randy3k** [comment]
I am not sure, but it doesn't seem that it has been retagged.

https://github.com/rstudio/rstudio/releases/tag/v1.0.153

by the way, how can I reconstruct the tar ball locally as in GitHub.com?

**Comment by randy3k** [comment]
Updated the checksum sha, it works except for the strict audit test blaming me for changing sha without updating the version.

**Comment by sjackman** [comment]
@ilovezfs Was the change in SHA-256 a result of the great SHApocalypse? I'd like to merge this PR.
@randy3k Thanks for this work! Could you please rebase this PR onto `master`?

**Comment by randy3k** [comment]
Rebased.

**Comment by sjackman** [comment]
The only error is
```
Error: 1 problem in 1 formula
homebrew/science/rstudio-server:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
==> FAILED
```
@ilovezfs Can I merge this PR?

**Comment by ilovezfs** [comment]
@sjackman nope, but I think there have been new tags since then so the right answer would be to upgrade it rather than change the checksum for the existing version.

**Comment by randy3k** [comment]
@ilovezfs there is no newer release than 1.0.153 
https://www.rstudio.com/products/rstudio/download-server/ 
The "newer" tags are preview versions.

**Comment by ilovezfs** [comment]
Then we should follow the usual procedure of reporting the checksum change and waiting for an explanation.

**Comment by sjackman** [comment]
@ilovezfs Why do you believe the change in SHA-256 is not a result of the SHApocalypse?

**Comment by ilovezfs** [comment]
Because the usual procedure for detecting the change did not produce the current SHA-256.

**Comment by sjackman** [comment]
@randy3k Release 1.1.374 seems newer than 1.0.153. Can we update this formula to that version?

**Comment by jonchang** [comment]
Aren't those preview versions and not actual 'releases'? Their website still [says 1.0.153 is the latest version](https://www.rstudio.com/products/rstudio/download-server/).

**Comment by sjackman** [comment]
Got it. Thanks for the clarification, Jon.

**Comment by sjackman** [comment]
I'm not able to reproduce either of those `sha256` at the command line. It's probably something that I'm doing wrong. Any idea what? @ilovezfs @peff
```sh
❯❯❯ /usr/bin/git archive --format=tar.gz --prefix=rstudio-1.0.153/ v1.0.153 | gsha256sum
54531dbcfe1521479d415ea8ec80710e14f992bd684742c3dc61f18cd565cf59  -
```
is neither 79b90e21e56b114e28b03fd8543a208c55bb9d5f47a87fd29143d08b9a06f7a0
nor 10521e6ef2e5b7497458007c55fa911cc0454685e6079e67ac5cb7e55ae9f617

**Comment by peff** [comment]
@sjackman Repeating those commands, I do get `10521e6ef...` (using git v2.14.2, but going back as far as v1.8.5.6; switching to v1.7.10.5 gives me `79b90e21e56...`. And using `sha256sum` rather than `gsha256sum`, since I'm on Linux).

Git uses `gzip` to do the compression for a `tar.gz`. It's possible your system `gzip` behaves differently than mine. Try this:

```
$ git archive --format=tar --prefix=rstudio-1.0.153/ v1.0.153 >rstudio-v1.0.153.tar
$ sha256sum rstudio-v1.0.153.tar
30db27af8a3ad7de0064d7733453e71fdf3821dd9ff75bf6b28fae37578c57b2  rstudio-v1.0.153.tar
$ gzip -n rstudio-v1.0.153.tar
$ sha256sum rstudio-v1.0.153.tar.gz
10521e6ef2e5b7497458007c55fa911cc0454685e6079e67ac5cb7e55ae9f617  rstudio-v1.0.153.tar.gz
```

That should tell us in which step the difference first appears.

**Comment by sjackman** [comment]
Success! The problem was an outdated version of `gzip`.
```
❯❯❯ git archive --format=tar --prefix=rstudio-1.0.153/ v1.0.153 | gzip -n | gsha256sum
10521e6ef2e5b7497458007c55fa911cc0454685e6079e67ac5cb7e55ae9f617  -
```

**Comment by sjackman** [comment]
> going back as far as v1.8.5.6; switching to v1.7.10.5 gives me `79b90e21e56`

Woohoo! Thanks for your help, Jeff.
@ilovezfs Sounds like the change is due to the SHApocalypse.

**Comment by sjackman** [comment]
I can corroborate that
```
❯❯❯ git --version
git version 1.7.1
❯❯❯ git archive --format=tar --prefix=rstudio-1.0.153/ v1.0.153 | gzip -n | gsha256sum
79b90e21e56b114e28b03fd8543a208c55bb9d5f47a87fd29143d08b9a06f7a0  -
```

**Comment by sjackman** [comment]
@ilovezfs Shall I merge this PR?

**Comment by randy3k** [comment]
@sjackman Thanks for figuring it out.

**Comment by sjackman** [comment]
It was Jeff really. Thanks again for your help.

**Comment by peff** [comment]
@sjackman It does look like it's related to the SHApocalypse, and the technique I gave for generating the mapping (reverting git/git@22f0dcd9634a818a0c83f23ea1a48f2d620c0546 and generating the archive with that) _does_ work.

I wondered at first why I didn't find it in the mass-search I did earlier, but the answer is that I only looked over `homebrew-core`, not `homebrew-science`.

**Comment by peff** [comment]
> I wondered at first why I didn't find it in the mass-search I did earlier, but the answer is that I only looked over homebrew-core, not homebrew-science.

I've run my script now over `homebrew-science` (and [a few others](https://github.com/Homebrew/homebrew-core/pull/18073#issuecomment-332315297)) and this hash was the only one that still needs fixing.

**Comment by sjackman** [comment]
Merged. Thank you, Randy, and thanks for sticking with this PR!

**Comment by ilovezfs** [comment]
Thanks, @peff. If I had to guess, I was probably using the wrong prefix when I did the check for this one.

**Comment by sbamin** [comment]
Wow! This is indeed a tough build and thanks for putting it in brew. About @sjackman's earlier comment on updated preview versio, rstudio server `v1.1` is now a major release (came out of beta today). I am new to this and going through [help section](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) to see if I can push an updated version. Appreciate tips and additional links to get started on updating to v1.1

**Pull request closed without merging**
