### PR TITLE
w2rap-contigger HEAD [WIP]

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Does not build on mac:
> CMakeFiles/base_libs.dir/src/system/System.cc.o -c /tmp/w2rap-contigger-20170702-47276-hoziiu/src/system/System.cc
/tmp/w2rap-contigger-20170702-47276-hoziiu/src/system/SysConf.cc: In function 'size_t physicalMemory()':
/tmp/w2rap-contigger-20170702-47276-hoziiu/src/system/SysConf.cc:58:31: error: '_SC_PHYS_PAGES' was not declared in this scope
         long result = sysconf(_SC_PHYS_PAGES);
                               ^~~~~~~~~~~~~~
/tmp/w2rap-contigger-20170702-47276-hoziiu/src/system/SysConf.cc:58:31: note: suggested alternative: '_SC_PASS_MAX'
         long result = sysconf(_SC_PHYS_PAGES);
                               ^~~~~~~~~~~~~~
                               _SC_PASS_MAX
make[2]: *** [CMakeFiles/base_libs.dir/src/system/SysConf.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/base_libs.dir/all] Error 2
make: *** [all] Error 2

Also, as always, it would be great to have a tagged version.
> homebrew/science/w2rap-contigger:
>  * Head-only (no stable download)

**Comment by sjackman** [comment]
@bjclavijo Any plans for a stable release of `w2rap-contigger`?

**Comment by bjclavijo** [comment]
Yes, coming soon, we've had a couple of bugs lately that Luis is fixing. I would say one or two weeks... but then nobody will really believe it.
Imminent?

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
