### PR TITLE
sailfish 0.10.1

### PR DESCRIPTION
**Pull request by rob-p**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by rob-p** [comment]
I'm about to push a change that can adversely effect source builds of the current package — an update to a dependency that is pulled and built from source.  This pull request will guarantee stability, and that the homebrew package will not be affected by the upstream changes.

**Comment by sjackman** [comment]
There can be no spaces in the checked box `[x]`. I usually submit the PR without typing `x`s (with empty boxes) and then use the GitHub GUI to check the boxes.

**Comment by rob-p** [comment]
dohh! Thanks, Shaun.  I'm new to these fancy boxes etc. ;P.

**Comment by sjackman** [comment]
No worries. Thanks for your contribution!

**Comment by sjackman** [comment]
Did you notice that Linuxbrew has precompiled binary bottles now? I noticed that your package is not `cellar :any`, which means that the bottle can only be used on systems that install Linuxbrew in `/home/linuxbrew/.linuxbrew` and on Macs in `/usr/local`. After it builds binaries, it looks for the string `/home/linuxbrew` in the binary executables, and if it finds it, it marks the package as non-relocatable, meaning it thinks that it will break if it's installed in, for example, `/home/sjackman` instead of `/home/linuxbrew`. Do you know wether `sailfish` is relocatable?

**Comment by rob-p** [comment]
Ahh, I didn't know this.  Sailfish should work so long as it's libraries are in `../lib` relative to the binary location.  I know this is the case on Linux, but I aways run into library problems on OSX.  What's the easiest way to test this?

**Comment by sjackman** [comment]
```sh
brew install --build-bottle sailfish
brew bottle -v sailfish
```
and check the report for where it's finding the hardcoded paths in the executables, then modify the code to remove hard-coded paths and use relative paths instead.

**Comment by rob-p** [comment]
I'll give this a go tonight and see what I come up with.  If it's not relocatable, I'll try to address this in the next update.

**Comment by rob-p** [comment]
ok it's not relocatable b/c I get this output:

```
arning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/sailfish/0.10.1/bin/sailfish
 --> match '/usr/local/Cellar/sailfish/0.10.1/lib' at offset 0xa34

./sailfish-0.10.1.el_capitan.bottle.1.tar.gz
  bottle do
    revision 1
    sha256 "836bbc795005365ec61579debd7c2b26aa7396b3184ad8e77cb553e7626919e0" => :el_capitan
  end
```

So, the thing I have to figure out now is how to tell CMake, to tell `install_name_tool` (I guess) to do the right thing . . . sigh.

**Comment by sjackman** [comment]
Homebrew automatically changes references of `/usr/local/Cellar` in `install_name` to `@@HOMEBREW_CELLAR@@` (a dummy variable) using `install_name_tool`. See [`relocate_install_names `](https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/keg_relocate.rb#L31). I don't believe that it changes the `RPATH`. Perhaps that's where the reference is.

**Comment by sjackman** [comment]
Yep, there is an RPATH entry:
```
❯❯❯ otool -l sailfish |grep -A2 RPATH
          cmd LC_RPATH
      cmdsize 56
         path /usr/local/Cellar/sailfish/0.10.1/lib (offset 12)
```
This issue could be improved in Homebrew.

**Comment by sjackman** [comment]
I opened an issue in Homebrew/brew to discuss https://github.com/Homebrew/brew/issues/371

**Comment by sjackman** [comment]
It'll probably get fixed in Homebrew eventually, but it turns out there's a few tricky details that don't apply to `sailfish` involving `dlopen`. To get it fixed quickly, your original plan of fixing the `cmake` script to delete the `RPATH` on Mac is best.

**Comment by rob-p** [comment]
Ok.  I must admit, I'm still somewhat confused about how dynamic library search works on OSX.  If I delete the RPATH, how do I ensure that the executable knows where to look for the libraries relative to the binary?

**Comment by sjackman** [comment]
Mac uses absolute paths to the executables dependent libraries. `RPATH` is only used if explicitly requested. `sailfish` doesn't use `RPATH` to locate its libraries, but uses absolute paths.
e.g.
`install_name = /usr/lib/libncurses.5.4.dylib`
is equivalent to
`install_name = @rpath/libncurses.5.4.dylib`, `RPATH=/usr/lib`

```
❯❯❯ otool -L /usr/local/bin/sailfish
/usr/local/bin/sailfish:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/tbb/lib/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/tbb/lib/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

**Pull request closed without merging**
