### PR TITLE
bowtie: fixes stdout for builds with clang on OS X

### PR DESCRIPTION
**Pull request by ilovezfs**
Upstream PR BenLangmead/bowtie#25 avoids implementation specific
`pubsetbuf`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@mikemcquaid Do you prefer those trinity commits squashed together?

**Comment by sjackman** [comment]
Can you split this PR into three separate PR, one for each formula?
If the first `trinity` commit fixes 2.0.6, and the second commit bumps the version to 2.2.0, then I prefer two commits.

**Comment by ilovezfs** [comment]
@sjackman Sure. The purpose of having them together was to get the CI to actually test that it fixed the issue (trinity needed to at least build with gcc5 or nothing would be tested with respect to the original bug) but now that we know it all works, there's no reason to keep them together.


>If the first trinity commit fixes 2.0.6

Yep, it does.

**Comment by sjackman** [comment]
Ah, thanks for the explanation.

**Comment by ilovezfs** [comment]
@sjackman OK, they're all split now. I'd review them in this order: atram, bowtie, trinity206, trinity220

**Comment by sjackman** [comment]
:+1: Thanks, Joe.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
