### PR TITLE
arb 2.10.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@sjackman Seems I have problems pulling the Linux bottles

> Error: Failure while executing: /usr/local/bin/brew pull-linux --bottle https://github.com/Homebrew/homebrew-science/pull/5199

**Comment by sjackman** [comment]
Likely related to the AWS S3 outage, which CircleCI uses to store artifacts. The error message was
```
Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.X.Y\ (Linux;\ x86_64\ 4.4.35-33.55.amzn1.x86_64)\ curl/7.40.0 --fail --silent -O https://3628-4106792-gh.circle-artifacts.com/0/tmp/circle-artifacts.4H25kjX/arb-2.10.0.x86_64_linux.bottle.json
```

If there's not tag at https://github.com/LinuxbrewTestBot/homebrew-science/releases/tag/pr-5199
You can manually trigger a transfer with
```
http://bot.linuxbrew.sh/ci-upload/github.com/Homebrew/homebrew-science/pull/5199
```
You'll get the message after thirty seconds: `{"message": "Endpoint request timed out"}`
Wait two minutes, then check
https://github.com/LinuxbrewTestBot/homebrew-science/releases/tag/pr-5199

**Comment by iMichka** [comment]
@sjackman Thanks that worked. Good to know next time I have a similar problem. Thanks for the details.

**Pull request closed without merging**
