### PR TITLE
sumo 0.22.0 (new formula)

### PR DESCRIPTION
**Pull request by alexvoronov**
A formula for Simulation of Urban MObility (SUMO).

I added a simple test in 'do test', since the full 'make test' suite
is not distributed with the source. Full test is only available in the
source repository http://sumo.dlr.de/trac.wsgi/browser/trunk/sumo/tests

### CODE REVIEW

**Comment by dpo** [comment]
Sorry for the delay. Could you please squash your commits into one?

**Comment by alexvoronov** [comment]
I'm not really sure how to squash commits correctly... There are too many options that I can mess up with, and I think I already executed a few wrong commands :) 
Is there a simple command I can use?

**Comment by dpo** [comment]
See, e.g., [these instructions](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

**Comment by iml** [comment]
`git rebase -i HEAD~7` or so and then fixup (`f`) all the commits after the initial one. Then push to your branch with `--force`.

**Comment by alexvoronov** [comment]
Thanks, I was missing the `--force`, that's why my `push` was failing. I also see that comments in this thread have disappeared due to `rebase`, there is no way / no need to preserve them?

**Comment by dpo** [comment]
Sorry to bother you with this. Do you think you could fix the audit warnings and rebase one last time?
````
$ brew audit ./sumo.rb --strict
==> brew style sumo
== sumo.rb ==
C: 31:  1: Extra empty line detected at method body beginning.
C: 32: 29: Avoid using {...} for multi-line blocks.
C: 60:  1: Extra empty line detected at method body end.
C: 63:  1: Extra blank line detected.
C: 70:  1: Extra blank line detected.

1 file inspected, 5 offenses detected

==> audit problems
sumo:
 * `require "formula"` is now unnecessary

Error: 1 problems in 1 formulae
````

**Comment by alexvoronov** [comment]
This is probably something new in Homebrew (`--strict`), that's why I missed it. I also start to be more comfortable with `rebase`, so no problems there :)

**Pull request closed without merging**
