### PR TITLE
cmdstan 2.7.0 (new formula)

### PR DESCRIPTION
**Pull request by sjackman**
Stan is a probabilistic programming language implementing full Bayesian
statistical inference.

### CODE REVIEW

**Comment by sjackman** [comment]
See https://github.com/stan-dev/cmdstan/issues/145

**Comment by dustinvtran** [comment]
Could you change the desc to "probabilistic programming language for Bayesian inference"? The "full" part is attributed to MCMC, which is only a subset of the inference algorithms Stan has. It also does approximate Bayesian inference and optimization.

**Comment by sjackman** [comment]
Sure. Done.

**Comment by dpo** [comment]
```
* GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
```
That's interesting ;-)

**Comment by sjackman** [comment]
Yes, quite. I had a chuckle the first time I saw that "error" as well.

**Comment by sjackman** [comment]
```
In file included from /usr/local/include/stan/math/prim/scal/meta/is_constant_struct.hpp:4:
/usr/local/include/stan/math/prim/scal/meta/is_constant.hpp:4:10: fatal error: 'boost/type_traits/is_convertible.hpp' file not found
#include <boost/type_traits/is_convertible.hpp>
         ^
1 error generated.
```

**Pull request closed without merging**
