### PR TITLE
Trilinos 12.2.1 (update)

### PR DESCRIPTION
**Pull request by davydden**
Made python optional.
Enabled ShyLU, Cholmod and Teko by default.
Force C++11 as main packages require it.

- [x] check on linux

### CODE REVIEW

**Comment by dpo** [comment]
Why make Python `:optional`? Because of `dealii`? Isn't there a patch yet for that bug?!

**Comment by davydden** [comment]
unfortunately not... 

but how about we do some `replace` in trilinos config files which got installed to Cellar to correct this issue? I am not sure if that will break python usage, though...

**Comment by davydden** [comment]
do you use `python` interface of trilinos to test it?

**Comment by davydden** [comment]
to be more specific what @wfspotz suggested here https://github.com/Homebrew/homebrew-science/issues/2148#issuecomment-103614509

> A workaround is to remove libpytrilinos from the export Makefile you are using. 

namely modify `/lib/cmake/Trilinos/TrilinosConfig.cmake` to remove `pytrilinos` from `Trilinos_LIBRARIES` list.

What I don't know is wheter or not it will break any python programs which use trilinos. I have no idea how it works there and wheterh or not they might be using that `.cmake` file to set up something.

**Comment by davydden** [comment]
the current version, namely with 
```
inreplace "#{lib}/cmake/Trilinos/TrilinosConfig.cmake" do |s|
  s.gsub! "PyTrilinos;", "" if s.include? "COMPONENTS_LIST"
end
```
worked fine for me with `dealII` on `10.10.5`. Hopefully there will not be any problems with test bot...

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by wfspotz** [comment]
I talked to the build folks not too long ago about making the removal of libpytrilinos from the export Makefiles a part of the build system.  At the very least it is higher on their priority list.

I do this in a build script for a project I work on and it works just fine.  If you want to add this to your build process, it should not create any problems.

**Comment by davydden** [comment]
thanks, Bill! I implemented this strategy here (https://github.com/Homebrew/homebrew-science/pull/2712#issuecomment-138061653) in this PR and it works good so far.

**Comment by dpo** [comment]
@davydden You have a check box in your original message. Are you currently testing on Linux, or is this good to go?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
just tested on Ubuntu 14.04. All good.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
