### PR TITLE
hdf5 1.8.17

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Looks like a lot of dependencies will need a revision bump.

@ilovezfs Is there a clever `brew` command to do that? :smile:

**Comment by ilovezfs** [comment]
@tschoonj not yet. I'd like to have a `brew revise-formula-pr` that takes a `"--for=#[some other formula}"` argument for the commit message but that doesn't exist yet.

**Comment by dpo** [comment]
Please consider whether this subsumes #3332 and #3832.

**Comment by ilovezfs** [comment]
is 1.10 non-stable release?

**Comment by tschoonj** [comment]
Don't know about #3332 (seems harmless)

Ideally 1.10.0-patch1 one would come here, as it is now officially designated as the stable release. That being said, I have serious doubts about the stability of this release after participating in a webinar by the HDF5 developers a couple of months ago when they released 1.10.0.

To the best of my knowledge, no API was broken in 1.10.0, so all dependent packages should still compile against it.

Perhaps a compromise could be to create a 1.8.17 Formula in Homebrew-Versions, while keeping 1.10.0 here?

**Comment by ilovezfs** [comment]
>I have serious doubts about the stability of this release after participating in a webinar by the HDF5 developers

@tschoonj I tend to trust your judgment :) Maybe it should be the reverse for a while with a hdf5-110 in versions until it gets a TomSchoonjanSealOfApproval? CC @DomT4 @dpo @sjackman for thoughts.

**Comment by dpo** [comment]
We've had two versions of a library in Science before (e.g, SuiteSparse, SuperLU), so I wouldn't be opposed to having `hdf5-110` here with an option to build dependents against it (but that's a lot of formulae to modify).

**Comment by tschoonj** [comment]
It's probably best to make 1.10.0-patch1 the default: the stability issues I was referring to would likely impact those formulas that make use of the SWMR (single write - multiple read) technology that was added. Formulas that need SWMR will have a hard dependency on 1.10.0.

**Comment by ilovezfs** [comment]
@tschoonj thanks for the PR! I shipped it, and also slipped in an audit fix (I hope you don't mind I didn't do this in a separate commit) for the non-library file libhdf5.settings installed in `lib` and corrected the conditional `build.with? "check"` to use the new option `build.with? "test"` since otherwise it won't work. I'll now generate the bottles with the Homebrew Testing job on Jenkins since the location of that file changed. Then I'll open separate PRs for each of those revision bumps. Then we'll do 1.10-patch1 in the next round after that.

**Comment by ilovezfs** [comment]
Bottles shipped in https://github.com/Homebrew/homebrew-science/commit/0e2d0a9153b81ffe8445c6e79d6bfd53555932c7

**Pull request closed without merging**
