### PR TITLE
MLPack: version 1.0.12.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by saketkc** [comment]
Thanks!
Sorry, I am busy with my screening exams.

**Comment by dpo** [comment]
@iml Is this what you were recommending?

**Comment by iml** [comment]
Yeah, but just `ENV.cxx11` since it's non-optional, and `needs` only affects compiler selection.

**Comment by dpo** [comment]
Thanks @iml! We finally have bottles for Mountain Lion! There's still a compilation error in the test on ML that I'm trying to resolve.

**Comment by dpo** [comment]
Thanks @iml and @saketkc !

**Pull request closed without merging**
