### PR TITLE
clark 1.2.2-b

### LINKED ISSUE #3418: clark: 403 Forbidden
```
==> Downloading http://clark.cs.ucr.edu/Download/CLARKV1.1.2.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "clark"
Download failed: http://clark.cs.ucr.edu/Download/CLARKV1.1.2.tar.gz
```

### PR DESCRIPTION
**Pull request by sjackman**
Closes #3418.

### CODE REVIEW

**Comment by sjackman** [comment]
```
 Testing homebrew/science/clark
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160312-65702-18rq2ae.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/clark.rb --verbose
==> CLARK 2>&1
Error: homebrew/science/clark: failed
<255> expected but was
<127>.
```

**Comment by sjackman** [comment]
This version of `clark` no longer installs an executable named `CLARK`.
```
brew list clark
/usr/local/Cellar/clark/1.2.2-b/bin/converter
/usr/local/Cellar/clark/1.2.2-b/bin/getAbundance
/usr/local/Cellar/clark/1.2.2-b/bin/getConfidenceDensity
/usr/local/Cellar/clark/1.2.2-b/bin/getGInTaxID
/usr/local/Cellar/clark/1.2.2-b/bin/getGammaDensity
/usr/local/Cellar/clark/1.2.2-b/bin/getTargetsDef
/usr/local/Cellar/clark/1.2.2-b/bin/getfilesToTaxNodes
/usr/local/Cellar/clark/1.2.2-b/share/doc/ (2 files)
```

**Comment by sjackman** [comment]
@tseemann Any thought on this? Where did the `CLARK` executable go?

**Comment by tseemann** [comment]
The `install.sh` script attempts to check for openmp support
```
## Checking if OPENMP libraries are installed
echo |cpp -fopenmp -dM |grep -i open > .tmp

clang: error: unsupported option '-fopenmp'
```

Then it fails compiling:
```
/.dCLARK/./CLARK_hh.hh:499:8: error: use of undeclared identifier 'open64'; did you mean 'open'?
                fd = open64(_fileTofilesname, O_RDONLY);
                     ^~~~~~
                     open
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/fcntl.h:478:5: note:
      'open' declared here
int     open(const char *, int, ...) __DARWIN_ALIAS_C(open);
        ^
1 error generated.
```

then later fails because it didn't built CLARK:
```
mv: rename ./.dCLARK/CLARK to ./exe/CLARK: No such file or directory
mv: rename ./.dCLARK/CLARK-l to ./exe/CLARK-l: No such file or directory
```

**Comment by sjackman** [comment]
`clark` declares `needs :openmp`. Why is it being build using `clang`? I thought that the default was `gcc` for formula that need `clang`. I've heard OpenMP support is coming to Apple `clang`. Has that happened?

**Comment by dpo** [comment]
No, `clang` doesn't yet have OpenMP support. Here, `cpp` and `gcc`/`g++` are hard-coded in `install.sh`, so it doesn't look like you can use anything other than `gcc` to build this. The `install.sh` script should be modified to make it more generic.

**Comment by dpo** [comment]
ps: I'm getting a `sha256` mismatch.

**Comment by sjackman** [comment]
I thought that `superenv` should take care of using the appropriate compiler, regardless the compiler specified in `install.sh`.

**Comment by dpo** [comment]
I didn't think so. If I add
```
inreplace "install.sh" do |s|
       s.gsub! "g++", ENV["CXX"]
       s.gsub! "cpp", ENV["CXX"]
end
```
to the formula, the values get replaced with `g++-5` when `needs :openmp` is in there, and with `clang++` if I comment it out. I still get compilation errors though.

**Comment by sjackman** [comment]
There are symlinks named `g++` and `cpp` in `Library/ENV/4.3` pointing to `Library/ENV/4.3/cc`
Is `install.sh` modifying the path so that it finds `/usr/bin/g++` before `Library/ENV/4.3/g++`?

**Comment by tseemann** [comment]
I'm trying a fresh one here: https://github.com/Homebrew/homebrew-science/pull/4107

**Comment by jonchang** [comment]
Superceded by #4107.

**Pull request closed without merging**
