### PR TITLE
hdf5 1.10.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
I will probably need to bump some formulas too...

**Comment by iMichka** [comment]
Last time I rebuilt all this with 1 PR for each formula. Because it will be a pain to rebuild everything at once. There are some broken formula in there. Don't know what is the best strategy though.

**Comment by iMichka** [comment]
@tschoonj I hijacked your PR and rebased it on master, and just kept the 2 important commits. Mac bottles are ready, I am waiting for the Linux build to come back. I'm postponing this to tomorrow, it's already late here, and I will probably need to babysit the builds for a few hours :)

**Comment by darryln** [comment]
This change appears to have broken 'brew tap homebrew/science' on  macOS 10.12.5 (Sierra). Says the Alias isn't a file; invalid file name on mac?

```
Machine:~ user$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 694, done.
remote: Compressing objects: 100% (687/687), done.
remote: Total 694 (delta 0), reused 52 (delta 0), pack-reused 0
Receiving objects: 100% (694/694), 637.12 KiB | 0 bytes/s, done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases/hdf5@1.10
Error: Cannot tap homebrew/science: invalid syntax in tap!
Machine:~ user$
```

**Comment by ilovezfs** [comment]
@darryln should be fixed now

**Comment by darryln** [comment]
cool, thanks for the quick response.

**Pull request closed without merging**
