### PR TITLE
rstudio-server 1.1.383

### PR DESCRIPTION
**Pull request by randy3k**
Resubmit it again as homebrew-core doesn't accept formula with binary resources. Hope it will get merged before homebrew-science is deprecated.

Ultimately, rstudio-server may need its own tap.

### CODE REVIEW

**Comment by randy3k** [comment]
@sjackman 

Oddly, with
```
ENV["JAVA_HOME"] = Formula["jdk@8"].prefix
```
CI build passes and Travis CI fails which is the other way round of what I found in earlier PR.

**Comment by randy3k** [comment]
Should I remove `ENV["JAVA_HOME"] = Formula["jdk@8"].prefix` as circle ci is where the bottle is built?

**Comment by sjackman** [comment]
TravisCI error is…
```
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [java] 	... 35 more
     [java]       [ERROR] at RStudioGinjectorImpl.java(9058): GWT.create(RSAccountConnector$Binder.class)
     [java]          com.google.gwt.dev.jjs.ast.JMethodCall
```
https://travis-ci.org/Homebrew/homebrew-science/builds/297787384#L8470

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Homebrew/science, Randy!
I don't watch this repo, so tag me in an issue if you need a PR merged.

**Pull request closed without merging**
