### PR TITLE
ncbi-c++-toolkit 18.0.0

### PR DESCRIPTION
**Pull request by iMichka**
Audit fixes for:
* `head` (line 14) should be put before `bottle block` (line 8)
* Formula should have a desc (Description).
* C: 21: col 21: Freeze mutable objects assigned to constants.
* C: 22: col 23: Freeze mutable objects assigned to constants.
* C: 23: col 26: Freeze mutable objects assigned to constants.

The patch fails to apply and seems not to be needed anymore.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Fails locally for me during the `make install step`:

> cd /private/tmp/ncbi-c++-toolkit-20170206-30699-47g6w5/ncbi_cxx--18_0_0/include && find * -name CVS -prune -o -print |\
            cpio -pd /usr/local/Cellar/ncbi-c++-toolkit/18.0.0/include/ncbi-tools++
65929 blocks
/usr/bin/install -c -m 644 /private/tmp/ncbi-c++-toolkit-20170206-30699-47g6w5/ncbi_cxx--18_0_0/Clang10120-DebugMT64/inc/* /usr/local/Cellar/ncbi-c++-toolkit/18.0.0/include/ncbi-tools++
install: /private/tmp/ncbi-c++-toolkit-20170206-30699-47g6w5/ncbi_cxx--18_0_0/Clang10120-DebugMT64/inc/common: Inappropriate file type or format
make[1]: *** [install-toolkit] Error 71
make: *** [install] Error 2

I stopped the bots because this takes around 1h30 to build. The problem will need to be solved first.
Full gist can be found here: https://gist.github.com/iMichka/eb3e02794dff574f15f8d70d04a9d53a

**Comment by iMichka** [comment]
Looking at the [documentation](https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/public_releases/release_notes.html#release_notes.Platforms_OSs__compi):

> Mac OS X 10.8 (Xcode 3.0 - 3.2.6)
> Ubuntu 9.04 ("jaunty") with GCC 4.3.3 and CentOS 6.x with GCC 4.4.2

Last version is from May 2013.

@ilovezfs I think we should drop this.

**Comment by ilovezfs** [comment]
26 installs in the last 30 days, 144 since July, so seems to be used "sort of"

**Comment by iMichka** [comment]
So how do people do it, because for me the current formula fails with:
> Error: Failed to download resource "ncbi-c++-toolkit"
Download failed: ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/CURRENT/ncbi_cxx--12_0_0.tar.gz

**Comment by ilovezfs** [comment]
Maybe the URL only recently changed? It should be ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/ARCHIVE/12_0_0/ncbi_cxx--12_0_0.tar.gz

**Comment by iMichka** [comment]
Superseded by #5166

Version 18.0.0 does not build, users should make pressure on ncbi to fix their stuff.

**Pull request closed without merging**
