### PR TITLE
mummer: resolve the conflict with gd

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman please, merge it!

**Comment by iMichka** [comment]
> ==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170610-59365-1bwge04.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/mummer.rb --verbose
==> /usr/local/Cellar/mummer/3.23_1/bin/annotate -h 2>&1
Error: homebrew/science/mummer: failed
Expected /U(sage|SAGE)/ to match "sh: /usr/local/Cellar/mummer/3.23_1/bin/annotate: No such file or directory\n".

**Comment by sjackman** [comment]
@tmozgach You'll have to fix the test. One possible fix is…
```diff
-assert_match /U(sage|SAGE)/, pipe_output("#{bin}/#{tool} -h 2>&1")
+assert_match /U(sage|SAGE)/, pipe_output("#{prefix}/#{tool} -h 2>&1")
```

**Comment by iMichka** [comment]
BTW +1 on changing the binary name. Probably better than my change. Thanks for taking care of this.

**Comment by tseemann** [comment]
I agree with changing the mummer `annotate` binary name.  I don't think I've ever used it!

**Comment by tmozgach** [comment]
@sjackman I fixed that, please, merge it!

**Comment by sjackman** [comment]
@tmozgach Please add `revision 1`, then it's good to merge!

**Comment by tmozgach** [comment]
@sjackman Done! Merge it please.

**Comment by iMichka** [comment]
@tmozgach Thanks!

**Comment by sjackman** [comment]
Thanks, Tanya! 🎉

**Pull request closed without merging**
