### PR TITLE
trimal: use pkgshare, add desc

### PR DESCRIPTION
**Pull request by iml**

### CODE REVIEW

**Comment by iml** [comment]
10.10 and 10.9:
```
Testing homebrew/science/trimal
==> trimal 2>&1
Error: homebrew/science/trimal: failed
invalid byte sequence in US-ASCII
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `assert_match'
/usr/local/Library/Taps/homebrew/homebrew-science/trimal.rb:26:in `block in <class:Trimal>'
/usr/local/Library/Homebrew/formula.rb:836:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:832:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'

**Comment by tseemann** [comment]
@iml This issue has happened previously when I first wrote the formula:
https://github.com/Homebrew/homebrew-science/pull/2045

@sjackman wrote: *My guess is that it's specific to the version of Ruby. It works for me. It's almost certainly caused by the accents in the author's name and the region being set to US-ASCII instead of UTF-8*

**Comment by sjackman** [comment]
This issue is probably fixable by changing the encoding from `US-ASCII` to `UTF-8` before using `assert_match`. I'm also totally fine ignoring it and pulling it as is. Your call.

**Comment by iml** [comment]
I can't reproduce it locally so not going to bother with the encoding.

**Comment by sjackman** [comment]
It only affects old versions of Ruby.

**Pull request closed without merging**
