### PR TITLE
vtk: Depends on libxml2 for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?
- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

Fix error:
`Could NOT find LibXml2 (missing: LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR)`

No need to rebuild the Mac bottles when this PR is merged. Please pull the Linux bottle.

### CODE REVIEW

**Comment by sjackman** [comment]
```
[ 12%] Building CXX object Common/Math/CMakeFiles/vtkCommonMath.dir/vtkRungeKutta4.cxx.o
cd /tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/build/Common/Math && /usr/bin/g++-4.8   -DVTK_IN_VTK -DvtkCommonMath_EXPORTS -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/build/Common/Core -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/Common/Core -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/build/Utilities/KWSys -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/Utilities/KWSys -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/build/Common/Math -I/tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/Common/Math  -Os -w -pipe -march=core2   -DNDEBUG -fPIC   -fvisibility=hidden -fvisibility-inlines-hidden -o CMakeFiles/vtkCommonMath.dir/vtkRungeKutta4.cxx.o -c /tmp/vtk-20160616-91790-1ct4jv6/VTK-7.0.0/Common/Math/vtkRungeKutta4.cxx
make[2]: *** No rule to make target `/home/linuxbrew/.linuxbrew/Cellar/python/2.7.11/lib/libpython2.7.dylib', needed by `lib/libvtkWrappingPython27Core-7.0.so.1'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

Looks like a `Makefile` race condition to me.

**Comment by iMichka** [comment]
Could you please review the changes in #4446 ?. We are now more careful when setting `-DPYTHON_LIBRARY`.

**Comment by iMichka** [comment]
@sjackman VTK has been updated to 7.1.0. I think this could be rebased and merged too.

**Comment by iMichka** [comment]
@sjackman #4834 contains the fix and has been merged. I'll let you close this.

**Comment by sjackman** [comment]
Thanks, Michka. Resolved by #4834.

**Pull request closed without merging**
