### PR TITLE
octave 4.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @schoeps

**Comment by schoeps** [comment]
Thanks! It works nicely but octave crashes on exit when using the qt backend for plotting. Try this:
```
graphics_toolkit('qt');
figure;
plot(1:10);
exit;
```

**Comment by ilovezfs** [comment]
@schoeps how splendid!

**Comment by ilovezfs** [comment]
@schoeps I think that goes away on second use.

**Pull request closed without merging**
