### PR TITLE
repeatmodeler 1.0.8

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1878/version=yosemite/testReport/junit/brew-test-bot/yosemite/fetch_blast_boost_hmmer_jpeg_libpng_pcre_recon_repeatmasker_repeatscout_rmblast_trf_xz/
```
==> Downloading https://homebrew.bintray.com/bottles-science/recon-1.07.yosemite.bottle.tar.gz
Warning: Formula reports different SHA256: 2edce365cc98496064c014f68e8ae60fd9be691f7fae10834386acc40f9401d6
Downloaded to: /Library/Caches/Homebrew/recon-1.07.yosemite.bottle.tar.gz
SHA1: dfa6662bc074d8f90c40a2a02ac73cf68f45c29a
SHA256: b3e222db9633614433c6cabd5c2ee46c78f18194421cb4e8df0820608eb90d22
```

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1878/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_Homebrew_science_repeatmodeler/
```
Testing repeatmodeler
==> /usr/local/Cellar/repeatmodeler/1.0.8/bin/RepeatModeler
Failed to execute: /usr/local/Cellar/repeatmodeler/1.0.8/bin/RepeatModeler
Error: repeatmodeler: failed
Failed executing: /usr/local/Cellar/repeatmodeler/1.0.8/bin/RepeatModeler 
/usr/local/Library/Homebrew/formula.rb:843:in `block in system'
/usr/local/Library/Homebrew/formula.rb:800:in `open'
/usr/local/Library/Homebrew/formula.rb:800:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/repeatmodeler.rb:63:in `block in <class:Repeatmodeler>'
/usr/local/Library/Homebrew/formula.rb:743:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:739:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by sjackman** [comment]
```
❯❯❯ brew fetch recon
==> Fetching recon from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/recon-1.07.yosemite
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/recon-1.07.yosemite.bottle.tar.gz
SHA1: dfa6662bc074d8f90c40a2a02ac73cf68f45c29a
SHA256: b3e222db9633614433c6cabd5c2ee46c78f18194421cb4e8df0820608eb90d22
Warning: Formula reports different SHA256: 2edce365cc98496064c014f68e8ae60fd9be691f7fae10834386acc40f9401d6
```

**Comment by iml** [comment]
Somehow the first build was pulled but the bottle from the second build still got uploaded. Console output for non-Yosemite is weird:
```
==> brew cleanup --prune=30						 PASSED
Recording test results
Archiving artifacts
WARN: No artifacts found that match the file pattern "*.bottle*.*". Configuration error?
WARN: ‘*.bottle*.*’ doesn’t match anything

Deleting project workspace... 
done

Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS

**Comment by sjackman** [comment]
Fixed SHA issue in ba4d8c9072255916c40826bd961534bab05f0dcd

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
`brew postinstall repeatmodeler` seems to have no effect at all on the BrewTestBot and leaves the Perl interpreter of `bin/RepeatModeler` as the default `/usr/local/bin/perl`, which fails to execute.

**Comment by sjackman** [comment]
`brew postinstall repeatmodeler` fails unless [Repbase](http://www.girinst.org/repbase/) is installed.

```
Missing full RepeatMasker repeat library!


  The version of RepeatMasker you have selected was installed
  with the minimal RepeatMasker repeat library.  This library
  is not sufficient for use with RepeatModeler and
  RepeatClassifier.  Please obtain the full repeat database
  from http://www.girinst.org and rerun RepeatMasker/configure
  and the RepeatModeler/configure scripts.
```

**Comment by sjackman** [comment]
Unfortunately it still returns a 0 exit code, even when it fails.

**Pull request closed without merging**
