### PR TITLE
wiggletools 1.2.2

### PR DESCRIPTION
**Pull request by dzerbino**
(prepared with brew bump-formula-pr, but hit a snag when pushing, so pushing manually)

### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dzerbino should the resource be updated too?

**Comment by dzerbino** [comment]
Do you mean libbigwig? I guess it could be, did not think of it.

**Comment by ilovezfs** [comment]
>Do you mean libbigwig?

Yup.

**Comment by dzerbino** [comment]
Good idea, thanks. PR updated.

**Comment by ilovezfs** [comment]
Shipped! Thanks for the upgrade

**Pull request closed without merging**
