### PR TITLE
oce: migrate tcl-tk from dupes to core

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> brew test-bot took more than 120 minutes to run
@sjackman Seems there are no llvm linux bottles, so it takes ages to build. 
I don't know how the bottles were built last time, probably there was a llvm bottle at that moment.

**Comment by sjackman** [comment]
`llvm` takes more than 120m to build on CircleCI, so @maxim-belkin built the `llvm` bottle in Docker last time. I believe he's doing that again this time. I've thought of using AWS Batch for formulae that take too long to build on CircleCI. CircleCI 2.0 is by some accounts 2x faster that CircleCI 1.0. We haven't yet migrated.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Error on Travis:
> this isn't a Tk application

We ignored that one last time: #5133

**Pull request closed without merging**
