### PR TITLE
getdp version 2.8.0

### PR DESCRIPTION
**Pull request by schoeps**
update to version 2.8.0 and some clean ups according to `brew audit --strict --online getdp`

### CODE REVIEW

**Comment by dpo** [comment]
There's a build error due to a missing symbol:
https://travis-ci.org/Homebrew/homebrew-science/jobs/118486763#L3957

**Comment by schoeps** [comment]
Sorry, it requires the new gmsh version (is there a way to state this depends_on ... version>xx)?

**Comment by dpo** [comment]
There's a build error on 10.10:
https://travis-ci.org/Homebrew/homebrew-science/jobs/118486762#L2131

**Comment by schoeps** [comment]
I can compile getdp on my 10.10 without error. Maybe the error is due to a (missing?) xcode update? see
https://github.com/Homebrew/homebrew/issues/46832

**Comment by dpo** [comment]
Do you use Xcode 7.3 locally?

**Comment by schoeps** [comment]
I can compile getdp from scratch 
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install getdp
```
using Xcode 7.2 (7C68) on OS X 10.10 in a virtual machine. gcc is
```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posi
```

**Comment by ilovezfs** [comment]
@schoeps If you try Yosemite + Xcode 7.1.1 I think you'll reproduce the 10.10 Travis failure. If you try El Capitan + Xcode 7.3 I think you'll be able to reproduce the 10.11 Jenkins failure.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Now with the metis and petsc refresh, fixed for the latest OS and Xcode versions.

**Comment by schoeps** [comment]
cool. thanks!

**Comment by ilovezfs** [comment]
@schoeps You're welcome, and thanks for the pull request!

**Pull request closed without merging**
