### PR TITLE
Update tasr.rb

### PR DESCRIPTION
**Pull request by warrenlr**
### Have you:
- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [ ] Written a sensible test? (The best test is to compile and run a sample program.)
### Updates to existing formula: have you
- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

update to v1.6

### CODE REVIEW

**Comment by dpo** [comment]
```
Error: No such file or directory - TASR.readme
```
Did you build locally before submitting?

**Comment by warrenlr** [comment]
yes I did, but that's my mistake.. the content of the directory has changed:

TASR-readme.txt

I realize that I need to make additional changes too

For instance, the following subdirectories exist
lib
test
tools

and the additional "TASR-Bloom"

**Comment by dpo** [comment]
```
==> brew audit homebrew/science/tasr
Error: 1 problem in 1 formula
homebrew/science/tasr:
 * Non-libraries were installed to "/usr/local/Cellar/tasr/1.6.0/lib"
Installing non-libraries to "lib" is discouraged.
The offending files are:
  /usr/local/Cellar/tasr/1.6.0/lib/Bloom-Faster-1.6.tar
  /usr/local/Cellar/tasr/1.6.0/lib/Bloom-Faster-1.7.tar
```
Do those files have to be in `lib`?

**Comment by jonchang** [comment]
ping @warrenlr

**Comment by warrenlr** [comment]
We could remove these files from lib:

  /usr/local/Cellar/tasr/1.6.0/lib/Bloom-Faster-1.6.tar
  /usr/local/Cellar/tasr/1.6.0/lib/Bloom-Faster-1.7.tar

as users may fetch these dependencies

**Comment by jonchang** [comment]
Yes, they should be removed. It looks like there are merge conflicts now, could you please rebase and push your changes?

**Comment by iMichka** [comment]
1.6.2 is out. This pull request is superseded by #5210

**Pull request closed without merging**
