### PR TITLE
insighttoolkit: fix Linux build

### PR DESCRIPTION
**Pull request by iMichka**
- expat and USE_SYSTEM_EXPAT is needed for the Linux build.
The VTK formula does something similar.
- The GPU module needs OpenCL, but as we have no OpenCL
formula, that submodule is disabled on Linux. This should
not impact too many people.
- The python paths logic was aligned with the VTK formula.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman Looks like we have Linux bottles :)

**Comment by sjackman** [comment]
Looks like `test do` needs a fix.

```
NaNs==> brew test homebrew/science/insighttoolkit --verbose
Testing homebrew/science/insighttoolkit
==> /usr/bin/g++-4.8 -isystem /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/include/ITK-4.11 -o test.cxx.o -c test.cxx
==> /usr/bin/g++-4.8 test.cxx.o -o test /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKCommon-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKVNLInstantiation-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl_algo-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl-4.11.1.dylib
.
Last 150 lines from /home/travis/.cache/Homebrew/Logs/insighttoolkit/test.02.g++-4.8:
2017-02-06 20:27:55 +0000
/usr/bin/g++-4.8
test.cxx.o
-o
test
/home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKCommon-4.11.1.dylib
/home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKVNLInstantiation-4.11.1.dylib
/home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl_algo-4.11.1.dylib
/home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl-4.11.1.dylib
g++-4.8: error: /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKCommon-4.11.1.dylib: No such file or directory
g++-4.8: error: /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKVNLInstantiation-4.11.1.dylib: No such file or directory
g++-4.8: error: /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl_algo-4.11.1.dylib: No such file or directory
g++-4.8: error: /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl-4.11.1.dylib: No such file or directory
Error: homebrew/science/insighttoolkit: failed
Failed executing: /usr/bin/g++-4.8 test.cxx.o -o test /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKCommon-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libITKVNLInstantiation-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl_algo-4.11.1.dylib /home/linuxbrew/.linuxbrew/Cellar/insighttoolkit/4.11.0_2/lib/libitkvnl-4.11.1.dylib
```
https://travis-ci.org/Homebrew/homebrew-science/builds/198966066#L4112

**Comment by sjackman** [comment]
> `fix Linux build`

The git commit message log I prefer is
`insighttoolkit: Fix for Linuxbrew`
or simply
`insighttoolkit: Fix for Linux`

**Comment by sjackman** [comment]
Thanks, Michka for this fix!

**Comment by iMichka** [comment]
I'll have a look at the travis failure later today, thanks.

**Comment by iMichka** [comment]
Fix for the linux test is here: #5084

**Pull request closed without merging**
