### PR TITLE
sundials: revision for open-mpi

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
I just noticed you don't need to fill out a form to download sundials any more! So now we can update. I DO see a PR in my future!

**Comment by ilovezfs** [comment]
@dpo notice I switched this over to the new version...but still build mysteriously fails on that example though I'm not seeing that locally...

**Comment by ilovezfs** [comment]
oh there's a 2.6 series too? oy...

**Comment by ilovezfs** [comment]
Not sure what's up with cvsHessian_ASA_FSA but it's the criminal.

**Pull request closed without merging**
