### PR TITLE
bcftools 1.5

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
@jonchang  i think this is why I originally had `fails_with :clang`. Any ideas?

```
Undefined symbols for architecture x86_64:
  "_bcf_get_format_values", referenced from:
      _process in GTsubset-20bc1b.o
  "_bcf_hdr_destroy", referenced from:
      _destroy in GTsubset-20bc1b.o
  "_bcf_hdr_dup", referenced from:
      _init in GTsubset-20bc1b.o
  "_bcf_hdr_id2int", referenced from:
      _init in GTsubset-20bc1b.o
  "_bcf_unpack", referenced from:
      _process in GTsubset-20bc1b.o
  "_hts_readlist", referenced from:
      _init in GTsubset-20bc1b.o
  "_hts_version", referenced from:
      _version in version-2ea64b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
GCC has the problems too:
```
Undefined symbols for architecture x86_64:
  "_bcf_get_format_values", referenced from:
      _process in ccbubfid.o
  "_bcf_hdr_destroy", referenced from:
      _destroy in ccbubfid.o
  "_bcf_hdr_dup", referenced from:
      _init in ccbubfid.o
  "_bcf_hdr_id2int", referenced from:
      _init in ccbubfid.o
  "_bcf_unpack", referenced from:
      _process in ccbubfid.o
  "_hts_readlist", referenced from:
      _init in ccbubfid.o
  "_hts_version", referenced from:
      _version in cckWd4xj.o
```
I wonder if it is something to do with them being 'plugins' that are dynloaded at runtime.

**Comment by tseemann** [comment]
I've submitted a new 1.6 PR.

**Pull request closed without merging**
