### PR TITLE
yices 2.5.2 (new formula)

### PR DESCRIPTION
**Pull request by Moisan**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

Upstream also had an [issue](https://github.com/SRI-CSL/yices2/issues/60) to create a homebrew-science package.

### CODE REVIEW

**Comment by Moisan** [comment]
The build fails due to the GitHub repository being not notable enough (<20 forks, <20 watchers and <50 stars). Yices is also available on their [homepage](http://yices.csl.sri.com/) but needs to play but need to agree to a license. Any way to get around either source?

**Comment by iMichka** [comment]
@Moisan You can point use the release files from their GitHub account: https://github.com/SRI-CSL/yices2/releases

For the notability of the project, we made numerous exceptions for projects with less stars and forks. That check is mainly for homebrew-core. So we can ignore this.

**Comment by Moisan** [comment]
@iMichka Great, that's what I used. Is anything else missing to get this merged?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
circleci fail: `webhook returned http status 504, connecting to https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload`
jenkins fail: GitHub repository being not notable enough
travis fail: GitHub repository being not notable enough

Overall, if we ignore the "repository being not notable enough" error, there doesn't seem to be any issue.

**Comment by iMichka** [comment]
Could you fix this, and we are good to go:
> * C: 13: col 22: Trailing whitespace detected.

The webhook error is not a real error per se, we can ignore it. All builds have the same problem.

**Comment by iMichka** [comment]
@Moisan thanks for your contribution!

**Comment by ianamason** [comment]
Hey great job guys. My guess though is that the job is not quite done.
I hope you do not get the idea that I am looking a gift horse in the mouth here,
I just want yices to be the best it can be.

We would like the yices formula to be built using libpoly. So we will need a 
formula for [libpoly](https://github.com/SRI-CSL/libpoly) and have that as a yices
dependency, then configure yices with:

```
./configure --enable-mcsat
```

**Pull request closed without merging**
