### PR TITLE
scram 0.11.6 (new formula)

### PR DESCRIPTION
**Pull request by rakhimov**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by rakhimov** [comment]
Sorry for abusing your CI. I don't have a local environment for testing.

**Comment by rakhimov** [comment]
This package requires C++14 with gcc-4.9 or clang-3.4 or later.
Travis is failing with gcc-4.8.
Is there a way to force CI use clang instead of gcc?

**Comment by ilovezfs** [comment]
You can try
```
fails_with :gcc => "4.8"
depends_on "gcc" if OS.linux?
```

**Comment by rakhimov** [comment]
@ilovezfs Is there a way to say ``needs :cxx14`` (or ``needs :cxx1y``)?

**Comment by ilovezfs** [comment]
Some day: https://github.com/Homebrew/brew/issues/1740

**Comment by rakhimov** [comment]
This is nasty. Travis now downloading gcc-5 and using libraries built with gcc-4.8 ABI.
It is not going to link.

**Comment by rakhimov** [comment]
Hmm... @ilovezfs Travis is stuck. Could you please cancel and restart it?
Thanks. (I am trying to build with clang instead of gcc.)

**Comment by rakhimov** [comment]
@ilovezfs Never mind. It is running.

**Comment by rakhimov** [comment]
The default CI is stuck on my build.

**Comment by rakhimov** [comment]
This is ready to go. Could any managers give feedback or merge?
@ilovezfs Could you help?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@rakhimov Thanks for you contribution. This has been merged now.

**Pull request closed without merging**
