### PR TITLE
diamond 0.7.3: Fix sha256, allow different aclocal versions

### LINKED ISSUE #1940: parsnp 1.1 - Error: SHA1 mismatch (Linux)
```
brew install parsnp -v
==> Installing parsnp from homebrew/homebrew-science
==> Downloading https://github.com/marbl/parsnp/releases/download/v1.1/parsnp-Linux64-v1.1.tar.gz
Already downloaded: /root/.cache/Homebrew/parsnp-1.1.tar.gz
==> Verifying parsnp-1.1.tar.gz checksum
Error: SHA1 mismatch
Expected: 443d2db8b498081b1c608ce8641d25dfcc39ad48
Actual: 7c73daa2dd66c0c8dea4897f30850bace5127ac9
```

### PR DESCRIPTION
**Pull request by saketkc**
Closes #1940

### CODE REVIEW

**Comment by sjackman** [comment]
[Log](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1256/version=yosemite/console)

```
checking for Boost headers version >= 1.53.0... yes
checking for Boost's header version... 1_57
checking for the toolset name used by Boost for g++-4.9... configure: WARNING: could not figure out which toolset name to use for g++-4.9

checking boost/system/error_code.hpp usability... yes
checking boost/system/error_code.hpp presence... yes
checking for boost/system/error_code.hpp... yes
checking for the Boost system library... yes
checking for the flags needed to use pthreads... 
checking for boost/system/error_code.hpp... (cached) yes
checking for the Boost system library... (cached) yes
checking boost/thread.hpp usability... yes
checking boost/thread.hpp presence... yes
checking for boost/thread.hpp... yes
checking for the Boost thread library... (cached) yes
checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... no
configure: error: cannot find the flags to link with Boost program_options
```

**Comment by iml** [comment]
This is a new version, not just an issue with the checksum.

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Why is it necessary to build with boost 1.55? The error message that you're trying to fix should be included in a comment in the formula.

**Comment by saketkc** [comment]
The problem is with the `configure` script, the way it looks for `program_options` header. For some reason it fails to locate them on Mac(It works fine on linux). So the `boost155` attempt was a shot in the dark.

**Comment by sjackman** [comment]
This formula fails to build because it requires OpenMP, which build using GCC, but depends on boost, which is built using clang. Other formula are affected by this issue. See #1593

**Comment by saketkc** [comment]
Superseded by #2029

**Pull request closed without merging**
