### PR TITLE
Petsc 3.6.1 (update)

### PR DESCRIPTION
**Pull request by davydden**
update to 3.6.1. Propagate openblas dependecy to depends_on formule.

### CODE REVIEW

**Comment by tdsmith** [comment]
Do you get crashes if the dependencies don't agree about the blas?

**Comment by tdsmith** [comment]
I guess this is what you're alluding to in #2631. I think this seems fine but what's the failure mode, out of curiosity?

**Comment by davydden** [comment]
it's manly for `linuxbrew`. Imagine what happens if the user writes `brew install slepc` there - it will fail miserably.
In either case, it's good idea to use the same Blas/lapack throughout.

**Comment by dpo** [comment]
I can see it's a good idea to use the same BLAS through the entire chain, but would it really cause a crash (unless one BLAS was 32bit and another 64bit)? Does it crash on Linux?

**Comment by davydden** [comment]
it's not about crashing, it's about not being able to compile on `linuxbrew`. Look at https://github.com/Homebrew/homebrew-science/blob/master/superlu_dist.rb#L31 for example where `superlu_dist` would try to link against `-framework Accelerate` unless it's installed `--with-openblas`.

**Comment by dpo** [comment]
Ok, but that's just because `superlu_dist.rb` isn't ready for Linux. It needs to be changed as in https://github.com/Homebrew/homebrew-science/blob/master/scalapack.rb#L26. Same with `superlu.rb`.

**Comment by davydden** [comment]
To assume that there are `libblas` and `liblapack` (hardcoding `-lblas` and `-llapack`) is not a good/robust way to do it https://github.com/Homebrew/homebrew-science/blob/master/scalapack.rb#L30 . Please, see the discussion here https://github.com/Homebrew/linuxbrew/issues/504 . In a nutshell, there could be numerous different system/vendor blas/lapack.s, each with a different set of libraries files to be linked
against, such as `-L/soft/com/packages/intel/13/079/mkl -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lpthread -lm`.

**Comment by dpo** [comment]
I understand but all Linux distributions have `libblas` and `liblapack` as the standard BLAS option, just like OSX has the `Accelerate` framework. I don't think we support linking against any other BLAS.

**Comment by davydden** [comment]
could we perhaps merge it as the PR does not break anything but makes the formula more consistent in terms of a blas choice? Moreover it has a newer version.

**Comment by dpo** [comment]
I want to make sure it doesn't break `getdp` and `gmsh` (it has in the past).

**Comment by davydden** [comment]
i have `gmsh` installed
```
$ brew info gmsh
davydden/science/gmsh: stable 2.10.0 (bottled), HEAD
Gmsh is a 3D grid generator with a build-in CAD engine.
http://geuz.org/gmsh
/usr/local/Cellar/gmsh/2.9.3 (219 files, 58M)
  Built from source with: --with-fltk --with-petsc --with-slepc
/usr/local/Cellar/gmsh/2.10.0 (221 files, 58M) *
  Built from source with: --with-fltk --with-petsc --with-slepc
```

**Comment by davydden** [comment]
`getdp` installs fine but a test fails:
```
The following tests FAILED:
	  1 - ../demos/magnet.pro (OTHER_FAULT)
```
I am not using this software, but i would notify the developers so that they can investigate it. Perhaps it was failing even before `3.6.1`.

**Comment by dpo** [comment]
I get the same on OSX 10.9. @schoeps Any idea why this test might fail?

**Comment by dpo** [comment]
I confirm that the same test used to fail before the PETSc upgrade.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by schoeps** [comment]
@dpo the problem were the tests of getdp. The good news: getdp seems to work with the newest petsc, too :) I will submit a fix.

**Comment by davydden** [comment]
@dpo do i need to bump `mumps` to avoid using old bottles with the new `openmpi`?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
I think it's better to merge Scalapack first (make it dynamic again), then PETSc should be good for bottles.

**Comment by davydden** [comment]
Never-mind, just saw that u merged it already.

**Comment by davydden** [comment]
Mumps tests on Mavericks and Mountain Lion can't find Scalapack:
```
==> mpirun -np 2 /usr/local/Cellar/mumps/5.0.1_1/share/mumps/examples/ssimpletest < /usr/local/Cellar/mumps/5.0.1_1/share/mumps/examples/input_simpletest_real
dyld: Library not loaded: /usr/local/lib/libscalapack.dylib
  Referenced from: /usr/local/Cellar/mumps/5.0.1_1/share/mumps/examples/ssimpletest
  Reason: image not found
dyld: Library not loaded: /usr/local/lib/libscalapack.dylib
  Referenced from: /usr/local/Cellar/mumps/5.0.1_1/share/mumps/examples/ssimpletest
  Reason: image not found
```

**Comment by tdsmith** [comment]
I suppose it's not a :build dependency, then.

**Comment by tdsmith** [comment]
You can replace `:build` with an empty list (`[]`) in line 18 of mumps.rb.

**Comment by davydden** [comment]
agreed, will do.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
don't understand Jenkins output, don't think it even tried to build PETSc, the only thing I could dig is `Failed to determine (log)`.

**Comment by dpo** [comment]
Bot hiccup. I kicked off a new build.

**Comment by davydden** [comment]
PETSc website is down... Bot couldn't download the tar file.

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
Bot hiccup again...

**Comment by davydden** [comment]
We are good.

**Comment by dpo** [comment]
Thanks! On the with the rest.

**Pull request closed without merging**
