### PR TITLE
opencv: don't compare against nil

### PR DESCRIPTION
**Pull request by rwhogg**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

DevelopmentTools.clang_build_version can return nil in some cases, which lacks
a >= method.

See https://github.com/Linuxbrew/brew/issues/140

### CODE REVIEW

**Comment by dpo** [comment]
> Upstream is working on a general fix for this problem (which is that certain methods return nil, which can't be compared against), but until that fix lands we'll just have to fix individual formulae.

Could you please point to the upstream issue/pr?

**Comment by rwhogg** [comment]
https://github.com/Homebrew/brew/issues/729 appears to be one instance of the problem; there may be others too.

@mistydemeo might have more information on this one.

**Comment by dpo** [comment]
Thanks!

**Comment by sjackman** [comment]
Thanks for this fix, Bob!

**Pull request closed without merging**
