### PR TITLE
Quaff 0.1.1 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
Quaff is a pair HMM for aligning FASTQ reads to FASTA references, with the following features:

it pre-filters and bands the DP algorithms by looking for diagonals with lots of k-mer matches

you can train the pair HMM on sequences using the Forward-Backward algorithm

you can align reads to references using the Viterbi algorithm

you can also align reads to reads (i.e. look for overlaps), using Viterbi

it attempts to model the FASTQ quality scores (using a negative binomial distribution), and also uses k-mer context for modeling substitution and/or gap-opening probabilities

it's highly parallel: multithreaded, can run remote servers, or launch its own temporary Amazon EC2 cluster

### CODE REVIEW

**Comment by ihh** [comment]
Yeah, I seem to have broken the build when gsl-config is not present
I think I've fixed this now, with this release: https://github.com/ihh/quaff/releases/tag/v0.1-alpha.1

**Comment by tseemann** [comment]
Any ideas?

```
brew tap homebrew/science --full
Error: Permission denied - /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-science/brewbot
```

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Probably a transient error... I'm restarting the build.

**Comment by tseemann** [comment]
Sigh:

```
Error: 1 problem in 1 formula
homebrew/science/quaff:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

**Comment by tseemann** [comment]
```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/3025
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-science/pull/3025.patch
==> Applying patch
Applying: Quaff 0.1/1 (new formula)
==> Patch closes issue #3025
Warning: Nonstandard bump subject: Quaff 0.1/1 (new formula)
Warning: Subject should be: quaff: remove stable
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-3025
```

**Comment by dpo** [comment]
https://github.com/Homebrew/homebrew-science/issues/2854#issuecomment-146553766

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
downstream build view show success so this should be pullable now. the error seems to indicate you already have the formula locally where you're attempting to pull it or something.

**Pull request closed without merging**
