### PR TITLE
opencascade 7.1.0

### PR DESCRIPTION
**Pull request by bblacey**
* Use out-of-source build as recommended by OCCT documentation
    * Build and install Overview docs if --with-extras is specified (install doxygen)
    * Install adm/templates if --with-extras is specified
    * Removed deprecated cmake args
    * Reduce install size by over 700MB by installing src without cmake intermediate artifacts
    * Default to building without-extras to reduce bottle size from 258 MB to 36 MB (rarely
      used even by developers)

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by bblacey** [comment]
Homebrew MODs - The [formula line](https://github.com/Homebrew/homebrew-science/pull/5098/files#diff-fb76ace3f8e850e76d9985fe6d96b587L31) that fails on LinuxBrew CI existed in the opencascade 7.0.0 so this PR does not introduce a regression - obviously xcrun is not available under Linux however the bottle-build jobs completed successfully on macOS 10.10, 10.11 and 10.12 as expected.

This is my first Homebrew PR so what is the policy/procedure in this case (i.e. what else do I need to do to prepare this for merge into master)?

**Comment by jonchang** [comment]
The formula shouldn't have even been tested anyway since there's a `depends_on :macos => :snow_leopard` line. @sjackman might know why. Either way, I'll merge this soon.

**Comment by sjackman** [comment]
`depends_on :macos => :foo` is ignored on Linuxbrew.

It looks at first glance like it wouldn't be too hard to get it running on Linux, if you have the time and inclination. The following may be enough:

```ruby
    sdk_path = Pathname.new `xcrun --show-sdk-path`.strip if OS.mac?
…
if OS.mac?
    cmake_args << "-D3RDPARTY_TCL_INCLUDE_DIR:PATH=#{sdk_path}/usr/include/"
    cmake_args << "-D3RDPARTY_TK_INCLUDE_DIR:PATH=#{sdk_path}/usr/include/"
end
```

**Comment by jonchang** [comment]
@bblacey I downloaded `opencascade-7.1.0.tgz` from the official website http://www.opencascade.org, but it's very different than the one provided in the github repository. What is different between the two packages?

**Comment by bblacey** [comment]
@jonchang - nothing significant.  I downloaded the V7_1_1 source from the opencascade git repo using `curl -L -O "http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_1_0;sf=tgz"`

@sjackman - I thought about doing that but it seems to complicate the formula for little value.  I believe I would need to make that type of change in more than one place.  Thoughts of ROI?

Thanks to both of you for the prompt response and feedback!

**Comment by sjackman** [comment]
Looking at the formula, it looks as though it was already working on Linux at one point, so with any luck most of the hard work has already been done.

**Comment by bblacey** [comment]
@sjackman.  So be it.  I have installed LinuxBrew in a Ubuntu VM and am installing the opencascade dependencies now so I can take a look at making opencascade work on LinuxBrew.  This will also allow me to assess the merit of potentially using LinuxBrew for FreeCAD on Linux.

**Comment by sjackman** [comment]
Great. There's also a Docker image for Linuxbrew.
```sh
docker run linuxbrew/linuxbrew
```

**Comment by sjackman** [comment]
The fixes for Linux were made by @davydden in PR https://github.com/Homebrew/homebrew-science/pull/2747 for Opencascade 6.8.0.

**Comment by bblacey** [comment]
@sjackman thanks for pointing me to the linuxbrew docker image. Freeimage actually failed to `brew install` because the installed unzip was incompatible with brew.  A simple `apt-get install unzip` resolved the issue but you may want to update the docker image at some point to include a brew compatible unzip.

I spent some time refactoring the formula to restore the original LinuxBrew scope that existed in OCCT 6.8 but regressed somewhere between OCCT 6.9 and 7.0.  The OCCT 7.1 formula now builds on macOS and Linux but fails on Circle-CI and Travis-CI due to missing system dependencies, x11 being one.  Per the original Linux scope, the formula expects certain apt packages to be installed:
```
On Linux make sure the following libraries are installed:
   sudo apt-get install libgl2ps-dev tcl8.6-dev tk8.6-dev libgl1-mesa-dev libglu1-mesa-dev libxmu-dev libxext-dev libxi-dev
```
I have limited cycles these days so if you know of a quick path, I'm open to ideas, but would really like to move OCCT 7.1 forward for broader macOS community.  The updated formula improves upon many aspects of the build, bottling and install, above and beyond the current production version, albeit without Travis or Circle ci confirmation of Linux compatibility due to missing pre-requisites.  Please advise.

**Comment by sjackman** [comment]
Support for building opencascade on Linux is up to you, and your time and inclination.

> Freeimage actually failed to brew install because the installed unzip was incompatible with brew. A simple apt-get install unzip resolved the issue but you may want to update the docker image at some point to include a brew compatible unzip.

Does `depends_on "unzip" => :build unless OS.mac?` resolve this issue?

> `sudo apt-get install libgl2ps-dev tcl8.6-dev tk8.6-dev libgl1-mesa-dev libglu1-mesa-dev libxmu-dev libxext-dev libxi-dev`

I believe these dependencies are all available on Linuxbrew:
```ruby
unless OS.mac?
  depends_on :x11
  depends_on "gl2ps"
  depends_on "homebrew/dupes/tcl-tk"
  depends_on "linuxbrew/xorg/mesa"
end  
```

@maxim-belkin Is `linuxbrew/xorg/mesa` working?

**Comment by bblacey** [comment]
Shaun, thanks for the quick feedback

>Does depends_on "unzip" => :build unless OS.mac? resolve this issue?

I'm not sure so I decided to give your suggestions a quick go using:
```
+  unless OS.mac?
+    depends_on :x11
+    depends_on "gl2ps"
+    depends_on "homebrew/dupes/tcl-tk"
+    depends_on "linuxbrew/xorg/mesa"
+    depends_on "unzip" => :build
+  end
```
but it failed pretty much out of the gate with...
```
brew install --verbose --build-from-source opencascade
==> Installing opencascade from bblacey/science
==> Tapping linuxbrew/xorg
git clone https://github.com/Linuxbrew/homebrew-xorg /home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg --depth=1 --config core.autocrlf=false
Cloning into '/home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg'...
remote: Counting objects: 185, done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 185 (delta 120), reused 25 (delta 1), pack-reused 0
Receiving objects: 100% (185/185), 72.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (120/120), done.
Checking connectivity... done.
Tapped 174 formulae (205 files, 400.1K)
git config --replace-all homebrew.private false
intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
systemd: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: Unsatisfied requirements failed this build.
```
What's the recommended way to properly handle the "special Perl dependencies" within the context of a brew formula so it will work on Travis and Circle-CI?

**Comment by sjackman** [comment]
`XML::Parser` being broken is a known bug at the moment in Linuxbrew. I'll see if I can find some time to fix it today.

**Comment by maxim-belkin** [comment]
mesa depends on `llvm` so it was not working until recently :)

**Comment by sjackman** [comment]
@maxim-belkin Well that's timely!

**Comment by sjackman** [comment]
TravisCI
```
==> make install
.................
Last 150 lines from /home/travis/.cache/Homebrew/Logs/opencascade/02.make:
/usr/bin/ld: cannot find -lXi
collect2: error: ld returned 1 exit status
make[2]: *** [lin64/gcc/lib/libTKService.so.7.1.0] Error 1
```
https://travis-ci.org/Homebrew/homebrew-science/builds/200246224#L2994

`libxi.so` is provided by `linuxbrew/xorg/libxi`. That error will be resolved by
```ruby
  depends_on :x11
```

**Comment by sjackman** [comment]
> intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`

Was this error message from CI or your local system?

> What's the recommended way to properly handle the "special Perl dependencies" within the context of a brew formula so it will work on Travis and Circle-CI?

@bblacey For CI there's nothing you need to do. On your local system,
```sh
brew install cpanm
cpanm XML::Parser
```

**Comment by bblacey** [comment]
>Was this error message from CI or your local system

Yes, using the Linuxbrew/linuxbgrew docker image.

**Comment by sjackman** [comment]
> Yes, using the Linuxbrew/linuxbgrew docker image.

`brew install perl` also installs `XML::Parser` (in the `postinstall` step).

@bblacey Can you please add these dependencies to your PR?
```ruby
unless OS.mac?
  depends_on :x11
  depends_on "gl2ps"
  depends_on "homebrew/dupes/tcl-tk"
  depends_on "linuxbrew/xorg/mesa"
end  
```

**Comment by sjackman** [comment]
I opened PR https://github.com/Linuxbrew/homebrew-core/pull/1773 to bottle `gl2ps` for Linuxbrew.

**Comment by sjackman** [comment]
`gl2ps` doesn't yet work for Linuxbrew. You'll have to wait until Linuxbrew/homebrew-core#1773 is merged to add `gl2ps` as a dependency to this formula. Is `gl2ps` a strict requirement or an optional dependency?

**Comment by bblacey** [comment]
>On your local system,
>brew install cpanm
>cpanm XML::Parser

Good that the CI systems have this pre-requisite.  I knew how to solve it locally but wasn't sure if I need to do satisfy the pre-req within the context of the formula to make it through the CI systems.

>gl2ps doesn't yet work for Linuxbrew. You'll have to wait until Linuxbrew/homebrew-core#1773 is >merged to add gl2ps as a dependency to this formula. Is gl2ps a strict requirement or an optional >dependency?

gl2ps was a legacy comment from the original Linux port done for OCCT 6.8 and don't think it is a hard requirement.  Will know soon.

**Comment by bblacey** [comment]
@sjackman - thanks for your help.  I have updated the formula for Linuxbrew.  All dependencies required to build on Linuxbrew, other than cpanm, are now declared in the formula.  gl2ps is an optional package for OCCT7.1 so I declared it as `=> :recommended if OS.mac?` until gl2ps is available on Linuxbrew.  Let me know if you want me to squash the two commits into a single "Opencascade 7.1.0" commit before merging.  I left them separate to track the changes from base OCCT 7.1 vs. Linuxbrew for traceability while fleshing out this PR.

**Comment by bblacey** [comment]
@sjackman & @jonchang - it looks like the Travis env does not yet include the [cpan XML::Parser](https://travis-ci.org/Homebrew/homebrew-science/builds/200593707#L1279) dependency however it does on Circle-CI demonstrating Linuxbrew compatibility.  It believe you will want to update the [Travis config](https://github.com/Homebrew/homebrew-science/blob/master/.travis.yml#L8-L16) should be updated to ensure parity with the [Circle CI config](https://github.com/Homebrew/homebrew-science/blob/master/circle.yml#L22).  

Is there anything else that I need to do in order for this PR to be merged into master?

**Comment by jonchang** [comment]
Ok, I've confirmed that the contents of the unofficial github release match that of the download from their git repository. They really don't make it easy for us. I'll merge both mac and linux bottles soon.

**Comment by jonchang** [comment]
Thanks @bblacey for contributing your hard work to Homebrew! This has been merged.

**Comment by sjackman** [comment]
Thanks for putting in the effort to get it working on Linuxbrew, Bruce!

> @sjackman & @jonchang - it looks like the Travis env does not yet include the cpan XML::Parser dependency however it does on Circle-CI demonstrating Linuxbrew compatibility. It believe you will want to update the Travis config to ensure parity with the Circle CI config.

Yes, the Travis configuration needs to be updated.

> @sjackman - another thought is to consider updating the linuxbrew/linuxbrew docker image to ensure parity with Travis and Circle so local development is done in an environment that matches the CI environment.

There's a docker image to emulate the TravisCI configuration: https://github.com/Linuxbrew/docker
We want to do the same thing for CircleCI.

> I think you may even be able to boot the Travis and Circle worker nodes using the linuxbrew/linuxbrew image making the linuxbrew/linuxbrew docker image the since source. Food for thought.

CircleCI is going to better support Docker images in CircleCI 2.0. We're waiting on that. Good idea.

**Pull request closed without merging**
