### PR TITLE
htslib 1.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
@dzerbino this patch version update [seems to break wiggletools](https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/431/version=sierra/testReport/junit/brew-test-bot/sierra/test_wiggletools/) -- any insight on how to fix it?

**Comment by jonchang** [comment]
@dzerbino ILZ used `git bisect` to narrow down the offending commit to this: https://github.com/samtools/htslib/commit/8e96d8ae968ac8e091ba701aca2367ada3b15937

**Comment by dzerbino** [comment]
Thanks for the heads up, looking into it.

**Comment by dzerbino** [comment]
Issue raised with the htslib team: https://github.com/samtools/htslib/issues/535

**Comment by dzerbino** [comment]
Issue was a red herring, the bug was on my side (as usual). I have pushed correction on the WiggleTools repo, need to update the recipe.

**Comment by ilovezfs** [comment]
@dzerbino do you mind marking 1.2.2 as the latest release https://github.com/Ensembl/WiggleTools/releases ?

**Comment by dzerbino** [comment]
Fix is now in PR: https://github.com/Homebrew/homebrew-science/pull/5728

**Comment by dzerbino** [comment]
Marked it as latest release

**Comment by dzerbino** [comment]
Let me know if you need anything else from me, I'm very much a Brew newbie.

**Comment by ilovezfs** [comment]
Thank you @dzerbino

**Comment by iMichka** [comment]
Merged. Thanks all :)

**Pull request closed without merging**
