### PR TITLE
trinity 2.0.3

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error Message

failed: brew test --verbose trinity
Stacktrace

        Testing trinity
==> /usr/local/Cellar/trinity/2.0.3/bin/Trinity --no_distributed_trinity_exec --seqType fq --max_memory 1G --SS_lib_type RF --left reads.left.fq.gz,reads2.left.fq.gz --right reads.right.fq.gz,reads2.right.fq.gz
Error, Trinity requires access to Java version 1.7.  Currently installed version is: java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
Error: trinity: failed
```

**Comment by iml** [comment]
I thought the Java logic was fixed last release.

**Comment by sjackman** [comment]
The java dependency selects the correct Java version for `brew install`, but perhaps it does not for `brew test`. It also does nothing for selecting the correct Java when actually running the tool outside of Homebrew.

**Comment by iml** [comment]
I meant `brew test` worked on the bot in the prior version, but it looks like they changed it to require 1.7 explicitly: https://github.com/trinityrnaseq/trinityrnaseq/commit/271b8537dccae6bb13dba9b322b969df90d9a6fb#diff-16d00ec132daebedc1dc487a10d4261cR793

**Comment by iml** [comment]
We could add `--bypass_java_version_check` though.

**Pull request closed without merging**
