### PR TITLE
blasr: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Reported upstream: https://github.com/PacificBiosciences/blasr/issues/355

**Comment by sjackman** [comment]
@tmozgach The blasr formula is at 2.2. There's two upstream releases since then: 3.0 and 4.0.0. Could you please update the blasr formula to version 4.0.0?
https://github.com/PacificBiosciences/blasr/releases
https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-4.0.0.tar.gz

**Comment by iMichka** [comment]
I thought of doing that too, but they are not marked as the latest release (2.2 is the latest one).

But it may worth a try; if somebody can pick this up I would be glad, I have way too many PR's open :)

**Comment by sjackman** [comment]
> but they are not marked as the latest release

I'm not sure why that is, but my guess is that it's unintentional.

**Pull request closed without merging**
