### PR TITLE
sratoolkit 2.5.2 (update)

### PR DESCRIPTION
**Pull request by tseemann**

### CODE REVIEW

**Comment by tseemann** [comment]
```
Warning: homebrew/science/sratoolkit dependency hdf5 was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
```
Just noticed this formula does *not* have a dependency on HDF5...

**Comment by sjackman** [comment]
I ignore it, unless something breaks. =/

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@sjackman Another error with `--bottle`

```
==> Applying patch
Applying: sratoolkit 2.5.2 (update)
==> Patch closes issue #2454
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ OS\ X\ 10.10.3) --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-2454
```

If I pull without `--bottle` it says there is a bottle there!

**Comment by iml** [comment]
Follow the "downstream build view" link in Jenkins and it will show the attempt at uploading the bottle. Here it looks like the file was already published (probably from running `brew pull --bottle` on an earlier build). You'll need to delete the file in Bintray and retry/rebuild http://bot.brew.sh/job/Homebrew%20Bottles/25897/
```
curl -I --silent --fail --output /dev/null https://homebrew.bintray.com/bottles-science/sratoolkit-2.5.2.mavericks.bottle.tar.gz
Error: sratoolkit-2.5.2.mavericks.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles-science/sratoolkit/view#files

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
