### PR TITLE
upgrade shogun to 6.1.2

### PR DESCRIPTION
**Pull request by vigsterkr**

### CODE REVIEW

**Comment by sjackman** [comment]
`shogun` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is being retired at the end of this year. See https://github.com/Homebrew/homebrew-science/issues/6331

**Comment by vigsterkr** [comment]
ah great then i'm closing this one :)

**Comment by vigsterkr** [comment]
just for the reference: shogun 6.1.3 pr for homebrew-core: https://github.com/Homebrew/homebrew-core/pull/21444

**Comment by sjackman** [comment]
Thanks, Viktor. Please open a PR against Homebrew/science to remove the formula and add it to this file:
https://github.com/Homebrew/homebrew-science/blob/master/tap_migrations.json

**Pull request closed without merging**
