### PR TITLE
salmon 0.3.0: Needs C++11

### PR DESCRIPTION
**Pull request by sjackman**
Fix error: no member named 'all_of' in namespace 'std'
See https://github.com/kingsfordgroup/sailfish/issues/74

### CODE REVIEW

**Comment by sjackman** [comment]
See https://stackoverflow.com/questions/24764478/clang-doesnt-recognize-stdall-of-in-algorithm

**Comment by sjackman** [comment]
Hmm. Still doesn't build on Mountain Lion, even with `needs :cxx11`.

**Comment by sjackman** [comment]
Salmon does require C++11.

**Comment by sjackman** [comment]
Jellyfish fails to build on Mountain Lion for the same reason.

**Comment by iml** [comment]
Might need to set `ENV.libstdcxx if MacOS.version <= :mountain_lion`?

**Comment by sjackman** [comment]
Thanks for the suggestion, Ian. I'm trying it out at https://github.com/Homebrew/homebrew-science/pull/1858

**Comment by sjackman** [comment]
@iml Still fails on Mountain Lion, even with `ENV.libstdcxx if MacOS.version <= :mountain_lion`.
```
  CXX    lib/misc.lo
lib/misc.cc:86:11: error: no member named 'all_of' in namespace 'std'
  if(std::all_of(arg.begin(), arg.end(), isblunt))
     ~~~~~^
1 error generated.
```

**Pull request closed without merging**
