### PR TITLE
libcitygml 1.4.0 (new formula)

### PR DESCRIPTION
**Pull request by kenohori**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Mac audits:
> homebrew/science/libcitygml:
>  * C: 20: col 4: Final newline missing.
>  * File should end with a newline

Please fix this, amend your commit and force push the change to your branch.

Linux build failure is due to:
> /tmp/gdal-20170331-50262-gpjxfc/gdal-1.11.5/.libs/libgdal.so: undefined reference to `curl_multi_info_read'

Seems gdal is missing the curl dependency for Linux? Or libcitygml needs to depend on curl? I think best is to first fix the audits, and push. This will trigger a new Linux build, so we can see if this works.

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
