### PR TITLE
stiff 2.4.0 (new formula)

### PR DESCRIPTION
**Pull request by rillian**
Converts astronomical FITS image files to TIFF for display.

### CODE REVIEW

**Comment by rillian** [comment]
Sorry for the churn. Looks to be working now.

**Comment by dpo** [comment]
Please squash your commits

**Comment by rillian** [comment]
squashed.

**Comment by rillian** [comment]
```
==> brew readall							 FAILED
Error: problem in /home/travis/build/Homebrew/linuxbrew/Library/Formula/abinit.rb
```

Test script error?

**Pull request closed without merging**
