### PR TITLE
meme: add the dependency on ImageMagick

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman, Shaun, Merge it, please.

**Comment by sjackman** [comment]
I'm not able to reproduce this error. What was the error message that you were seeing?

**Comment by tmozgach** [comment]
@sjackman brew test meme
The same error was considered there:
https://github.com/galaxyproject/galaxy/issues/1481

**Comment by sjackman** [comment]
Hi, Tanya. I tested `meme` in the `linuxbrew/linuxbrew` Docker image and found that the dependency on `XML::Parser` is a hard dependency, and `brew test` fails without it. It's only a soft dependency on `imagemagick` though. `brew test` succeeds even when `imagemagick` is not installed. It's only a warning message, as it can still produce an EPS file, though not a PNG file.
```
Warning: Can not convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.
```
As such I'm inclined to close this PR without merging to avoid introducing an unnecessary dependency.

**Pull request closed without merging**
