### PR TITLE
nest: fix python3 brew dependancies

### PR DESCRIPTION
**Pull request by tammoippen**
The homebrew dependencies `numpy`, `scipy` and `matplotlib` need the `with-python3` flag for python3 installation.

Apparently, `nest` changed directory name in the tar, all other files are the same - but still the sha changed.

### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [X] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles? *No effect.*
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Thanks for your contribution.

Changing sha256 is always bad. It's good that this is a GitHub account, and I guess the tar was not hacked and replaced by another one, but a confirmation by upstream would be good.

Could you please bump the revision number to 2, so that new bottles are built. We do want to distribute the new directory structure to homebrew's users.

**Comment by physicalist** [comment]
FWIW, I compared the 'latest' nest-2.12.0.tar.gz with the new sha256 to the one that was in my ~/Library/Caches/Homebrew/nest-2.12.0.tar.gz and found no differences _after_ extraction:
```
~ #> tar xzf ~/Library/Caches/Homebrew/nest-2.12.0.tar.gz
~ #> tar xzf nest-2.12.0.tar.gz
~ #> diff -urd nest-{simulator-,}2.12.0
~ #>
```
However, the .tar.gz files differ in size:
``` ~ #> ls -l nest-2.12.0.tar.gz
-rw-r--r--@ 1 me staff  7386186 Mar 21 22:40 nest-2.12.0.tar.gz
~ #> ls -l /Users/me/Library/Caches/Homebrew/nest-2.12.0.tar.gz 
-rw-r--r--  1 me  staff  7260339 Mar  1 11:44 /Users/me/Library/Caches/Homebrew/nest-2.12.0.tar.gz
~ #>
```
which obviously explains the different sha256. I couldn't find any note on their project site when & why the archive was replaced, without comment or bumping the revision. Surely not just to save 100kb?

Btw @tammoippen, you beat me to it regarding `with-python3`, I meant to submit my own patch tonight :)

**Comment by iMichka** [comment]
@physicalist This is very weird. In general there are some differences when such things happen. Could you please open an issue upstream, and link to it in this issue? When weird things like this happen, I prefer to know what happened. It's not really paranoia, but upstream should know that it is a bad idea to fiddle with release tags.

**Comment by physicalist** [comment]
Well, as @tammoippen pointed out, the directory name was changed in the archive. That should account for the file size change.

**Comment by tammoippen** [comment]
@iMichka Bumped the revision.

**Comment by iMichka** [comment]
@tammoippen Thanks for your contribution; these changes have been merged.

**Pull request closed without merging**
