### PR TITLE
gap: Rename option InstPackages to BuildPackages

### PR DESCRIPTION
**Pull request by alex-konovalov**
Following #3918 by @sjackman, I suggest to rename the `InstPackages` option to `BuildPackages`.

### CODE REVIEW

**Comment by sjackman** [comment]
How about `--with-packages`?

**Comment by sjackman** [comment]
Also add
```ruby
deprecated_option "with-InstPackages" => "with-packages"
```

**Comment by alex-konovalov** [comment]
@sjackman good suggestions, thanks! I've just force-pushed the new version.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Alex.

**Pull request closed without merging**
