### PR TITLE
Superlu_dist (fix)

### PR DESCRIPTION
**Pull request by davydden**
update sha256 as the file was changed upstream.

### CODE REVIEW

**Comment by davydden** [comment]
very strange...
```
ld: file not found: /usr/local/lib/libmpi.1.dylib for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [pddrive] Error 1
```

**Comment by dpo** [comment]
Might be that OpenMPI was recently updated: https://github.com/Homebrew/homebrew/pull/43411. We probably need to bump `parmetis`.

**Comment by davydden** [comment]
I bumped revison of parmetis, let's see...

**Comment by davydden** [comment]
seems to be good!

**Comment by tdsmith** [comment]
Website notes:

>  (Last update: 08/05/2015, minor corrections to a few prototypes)

so assuming the change is benign.

**Comment by tdsmith** [comment]
Thanks for the PR!

**Pull request closed without merging**
