### PR TITLE
gmap-gsnap: Fix make check fail with ENV.deparallelize

### PR DESCRIPTION
**Pull request by harper357**
This is the fix for the issue raised in #5110

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like `brew linkage` is failing on Linux due to a dependency on system libraries:

```
==> brew linkage --test homebrew/science/gmap-gsnap
System libraries:
  /lib/x86_64-linux-gnu/libbz2.so.1.0
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/libz.so.1
No broken dylib links
==> FAILED
```

**Comment by harper357** [comment]
That's weird, I just tried it on the linuxbrew docker and it seemed to work.

**Comment by sjackman** [comment]
I've rebased this PR onto `master` at PR https://github.com/Homebrew/homebrew-science/pull/5655 to give the CI another go at it.
This new PR retains your authorship, @harper357.

**Comment by sjackman** [comment]
Superseded and fixed by https://github.com/Homebrew/homebrew-science/pull/5655
Thanks for your contribution to Homebrew/science!

**Pull request closed without merging**
