### PR TITLE
openfst 1.6.5

### PR DESCRIPTION
**Pull request by stevenbedrick**
Also including bumped versions for opengrm-ngram and opengrm-thrax, both of which depend on openfst.

Minor modifications to descriptions for brew audit compliance.

### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by stevenbedrick** [comment]
If I'm reading through the CI results properly, they failed because the CI server doesn't have Python installed. Any ideas what to do about this?

**Comment by iMichka** [comment]
Yes. You can add `depends_on :python unless OS.mac?` to the dependency list.

**Comment by iMichka** [comment]
By the way, would it be possible to have 1 pull request for each separate formula?

**Comment by stevenbedrick** [comment]
The problem with doing it as multiple pull requests is that the new version of openfst necessitated changes to opengrm-ngram and opengrm-thrax. If I just do one PR for openfst, its tests will fail because it will break its dependent libraries. Unless there's a trick that I'm not aware of for managing this sort of situation?

**Comment by stevenbedrick** [comment]
Thanks for the tip on adding the python dependency!

**Comment by belambert** [comment]
Any hold-up on merging this?

**Comment by sjackman** [comment]
The bottles have expired. Please rebase onto `master`, and `@tag` me when the builds have completed. I'll merge it.

**Comment by sjackman** [comment]
Note that this tap Homebrew/science is being retired at the end of the year. You may wish to create your own tap to house this and similar formulae.
See https://github.com/Homebrew/homebrew-science/issues/6365
and https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

**Comment by stevenbedrick** [comment]
Hi, @sjackman - I was able to rebase and get the rebased version up on this pull request, but I seem to have introduced a merge commit while I was at it. I'm happy to try and clean that up, but am not entirely sure how, or even if it's a problem. Also, one of the CI checks failed, and from looking at its output, it is not clear why...

**Comment by sjackman** [comment]
Yes, please clean up the merge. I'd suggest `git checkout -B  openfst-1.6.5 origin/master` (note that this will command will reset your working copy, and lose any uncommitted work) and then `git cherry-pick` the commits that you want, then `git push --force`.

**Comment by sjackman** [comment]
Note that this tap Homebrew/science is being retired at the end of the year. You may wish to create your own tap to house this and similar formulae.
See https://github.com/Homebrew/homebrew-science/issues/6365
and https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

**Pull request closed without merging**
