### PR TITLE
quast 4.6.0

### PR DESCRIPTION
**Pull request by alexeigurevich**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
Change
```ruby
  if (OS.mac? && MacOS.version <= :mountain_lion) || !OS.mac?
    depends_on "matplotlib"
  else
    # Mavericks and newer include matplotlib
    depends_on "matplotlib" => :python
  end
```
to
```ruby
    depends_on "matplotlib"
```

**Comment by alexeigurevich** [comment]
Just for the history reasons: the original error message was "* python modules should be vendored rather than use deprecated `depends_on "matplotlib" => :python`". I fixed the problem, as Shaun kindly suggested above, and most of the problems have gone. 
However, there are few more issues preventing some tests to successfully complete.
1.  MacOS high_sierra build failed due to a problem in matplotlib 2.0.2 compilation. At the same time, two other MacOS builds (el capitan and sierra) finished successfully.
2. Travis build failed at quast.py --test stage. According to the error message, it looks like the problem is with compilation of both aligners (E-MEM by default and Nucmer as a backup option also failed) and GlimmerHMM gene prediction software, so maybe something is wrong with the C++ compiler or its usage or its dependencies. However, I do not seen any errors related to compilation in the log.

@sjackman do you have any ideas how to fix this?

**Comment by sjackman** [comment]
There's no `high_sierra` bottle for `matplotlib`. That's a separate issue, so I'm going to punt on that particular problem. I'm not sure what's up with the TravisCI failure, but it's not critical. The bottles for Linux are built on CircleCI. I'm merging this PR with the bottles for `el_capitan`, `sierra`, and `x86_64_linux`.

**Comment by sjackman** [comment]
Thanks for your contribution to Homebrew-science!

**Comment by alexeigurevich** [comment]
Thank you for your assistance!

**Pull request closed without merging**
