### PR TITLE
datamash 1.0.7

### PR DESCRIPTION
**Pull request by saketkc**

### CODE REVIEW

**Comment by tseemann** [comment]
@saketkc The desc tag limit of 80 chars *includes* the name of the tool ie "datamash" so you only have 72 chars really.

```
brew audit --strict datamash
==> brew style datamash

1 file inspected, no offenses detected

==> audit problems
homebrew/science/datamash:
 * Description is too long. "name: desc" should be less than 80 characters (currently 86).

Error: 1 problem in 1 formula
```

**Comment by saketkc** [comment]
@tseemann I am a bit confused: (I am setting this all up on a Mac server)
```
 brew audit --strict datamash.rb 
==> brew style datamash

1 file inspected, no offenses detected
```

BTW, my `desc` is 68 characters including everything.

**Comment by tseemann** [comment]
Hmm, i've encountered this issue before too.  I'm not sure what is going on. @iml ?

**Comment by saketkc** [comment]
Shouldn't @BrewTestBot complain in that case?

**Comment by tseemann** [comment]
It all checks out otherwise so I'm accepting it.

**Pull request closed without merging**
