### PR TITLE
poretools: Build a bottle for Linuxbrew: h5py: cc: error: unrecognized command line option '-R'

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Circle
```
    cc -pthread -shared -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -Os -w -pipe -march=core2 -isystem/home/linuxbrew/.linuxbrew/include build/temp.linux-x86_64-2.7/tmp/pip-9a2PpU-build/h5py/defs.o -L/home/linuxbrew/.linuxbrew/opt/hdf5/lib -L/opt/local/lib -L/usr/local/lib -L/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib -R/home/linuxbrew/.linuxbrew/opt/hdf5/lib -R/opt/local/lib -R/usr/local/lib -lhdf5 -lhdf5_hl -lpython2.7 -o build/lib.linux-x86_64-2.7/h5py/defs.so
    cc: error: unrecognized command line option '-R'
```
https://circleci.com/gh/Homebrew/homebrew-science/3214

**Comment by ilovezfs** [comment]
Same error with the older hdf5: https://github.com/Homebrew/homebrew-science/pull/5076

**Comment by sjackman** [comment]
It's an error when building the Python module `h5py`. Its build script is using the command line option `-R` when it should be using `-Wl,-rpath`.

**Comment by ilovezfs** [comment]
right. this is the sort of thing superenv handles.

**Comment by sjackman** [comment]
Yep. Linuxbrew still doesn't have superenv. One day…

**Comment by ilovezfs** [comment]
Could throw a little one-off shim at this one.

**Comment by ilovezfs** [comment]
I'm baffled that upstream doesn't seem to have ever had this reported. I wonder if we're doing something weird that makes it think -R is a good idea on the platform.

**Comment by ilovezfs** [comment]
Oh look! Now they've had it reported hehe

**Comment by sjackman** [comment]
I've got a feeling that the issue is that the `LD` environment variable is being set to `cc`, and they expect it to be set to `ld`. `-R` is a non-standard synonym for `-rpath` for `ld`.

>            For compatibility with other ELF linkers, if the -R option is
           followed by a directory name, rather than a file name, it is
           treated as the -rpath option.

**Comment by ilovezfs** [comment]
maybe we should try ENV["LD"] = "ld" ?

**Comment by sjackman** [comment]
Yep, or simply
```
ENV["LD"] = nil
```

**Comment by sjackman** [comment]
Funny thing is, I don't think Homebrew or Linuxbrew actually sets the `LD` environment variable.

**Comment by ilovezfs** [comment]
Yeah something weird is going on or you'd think this would have been reported by now.

**Comment by sjackman** [comment]
In any case, `cc -R` is broken. It should either be `cc -Wl,-rpath` or `ld -rpath`.

**Comment by ilovezfs** [comment]
I think cc -Wl,-R may work too

**Comment by ilovezfs** [comment]
@sjackman maybe needs to be reported to Cython instead now?

**Comment by sjackman** [comment]
Yeah, I think that's likely. I wanted to first confirm that it's a Cython issue before I reported the bug. I won't have time for that myself though. =/

**Pull request closed without merging**
