### PR TITLE
field3d: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Linux builds fails with:
> compilation terminated.
In file included from src/FieldMapping.cpp:48:0:
export/Field.h:52:36: fatal error: boost/intrusive_ptr.hpp: No such file or directory
 #include <boost/intrusive_ptr.hpp> 
                                    ^
compilation terminated.
In file included from src/FileSequence.cpp:52:0:
export/Log.h:50:34: fatal error: boost/lexical_cast.hpp: No such file or directory
 #include <boost/lexical_cast.hpp>
                                  ^

**Comment by iMichka** [comment]
@sjackman This one may be interesting to fix, because it will help bottle openimagio on Linux.

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/opt/scons/bin/scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Compiling build/linux2/m64/release/ClassFactory.os
Compiling build/linux2/m64/release/DenseFieldIO.os
In file included from src/DenseFieldIO.cpp:44:0:
include/DenseFieldIO.h:51:35: fatal error: boost/intrusive_ptr.hpp: No such file or directory
 #include <boost/intrusive_ptr.hpp>
```
https://travis-ci.org/Homebrew/homebrew-science/builds/231239251#L1738

**Comment by sjackman** [comment]
Those two files `intrusive_ptr.hpp` and `lexical_cast.hpp` are found in the `boost` bottle for Linuxbrew. The issue may be related to `scons`. I have no familiarity with `scons` myself.

**Pull request closed without merging**
