### PR TITLE
update statismo formula for statismo v0.10.2

### PR DESCRIPTION
**Pull request by arnaudgelas**

### CODE REVIEW

**Comment by dpo** [comment]
Still fails. Isn't it `BUILD_TESTING` that you wanted to turn off?

**Comment by arnaudgelas** [comment]
my bad :/, going to fix it right away

**Comment by dpo** [comment]
I'm not familiar with this software but it's really looking for Python:
````
make[2]: *** No rule to make target `/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib', needed by `bin/itkLowRankGaussianProcessImageToImageRegistration'.  Stop.
````

**Comment by dpo** [comment]
It seems like this needs to have `depends_on :python`.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by arnaudgelas** [comment]
@dpo anything left to be fixed?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
