### PR TITLE
Update nextflow to version 0.14.1

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by tdsmith** [comment]
The bot thinks the hash is wrong:

> ==> Fetching nextflow from homebrew/homebrew-science
==> Downloading http://www.nextflow.io/releases/v0.14.1/nextflow
Downloaded to: /Library/Caches/Homebrew/nextflow-0.14.1
SHA1: 18deac143f2ac222e0130e4608f602f05a51c742
SHA256: 08d1166ab989f7933375063389b1620e9916d6f5bc0d4a3354529236da4032c0

**Comment by pditommaso** [comment]
There's something odd here. Looking the jenkins looks it says: 

    Expected: 8d1166ab989f7933375063389b1620e9916d6f5bc0d4a3354529236da4032c0
    Actual: 08d1166ab989f7933375063389b1620e9916d6f5bc0d4a3354529236da4032c0

It looks that there's an extra heading `0` in the hash generated by the CI server. I'm assuming that one is wrong because sha256 hash should be 64 characters length, instead that is 65. 

Any idea why is happening that?

**Comment by tdsmith** [comment]
```
tim@rocketman:tds-004-14-2 eve pilot$ printf 08d1166ab989f7933375063389b1620e9916d6f5bc0d4a3354529236da4032c0 | wc
       0       1      64
```

I think you're counting a newline.

**Comment by pditommaso** [comment]
You were right. Just updated. Thanks.

**Comment by iml** [comment]
Thanks!

**Pull request closed without merging**
