### PR TITLE
openblas: fix symbolic links

### LINKED ISSUE #3737: openblas for linux boottle installation problem
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

- Brief summary of issue:

I got the following erorr when installing the openblas error
```
(bootstrap)-~$ brew install openblas
==> Installing openblas from homebrew/science
==> Downloading https://linuxbrew.bintray.com/bottles-science/openblas-0.2.18.x86_64_li
Already downloaded: /home/ubuntu/.cache/Homebrew/openblas-0.2.18.x86_64_linux.bottle.tar.gz
==> Pouring openblas-0.2.18.x86_64_linux.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /home/ubuntu/.linuxbrew
No such file or directory @ realpath_rec - /home/linuxbrew
Error: No such file or directory @ realpath_rec - /home/linuxbrew
```

However, the `--build-from-source` option works fine.

### PR DESCRIPTION
**Pull request by dpo**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

Fixes #3737

### CODE REVIEW

**Comment by sjackman** [comment]
I haven't had a chance to look into this yet, but something went funny with the `libopenblas.{dylib,so}` symlink. It is missing from the new bottle.

### openblas 0.2.18
```
❯❯❯ ls openblas/0.2.18/lib
cmake                      libopenblas.dylib
libblas.dylib              libopenblasp-r0.2.18.a
liblapack.dylib            libopenblasp-r0.2.18.dylib
libopenblas.a
```

### openblas 0.2.18_1
```
❯❯❯ ls openblas/0.2.18_1/lib
cmake                      libopenblasp-r0.2.18.a
libopenblas.a              libopenblasp-r0.2.18.dylib
```

`libopenblas.dylib` has been disappeared and the symlinks that point to it.

**Comment by sjackman** [comment]
I know why. My suggested patch was bad. My suggestion:
```ruby
    lib.install_symlink "libopenblas.#{so}", "libblas.#{so}"
    lib.install_symlink "libopenblas.#{so}", "liblapack.#{so}"
```
should have been
```ruby
    lib.install_symlink "libopenblas.#{so}" => "libblas.#{so}"
    lib.install_symlink "libopenblas.#{so}" => "liblapack.#{so}"
```
Sorry. I should have mentioned that my suggested code was untested (as is this code).

**Comment by dpo** [comment]
That doesn't end up in the bottle either.

**Comment by sjackman** [comment]
My previous suggested fix works for me. I've submitted PR #3748

**Comment by sjackman** [comment]
I've merged #3748.

**Pull request closed without merging**
