### PR TITLE
sundials: openmp and superlu_mt options, fixes

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@ilovezfs `brew` didn't detect a circular dependency here (`petsc` => `sundials` and `sundials` => `petsc`). I wonder if there are others and what the preferred resolution is?

**Comment by dpo** [comment]
And another issue: cmake is needed in the test, so can't be a `:build` dep.

**Comment by schoeps** [comment]
Thanks for cleaning up my mess :-/

**Comment by dpo** [comment]
@schoeps No worries. I should have looked more closely at your earlier PR but was too busy.

**Comment by dpo** [comment]
Moved the sundials update to #4440.

**Comment by dpo** [comment]
Closing in favor ofv#4440.

**Pull request closed without merging**
