### PR TITLE
nextflow 0.24.1

### PR DESCRIPTION
**Pull request by pditommaso**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by neutric** [comment]
The hash you used in #5311 is fine... Either reopen your previous PR or fix the `sha256` here. No need to open another PR, though. ;)

**Comment by pditommaso** [comment]
Nope. The build failed because there was a problem on binary uploaded on the NF web server. Now it should be fine. Is there any way to trigger the CI builds manually ?

**Comment by neutric** [comment]
@BrewTestBot test this please

**Comment by neutric** [comment]
Apologies. I went and downloaded the binary and the checksum still matched that of the previous PR. Now "retired" makes more sense to me...

Concerning restarting CI builds: for you I believe the only way to force a restart would be to push a new commit (or reset and force push the old one). I am not in my usual environment at the moment, so all I can restart from here is the last one of the three...

**Comment by pditommaso** [comment]
OK, reset and pushed again.

**Comment by iMichka** [comment]
@pditommaso Thanks for your contribution

**Pull request closed without merging**
