### PR TITLE
LSD 0.3b (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by tseemann** [comment]
Are we still restricting s/w on github notability?
```homebrew/science/lsd:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

**Comment by ilovezfs** [comment]
For new formulae, typically yes. Also, the repository has "beta" in the title so that will be another demerit here as well.

**Comment by tseemann** [comment]
@ilovezfs I think published software (with a `# doi` entry) should be exempt.  I don't know why they chose the beta tag, nor why they named their actual repo with that version. Inexperience with git I suspect.

**Comment by tseemann** [comment]
I have pulled, installed and tested and pushed it.

**Comment by ilovezfs** [comment]
@tseemann yeah I don't really think the usual notability guidelines make much sense for homebrew/science. Note that the notability requirement is only checked for a new formula so you won't see it again for this one thankfully.

**Pull request closed without merging**
