### PR TITLE
cd-hit 4.6.4

### PR DESCRIPTION
**Pull request by sjackman**
CD-HIT now requires OpenMP to build.

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3343/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_homebrew_science_cd_hit/
```
Testing homebrew/science/cd-hit
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151009-96951-1onun39.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/cd-hit.rb --verbose
==> /usr/local/Cellar/cd-hit/4.6.4/bin/cd-hit -h
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/lib/gcc/5/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/cd-hit/4.6.4/bin/cd-hit
  Reason: image not found
Error: homebrew/science/cd-hit: failed
<1> expected but was
<nil>.
```

**Comment by sjackman** [comment]
@dpo Have you run into this error before? I added `needs :openmp`.

**Comment by dpo** [comment]
Seems fine to me and it works on my machine:
```
$ otool -L /usr/local/Cellar/cd-hit/4.6.4/bin/cd-hit
/usr/local/Cellar/cd-hit/4.6.4/bin/cd-hit:
	/usr/local/lib/gcc/5/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.21.0)
	/usr/local/lib/gcc/5/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/local/lib/gcc/5/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
I've seen error messages with `@@HOMEBREW_PREFIX@@` in them recently. I'm not sure what that placeholder really is.

**Comment by sjackman** [comment]
@mikemcquaid Any thoughts on this `dyld: Library not loaded: @@HOMEBREW_PREFIX@@/lib/gcc/5/libgomp.1.dylib` error message above?

**Comment by mikemcquaid** [comment]
@sjackman Needs a `brew reinstall` to fix the relocation with `install_name_tool`

**Comment by sjackman** [comment]
@mikemcquaid The error message if from the BrewTestBot. How do I force the BrewTestBot to `brew reinstall`?

**Comment by mikemcquaid** [comment]
@sjackman Weird. Let's try a rebuild and see.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Ah, `cd-hit` is tagged as [`:any_skip_relocation`](https://github.com/Homebrew/homebrew-science/blob/master/cd-hit.rb#L15). That's an error, it seems, and would cause this bug, no?

**Comment by mikemcquaid** [comment]
CC @xu-cheng who worked on that code.

**Comment by xu-cheng** [comment]
The formula used to be `:any_skip_relocation`, but since this PR it becomes `:any`, which is [correctly tagged in CI](https://travis-ci.org/Homebrew/homebrew-science/jobs/84602466#L377). However, when test-bot installs the new bottle, it loads the old formula and mistakes it as `:any_skip_relocation`. In the result, we will see this bug.

Will work on a fix.

**Comment by xu-cheng** [comment]
https://github.com/Homebrew/homebrew/pull/44982

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Fixed. Thanks Mike and Xu.

**Pull request closed without merging**
