### PR TITLE
dynare: revision for gsl

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> SKIPPING: homebrew/science/dynare
A LaTeX distribution is required for Homebrew to install this formula.

Make sure that "/usr/texbin", or the location you installed it to, is in
your PATH before proceeding.
TeXRequirement unsatisfied!

You can install with Homebrew Cask:
  brew cask install mactex

You can download from:
  https://www.tug.org/mactex/
```

**Comment by ilovezfs** [comment]
hmm seems the with-check option does nothing

**Comment by ilovezfs** [comment]
apparently for good reason... it runs forever and a day and then dies with
```
DYNARE_VERSION="4.4.3" TOP_TEST_DIR="/private/tmp/dynare-20161023-43221-19jztgb/dynare-4.4.3/tests" FILESTEM="kalman_filter_smoother/algoH2" \
		octave --no-init-file --silent --no-history run_test_octave.m > kalman_filter_smoother/algoH2.o.log 2>&1
DYNARE_VERSION="4.4.3" TOP_TEST_DIR="/private/tmp/dynare-20161023-43221-19jztgb/dynare-4.4.3/tests" FILESTEM="estimation/fs2000_mc6_mf" \
		octave --no-init-file --silent --no-history run_test_octave.m > estimation/fs2000_mc6_mf.o.log 2>&1
./read_trs_files.sh " estimation/fs2000_mc4.o.trs  estimation/fs2000_mc4_mf.o.trs  estimation/fs2000_mc6.o.trs  estimation/fs2000_mc6_mf.o.trs  estimation/fs2000_MCMC_jumping_covariance.o.trs  estimation/fs2000_initialize_from_calib.o.trs  estimation/fs2000_calibrated_covariance.o.trs  gsa/ls2003.o.trs  ramst.o.trs  ramst_a.o.trs  ramst_static_tag.o.trs  example1.o.trs  example2.o.trs  example1_use_dll.o.trs  example1_with_tags.o.trs  example1_irf_shocks.o.trs  example1_abs_sign.o.trs  example1_macroif.o.trs  t_sgu_ex1.o.trs  osr_example.o.trs  optimal_policy/ramsey.o.trs  optimal_policy/nk_ramsey.o.trs  optimal_policy/nk_ramsey_expectation.o.trs  optimal_policy/nk_ramsey_expectation_a.o.trs  optimal_policy/mult_elimination_test.o.trs  discretionary_policy/dennis_1.o.trs  ramst_initval_file.o.trs  ramst_normcdf_and_friends.o.trs  ramst_vec.o.trs  example1_varexo_det.o.trs  predetermined_variables.o.trs  fs2000_nonstationary.o.trs  fs2000_ssfile.o.trs  comments.o.trs  histval_sto.o.trs  histval_det.o.trs  auxiliary_variables/test1.o.trs  expectations/expectation.o.trs  expectations/expectation_ss.o.trs  expectations/expectation_ss_old.o.trs  expectations/expectation_nested.o.trs  steady_state/walsh1_initval.o.trs  steady_state/walsh1_old_ss.o.trs  steady_state/walsh1_ssm.o.trs  steady_state/walsh1_ssm_block.o.trs  steady_state/multi_leads.o.trs  steady_state_operator/standard.o.trs  steady_state_operator/use_dll.o.trs  steady_state_operator/block.o.trs  steady_state_operator/bytecode_test.o.trs  block_bytecode/ireland.o.trs  block_bytecode/ramst_normcdf_and_friends.o.trs  k_order_perturbation/fs2000k2a.o.trs  k_order_perturbation/fs2000k2_use_dll.o.trs  k_order_perturbation/fs2000k_1_use_dll.o.trs  k_order_perturbation/fs2000k3_use_dll.o.trs  k_order_perturbation/fs2000k2_m.o.trs  k_order_perturbation/fs2000k_1_m.o.trs  k_order_perturbation/fs2000k3_m.o.trs  k_order_perturbation/fs2000k3_p.o.trs  partial_information/PItest3aHc0PCLsimModPiYrVarobsAll.o.trs  partial_information/PItest3aHc0PCLsimModPiYrVarobsCNR.o.trs  arima/mod1.o.trs  arima/mod1a.o.trs  arima/mod1b.o.trs  arima/mod1c.o.trs  arima/mod2.o.trs  arima/mod2a.o.trs  arima/mod2b.o.trs  arima/mod2c.o.trs  data/mod1a.o.trs  fs2000/fs2000.o.trs  fs2000/fs2000a.o.trs  fs2000/fs2000c.o.trs  fs2000/fs2000d.o.trs  fs2000/fs2000e.o.trs  fs2000/fs2000_cmaes.o.trs  fs2000/fs2000_calib.o.trs  fs2000/fs2000_analytic_derivation.o.trs  fs2000/fs2000_missing_data.o.trs  fs2000/fs2000_sd.o.trs  fs2000/fs2000_mode_compute_8.o.trs  homotopy/homotopy1_test.o.trs  homotopy/homotopy2_test.o.trs  homotopy/homotopy3_test.o.trs  bvar_a_la_sims/bvar_standalone.o.trs  bvar_a_la_sims/bvar_and_dsge.o.trs  AIM/fs2000x10L9_L.o.trs  AIM/fs2000x10L9_L_AIM.o.trs  AIM/fs2000x10_L9_L.o.trs  AIM/fs2000x10_L9_L_AIM.o.trs  AIM/fs2000_b1L1L.o.trs  AIM/fs2000_b1L1L_AIM.o.trs  AIM/ls2003_2L0L.o.trs  AIM/ls2003_2L0L_AIM.o.trs  AIM/ls2003_2L2L.o.trs  AIM/ls2003_2L2L_AIM.o.trs  conditional_variance_decomposition/example1.o.trs  dsge-var/simul_hybrid.o.trs  dsge-var/dsgevar_forward_calibrated_lambda.o.trs  dsge-var/dsgevar_forward_estimated_lambda.o.trs  external_function/first_and_2nd_deriv_fcns_provided.o.trs  external_function/first_and_2nd_deriv_fcns_provided_dll.o.trs  external_function/first_deriv_fcn_provided.o.trs  external_function/first_deriv_fcn_provided_dll.o.trs  external_function/no_deriv_fcns_provided.o.trs  external_function/no_deriv_fcns_provided_dll.o.trs  seeds.o.trs  identification/kim/kim2.o.trs  identification/as2007/as2007.o.trs  simul/example1.o.trs  conditional_forecasts/fs2000_cal.o.trs  conditional_forecasts/fs2000_est.o.trs  recursive/ls2003.o.trs  recursive/ls2003_bayesian.o.trs  ms-sbvar/test_exclusions.o.trs  ms-sbvar/test_exclusions_nc.o.trs  ms-sbvar/test_lower_cholesky.o.trs  ms-sbvar/test_lower_cholesky_a.o.trs  ms-sbvar/test_lower_cholesky_nc.o.trs  ms-sbvar/test_upper_cholesky.o.trs  ms-sbvar/test_upper_cholesky_nc.o.trs  ms-sbvar/test_ms_variances.o.trs  ms-sbvar/test_ms_variances_repeated_runs.o.trs  kalman_filter_smoother/gen_data.o.trs  kalman_filter_smoother/algo1.o.trs  kalman_filter_smoother/algo2.o.trs  kalman_filter_smoother/algo3.o.trs  kalman_filter_smoother/algo4.o.trs  kalman_filter_smoother/algo4a.o.trs  kalman_filter_smoother/algo4b.o.trs  kalman_filter_smoother/algoH1.o.trs  kalman_filter_smoother/algoH2.o.trs  kalman_filter_smoother/algoH3.o.trs  kalman_filter_smoother/fs2000.o.trs  kalman_filter_smoother/fs2000_1.o.trs  kalman_filter_smoother/fs2000_2.o.trs  kalman_filter_smoother/fs2000a.o.trs  second_order/burnside_1.o.trs  second_order/ds1.o.trs  second_order/ds2.o.trs  ep/rbc.o.trs  ep/rbc2.o.trs  ep/rbcii.o.trs  ep/linear.o.trs  deterministic_simulations/deterministic_model_purely_forward.o.trs  deterministic_simulations/deterministic_model_purely_backward.o.trs  deterministic_simulations/rbc_det1.o.trs  deterministic_simulations/rbc_det2.o.trs  deterministic_simulations/rbc_det3.o.trs  deterministic_simulations/rbc_det4.o.trs  deterministic_simulations/rbc_det5.o.trs  walsh.o.trs  measurement_errors/fs2000_corr_me_ml_mcmc/fs2000_corr_ME.o.trs  trend_var/fs2000_nonstationary.o.trs  trend_var/fs2000_log_nonstationary.o.trs  third_order/FV2011.o.trs  shock_decomposition/example1_calib_shock_decomp.o.trs  shock_decomposition/fs2000_est.o.trs  shock_decomposition/fs2000_est_varlist.o.trs  stochastic_purely_forward/stochastic_purely_forward.o.trs  stochastic_purely_forward/stochastic_purely_forward_with_static.o.trs  gradient/fs2000_numgrad_13.o.trs  gradient/fs2000_numgrad_15.o.trs  gradient/fs2000_numgrad_2.o.trs  gradient/fs2000_numgrad_3.o.trs  gradient/fs2000_numgrad_5.o.trs  filter_step_ahead/fs2000_filter_step_ahead_bayesian.o.trs  filter_step_ahead/fs2000_filter_step_ahead_ML.o.trs  loglinear/example4_loglinear.o.trs run_block_byte_tests_octave.o.trs run_reporting_test_octave.o.trs run_all_unitary_tests.o.trs" " ramst_xfail.o.trs  estim_param_in_shock_value.o.trs"
grep: run_all_unitary_tests.o.trs: No such file or directory
./read_trs_files.sh: line 13: ((: total += : syntax error: operand expected (error token is " ")
grep: run_all_unitary_tests.o.trs: No such file or directory
./read_trs_files.sh: line 17: [: -ne: unary operator expected
Octave Tests Done
cat: run_test_matlab_output.txt: No such file or directory
make[2]: *** [check-local] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by houtanb** [comment]
@ilovezfs though I know the standard on hombrew is to build with-check, I would recommend without because the check on Octave takes 6 hours or so (It takes 1 hour on Matlab for the same set of tests, but even this is too long). Is it possible to change `option "without-test", "Disable build-time checks (not recommended)"` to `option "without-test", "Disable build-time checks (recommended)"` or even to change `without-test` to `with-test`, disabling the check by default?

**Comment by ilovezfs** [comment]
It would be good to know why it's failing before disabling it.

Also, hopefully someone who has matlab installed can verify I didn't break anything!

**Comment by houtanb** [comment]
@ilovezfs I don't know why it's not finding `run_all_unitary_tests.o.trs` as we run the test suite every night and this is found. That said, we run the test suite on the HEAD not on 4.4.3. Do you have the rest of the test output?

**Comment by ilovezfs** [comment]
Not anymore but I'm wondering if the tests actually require matlab since it says

`cat: run_test_matlab_output.txt: No such file or directory`

**Comment by houtanb** [comment]
Also, you should know that 4.4.3 was released on 31 July 2014 and is compatible with Octave 3.8. We had a lot of problems with 4.0 and the HEAD works (with errors) on 4.2. We are working on fixing these to align the test results with Matlab.

**Comment by houtanb** [comment]
@ilovezfs There was a bug in the test suite where we didn't forsee runinng the matlab or octave tests independently. This has been fixed in master

**Comment by ilovezfs** [comment]
@houtanb let's just disable the test-suite entirely until upstream actually expects it to pass with stable, HEAD, or both.

**Comment by ilovezfs** [comment]
@houtanb PR refreshed.

**Comment by houtanb** [comment]
@ilovezfs thanks for your work.

I agree that we should disable the test suite, perhaps forever. It won't help our users to run the 6 hour test suite on Octave or the 1 hour test suite on Matlab. 

I just ran the refreshed PR. The `HEAD` install works for Octave and Matlab, after I pushed DynareTeam/dynare@bc8a7f1b096e0634aef0507d78d12a9d4ab45a56. For the stable version, would it be possible to `inreplace` `10.6` with `10.7` in `m4/ax_mexopts.m4`? Stable should then build for Octave and Matlab. I can't really `cherry-pick` the commit because we stopped updating the stable branch a while back. We will (hope) to release a new stable sometime in the next few months.

**Comment by ilovezfs** [comment]
@houtanb PR refreshed. Also, please check `brew test -v dynare` since that's where I'm most concerned about whether there are octave and/or matlab issues with the changes I made.

**Comment by houtanb** [comment]
@ilovezfs the octave test was fine. The Matlab test gave the following error. Could the problem be the space between `/Applications/MATLAB_R2016b.app` and `/bin/matlab`?
```
==> /Applications/MATLAB_R2016b.app
/bin/matlab -nosplash -nodisplay -r addpath /usr/local/Cellar/dynare/4.4.3_2/lib/dynare/matlab; dynare bkk.mod console; exit
Failed to execute: /Applications/MATLAB_R2016b.app
/bin/matlab
Error: homebrew/science/dynare: failed
Failed executing: /Applications/MATLAB_R2016b.app
/bin/matlab -nosplash -nodisplay -r addpath\ /usr/local/Cellar/dynare/4.4.3_2/lib/dynare/matlab;\ dynare\ bkk.mod\ console;\ exit
/usr/local/Homebrew/Library/Homebrew/formula.rb:1733:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1671:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1671:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/dynare.rb:129:in `block in <class:Dynare>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1571:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1570:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by ilovezfs** [comment]
What directory inside the app bundle has the "bin" directory containing a "matlab" executable? Is it really just hanging out in the .app dir itself not inside like MATLAB_R2016b.app/Contents/bin/matlab?

Also please try changing
```
matlab_path = File.read(prefix/"matlab.config").lines.first
```
to
```
matlab_path = File.read(prefix/"matlab.config").lines.first.chomp
```

**Comment by ilovezfs** [comment]
@houtanb ^^

**Comment by houtanb** [comment]
Hi @ilovezfs, sorry for the delay in reply--I had left the office before receiving your last message. The Matlab executable is located in `/Applications/MATLAB_R2016b.app/bin/matlab`. No `Contents` directory.

Appending `.chomp` works. Thanks for all of your work.

**Comment by ilovezfs** [comment]
@houtanb you're welcome. Thank you for testing that.

**Comment by houtanb** [comment]
@ilovezfs anytime

**Comment by ilovezfs** [comment]
@houtanb PR refreshed.

**Comment by houtanb** [comment]
@ilovezfs `brew test -v dynare` worked well.

Thanks!

**Comment by ilovezfs** [comment]
@houtanb shipped! Now `dynare` has bottles :)

**Comment by houtanb** [comment]
Great!! Now, a question: is it possible for me to add to the bottles mex files that would work with Matlab?

**Comment by ilovezfs** [comment]
@houtanb probably. Are they additional files or changes to the files the bottle currently installs?

**Comment by houtanb** [comment]
@ilovezfs they are files that would be installed if the user had a local installation of Matlab. What I'm thinking is that, for the stable version, I can provide these mex files for the bottles. The head would be trickier because the mex files would have to be updated in the bottles whenever the source they're built from is updated. The goal of all this would be to allow our users to install dynare via homebrew without needing to download all of the dependencies needed to build it.

**Comment by dpo** [comment]
@ilovezfs You need Matlab to generate those mex files.

@houtanb Do you have Matlab on all supported architectures?

We have other formulas with Matlab support; users must build from source.

**Comment by houtanb** [comment]
@dpo I could make mex files that would work on the supported architectures. In fact, they're currently distributed with our installation package: http://www.dynare.org/download/dynare-stable/dynare-for-mac-os-x . There are three sets of them, depending on the version of Matlab the user has, located in `/Applications/Dynare/4.4.3/mex/matlab/`

**Comment by ilovezfs** [comment]
The bottles are linked to
```
fftw
gcc
gsl
homebrew/science/hdf5
homebrew/science/libmatio
homebrew/science/metis
homebrew/science/octave
homebrew/science/suite-sparse
homebrew/science/veclibfort
readline
```
So the user will have to install those regardless.

**Comment by houtanb** [comment]
@ilovezfs ok, so perhaps it's not of much use to add the mex files

**Comment by ilovezfs** [comment]
All the dependencies have bottles too, so it still may be worth pursuing.

**Comment by ilovezfs** [comment]
Note also that you have to have the CLT installed for `gcc` to pour from the bottle, otherwise gcc builds from source, which takes a while.

**Comment by houtanb** [comment]
@ilovezfs thanks for the info. Basically, if it'd be easy to add mex files to the stable distribution bottles, I'd like to do that. Otherwise, we can just leave the formula as is. It's still very useful and our sole mode of distributing our software to Octave users on macOS

**Comment by dpo** [comment]
How large are the mex files?

**Comment by houtanb** [comment]
15MB for all mex files on all Matlab versions

**Comment by ilovezfs** [comment]
```
iMac-TMP:ex joe$ otool -L  ./mex/matlab/osx64/sparse_hessian_times_B_kronecker_C.mexmaci64 
./mex/matlab/osx64/sparse_hessian_times_B_kronecker_C.mexmaci64:
	@loader_path/libmx.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libmex.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libmat.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 56.0.0)
	@loader_path/libmwlapack.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libmwblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```
What provides those libraries? matlab or dynare or something else?

**Comment by houtanb** [comment]
Matlab:
```
/Applications/MATLAB_R2016b.app/bin/maci64
• ls -la libmx.dylib libmex.dylib libmat.dylib libmwlapack.dylib libmwblas.dylib 
-r-xr-xr-x  1 houtanb  admin   432K Jul 22 14:43 libmat.dylib*
-r-xr-xr-x  1 houtanb  admin   205K Jul 22 16:09 libmex.dylib*
-r-xr-xr-x  1 houtanb  admin    84K Jul 22 15:54 libmwblas.dylib*
-r-xr-xr-x  1 houtanb  admin   1.4M Jul 22 15:55 libmwlapack.dylib*
-r-xr-xr-x  1 houtanb  admin   1.6M Jul 26 16:56 libmx.dylib*
```

**Comment by ilovezfs** [comment]
So one question is whether it's possible to convince the dynare build to build with the matlab option enabled without actually having matlab itself installed. Or is the creation of these mex files actually all that the option controls anyway?

**Comment by houtanb** [comment]
The creation of these mex files is the only thing that option controls. If you pass the `--with-matlab=` option to the `configure` script and a valid Matlab installation is not found, the `configure` script will continue processing, deciding not to build the `mex` files when `make` is run. In other words, this option helps the `configure` script find Matlab and, if it's found, the `mex` files will be built. If it's not found (either the option is missing or an incorrect path was provided), only `mex` files for Octave will be built, provided it was found by the `configure` script

**Comment by dpo** [comment]
Couldn't the mex files just be downloaded as resources?

**Comment by ilovezfs** [comment]
@dpo yup, but they may violate someone's religion since they're binaries.

**Comment by dpo** [comment]
License-wise?

**Comment by ilovezfs** [comment]
I think it may be best to just toss them into the bottle prebuilt and let the octave-only users complain about the extra 15MB to houtanb :)

**Comment by houtanb** [comment]
@dpo yes. This is feasible too. I was just trying to think of a way to simplify the process for our users. I don't know how comfortable they'd be with installing files to `/usr/local` by hand (our Matlab paths are set relative to the installation path). But, please, don't worry about this. It was just a request if it was something that was easy to do. I do not want to take up your and @ilovezfs time because, regardless, we will continue to make installation packages.

**Comment by dpo** [comment]
If we download them as resources, they'll be built into the bottles, and that will enable us to update bottles in the future without human intervention.

**Comment by houtanb** [comment]
@dpo ah, I didn't know that. Ok, then, yes, let's do that, if it's not too much work on your end. I can put them up somewhere on our site so they can be downloaded directly.

**Comment by ilovezfs** [comment]
what path are they ultimately supposed to end up installed to?

**Comment by houtanb** [comment]
`{homebrew_prefix}/Cellar/dynare/4.4.3_2/lib/dynare/mex`

**Comment by dpo** [comment]
Seems fine to me. @houtanb Why don't you put them up somewhere on the Dynare website?

**Comment by ilovezfs** [comment]
```
  resource "matlab-mex-files" do
    url "somewhere"
    sha256 "something"
  end
...

  def install
  ...

    (lib/"dynare/mex").install resource("matlab-mex-files")
```

if you want to play around with it.

**Comment by houtanb** [comment]
@dpo doing that now. I'll let you know when it's done
@ilovezfs I think that's ok. Do you want them all in a tar ball?

**Comment by ilovezfs** [comment]
@houtanb Yes `.tar.gz` or `.tar.xz` and `(lib/"dynare/mex").install resource("matlab-mex-files")` will automatically unpack the tarball into that directory.

**Comment by houtanb** [comment]
Here are the `mex` files: http://www.dynare.org/stable-mex-homebrew/matlab.tar.xz

They'll untar to `matlab` so you can replace `/Cellar/dynare/4.4.3_2/lib/dynare/mex/matlab` with the folder from this tar ball.

**Pull request closed without merging**
