### PR TITLE
libpoly (new formula)

### PR DESCRIPTION
**Pull request by Moisan**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

This a new formula for libpoly. It was requested by the team upstream as a dependency for Yices in #5757 and in the [Yices issues](https://github.com/SRI-CSL/yices2/issues/60). All tests passes except the one regarding the size of the repository (stars and forks numbers). It wasn't an issue for Yices so I guess this can be ignored.

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Build errors on Mac and Linux. Possibly missing `depends_on "gmp"` and `depends_on :python`?

Mac error: 

```
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:33 (MESSAGE):
  Could not the GMP number library (sudo apt-get install libgmp-dev)
```

Linux:

```
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "polypy" in directory /tmp/libpoly-20170710-42243-1nvd82m/libpoly-0.1.3/python
```

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
The checks only seem to fail on "GitHub repository not notable enough".

**Comment by ianamason** [comment]
Is it possible that we can make progress on this? We would like to update our yices formula,
and having a libpoly formula would be much appreciated.

Let me know if there is anything I can do to help this process along.

**Comment by iMichka** [comment]
Woups forgot to close here.

We updated our "new formula" policy for homebrew-science:

We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

See also #6365 for the discussion about what is going to happen with homebrew-science.

**Comment by ianamason** [comment]
Thanks for the info @iMichka   so I went ahead and did as you suggested. 

SRI now hs its own [tap](https://github.com/SRI-CSL/homebrew-sri-csl)

I guees that means we would prefer not to have yices.rb migrate from homebrew-science to
homebrew-core. Is this easy to achieve?

Thanks in advance, Ian.

**Comment by iMichka** [comment]
See #6365 again; the discussion is going on there about the future of homebrew-science. We are looking for some tap maintainers that would be willing to join a sort of new `brew science` org.

**Pull request closed without merging**
