### PR TITLE
vtk: Depends on linuxbrew/xorg/mesa for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error:
```
Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
```

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
TravisCI timed out while building `llvm`.
https://travis-ci.org/Homebrew/homebrew-science/builds/209863025#L5494

**Comment by sjackman** [comment]
```
==> brew install ./vtk-7.1.0_6.x86_64_linux.bottle.1.tar.gz
==> Installing vtk from homebrew/science
==> Installing dependencies for homebrew/science/vtk: linuxbrew/xorg/xtrans, inputproto, kbproto, xextproto, xproto, linuxbrew/xorg/xproto, readline, openssl
==> Installing homebrew/science/vtk dependency: linuxbrew/xorg/xtrans
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/xtrans-1.3.5.x86_64_linux.bottle.tar.gz
Already downloaded: /home/travis/.cache/Homebrew/xtrans-1.3.5.x86_64_linux.bottle.tar.gz
==> Pouring xtrans-1.3.5.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/xtrans/1.3.5: 14 files, 315.3K
==> Installing homebrew/science/vtk dependency: inputproto
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/inputproto-2.3.2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/travis/.cache/Homebrew/inputproto-2.3.2.x86_64_linux.bottle.tar.gz
==> Pouring inputproto-2.3.2.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/inputproto/2.3.2: 10 files, 259.1K
==> Installing homebrew/science/vtk dependency: kbproto
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/kbproto-1.0.7.x86_64_linux.bottle.tar.gz
Already downloaded: /home/travis/.cache/Homebrew/kbproto-1.0.7.x86_64_linux.bottle.tar.gz
==> Pouring kbproto-1.0.7.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/kbproto/1.0.7: 10 files, 169.2K
==> Installing homebrew/science/vtk dependency: xextproto
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/xextproto-7.3.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/travis/.cache/Homebrew/xextproto-7.3.0.x86_64_linux.bottle.tar.gz
==> Pouring xextproto-7.3.0.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/xextproto/7.3.0: 38 files, 218.5K
==> Installing homebrew/science/vtk dependency: xproto
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/xproto-7.0.31.x86_64_linux.bottle.tar.gz
Already downloaded: /home/travis/.cache/Homebrew/xproto-7.0.31.x86_64_linux.bottle.tar.gz
==> Pouring xproto-7.0.31.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/xproto/7.0.31: 33 files, 496.0K
==> PASSED
==> brew test homebrew/science/vtk --verbose
Error: Testing requires the latest version of homebrew/science/vtk
==> FAILED
```
https://travis-ci.org/Homebrew/homebrew-science/builds/210759923#L7032
I think this is a bug in `brew`.

**Comment by sjackman** [comment]
The bottle built successfully, though it wasn't tested with `brew test` due to the above bug. Merging anyways.

**Pull request closed without merging**
