### PR TITLE
SHRiMP 2.2.3 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
SHRiMP is a software package for aligning genomic reads against a target genome. It was primarily developed with the multitudinous short reads of next generation sequencing machines in mind, as well as Applied Biosystem's colourspace genomic representation.

### CODE REVIEW

**Comment by tseemann** [comment]
Only failure was for Mountain Lion - something to do with OpenMP I assume?

```
llvm-g++ -g -O2 -DNDEBUG -mmmx -msse -msse2 -fopenmp -Wall -Wno-deprecated -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DGIT_VERSION=e507fc8 -c -o gmapper/seeds.o gmapper/seeds.c
In file included from gmapper/seeds.h:8,
                 from gmapper/seeds.c:5:
gmapper/gmapper.h:252: sorry, unimplemented: threadprivate variables not supported in this target
gmapper/gmapper.h:294: sorry, unimplemented: threadprivate variables not supported in this target
In file included from gmapper/gmapper.h:298,
                 from gmapper/seeds.h:8,
                 from gmapper/seeds.c:5:
gmapper/../common/f1-wrapper.h:40: sorry, unimplemented: threadprivate variables not supported in this target
make: *** [gmapper/seeds.o] Error 1
```

**Comment by iml** [comment]
Add `fails_with :llvm`. `:openmp` doesn't blacklist llvm-gcc but probably should.

**Comment by tseemann** [comment]
Thanks @lml 
@BrewTestBot test this please

**Comment by tseemann** [comment]
@sjackman Looks good to go.

**Comment by sjackman** [comment]
Thanks, Torsten.

**Pull request closed without merging**
