### PR TITLE
getdp 2.6.0

### PR DESCRIPTION
**Pull request by schoeps**
New version. Requires an updated gmsh.rb to compile

### CODE REVIEW

**Comment by schoeps** [comment]
Error is probably due to broken dependency (e.g. petsc) that rely on an old gcc.

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by schoeps** [comment]
has this error something to do with the formula?

**Comment by dpo** [comment]
Please squash.

**Comment by schoeps** [comment]
done

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@schoeps - it seemed to build ok but the formula needs some alterations:
```
brew audit --strict getdp
==> brew style getdp
== getdp.rb ==
C:  4: 25: Use def with parentheses when there are parameters.
C: 22:  8: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 36:  1: Extra empty line detected at method body beginning.
C: 51: 37: Prefer double-quoted strings inside interpolations.
C: 56: 30: Use || instead of or.
C: 70:  1: Extra empty line detected at class body end.

1 file inspected, 6 offenses detected

==> audit problems
homebrew/science/getdp:
 * `head`(line 22) should be put before `bottle block`(line 14)
 * A `test do` test block should be added
 * Formula should have a desc (Description).
 * `require "formula"` is now unnecessary

Error: 4 problems in 1 formula
```

**Comment by schoeps** [comment]
Done. However, do you really want to have external contributions? It is quite demotivating. The logic of the formula has not changed since my initial commit (~1.5 month ago). I have been fixing every small bit immediately but the formula is still not approved.

**Comment by tseemann** [comment]
@schoeps I understand your frustration! I have been going through the same issues as you. It drives me crazy some times.  

The official brew style seems to have changed over the few months. I think the "Style" problems are not as serious as the "audit" problems. The main one is you have **no** test whatsoever, so we can't easily just see if it runs. 

I am new to this, and am just following the rules for accepting formulae.  Perhaps @sjackman @iml @dpo can give some advice here.

**Comment by schoeps** [comment]
I hope you saw that I have added a test in my latest commit? In either case, thanks for doing this work.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@schoeps Sorry for the long delay. The past month has been very busy for me. I'll merge this today.

**Comment by dpo** [comment]
For some reason I'm not able to pull this bottle. I'm getting a curl error. @tseemann could you see if you're able to pull it? It's ready to go.

**Comment by xu-cheng** [comment]
@dpo This PR's [bottle uploading job](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2419/downstreambuildview/) fails. You need to manually fix [the problem](http://bot.brew.sh/job/Homebrew%20Bottles/26053/console) then rerun the uploading job.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@xu-cheng I've no idea what the problem is or how to begin fixing it. I'm having the same issue with other PRs. What's the procedure?

**Comment by xu-cheng** [comment]
@dpo If you cannot pull bottle, it usually means "Homebrew Bottles" job failed. You can find it on the left side of [PR CI page](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2476/) which calls ["Downstream build view"](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2476/downstreambuildview/). You should re-run the Homebrew Bottles job and maybe fix the problem shown on the CI log.

**Comment by schoeps** [comment]
is there anything that I can do? I have three pending requests (gmsh,getdp,qhull) and IMHO they fulfill all homebrew standards....

**Comment by sjackman** [comment]
@dpo To handle a formula with stale bottles, do the following:
1. Delete the stale bottles from Bintray: https://bintray.com/homebrew/bottles-science/getdp#files
2. Trigger a rebuild of BrewTestBot: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2476/
3. Pull the PR

I've done 1 and 2.

**Comment by dpo** [comment]
@sjackman Thanks! For some reason the build fails now. I'll rebuild and see what happens.

**Comment by dpo** [comment]
@BrewTestBot test this please.

**Comment by schoeps** [comment]
It seems that mpi is messed up on the testbot:
```
#    error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
```

**Comment by sjackman** [comment]
Open-MPI was recently bumped to version 1.8.6. Perhaps `petsc` and `getdp` need to be recompiled and rebottled.

**Comment by schoeps** [comment]
...maybe we just ask the TestBot another time?

**Comment by dpo** [comment]
This one is currently blocked by PETSc, which is in turn blocked by SuperLU. It should hopefully unblock soon.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Ok, PETSc is in. But there's a test failure here:
```
==> make test
Running tests...
/usr/local/Cellar/cmake/3.2.3/bin/ctest --force-new-ctest-process 
Test project /tmp/getdp20150720-70879-mk7onj/getdp-2.5.1-source/build
    Start 1: ../demos/magnet.pro
1/1 Test #1: ../demos/magnet.pro ..............***Exception: Other  0.34 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   3.41 sec

The following tests FAILED:
	  1 - ../demos/magnet.pro (OTHER_FAULT)
Errors while running CTest
```
Any idea what this is?

**Comment by schoeps** [comment]
Not sure but I guess it's a linking problem and most probably another package is guilty (maybe some dependency was not updated after the last petsc change?). On my machine the formula passes all tests but I rarely install from bottles. 

How do people typically debug this kind of problems? I could replicate the steps of the bot but then I need to uninstall my brewed stuff?! Could we disable the test such that I can install the broken bottle for debugging?

**Comment by sjackman** [comment]
I don't see any unpublished bottles for `getdp`. They would have been deleted if they're too old (is it 72 hours?). You can rebuild the package and download the unpublished bottles from https://bintray.com/homebrew/bottles-science/getdp You may need someone with permissions to send them to you.

**Comment by dpo** [comment]
We're getting something else now:
```
/tmp/getdp20150724-67066-k1fmx0/getdp-2.5.1-source/Legacy/EigenSolve_SLEPC.cpp:560:8: error: no matching function for call to 'PEPSetScale'
  _try(PEPSetScale(pep, PEP_SCALE_SCALAR, PETSC_DECIDE, PETSC_DECIDE, PETSC_DECIDE));
       ^~~~~~~~~~~
/usr/local/include/slepcpep.h:213:29: note: candidate function not viable: requires 7 arguments, but 5 were provided
PETSC_EXTERN PetscErrorCode PEPSetScale(PEP,PEPScale,PetscReal,Vec,Vec,PetscInt,PetscReal);
                            ^
/tmp/getdp20150724-67066-k1fmx0/getdp-2.5.1-source/Legacy/EigenSolve_SLEPC.cpp:682:8: error: no matching function for call to 'PEPSetScale'
  _try(PEPSetScale(pep,PEP_SCALE_SCALAR,PETSC_DECIDE,PETSC_DECIDE,PETSC_DECIDE));
       ^~~~~~~~~~~
/usr/local/include/slepcpep.h:213:29: note: candidate function not viable: requires 7 arguments, but 5 were provided
PETSC_EXTERN PetscErrorCode PEPSetScale(PEP,PEPScale,PetscReal,Vec,Vec,PetscInt,PetscReal);
                            ^
2 errors generated.
```
Could there have been an API change in the most recent PETSc/SLEPc update?

**Comment by schoeps** [comment]
You are right. There seem to be some API changes. Did someone check that all other formulas still compile before upgrading petsc and slepc? 

However, there are new versions of getdp and gmsh. I will update both formulas and hope that they fix the errors. However, this might be my last attempt. When dependencies are updated quicker than you guys accept my updates (I submitted the file two month ago and there was hardly anything wrong with my formula in the first place) then the system is not working for me.

**Comment by dpo** [comment]
Sorry about all the trouble. Now this builds. Does it have to wait for the updated `gmsh`?

**Comment by schoeps** [comment]
Now that everything seem to be working I am less frustrated :) However, I suggest to wait for [gmsh](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2648/ ) but that should be only a matter of an hour or so?

**Comment by dpo** [comment]
Yes, shouldn't be very long, if bottles cooperate.

**Comment by dpo** [comment]
I'll rebuild against the `gmsh` that was just merged.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Phew! Thanks for your patience!

**Comment by schoeps** [comment]
I am going to propose an octave 4.0 formula soon, let's see how this goes :)

**Comment by dpo** [comment]
That's ambitious! Does it even compile on OSX? You may want to join efforts with @mcg1969.

**Pull request closed without merging**
