### PR TITLE
Salmon 0.8.2

### PR DESCRIPTION
**Pull request by rob-p**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Circle build failing with:
> undefined reference to `boost::iostreams::zlib::stream_end'

**Comment by rob-p** [comment]
Yea --- the problem is I can't reproduce this locally (my travis CI and Drone io builds all pass).

**Comment by iMichka** [comment]
For the first error you can add `-lboost_iostreams` to the make args, see: http://stackoverflow.com/questions/38420160/boost-iostreams-compilation-error
See the `mira` formula for an example.

For the second one; the flag should be `-lboost_program_options`.

Please add the flags just for the linux build (using `if OS.linux?`), this is not needed for the mac build. Thanks

**Comment by rob-p** [comment]
@iMichka,

  These flags are already part of the build.  For example, see the linking that is attempted before all of the unresolved symbols:

```
/usr/bin/g++-4.8   -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -static-libstdc++  -Wno-unused-local-typedefs -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -static-libstdc++  -Wno-unused-local-typedefs  -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/bzip2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/boost/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/jemalloc/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/tbb/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/xz/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/python/lib CMakeFiles/salmon.dir/QSufSort.c.o CMakeFiles/salmon.dir/is.c.o CMakeFiles/salmon.dir/bwt_gen.c.o CMakeFiles/salmon.dir/bwtindex.c.o CMakeFiles/salmon.dir/xxhash.c.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/RapMapFileSystem.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/RapMapSAIndexer.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/RapMapSAIndex.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/RapMapUtils.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/HitManager.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/rank9b.cpp.o CMakeFiles/salmon.dir/__/external/install/src/rapmap/bit_array.c.o CMakeFiles/salmon.dir/CollapsedEMOptimizer.cpp.o CMakeFiles/salmon.dir/CollapsedGibbsSampler.cpp.o CMakeFiles/salmon.dir/Salmon.cpp.o CMakeFiles/salmon.dir/BuildSalmonIndex.cpp.o CMakeFiles/salmon.dir/SalmonQuantify.cpp.o CMakeFiles/salmon.dir/FragmentLengthDistribution.cpp.o CMakeFiles/salmon.dir/FragmentStartPositionDistribution.cpp.o CMakeFiles/salmon.dir/SequenceBiasModel.cpp.o CMakeFiles/salmon.dir/TranscriptGroup.cpp.o CMakeFiles/salmon.dir/GZipWriter.cpp.o CMakeFiles/salmon.dir/FASTAParser.cpp.o CMakeFiles/salmon.dir/ErrorModel.cpp.o CMakeFiles/salmon.dir/AlignmentModel.cpp.o CMakeFiles/salmon.dir/SalmonQuantifyAlignments.cpp.o  -o salmon  -L/tmp/salmon-20170317-40713-tdtf5v/salmon-0.8.2/lib  -L/tmp/salmon-20170317-40713-tdtf5v/salmon-0.8.2/external/install/lib -Wl,-rpath,"\$ORIGIN/../lib:\$ORIGIN/../../lib:\$ORIGIN/:\$ORIGIN/../../external/install/lib" -rdynamic libsalmon_core.a -lgff -lpthread -Wl,-Bstatic -lboost_iostreams-mt -lboost_filesystem-mt -lboost_system-mt -lboost_thread-mt -lboost_timer-mt -lboost_chrono-mt -lboost_program_options-mt -lboost_regex-mt -lboost_date_time-mt -lboost_atomic-mt -Wl,-Bdynamic ../external/install/lib/libstaden-read.a -Wl,-Bstatic -lz -Wl,-Bdynamic ../external/install/lib/libdivsufsort.a ../external/install/lib/libdivsufsort64.a ../external/install/lib/libjellyfish-2.0.a ../external/install/lib/libbwa.a -lm -Wl,-Bstatic -llzma -lbz2 -Wl,-Bdynamic -ltbbmalloc_proxy -ltbbmalloc -ltbb -lgomp -lrt -Wl,-Bstatic -ljemalloc -Wl,-Bdynamic -lrt -Wl,-Bstatic -ljemalloc -Wl,-Bdynamic 
```

Note the linking against `-lboost_iostreams-mt`.  CMake asks for (and finds, and links with) boost iostreams.  However, the problem is that it doesn't find the specific symbol it's looking for.  This often occurs when name mangling is different, or when the linker wants a specific variant of the symbol that doesn't exist.

**Comment by tseemann** [comment]
@rob-p @iMichka here's what I get on my attempt on Linuxbrew:

```
brew upgrade -v https://raw.githubusercontent.com/rob-p/homebrew-science/c4fbe3fa72954b1f4e7bcc0a839b4a064489cda1/salmon.rb

../external/install/lib/libstaden-read.a(libstaden_read_la-open_trace_file.o): In function `find_file_url':
open_trace_file.c:(.text+0xd30): warning: the use of `tempnam' is dangerous, better use `mkstemp'
libsalmon_core.a(SalmonUtils.cpp.o): In function `salmon::utils::processQuantOptions(SalmonOpts&, boost::program_options::variables_map&, int)':
SalmonUtils.cpp:(.text+0xe1c2): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
SalmonUtils.cpp:(.text+0xe236): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
SalmonUtils.cpp:(.text+0xed61): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [src/unitTests] Error 1
make[2]: Leaving directory `/tmp/salmon-20170530-102660-1epx45x/salmon-0.8.2'
make[1]: *** [src/CMakeFiles/unitTests.dir/all] Error 2
make[1]: Leaving directory `/tmp/salmon-20170530-102660-1epx45x/salmon-0.8.2'
make: *** [all] Error 2
```

**Comment by rob-p** [comment]
Hi @tseemann,

  This seems to be a problem with a mismatch between the boost version installed and what is required (i.e., these types of symbol resolution errors usually pop up when boost was compiled without c++11 support).  I'm still trying to work out the kinks that have come up (only with the most recent release) in the Homebrew environment.  For the time being, you can grab the latest Salmon in [bioconda](https://bioconda.github.io/recipes/salmon/README.html) --- and maybe help us figure out WTH is wrong with the linuxbrew build ;P.

**Pull request closed without merging**
