### PR TITLE
shogun: migrate to homebrew/core

### PR DESCRIPTION
**Pull request by vigsterkr**
as instrucated in https://github.com/Homebrew/homebrew-science/pull/6478#issuecomment-350185409 this drops shogun from homebrew-science. this PR depends on https://github.com/Homebrew/homebrew-core/pull/21444

### CODE REVIEW

**Comment by vigsterkr** [comment]
@sjackman i hope this is what you meant

**Comment by sjackman** [comment]
Yep, looks good. Once the PR is merged in Homebrew/core, please bump this PR, and I'll merge it.

**Comment by nilinswap** [comment]
On trying to install software( shogun ) , 
i.e. on doing `brew install home-brew/science/shogun`
getting error

`cd /tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/build/src/shogun && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src -I/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/build/src -isystem /usr/local/include/eigen3 -I/usr/local/include -I/usr/local/lib/../include -I/usr/local/include/json-c -I/usr/local/opt/libxml2/include/libxml2 -I/usr/local/Cellar/hdf5/1.10.1_2/include -I/usr/local/opt/szip/include -I/usr/local/opt/curl/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include  -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated  -O3 -funroll-loops -fPIC   -std=c++11 -o CMakeFiles/libshogun.dir/lib/external/gpdt.cpp.o -c /tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src/shogun/lib/external/gpdt.cpp
/tmp/shogun-20171224-4936-npg2dw/shogun-6.0.0/src/shogun/lib/external/cdflib.cpp:10052:15: error: ordered comparison between pointer and zero ('int *' and 'int')
  if ( n_data < 0 )
       ~~~~~~ ^ ~
1 error generated.
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/lib/external/cdflib.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2`

and brew sent to this open Issue ( probably just because it looks open.) Is it really the right place to discuss this problem? where should I go?
here is the gist [https://gist.github.com/nilinswap/7014f024688159c4778324298b4764f5](url)

**Comment by MikeMcQuaid** [comment]
This tap has been deprecated and will shortly be archived.

If you wish to [migrate other widely used formulae](https://github.com/Homebrew/homebrew-science/issues/6331) to Homebrew/homebrew-core please [submit a pull request](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) there.

**Pull request closed without merging**
