### PR TITLE
kallisto 0.42.5

### PR DESCRIPTION
**Pull request by pmelsted**
Version bump.

### CODE REVIEW

**Comment by pmelsted** [comment]
@sjackman any change this can be merged?

**Comment by sjackman** [comment]
Can do.

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Pall. Fell free to ping me, @iml or @tseemann if you don't get a response within five days.

**Comment by pmelsted** [comment]
Thanks. I'll keep that in mind.

**Pull request closed without merging**
