### PR TITLE
astrometry-net 0.70

### PR DESCRIPTION
**Pull request by jonchang**
Also don't vendor `numpy`.

### CODE REVIEW

**Comment by iMichka** [comment]
@jonchang this is a duplicate of #4751 
But you seem to have made more changes and we will see what happens with circle-ci.

You'll need to sort out with @ilovezfs which one you want to keep :)

**Comment by jonchang** [comment]
Whoops, lol. Let's use the one that doesn't vendor `numpy` (this one) so the bottles are smaller.

**Comment by jonchang** [comment]
Assuming that CI passes.

**Comment by jonchang** [comment]
Merged!

**Comment by dstndstn** [comment]
thanks from upstream :)

**Pull request closed without merging**
