### PR TITLE
lobstr: revision for gsl

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Fails on mac with:

> /usr/local/Cellar/cppunit/1.14.0/include/cppunit/TestCaller.h:155:28: error: no member named 'bind' in namespace 'std'; did you mean 'find'?
            m_test_function( std::bind(test, fixture) )

I think compiling with c++11 should help.

**Comment by tmozgach** [comment]
https://github.com/mgymrek/lobstr-code/issues/84

**Comment by sjackman** [comment]
Looks like `cppunit` may be missing a `#include <functional>`
std::bind http://en.cppreference.com/w/cpp/utility/functional/bind

**Comment by sjackman** [comment]
> I think compiling with c++11 should help.

Ah, I think you had it right here, Michka. This may be resolved by…
```ruby
needs :cxx11
def install
    ENV.cxx11
    …
end
```
@tmozgach Can you please open a PR to try the above fix?

**Comment by iMichka** [comment]
This will also serve as a revision for boost. Can this be rebased?

**Comment by sjackman** [comment]
`make check` failed now.
https://travis-ci.org/Homebrew/homebrew-science/builds/266174502#L1858

@tmozgach Can you try rebasing this PR? Maybe it will work with `g++-5`.

**Comment by tmozgach** [comment]
@sjackman I rebased, but it seems that it doesn't work.

**Comment by sjackman** [comment]
@tmozgach Can you please open an issue with the upstream authors?

**Comment by tmozgach** [comment]
https://github.com/mgymrek/lobstr-code/issues/88

**Comment by sjackman** [comment]
I've opened PR https://github.com/mgymrek/lobstr-code/pull/89 to hopefully address this issue.

@tmozgach You can use a `patch do` block with `url "https://patch-diff.githubusercontent.com/raw/mgymrek/lobstr-code/pull/89.patch"` to fix this until its merged upstream.

**Comment by tmozgach** [comment]
@sjackman Unfortunately, the patch didn't solve the problem.

**Comment by sjackman** [comment]
😢

**Pull request closed without merging**
