### PR TITLE
iqtree 1.4.3 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by tseemann** [comment]
Is this failing because we build on CPUs with only SSE2 or similar?

```
/usr/local/Library/Homebrew/shims/super/g++-6   -DIQ_TREE -D_USE_PTHREADS -D__SSE3 -I/tmp/iqtree-20160823-24366-1fu6z6x/IQ-TREE-1.4.3 -I/tmp/iqtree-20160823-24366-1fu6z6x/IQ-TREE-1.4.3/build  -fopenmp  -O3 -g   -mmacosx-version-min=10.6 -msse3 -o CMakeFiles/ncl.dir/nxsassumptionsblock.cpp.o -c /tmp/iqtree-20160823-24366-1fu6z6x/IQ-TREE-1.4.3/ncl/nxsassumptionsblock.cpp
{standard input}:4:no such instruction: `vhaddpd %ymm0, %ymm0,%ymm0'
{standard input}:5:no such instruction: `vhaddpd %ymm1, %ymm1,%ymm1'
{standard input}:6:no such instruction: `vperm2f128 $1, %ymm0,%ymm0,%ymm3'
```

**Comment by maxim-belkin** [comment]
Current failure reason:
```
Error: 1 problem in 1 formula
homebrew/science/iqtree:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

**Comment by tseemann** [comment]
@maxim-belkin thank you for figuring that out for me.  it is published and has a `# doi` so it should be accepted. most users download the binaries available and don't use github.

**Comment by tseemann** [comment]
@maxim-belkin the OSX binaries are still broken too 
```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Referenced from: /usr/local/bin/iqtree
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by ilovezfs** [comment]
That does not mean the binary is broken. It's a test-bot imperfection which causes it not to magically install gcc since it doesn't know that the requirement was fulfilled with gcc. To fix it, you just add a depends on gcc to the formula that appears to be broken and that will cause test-bot to install gcc before running the relevant test.

**Pull request closed without merging**
