### PR TITLE
root 5.34.36

### PR DESCRIPTION
**Pull request by veprbl**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
Apparently, this isn't finding `ruby/config.h` on 10.10:
```
In file included from /private/tmp/root-20160621-96487-1cali0z/root/bindings/ruby/src/TRuby.cxx:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^
```

**Comment by veprbl** [comment]
Can we rebuild current version on travis?

**Comment by dpo** [comment]
Travis only tests 10.11.

The `:python` dependency also only applies to systems that predate Mavericks, i.e.,
```
depends_on :python if MacOS.version <= :snow_leopard
```

**Comment by veprbl** [comment]
Pardon, jenkins, I meant, jenkins.

**Comment by dpo** [comment]
Sure. If you don't mind updating the `:python` dependency, a new build will be kicked off.

**Comment by veprbl** [comment]
I made #3776 , hope you don't mind

**Comment by veprbl** [comment]
So it doesn't find ```ruby/config.h``` on 10.10 with current root formula too. Also, why is it looking for it in MacOSX10.11.sdk?

**Comment by veprbl** [comment]
Fixed the build. If somebody wants to use ROOT with ruby they should add a proper dependency on the ruby formula.

**Comment by dpo** [comment]
Thanks. That's fine. But would you mind just updating the `:python` dependency as you did in the other pull request? It's fine to do it here.

**Comment by veprbl** [comment]
Why do we have to add this to our formula? Why not fix it in brew instead?

**Comment by dpo** [comment]
The `:python` dependency has nothing to do with the Ruby issue. Systems older than 10.8 ship with Python, so there's no need to force an install of Homebrew Python on them.

**Comment by veprbl** [comment]
I'm running 10.11 which is more modern than 10.8 and I have python installed as a part of Python framework. I also thought that the whole idea of :python was to manage python dependency in a portable way so that python is installed on the systems where it's needed.

**Comment by dpo** [comment]
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md#python-declarations

**Comment by dpo** [comment]
Great. Thank you.

**Pull request closed without merging**
