### PR TITLE
SPAdes 3.6

### PR DESCRIPTION
**Pull request by bede**
Lots of churn due to making changes recommended by `brew audit --strict`

### CODE REVIEW

**Comment by bede** [comment]
Jenkins tests were initially failing because of the `rm` of a non existent .pyc file. Line removed and they're now passing.

**Comment by sjackman** [comment]
Duplicate of #2673. This patch addresses more style issues.

**Comment by bede** [comment]
Of course @tseemann beat me to it! His But neither PR has been accepted?

**Comment by tseemann** [comment]
I can't seem to ```brew pull --bottle``` anymore - it keeps failing on `curl` step. 
@sjackman

**Pull request closed without merging**
