### PR TITLE
nixio: version update to 1.4.1

### PR DESCRIPTION
**Pull request by jgrewe**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jgrewe** [comment]
@ilovezfs, @iMichka I could use your advice with the failing linuxbrew builds (due to different  c++ std lib versions?). Is this critical? I see that quite a few formulae fail on that. Can you point me to a possible solution?
Second, what is the expected timescale for phasing out homebrew-science?
Thanks a lot

**Comment by iMichka** [comment]
I'm rebuilding the cppunit bottle with gcc5, https://github.com/Linuxbrew/homebrew-core/pull/4797
This should fix it.

**Comment by jgrewe** [comment]
@iMichka perfect, thank you!

**Comment by iMichka** [comment]
@jgrewe Thanks for your contribution.

Deprecation is planned for end of December. Discussion is going on about what we want to do with all the formulae here #6365

**Pull request closed without merging**
