### PR TITLE
madlib 1.9.1.

### PR DESCRIPTION
**Pull request by lifepillar**
### Have you:
- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?
### Updates to existing formula: have you
- [X] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
Please consider whether this fixes #3501 and/or #3998.

**Comment by lifepillar** [comment]
Re #3501, the error is that there is no PostgreSQL process running when the test is run and, for some reason, the `launchctl load` command in the test does not start the server (it fails silently). I am still trying to understand why. If a PostgreSQL server is already running when `brew test` is executed, then the tests pass.

Re #3998, that should have been fixed upstream: MADlib 1.9.1 installs just fine in PostgreSQL 9.5.4.

Re the failed Travis checks (a timeout and a permission denied error), they look to me like failures of the build system, not of the formula.

**Comment by lifepillar** [comment]
Ok, `launchctl load` not working is a problem with security restrictions in macOS. This is what I see in the Console:

```
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Caller not allowed to perform action: launchctl.70244, action = service bootstrap, code = 1: Operation not permitted
```

Time to wrap my head around the new `launchd` man pages…

**Comment by lifepillar** [comment]
I have removed `launchctl` commands from the test, because currently they do not work due to sandbox restrictions (https://github.com/Homebrew/homebrew-core/issues/5393). We can't do anything better than this, I think, at least for now.

**Comment by lifepillar** [comment]
I have reworked the test (and fixed some other things to make it build on macOS Sierra), but the test still fails with `madpack` returning `ERROR : Failed reading database version`, possibly because version 1.9.1 is not compatible with PostgreSQL 9.6. So, this is not to be merged yet. I am afraid that we should wait for the next MADlib release.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
