### PR TITLE
hdf5 1.10.0-patch1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @dpo @tschoonj

**Comment by tschoonj** [comment]
Nice!

But could you also keep the old version around as a separate Formula?

**Comment by ilovezfs** [comment]
@tschoonj yeah – not sure if it'll go in versions or here, but that shouldn't be a problem.

**Comment by ilovezfs** [comment]
@tschoonj just FYI these are the hdf5 1.8.17 revisions that haven't been successful yet, but I don't think any of the problems are actually hdf5:

- [ ] [blasr](https://github.com/Homebrew/homebrew-science/pull/4254)
- [ ] [minc](https://github.com/Homebrew/homebrew-science/pull/4267)
- [ ] [openimageio](https://github.com/Homebrew/homebrew-science/pull/4275)
- [ ] [openmeeg](https://github.com/Homebrew/homebrew-science/pull/4276)
- [ ] [shogun](https://github.com/Homebrew/homebrew-science/pull/4282)
- [ ] [vigra](https://github.com/Homebrew/homebrew-science/pull/4296)

**Comment by ilovezfs** [comment]
@MikeMcQuaid um ...
https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5878/version=el_capitan/
```
	Build Artifacts
	testbottest-0.1.el_capitan.bottle.json	434 B	 view
	testbottest-0.1.el_capitan.bottle.tar.gz	1.12 KB	 view
```
I think all bottles now have the same name?

**Comment by MikeMcQuaid** [comment]
@ilovezfs https://github.com/Homebrew/brew/pull/953

**Comment by zmwangx** [comment]
That's hilarious...

**Comment by ilovezfs** [comment]
- [ ] h5py
- [ ] alembic
- [ ] alpscore
- [ ] armadillo
- [ ] blasr
- [ ] blast
- [ ] cdo
- [ ] cgns
- [ ] dealii
- [ ] dextractor
- [ ] dynare
- [ ] field3d
- [ ] flann
- [ ] getdp
- [ ] gmtk
- [ ] gnudatalanguage
- [ ] h5utils
- [ ] insighttoolkit
- [ ] kallisto
- [ ] libmatio
- [ ] libminc
- [ ] mathgl
- [ ] moab
- [ ] moose
- [ ] nanopolish
- [ ] netcdf
- [ ] nexusformat
- [ ] nixio
- [ ] octave
- [ ] openimageio
- [ ] openmeeg
- [ ] paraview
- [ ] petsc
- [ ] poretools
- [ ] radx
- [ ] seqdb
- [ ] shogun
- [ ] silo
- [ ] slepc
- [ ] sratoolkit
- [ ] statismo
- [ ] trilinos
- [ ] vigra
- [ ] vtk
- [ ] xmi-msim

**Comment by iMichka** [comment]
Got already 4 failures with hdf5 1.10.0.
They may be unrelated, I did not investigate further but we already have something to churn on.

trilinios
https://gist.github.com/iMichka/dff2f5b327b559291fc229e2e71dbb8c

vtk
https://gist.github.com/iMichka/6fbf96a7945a7e0f41cc0fc32217bbdc

vigra
https://gist.github.com/iMichka/33cfa78d9e41c99a2d793223041dbcc4

slepc builds but the test fails:
```
Testing homebrew/science/slepc
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170124-11420-nqkaqe.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/slepc.rb -v
==> mpicc ex1.c -I/usr/local/opt/slepc/include -I/usr/local/opt/petsc/include -L/usr/local/opt/petsc/lib -lpetsc -L/usr/local/opt/slepc/lib -lslepc -o ex1
==> mpirun -np 3 ex1 2>&1 | tee ex1.out
dyld: Library not loaded: /usr/local/opt/hdf5/lib/libhdf5_hl.10.dylib
  Referenced from: /usr/local/opt/petsc/real/lib/libpetsc.3.7.dylib
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/hdf5/lib/libhdf5_hl.10.dylib
  Referenced from: /usr/local/opt/petsc/real/lib/libpetsc.3.7.dylib
  Reason: image not found
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node Dlul exited on signal 6 (Abort trap: 6).
--------------------------------------------------------------------------
Error: homebrew/science/slepc: failed
Failed assertion, no message given.
```

**Comment by ilovezfs** [comment]
@iMichka the slepc error should be correctable by first rebuilding petsc against the new hdf5.

**Comment by iMichka** [comment]
Which depends on `netcdf` (like a lot of other formulae). So we need a working netcdf first. Which fails to build with an error in the make check step:

```
FAIL: tst_h_dimscales
=====================

HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: H5Gdeprec.c line 1092 in H5Gget_objtype_by_idx(): can't get object type
    major: Symbol table
    minor: Inappropriate type
  #001: H5Gdeprec.c line 1144 in H5G_obj_get_type_by_idx(): can't locate type
    major: Symbol table
    minor: Object not found
  #002: H5Gstab.c line 1219 in H5G__stab_get_type_by_idx(): index out of bound
    major: Invalid arguments to routine
    minor: Inappropriate type
```

The error is documented here: https://github.com/Unidata/netcdf-c/issues/244
The current version of netcdf we have contains the "fix": https://github.com/Unidata/netcdf-c/commit/9136afdcbe7f5db5eebb83bfb201604ddedfacf3 , but that seems not be enough.

**Comment by ilovezfs** [comment]
@iMichka looks like all tests pass if netcdf is build with cmake.

**Comment by iMichka** [comment]
@ilovezfs Thanks for finding out. I opened a pull request to use cmake to build netcdf. I was able to build slepc and petsc. Making good progress.

**Comment by iMichka** [comment]
`trilinos` failed, but could not really find out what is broken though: https://gist.github.com/iMichka/afffa450eac3a43d3156c6f4284042df

@ilovezfs It may be worth getting the version bump done: https://github.com/Homebrew/homebrew-science/pull/4763

**Comment by iMichka** [comment]
`moab` has a sha256 mismatch, I opened a separate issue for that: #4933

**Comment by ilovezfs** [comment]
@iMichka I refreshed the trilinos PR.

**Comment by ilovezfs** [comment]
@iMichka odd ... `brew test alpscore` seems to work fine for me.

**Comment by ilovezfs** [comment]
vigra is fixed in HEAD so I've inquired about getting a new tag https://github.com/ukoethe/vigra/issues/404

**Comment by sjackman** [comment]
@sjackman :penguin:

**Pull request closed without merging**
