### PR TITLE
netcdf: use cmake for build

### PR DESCRIPTION
**Pull request by iMichka**
netcdf can be build with cmake. This will help for the hdf5 migration
from 1.8.18 to 1.10.0. It also fixes the build with the fortran option.

The test suits are run during the build. They are short and really help
find out potential problems.

One slight difference is that only the shared libs are built,
where before shared and static libs were to be built together.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
@ilovezfs This is done in preparation for #4300

@sebastianbeyer @jonchang This seems to fix the build problems when using `--with-fortran` flag (#4639)

**Comment by iMichka** [comment]
There is one audit failure, I will open a bug upstream for it:
> Non-libraries were installed to "/usr/local/opt/netcdf/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/netcdf/lib/libnetcdf-cxx.settings
      /usr/local/opt/netcdf/lib/libnetcdf.settings

We can probably live with it the time being.

**Comment by ilovezfs** [comment]
Yep, that pseudo-problem has been around for quite a while.

**Comment by ilovezfs** [comment]
```
abinit.rb:29:  depends_on "netcdf" => ["with-fortran", :recommended]
cdo.rb:28:  depends_on "netcdf"
cmor.rb:18:  depends_on "netcdf" => "with-fortran"
dealii.rb:35:  depends_on "netcdf"       => [:recommended, "with-fortran", "with-cxx-compat"]
etsf_io.rb:16:  depends_on "netcdf" => ["with-fortran"]
gmt.rb:19:  depends_on "netcdf"
gmt4.rb:16:  depends_on "netcdf"
gnudatalanguage.rb:20:  depends_on "netcdf"
libbi.rb:32:  depends_on "netcdf"
libminc.rb:17:  depends_on "netcdf"
mbsystem.rb:18:  depends_on "netcdf"
mfem.rb:35:  depends_on "netcdf" => :optional
moab.rb:20:  depends_on "netcdf"
nccmp.rb:15:  depends_on "netcdf"
nco.rb:22:  depends_on "netcdf"
ncview.rb:17:  depends_on "netcdf"
petsc.rb:57:  depends_on "netcdf"       => ["with-fortran", :recommended]
radx.rb:19:  depends_on "netcdf" => "with-cxx-compat"
trilinos.rb:56:  depends_on "netcdf"       => ["with-fortran", :optional]
xmgredit.rb:17:  depends_on "netcdf"
```
Have you tried rebuilding the others?

**Comment by ilovezfs** [comment]
- [ ] abinit https://github.com/Homebrew/homebrew-science/pull/4934
- [ ] cdo https://github.com/Homebrew/homebrew-science/pull/4935
- [ ] cmor https://github.com/Homebrew/homebrew-science/pull/4936
- [ ] dealii https://github.com/Homebrew/homebrew-science/pull/4937
- [ ] etsf_io https://github.com/Homebrew/homebrew-science/pull/4938
- [ ] gmt https://github.com/Homebrew/homebrew-science/pull/4939
- [ ] gmt4 https://github.com/Homebrew/homebrew-science/pull/4940
- [ ] gnudatalanguage https://github.com/Homebrew/homebrew-science/pull/4941
- [ ] libbi https://github.com/Homebrew/homebrew-science/pull/4942
- [ ] libminc https://github.com/Homebrew/homebrew-science/pull/4943
- [ ] mbsystem https://github.com/Homebrew/homebrew-science/pull/4944
- [ ] moab https://github.com/Homebrew/homebrew-science/pull/4946
- [ ] nccmp https://github.com/Homebrew/homebrew-science/pull/4947
- [ ] nco https://github.com/Homebrew/homebrew-science/pull/4948
- [ ] ncview https://github.com/Homebrew/homebrew-science/pull/4949
- [ ] petsc https://github.com/Homebrew/homebrew-science/pull/4953
- [ ] radx https://github.com/Homebrew/homebrew-science/pull/4950
- [ ] trilinos https://github.com/Homebrew/homebrew-science/pull/4951
- [ ] xmgredit https://github.com/Homebrew/homebrew-science/pull/4952

**Comment by ilovezfs** [comment]
Looks like we need `-DNC_EXTRA_DEPS=-lmpi` in the cases where it's using an mpi-enabled hdf5. Also, I think
```
      -BUILD_TESTING=ON
      -BUILD_TESTSETS=ON
```
should actually be
```
      -DBUILD_TESTING=ON
      -DBUILD_TESTSETS=ON
```

**Comment by ilovezfs** [comment]
Odd. How did this manage to change the library version number?

**Comment by ilovezfs** [comment]
I reported the library version issue upstream: https://github.com/Unidata/netcdf-c/issues/355

**Pull request closed without merging**
