### PR TITLE
Add explicit version for simpleitk

### PR DESCRIPTION
**Pull request by dewet22**
Brew misinterprets the URL to be just version "1", so I'm adding this override as a fix.

Before:
```
$ brew info simpleitk
homebrew/science/simpleitk: stable 1 (bottled), HEAD
Simplified layer built on top of ITK
http://www.simpleitk.org
/usr/local/Cellar/simpleitk/1 (398 files, 838.5M) *
  Poured from bottle on 2017-01-05 at 08:14:04
From: https://github.com/Homebrew/homebrew-science/blob/master/simpleitk.rb
...
```

After:
```
$ brew info simpleitk
homebrew/science/simpleitk: stable 0.10.0 (bottled), HEAD
Simplified layer built on top of ITK
http://www.simpleitk.org
/usr/local/Cellar/simpleitk/0.10.0_1 (374B)
  Built from source
From: https://github.com/Homebrew/homebrew-science/blob/master/simpleitk.rb
...
```

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
I don't think this needs a new revision, instead it should update its version scheme as 0.10 < 1 and upgrades won't be detected properly. See https://github.com/Homebrew/homebrew-core/pull/4006 for an example of this.

**Comment by dewet22** [comment]
@jonchang Gotcha. I wasn't sure whether `revision` should track the upstream versioning or whether it is unique to the `homebrew-science` repo. I incremented `version_scheme` as suggested in the docs.

**Comment by jonchang** [comment]
Thanks for contributing to Homebrew, @dewet22! This has been merged.

**Comment by iMichka** [comment]
+1 on the change 👍

**Pull request closed without merging**
