### PR TITLE
metaphlan: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman could you merge?
Unrelated error: 
```
brew test --verbose humann2
```

**Comment by sjackman** [comment]
Hi, Tanya. The bottle is 568 MB, which is too big to transfer to Bintray. Stripping the executables and libraries of their debugging symbols usually resolves this issue.
```ruby
    if OS.linux?
      # Strip the binaries to reduce their size.
      system "strip", *Dir[bin/"*", lib/"*"].select { |f| Pathname.new(f).elf? }
    end
```

**Comment by sjackman** [comment]
Could you please revisit this issue, Tanya?

**Comment by sjackman** [comment]
Hi, Tanya. Can you please take a look at this issue?
See https://github.com/Homebrew/homebrew-science/pull/6104#issuecomment-322051460

**Comment by tmozgach** [comment]
`strip` doesn't solve the problem. The problem is here:
```
596M	/home/tmozgacheva/.linuxbrew/Cellar/metaphlan/1.7.8/bowtie2db
```
@sjackman could you please upload a bottle manually?

**Pull request closed without merging**
