### PR TITLE
maude 2.7.1

### PR DESCRIPTION
**Pull request by mkhl**
The current version of maude can (finally) be built from source using clang.

This change includes
* build instructions
* a script that sets `MAUDE_LIB` automatically
* a more extensive test
* a formula for the required `BuDDy` library, also submitted separately as #4046

### CODE REVIEW

**Comment by dpo** [comment]
Is there a test that could be added to `libbuddy`? If not and if no other formula uses it, perhaps it should be a resource inside `maude`?!
```
==> brew audit homebrew/science/libbuddy --new-formula
==> FAILED
Error: 1 problem in 1 formula
homebrew/science/libbuddy:
  * A `test do` test block should be added
```

**Comment by mkhl** [comment]
It’s a C library, we could probably write a simple program using it and check that it compiles.
Would you prefer that?

**Comment by dpo** [comment]
Yes, that would be the best. Thanks!

**Comment by dpo** [comment]
Please remove `libbuddy` from here and update #4046.

**Comment by mkhl** [comment]
done

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by mkhl** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Great, thank you!

**Pull request closed without merging**
