### PR TITLE
bbtools 36.11

### PR DESCRIPTION
**Pull request by chrisgulvik**
**Enhancement 1**:
-generate libbbtoolsjni shared object file for faster computing with the usejni flag
**Enhancement 2**:
-update to newest version release 36.11
**Enhancement 3**:
-data processing test added on Line 37 in response to previously missed java errors

**Fix Error 1**:
--add 'current' dir which includes the java class files
**Fix Error 2**:
--add 'resources' dir which contains the file containing prime numbers that is required when requesting >1 thread

**Example Error 1**:

```
java -Djava.library.path=$HOME/.linuxbrew/Cellar/bbtools/35.85/bin/jni/ -ea -Xmx98385m -Xms98385m -cp $HOME/.linuxbrew/Cellar/bbtools/35.85/bin/current/ jgi.BBDukF threads=31 in=H5533_R1_001.fastq.gz in2=H5533_R2_001.fastq.gz out=H5533-noPhiX-R1.fsq out2=H5533-noPhiX-R2.fsq ref=$HOME/genome_references/PhiX/NC_001422.1.fasta k=31 hdist=1
Error: Could not find or load main class jgi.BBDukF
```

**Example Error 2**:

```
Set threads to 40
Warning!  Cannot find primes.txt.gz $HOME/.linuxbrew/Cellar/bbtools/35.85/bin/current/primes.txt.gz
Exception in thread "Thread-1" Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class kmer.HashArray1D
    at kmer.AbstractKmerTable$AllocThread.run(AbstractKmerTable.java:443)
java.lang.ExceptionInInitializerError
    at kmer.HashArray.<clinit>(HashArray.java:478)
    at kmer.AbstractKmerTable$AllocThread.run(AbstractKmerTable.java:443)
Caused by: java.lang.NullPointerException
    at fileIO.TextFile.<init>(TextFile.java:74)
    at kmer.Primes.fetchPrimes(Primes.java:152)
    at kmer.Primes.<clinit>(Primes.java:161)
    ... 2 more
Exception in thread "main" java.lang.RuntimeException: KmerTable allocation failed, probably due to lack of RAM: 0, 7
    at kmer.AbstractKmerTable.preallocate(AbstractKmerTable.java:410)
    at jgi.BBDukF.<init>(BBDukF.java:743)
    at jgi.BBDukF.main(BBDukF.java:67)

```
### Have you:
- [ **_YES_** ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ **_YES_** ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ **_YES_** ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ **_YES_** ] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [ **_YES_** ] Written a sensible test? (The best test is to compile and run a sample program.)
### Updates to existing formula: have you
- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [  **_YES_** ] Not altered the `bottle` section?
- [ **_YES_** ] Checked that the tests still pass?

### CODE REVIEW

**Comment by chrisgulvik** [comment]
@BrewTestBot test this please

**Comment by chrisgulvik** [comment]
Are the build errors for OS X due to using the same bottle sha256 but we're now downloading a newer version of bbtools? It works fine on Linux and looks like the builds still finished in OS X, so I'm unsure what to fix.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by chrisgulvik** [comment]
All checks have passed and no merge conflicts, awesome!

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Thanks @chrisgulvik!

**Pull request closed without merging**
