### PR TITLE
bowtie 1.1.2

### PR DESCRIPTION
**Pull request by iml**

### CODE REVIEW

**Comment by saketkc** [comment]
Was about to hit this. Thanks @iml!

**Comment by tseemann** [comment]
@saketkc out of interest, what apps still use bowtie and not bowtie2 ?

**Comment by saketkc** [comment]
Have found it useful for some short read data I analyse. And of course, those first year grad school assignments ;-)

**Comment by tseemann** [comment]
@iml 
I get his audit problem which seems like a genuine problem:
(But brewtestbot was happy?)

```
==> audit problems
homebrew/science/bowtie:
 * Non-executables were installed to "/usr/local/Cellar/bowtie/1.1.2/bin"
The offending files are:
  /usr/local/Cellar/bowtie/1.1.2/bin/bowtie-buildc
Error: 1 problem in 1 formula
```

```
file /usr/local/Cellar/bowtie/1.1.2/bin/bowtie-buildc
/usr/local/Cellar/bowtie/1.1.2/bin/bowtie-buildc: DBase 3 data file (1435212127 records)
```

**Comment by iml** [comment]
I can't reproduce that file and it isn't in the bottle. Maybe an upstream bug, and the make install is new to this release. Actually I think we need to go back to make allall and use `prefix=#{libexec}`.

Here's what this should ideally link to bin:
```
bowtie
bowtie-build
bowtie-build-debug
bowtie-debug
bowtie-inspect
bowtie-inspect-debug

**Pull request closed without merging**
