### PR TITLE
HISAT 0.1.5b (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
HISAT (hierarchical indexing for spliced alignment of transcripts) is a highly efficient system for aligning reads from RNA sequencing experiments.

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman I've completely stuffed up this and don't know how to fix it. I've tried to squash commits etc but made a mess. It keeps telling me to pull, and I go around in circles. Any advice?

```
git push
To https://github.com/tseemann/homebrew-science
 ! [rejected]        hisat -> hisat (non-fast-forward)
error: failed to push some refs to 'https://github.com/tseemann/homebrew-science'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by saketkc** [comment]
`git rebase master` and then `git push origin hisat -f`
You can also squash if need be after `git rebase master`

**Comment by tseemann** [comment]
@saketc Thank you! It seems ```-f``` is the solution to a lot of problems. "Use the force!".

**Comment by iml** [comment]
Thanks!

**Pull request closed without merging**
