### PR TITLE
vtk 6.3.0

### PR DESCRIPTION
**Pull request by quantumsteve**
updated vtk to version 6.3.0

### CODE REVIEW

**Comment by dpo** [comment]
@tdsmith What's the recommended way to fix this:
```
homebrew/science/vtk:
 * python modules have explicit framework links
These python extension modules were linked directly to a Python
framework binary. They should be linked with -undefined dynamic_lookup
instead of -lpython or -framework Python.
```
Pass the link options to CMake somehow?

**Comment by tdsmith** [comment]
It probably involves changes to the build system; this is what it looked like for opencv https://github.com/Itseez/opencv/pull/3866/files and for openimageio https://github.com/OpenImageIO/oiio/pull/1099/files.

This also permits removing the `:python` dependency altogether since it will be safe to build against system Python.

You might decide it's not worth blocking on.

**Comment by dpo** [comment]
Thanks. I'll look into it, but don't want to block the PR.

**Comment by mikepurvis** [comment]
We're getting an issue building PCL's ROS bindings:

```
[ 25%] Built target pcl_ros_gencfg
Scanning dependencies of target pointcloud_to_pcd
[ 26%] Building CXX object CMakeFiles/pointcloud_to_pcd.dir/tools/pointcloud_to_pcd.cpp.o
[ 28%] Linking CXX executable /Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/convert_pcd_to_image
ld: library not found for -lvtkRenderingFreeTypeOpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/convert_pcd_to_image] Error 1
make[1]: *** [CMakeFiles/convert_pcd_to_image.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Linking CXX executable /Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/pcd_to_pointcloud
ld: library not found for -lvtkRenderingFreeTypeOpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/pcd_to_pointcloud] Error 1
make[1]: *** [CMakeFiles/pcd_to_pointcloud.dir/all] Error 2
[ 31%] Linking CXX executable /Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/convert_pointcloud_to_image
ld: library not found for -lvtkRenderingFreeTypeOpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/convert_pointcloud_to_image] Error 1
make[1]: *** [CMakeFiles/convert_pointcloud_to_image.dir/all] Error 2
[ 33%] Linking CXX executable /Users/anon/indigo_desktop_full_ws/devel/lib/pcl_ros/pointcloud_to_pcd
ld: library not found for -lvtkRenderingFreeTypeOpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This previously worked with VTK 6.2 from Homebrew. Is there something on our side which needs adjusting?

**Pull request closed without merging**
