### PR TITLE
root6: add option to compile with RooFit/Minuit2

### PR DESCRIPTION
**Pull request by anuwish**
Added options to enable RooFit and Minuit2 support when compiling ROOT6.

### CODE REVIEW

**Comment by tdsmith** [comment]
Should we build these by default?

**Comment by anuwish** [comment]
Personally, I would be in favour of that. Though, following the ROOT developer's decision to not have RooFit and Minuit2 compiled by default, I think it's more "natural" to have them optional as well.

**Comment by tdsmith** [comment]
Let's do it, then. Root's huge so if these just make extra libraries available, I'm in favor of forcing these on so that they're built into the precompiled bottles, unless you know a reason someone might not want them.

**Comment by anuwish** [comment]
Ok, so I'll remove the "with-xyz" options and just add the additional flags for RooFit and Minuit2.

**Comment by tdsmith** [comment]
Thanks for the pull request!

**Pull request closed without merging**
