### PR TITLE
novoalign: v3.02.13

### PR DESCRIPTION
**Pull request by chapmanb**

### CODE REVIEW

**Comment by dpo** [comment]
```
==> brew audit Homebrew/science/novoalign				 FAILED
Error: 1 problem in 1 formula
homebrew/science/novoalign:
 * object files were linked against system openssl
These object files were linked against the deprecated system OpenSSL.
Adding `depends_on "openssl"` to the formula may help.
  /usr/local/Cellar/novoalign/3.02.13/bin/isnovoindex
  /usr/local/Cellar/novoalign/3.02.13/bin/novoalign
  /usr/local/Cellar/novoalign/3.02.13/bin/novoalignCS
  /usr/local/Cellar/novoalign/3.02.13/bin/novoalignCSMPI
  /usr/local/Cellar/novoalign/3.02.13/bin/novoalignMPI
  /usr/local/Cellar/novoalign/3.02.13/bin/novobarcode
  /usr/local/Cellar/novoalign/3.02.13/bin/novoindex
  /usr/local/Cellar/novoalign/3.02.13/bin/novomethyl
  /usr/local/Cellar/novoalign/3.02.13/bin/novosort
  /usr/local/Cellar/novoalign/3.02.13/bin/novoutil
```

**Comment by chapmanb** [comment]
Dominique;
Thanks much. Are you getting this failing check on Mac? Apologies, I'm a Linuxbrew person so was testing there. This is a pre-compiled binary distribution we're downloading and unpacking, so shouldn't depend on any external libraries. Can we skip the audit issues for this case?

**Comment by dpo** [comment]
That's the brew bot complaining, so yes, it's on a Mac. Bottles were produced nonetheless. I'll let @sjackman decide.

**Comment by sjackman** [comment]
Upstream binaries are not ideal, but I don't believe novoalign distributes source code. I'll merge.

**Comment by sjackman** [comment]
```
❯❯❯ brew audit --strict novoalign    ⬆ ◼
==> brew style novoalign
== novoalign.rb ==
C:  5:  3: Missing space after #.
C:  8: 66: Favor format over String#%.
C:  9: 15: Favor the ternary operator (?:) over if/then/else/end constructs.
C: 11:  7: Align elsif with if.
C: 12:  5: Align else with if.
W: 13:  5: end at 13, 4 is not aligned with if at 10, 9
C: 23:  7: Align the elements of an array literal if they span more than one line.
C: 24:  7: Align the elements of an array literal if they span more than one line.
C: 26:  5: Missing space after #.

1 file inspected, 9 offenses detected

==> audit problems
homebrew/science/novoalign:
 * `url` (line 8) should be put before `version` (line 7)
 * Formula should have a desc (Description).
 * `require "formula"` is now unnecessary

Error: 3 problems in 1 formula
```

**Comment by sjackman** [comment]
I'll tackle these style issues in a separate commit.

**Comment by sjackman** [comment]
Thanks for your contribution, Brad.

**Pull request closed without merging**
