### PR TITLE
Scotch 6.0.4 (fix)

### PR DESCRIPTION
**Pull request by davydden**
update download link and sha. PATCH is removed as it is already applied in this official download link.

Unfortunately, there is a compilation error: 
https://gforge.inria.fr/tracker/index.php?func=detail&aid=19407&group_id=248&atid=1079

### CODE REVIEW

**Comment by davydden** [comment]
adding `-DCOMMON_PTHREAD` solves the issue. The problem is that there is
```
typedef struct ThreadGroupHeader_ {
#if ((defined COMMON_PTHREAD) || (defined SCOTCH_PTHREAD))
  int                       flagval;              /*+ Thread block flags       +*/
  size_t                    datasiz;              /*+ Size of data array cell  +*/
  int                       thrdnbr;              /*+ Number of threads        +*/
  ThreadLaunchStartFunc     stafptr;              /*+ Pointer to start routine +*/
  ThreadLaunchJoinFunc      joifptr;              /*+ Pointer to join routine  +*/
  ThreadBarrier             barrdat;              /*+ Barrier data structure   +*/
#endif /* ((defined COMMON_PTHREAD) || (defined SCOTCH_PTHREAD)) */
} ThreadGroupHeader;
```
so if `COMMON_PTHREAD` or `SCOTCH_PTHREAD` are not defined, then this `struct` does not contain anything. Then accessing its attributes 
```
#ifdef GRAPHCOARSENTHREAD
  thrdnbr                  =
  coarptr->thrddat.thrdnbr = SCOTCH_PTHREAD_NUMBER; /* Required by graphMatchInit */
#else /* GRAPHCOARSENTHREAD */
  coarptr->thrddat.thrdnbr = 1;
#endif /* GRAPHCOARSENTHREAD */
```
gives the error, of course. 

Why it did not happen before - i don't know. I could speculate that there was a bug in configure system introduced between the current 6.0.4. and the original `6.0.4` release.

**Comment by davydden** [comment]
@dpo i see that you have manually specified those `cflags` in https://github.com/Homebrew/homebrew-science/pull/1681/ i wonder if you recall how you decided on them?

**Comment by dpo** [comment]
I seem to recall it was another bug of the same sort. Your latest version builds for me. Pull as is?

**Comment by davydden** [comment]
i would say so... if there will be some resolution or comments from the authors in that bug error, i will update the formula.

**Pull request closed without merging**
