### PR TITLE
graph-tool: update dependencies

### PR DESCRIPTION
**Pull request by tdsmith**
* add gtk+3 dep for interactive plotting
* don't rebuild deps for c++11 unless pre-Mavericks

Also don't add HOMEBREW_PREFIX/bin to LDFLAGS; I assume that's an error?

### CODE REVIEW

**Comment by tdsmith** [comment]
1ce12b6 reverts this change: https://github.com/Homebrew/homebrew-science/pull/1073/files#diff-61918d9630479baa09e9580d0b961aecL32

**Comment by joernhees** [comment]
i found out that the interactive visualization crashes with a nullpointer exception like the following if `gnome-icon-theme` isn't installed:
```
Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!

Gtk-WARNING **: Could not find the icon 'system-run'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

Gtk-WARNING **: Error loading theme icon 'system-run' for stock: Icon 'system-run' not present in theme

Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme
/usr/local/lib/python2.7/site-packages/graph_tool/draw/gtk_draw.py:493: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  icon = self.render_icon(Gtk.STOCK_EXECUTE, Gtk.IconSize.BUTTON)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/graph_tool/draw/gtk_draw.py", line 494, in draw
    Gdk.cairo_set_source_pixbuf(cr, icon, 10, 10)
TypeError: Argument 1 does not allow None as a value

Gtk-WARNING **: Error loading theme icon 'system-run' for stock: Icon 'system-run' not present in theme

Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/graph_tool/draw/gtk_draw.py", line 494, in draw
    Gdk.cairo_set_source_pixbuf(cr, icon, 10, 10)
TypeError: Argument 1 does not allow None as a value

Gtk-WARNING **: drawing failure for widget `graph_tool+draw+gtk_draw+GraphWindow': NULL pointer
Segmentation fault: 11
```

i'm not sure if i read Homebrew/homebrew#34337 correctly, that this should be fixed by adding `depends_on "gnome-icon-theme"` to this formula as well?!?

**Comment by tdsmith** [comment]
Added; thanks Jörn.

**Comment by gor-tanachat** [comment]
@tdsmith, have you checked building for python3? I am just curious if you run into any linker problems. I have been working on this formula to support building for both python version.

**Comment by tdsmith** [comment]
I haven't checked.

**Comment by tdsmith** [comment]
With python2 --with-gtk+3, I see a segfault at the GraphWindow() instantiation in this demo code: http://graph-tool.skewed.de/static/doc/demos/animation.html#sirs-epidemics

**Comment by tdsmith** [comment]
Nevermind; segfault went away after upgrading XQuartz.

**Comment by tnilanon** [comment]
I'll wait for your PR to be done before sending mine in.

**Comment by tnilanon** [comment]
On a related note: https://github.com/tdsmith/homebrew-science/commit/1ce12b66e23d76e7f278e2a35b6c5b6cfb7dd107
The
```sh
PYTHON_EXTRA_LDFLAGS=-L#{HOMEBREW_PREFIX}/bin
```
was a hack to disable
```sh
if test -z "$PYTHON_EXTRA_LDFLAGS"; then
  PYTHON_EXTRA_LDFLAGS=`$PYTHON -c "import distutils.sysconfig; \
    conf = distutils.sysconfig.get_config_var; \
    print (conf('LINKFORSHARED'))"`
fi
```
in `configure` that generates bad linker flags.
It is the reason why the auto-merged build failed. The code works fine for python2, not so for python3. This is why I posted https://github.com/Homebrew/homebrew/issues/37923

**Comment by tdsmith** [comment]
Setting PYTHON_EXTRA_LDFLAGS to whitespace works as well. As of 3aa9936, this formula works for both python and python3 without additional changes.

**Comment by tnilanon** [comment]
Looking great.

Can I trouble you to wrap `Language::Python.each_python(build)` around the `configure` and `install` part, so I won't have to send in a PR? As it stands, this formula only build for one python version at a time. Also line 40 needs a little change to support multiple python version build.

Thanks a lot!

**Comment by tdsmith** [comment]
Please send a PR; I never want to build graph-tool again. :) It's wrong to wrap the `=> :python` deps in an `elsif` if really building for both pythons.

**Comment by tnilanon** [comment]
OK! :+1:

**Comment by joernhees** [comment]
:+1: thanks for taking the suffering from me ;)

**Pull request closed without merging**
