### PR TITLE
getdp 2.9.2

### PR DESCRIPTION
**Pull request by schoeps**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### Comments
Gmsh (https://github.com/Homebrew/homebrew-science/pull/4404) should be merged first.

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by schoeps** [comment]
problem is sundials, see #4412

**Comment by schoeps** [comment]
#4412 is closed, so this one should be fine, too?

**Comment by ilovezfs** [comment]
Can you rebase this on master and force push? That will re-trigger CI.

**Comment by jonchang** [comment]
Looks like `petsc` needs a rev bump for sundials.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by schoeps** [comment]
Looks good, right?

**Comment by jonchang** [comment]
Thanks @schoeps!

**Pull request closed without merging**
