### PR TITLE
New version 3.1.1 (chamcham) 

### PR DESCRIPTION
**Pull request by dilawar**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for your contribution. Need any help? This will need to be rebased on master; moose has been updated since then.

**Comment by dilawar** [comment]
Thanks. Its building locally. 

Rebase to master? I am not sure I followed you. We are keeping version 3.1.1 on branch 'chamcham' where hot-fxes are applied. We cherry-pick these hot-fixes to master. This release is kept on chamcham branch. The master branch may contain some very unstable code. Are you suggesting that rebase chamcham branch onto master and use a tag on master?

**Comment by iMichka** [comment]
No, I was talking about this pull request, on `BhallaLab/homebrew-science/master`.

You would do this like this:
> git fetch origin            # Updates origin/master
git rebase origin/master    # Rebases

It would have been better if you had made a branch and kept your master branch pristine (per the docs: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html), but this will do.

You will need to fix the merge conflicts and push your changes.

**Comment by dilawar** [comment]
Is it ok  if I close this PR and create a new one? 

Moreover, we have now a snapshot repo in which we keep the stable snapshot of subprojects (using gitsubtree). That repo does not have enough 'stars' and forks. I remember that this being a requirement for a new formula to be accepted in homebrew. If we change the upstream link to this meta repo should it be a problem for updated formula?

**Comment by iMichka** [comment]
Hi. If you do not feel confident about squashing all the commits and solve the conflict, you can close this one and open a new one, I am OK with that.

Regarding the stars and forks, this requirement is not so important for homebrew-science (it's not an open door for everything, but it is not so strict as on homebrew-core for the moment).

**Comment by dilawar** [comment]
Closing this PR. Will create a new PR for latest version.

**Pull request closed without merging**
