### PR TITLE
gubbins: Build a bottle for Linuxbrew: syntax error near unexpected token `zlib'

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Succeeded on TravisCI but failed on CircleCI.
```
./configure: line 17064: syntax error near unexpected token `zlib,'
./configure: line 17064: `PKG_CHECK_MODULES(zlib, zlib)'
```
https://circleci.com/gh/Homebrew/homebrew-science/4200

**Comment by jonchang** [comment]
Doesn't `PKG_CHECK_MODULES` need `pkg-config`?

**Comment by sjackman** [comment]
Thanks for the tip, Jon. I'm trying out
```ruby
depends_on "pkg-config" => :build unless OS.mac?
```

**Comment by sjackman** [comment]
💚 Thanks, Jon!

**Comment by tseemann** [comment]
FYI @andrewjpage :)

**Pull request closed without merging**
