### PR TITLE
add a formula for nip2, the libvips GUI

### PR DESCRIPTION
**Pull request by jcupitt**
nip2 as a homebrew formula

see

	http://www.vips.ecs.soton.ac.uk/index.php?title=Nip2

for background on nip2

see

	https://github.com/jcupitt/nip2/issues/48

for users asking for this to be available via homebrew

### CODE REVIEW

**Comment by iml** [comment]
```
==> audit problems
nip2:
 * A `test do` test block should be added
 * `require "formula"` is now unnecessary

**Comment by iml** [comment]
Still needs a `test` block. It can run a binary or compile a program. See [glpk](https://github.com/Homebrew/homebrew-science/blob/master/glpk.rb#L23-L36) for example

**Comment by jcupitt** [comment]
I'm sorry this is taking so long.

The remaining error (I think) now is travis failing to install intltool:

```
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
```

I don't see this error locally and I'm not sure how to resolve it.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by jcupitt** [comment]
Sorry, I don't know how to fix this, I think I need some expert help.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
