### PR TITLE
Update swetest.rb

### PR DESCRIPTION
**Pull request by cesare-montresor**
update sourcecode url to the newest version:
http://www.astro.com/ftp/swisseph/swe_unix_src_2.06.tar.gz

### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Mac builds fail with:
```
  * The URL http://www.astro.com/swisseph/ could use HTTPS rather than HTTP
  * Stable: The URL http://www.astro.com/ftp/swisseph/swe_unix_src_2.06.tar.gz could use HTTPS rather than HTTP
  * Stable resource "seasnam": The URL http://www.astro.com/ftp/swisseph/ephe/seasnam.txt could use HTTPS rather than HTTP
  * Stable resource "sefstars": The URL http://www.astro.com/ftp/swisseph/ephe/sefstars.txt could use HTTPS rather than HTTP
  * Stable resource "seas": The URL http://www.astro.com/ftp/swisseph/ephe/seas_18.se1 could use HTTPS rather than HTTP
  * Stable resource "semo": The URL http://www.astro.com/ftp/swisseph/ephe/semo_18.se1 could use HTTPS rather than HTTP
  * Stable resource "sepl": The URL http://www.astro.com/ftp/swisseph/ephe/sepl_18.se1 could use HTTPS rather than HTTP
```

You have also a checksum mismatch:
```
==> Verifying swetest-2.06.tar.gz checksum
Error: SHA256 mismatch
Expected: bd601d5e7982926a291eb6ed50ef846f85412411ebdc2a7ae67dbd200f952289
Actual: e2e3ac2cee53b38865b071f6d86ae0a05e0f608fbf3acc569104589d5a23576f
```

**Comment by cesare-montresor** [comment]
@iMichka Apologies for the delay, I was very close to a deadline for another project.
I've been updating the the http to https and she sha sum, but I'm not really an expert of brew and I don't know what I'm supposed to do with the sha under build section

```
    sha256 "976eac94471025db6abbe500edb9a98eb17e903632794620a8a97a2ba6059bf5" => :yosemite
    sha256 "5fac3c730b4c69804fb54198a513067c83a51d080a5d8e6e243e3169b8e10d9c" => :mavericks
sha256 "705b0a2d4d7c3fbfaccad6bcb6137eafe4360464b028ebe0eb4aab8ca945bb1f" => :mountain_lion
```

**Comment by iMichka** [comment]
These are the sha sums of the precompiled binaries (bottles). You should not modify them, we automatically update these when merging the changes.

There is a final http address that needs to be updated (on top of the formula):
> homepage "http://www.astro.com/swisseph/"

Just make that last change, and this will be ready to be merged.

**Comment by cesare-montresor** [comment]
@iMichka Thank you for the step by step guidance ^_^

**Comment by iMichka** [comment]
@cesare-montresor Thanks for the update and thanks for your contribution.

**Pull request closed without merging**
