### PR TITLE
update pocl to 0.13

### PR DESCRIPTION
**Pull request by pthariensflame**
I think I need help figuring out what to put in the newly-required `test` section.

### CODE REVIEW

**Comment by pthariensflame** [comment]
:/

**Comment by dpo** [comment]
Build error on 10.9:
```
clang++ -DHAVE_CONFIG_H -I. -I../..  -I../../fix-include -I../../include -I../../include -I../../lib/CL -DSRCDIR='"/private/tmp/pocl-20160530-37879-fgc61n/pocl-0.13/tests/regression"'  -D_THREAD_SAFE  -std=c++11 -Wno-deprecated -Wno-deprecated-declarations -g -O2 -MT test_barrier_between_for_loops.o -MD -MP -MF .deps/test_barrier_between_for_loops.Tpo -c -o test_barrier_between_for_loops.o test_barrier_between_for_loops.cpp
In file included from test_barrier_between_for_loops.cpp:28:
In file included from ../../include/CL/cl2.hpp:478:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:253:9: error: field has incomplete type 'cl::Device'
    _T1 first;
        ^
```

Test failure on 10.10 and 10.11:
```
OpenCL specification tests

  2: example1: dot product                           ok
  3: example1: dot product (SPIR64)                  FAILED (testsuite.at:51)
```

**Comment by tdsmith** [comment]
Test failure log: https://gist.github.com/anonymous/50beceb9ae2ad44ee5df77f0c430c4e3

```

## ---------------------- ##
## Detailed failed tests. ##
## ---------------------- ##

#                             -*- compilation -*-
3. testsuite.at:44: testing example1: dot product (SPIR64) ...
#define POCL_DEVICE_ADDRESS_BITS 64
./testsuite.at:51: $abs_top_builddir/examples/example1-spir64/example1-spir
stderr:
Undefined symbols for architecture x86_64:
  "__stack_chk_guard", referenced from:
      _pocl_launcher_dot_product in dot_product.so.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Assertion failed: (error == 0), function const char *llvm_codegen(const char *, cl_kernel, cl_device_id), file common.c, line 108.
/private/tmp/pocl-20160606-60488-1hrcezw/pocl-0.13/tests/testsuite.dir/at-groups/3/test-source: line 31: 82262 Abort trap: 6           $abs_top_builddir/examples/example1-spir64/example1-spir
--- -	2016-06-06 17:13:56.000000000 -0700
+++ /private/tmp/pocl-20160606-60488-1hrcezw/pocl-0.13/tests/testsuite.dir/at-groups/3/stdout	2016-06-06 17:13:56.000000000 -0700
@@ -1,6 +1 @@
-(0.000000, 0.000000, 0.000000, 0.000000) . (0.000000, 0.000000, 0.000000, 0.000000) = 0.000000
-(1.000000, 1.000000, 1.000000, 1.000000) . (1.000000, 1.000000, 1.000000, 1.000000) = 4.000000
-(2.000000, 2.000000, 2.000000, 2.000000) . (2.000000, 2.000000, 2.000000, 2.000000) = 16.000000
-(3.000000, 3.000000, 3.000000, 3.000000) . (3.000000, 3.000000, 3.000000, 3.000000) = 36.000000
-OK
 
./testsuite.at:51: exit code was 134, expected 0
3. testsuite.at:44: 3. example1: dot product (SPIR64) (testsuite.at:44): FAILED (testsuite.at:51)

#                             -*- compilation -*-
24. testsuite.at:251: testing Kernel functions << >> rotate ...
./testsuite.at:266: $abs_top_builddir/tests/kernel/kernel test_rotate
--- expout	2016-06-06 17:15:59.000000000 -0700
+++ /private/tmp/pocl-20160606-60488-1hrcezw/pocl-0.13/tests/testsuite.dir/at-groups/24/stdout	2016-06-06 17:16:04.000000000 -0700
@@ -1,2 +1,34 @@
 Running test test_rotate...
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0xffff8080 good=0xffff8080
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0xffff8080 good=0xffff8000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0x00008080 good=0x00008080
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0x00008080 good=0x00008000
 OK
24. testsuite.at:251: 24. Kernel functions << >> rotate (testsuite.at:251): FAILED (testsuite.at:266)
```

**Comment by tdsmith** [comment]
This seems like good advice, in any case; can you do this?

```
Please send `tests/testsuite.log' and all information you think might help:

   To: <pocl-devel@lists.sourceforge.net>
   Subject: [pocl 0.13] testsuite: 3 failed

You may investigate any problem if you feel able to do so, in which
case the test suite provides a good starting point.  Its output may
be found below `tests/testsuite.dir'.
```

**Comment by iMichka** [comment]
Superseded by #5482, pocl 0.14 is out. Closing here;

**Pull request closed without merging**
