### PR TITLE
Bump graph-tool version to 2.5

### PR DESCRIPTION
**Pull request by count0**

### CODE REVIEW

**Comment by dpo** [comment]
There's a build error:
```
../../../../src/graph/centrality/../graph_adaptor.hh:605:39: error: expected ';' in 'for' statement specifier
    for(typeof(removed_edges.begin()) iter = removed_edges.begin();
                                      ^
../../../../src/graph/centrality/../graph_adaptor.hh:605:39: error: use of undeclared identifier 'iter'
```

**Comment by count0** [comment]
Which compiler were you using?

**Comment by dpo** [comment]
The failure occurs on the build bot: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3102/version=yosemite/console

**Comment by count0** [comment]
I've made a new release that addresses this. I will open a different merge request for it.

**Pull request closed without merging**
