### PR TITLE
lastz: Use GitHub URL

### PR DESCRIPTION
**Pull request by dbolser-ebi**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
I accidentally created a pull request against my own fork!

Anyway, here is some context:
https://github.com/Homebrew/homebrew-science/commit/6515cc53c2cc289aa90575f6c2735d89261b6121

**Comment by jonchang** [comment]
People who have downloaded the source tarball and have it in their cache will hit an checksum error when rebuilding. Is this ok?

**Comment by iMichka** [comment]
> Is this ok?

Probably not. Why is the sha different?

**Comment by dbolser-ebi** [comment]
Not sure why there is a difference... perhaps I can unpack both files and
diff?​

**Comment by jonchang** [comment]
Shrug, it'll probably be fine. @iMichka it's probably because github regenerates the tarballs from source.

**Comment by iMichka** [comment]
Yeah, it is probably fine :) +1 on the change.

**Pull request merged**
