### PR TITLE
bpipe 0.9.8.7

### PR DESCRIPTION
**Pull request by saketkc**

### CODE REVIEW

**Comment by tdsmith** [comment]
@xu-cheng The test is failing while executing ps: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2943/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_Homebrew_science_bpipe/ -- is there a quick fix here?

**Comment by xu-cheng** [comment]
Unfortunately, it seems that there is no fix. Sandbox log shows `deny forbidden-exec-sugid` for running ps, which is a hard coded rule inside sandbox mechanism.

**Comment by saketkc** [comment]
I changed the test. The bot seems to have failed again

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
