### PR TITLE
med-file 3.2.1

### PR DESCRIPTION
**Pull request by luzpaz**
update minor version

### CODE REVIEW

**Comment by luzpaz** [comment]
looks like it failed trying to apply the patch.

**Comment by iMichka** [comment]
This means that either the patch is no more needed, or the patch needs to be updated to work with that version.

**Comment by luzpaz** [comment]
Looks like this part of the patch needs to be removed:
```
diff --git a/include/H5public_extract.h.in b/include/H5public_extract.h.in
index c38765e..0e9451c 100644
--- a/include/H5public_extract.h.in
+++ b/include/H5public_extract.h.in
@@ -28,10 +28,6 @@ extern "C" {
 @HDF5_TYPEDEF_HID_T@
 @HDF5_TYPEDEF_HSIZE_T@
 
-#typedef int herr_t;
-#typedef int hid_t;
-#typedef unsigned long long   hsize_t;
-
 #ifdef __cplusplus
 }
 #endif
```

**Comment by ilovezfs** [comment]
Why is this patch still needed at all? Did upstream reject integrating it?

**Comment by luzpaz** [comment]
maybe @bvenkat has any insight? It doesn't look like upstream integrated the full patch. Any ideas why ?
I'm posting something to the upstream forum now, see http://www.salome-platform.org/forum/forum_9/344694157#410288231

**Comment by bvenkat** [comment]
@luzpaz no ideas why it was not integrated upstream.  Looking at the med git repository at:
https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary
only the patch for typos / grammer has been integrated so far:
https://git.salome-platform.org/gitweb/?p=modules/med.git;a=commit;h=16ea929e026d029a9d69b3aa977bc0ddd9ad0a4c

**Comment by iMichka** [comment]
@luzpaz This will need to be rebased on master too. Any progress on finding out what needs to be done?

**Comment by luzpaz** [comment]
Don't have the resources to dedicate time to this, apologies

**Comment by iMichka** [comment]
No problem, it is okay to say no :) We will try to have a look, but I can't promise when. I'll close this for the moment, so that somebody else can open a new pull request later.

**Comment by luzpaz** [comment]
CC @bblacey

**Pull request closed without merging**
