### PR TITLE
visp: revision for jpeg

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-science/issues/6075

This will need to be rebuilt after #6078 is merged

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is 👍

I tried to pull with Linux bottles, but it fails with:

```
Patch format detection failed.
fatal: Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.
Error: Failure while executing: /usr/local/bin/brew pull-linux --bottle https://github.com/Homebrew/homebrew-science/pull/6088
```

**Comment by ilovezfs** [comment]
Same error for me. CC @sjackman

**Comment by sjackman** [comment]
`brew pull-bottle https://github.com/Homebrew/homebrew-science/pull/6088` worked for me. Sorry that I don't have an explanation s to why it failed for you. Perhaps you had tried it in the five minute window after CircleCI had finished, and before the new bottle was transferred to Bintray.

Merged. Thanks for your contribution to Homebrew/science, @fxcoudert!

**Comment by ilovezfs** [comment]
@sjackman it looks like `brew pull-bottle` was broken by

```
Josephs-MacBook-Pro:Homebrew joe$ git bisect bad
ae4bafdb365cfa380d129b0a03bd99a1e4d960a4 is the first bad commit
commit ae4bafdb365cfa380d129b0a03bd99a1e4d960a4
Author: Markus Reiter <me@reitermark.us>
Date:   Tue Aug 8 18:10:13 2017 +0200

    Simplify CurlDownloadStrategy.

:040000 040000 b15c81e7126ee2555fddf4bcb14d9168bf4faf5f 4bffd1cd11b4d551b5bf1f39f28e4d459553df2f M	Library
```
CC @reitermarkus RE https://github.com/Homebrew/brew/pull/3026

**Comment by reitermarkus** [comment]
I hope this fixes it: https://github.com/Linuxbrew/homebrew-developer/pull/60

**Pull request closed without merging**
