### PR TITLE
graph-tool 2.26

### PR DESCRIPTION
**Pull request by count0**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by geoglrb** [comment]
It'll be great to have homebrew science move from 2.22 to 2.25! Thanks!

**Comment by geoglrb** [comment]
Hi @ilovezfs et al.! I admit freely that I should find ways to help rather than prompt others to do so, but as someone who loves brew science and appreciates having newer versions of graph-tool available through it, I'm wondering if this is ready for a new test and/or action after the 2.25 bump... Thanks again and apologies!

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by count0** [comment]
The new release (2.26) should fix some of the build problems. Some other ones don't seem related to graph-tool at al.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @count0!

**Comment by shongololo** [comment]
I run brew upgrade today and ran into #6461 - any advice? It seems to be looking for the python development libraries though I thought this was installed with the default python on brew.

**Pull request closed without merging**
