### PR TITLE
newick-utils 1.6: Move to Homebrew/science

### PR DESCRIPTION
**Pull request by sjackman**
Fix error: use of undeclared identifier 'LUA_GLOBALSINDEX'

### CODE REVIEW

**Comment by sjackman** [comment]
```
+brew audit newick-utils
newick-utils:
 * Incorrect file permissions: chmod 644 /home/travis/build/Homebrew/linuxbrew/Library/Formula/newick-utils.rb
Error: 1 problems in 1 formulae
```

**Comment by sjackman** [comment]
```
brew bottle --merge --write newick-utils-1.6.mavericks.bottle.rb newick-utils-1.6.mountain_lion.bottle.rb newick-utils-1.6.yosemite.bottle.rb
==> newick-utils
  bottle do
    root_url "https://downloads.sf.net/project/machomebrew/Bottles/science"
    cellar :any
    sha1 "c057ef32105d170f335df978bf8418bed148c400" => :yosemite
    sha1 "342f80c6971ae577ed0dd526beea2dfd3a247e1f" => :mavericks
    sha1 "3b7c38cd7e5f49745cec7e320af0c6b337848db6" => :mountain_lion
  end
fatal: /Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Formula/newick-utils.rb: '/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Formula/newick-utils.rb' is outside repository
Error: Failure while executing: git commit --no-edit --verbose --message=newick-utils:\ add\ 1.6\ bottle. -- /Users/brew/Jenkins/jobs/Homebrew\ Bottles/workspace/Library/Formula/newick-utils.rb
Error: Failure while executing: brew bottle --merge --write newick-utils-1.6.mavericks.bottle.rb newick-utils-1.6.mountain_lion.bottle.rb newick-utils-1.6.yosemite.bottle.rb
Build step 'Execute shell' marked build as failure
```

**Comment by sjackman** [comment]
I believe https://github.com/Homebrew/homebrew/pull/35671 has to be merged before the bottles will be built correctly.

**Comment by mikemcquaid** [comment]
Pushed bottle in c481d763d97afcde9456fa283cd38713a74da4df

**Comment by mikemcquaid** [comment]
Hmm, I'm getting Travis CI emails from this. Can it be configured to not do that? Thanks!

**Comment by saketkc** [comment]
Yes, will disable it in #1631.

**Comment by sjackman** [comment]
Disabled email notifications in 5500eae319278f116d21d77c31a45c817d918972.

**Pull request closed without merging**
