### PR TITLE
Bump revision of HDF5 dependents part 6.

### LINKED ISSUE #2751: MINC executables can't find libhdf5.9.dylib
The current head is 8a3a372. Package "minc" (installed from bottle) depends on libhdf5.9.dylib, which comes from package "hdf5". But package "hdf5" installs libhdf5.10.dylib. This results is that "minc" executables fail, e.g.:

    $ nii2mnc
    dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
      Referenced from: /usr/local/bin/nii2mnc
      Reason: image not found
    Trace/BPT trap: 5

Formula "hdf5" was updated on 2015-09-17. For some reason the bottle for "minc" is still out of date.

### PR DESCRIPTION
**Pull request by dpo**
Fixes #2751.

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
```
libsrc2/hyper.c:773:4: error: non-void function 'miget_real_value_hyperslab' should return a value [-Wreturn-type]
          return;
          ^
1 error generated.
make[1]: *** [libsrc2/hyper.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I./libsrc -I./volume_io/Include -I./volume_io/Include -I./progs/Proglib -I./conversion/Acr_nema -I./libsrc2 -g -O2 -c libsrc2/label.c -o libsrc2/label.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

```

**Comment by dpo** [comment]
`moab` has a failed test on 10.10 which prevents bottling:
```
PASS: verdict_test
../config/test-driver: line 107: 35596 Abort trap: 6           "$@" > $log_file 2>&1
```

**Comment by dpo** [comment]
@tseemann Not sure where you got that compilation error from.

**Comment by dpo** [comment]
`minc` also fails to build with the error mentioned above by @tseemann.

**Pull request closed without merging**
