### PR TITLE
Slepc 3.6 (updated)

### PR DESCRIPTION
**Pull request by davydden**
pull after https://github.com/Homebrew/homebrew-science/pull/2505

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
The download url is broken, but http://slepc.upv.es/download/download.php?filename=slepc-3.6.0.tar.gz seems to work.

**Comment by davydden** [comment]
hm, interesting... i updated the link.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
