### PR TITLE
nexusformat: rename hdf4 and make libmxml optional

### PR DESCRIPTION
**Pull request by quantumsteve**
nexusformat fails several tests when built with libmxml 2.10. I created an [issue upstream](https://github.com/nexusformat/code/issues/443).

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for your contribution. The hdf4 change is LGTM, I'm ok on that.

For the libmxml part, does it just break the special case where you would like to use that feature, or does it break nexusformat completely. We may leave libmxml as is and just wait for upstream to fix it.
It just that we are trying to avoid having too many optional dependencies, as they do not get tested/build against.

**Comment by quantumsteve** [comment]
Most NeXus files are HDF5 or HDF4 files. XML is a legacy format primarily used to aid debugging.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@quantumsteve Thanks for your contribution!

**Pull request closed without merging**
