### PR TITLE
TrimAL 1.4.1 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
trimAl is a tool for the automated removal of spurious sequences or poorly aligned regions from a multiple sequence alignment Access trimAl publication

trimAl can consider several parameters, alone or in multiple combinations, in order to select the most-reliable positions in the alignment. These include the proportion of sequences with a gap, the level of residue similarity and, if several alignments for the same set of sequences are provided, the consistency level of columns among alignments. Moreover, trimAl is able to manually select a set of columns to be removed from the alignment.

Additionally, trimAl implements a series of automated algorithms that apply different thresholds, based on the characteristics of each alignment, to be used so that the signal-to-noise ratio after alignment trimming phase is optimized.

### CODE REVIEW

**Comment by tseemann** [comment]
Huh?

```
Error Message

failed: brew doctor
Stacktrace

        Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install suite-sparse tbb

Run `brew missing` for more details.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
```

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@sjackman This is a new error! 
```
==> trimal 2>&1
Error: trimal: failed
invalid byte sequence in US-ASCII
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `assert_match'
/usr/local/Library/Taps/homebrew/homebrew-science/trimal.rb:18:in `block in <class:Trimal>'
```

**Comment by sjackman** [comment]
My guess is that it's specific to the version of Ruby. It works for me. It's almost certainly caused by the accents in the author's name and the region being set to `US-ASCII` instead of `UTF-8`
```
❯❯❯ brew test trimal -v
Testing trimal
==> trimal 2>&1
==> readal 2>&1
==> statal 2>&1
❯❯❯ trimal |head -n2

trimAl v1.4.rev15 build[2013-12-17]. 2009-2013. Salvador Capella-Gutierrez and Toni Gabaldón.
```

**Pull request closed without merging**
