### PR TITLE
P4est: Specify MPI compilers

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@sjackman Any idea why `pandaseq` isn't in Linuxbrew?

**Comment by sjackman** [comment]
pandaseq works fine on my Linux box. I'm not sure. Maybe it will be a transient issue? It's new package as of today.

```
$ brew info pandaseq
pandaseq: stable 2.8.1, HEAD
https://github.com/neufeld/pandaseq
/gsc/btl/linuxbrew/Cellar/pandaseq/2.8.1 (50 files, 2.0M) *
  Built from source
From: https://github.com/homebrew/homebrew-science/blob/master/pandaseq.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, pkg-config ✔
```

**Comment by sjackman** [comment]
```
==> brew readall							 FAILED
Error: problem in /home/travis/build/Homebrew/linuxbrew/Library/Formula/pandaseq.rb
No available formula for pandaseq 
```

**Pull request closed without merging**
