### PR TITLE
anvio 1.2.0 (new formula)

### PR DESCRIPTION
**Pull request by ozcan**
Anvi’o is an analysis and visualization platform for ‘omics data. 

Website: http://merenlab.org/projects/anvio/
Method paper: https://peerj.com/articles/1319/
Github repository: https://github.com/meren/anvio

To test after installation:

```
git clone -b v1.2.0 --depth=1 https://github.com/meren/anvio.git
cd anvio/tests
./run_mini_test.sh
```

After successfull completion you should see:

```
<<<LONG OUTPUT HERE>>>
#
#
# Firing up the interactive interface ...
#
#

Contigs DB ...................................: Initialized: test-output/CONTIGS.db (v. 3)
Auxiliary Data ...............................: Found: test-output/204-MERGED/AUXILIARY-DATA.h5 (v. 1)
Profile DB ...................................: Initialized: test-output/204-MERGED/PROFILE.db (v. 6)

* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.

* Clustering of 'tnf-cov' has been requested
```

And your default browser should open after this to take you to the interactive interface, then click 'Draw' at bottom left, and you should see something like this: 
screen shot 2015-11-04 at 11-compressed 2

### CODE REVIEW

**Comment by tseemann** [comment]
Can you squash your commits into a single commit please?
eg. `git rebase -i HEAD~6`

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
```
There are several valid include directories containing numpy/arrayobject.h
1: /usr/local/lib/python2.7/site-packages
2: /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Selection [default=1]:Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 36, in <module>
    s = input('Selection [default=1]:')
EOFError: EOF when reading a line
```

**Comment by dpo** [comment]
Will this be updated?

**Comment by jonchang** [comment]
Superceded by #4775.

**Pull request closed without merging**
