### PR TITLE
gnudatalanguage: migrate hdf4 from versions to science tap

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Travis error is probably that one: https://sourceforge.net/p/gnudatalanguage/mailman/gnudatalanguage-devel/thread/20170112180127.7ab965f6@planck4/

**Comment by iMichka** [comment]
> CMakeFiles/gdl.dir/magick_cl.cpp.o: In function `lib::magick_open(EnvT*)':
magick_cl.cpp:(.text+0x2eb): undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by iMichka** [comment]
Passing on the Travis build failure for the moment.

**Comment by ilovezfs** [comment]
:tada:

**Pull request closed without merging**
