### PR TITLE
blast 2.6.0

### PR DESCRIPTION
**Pull request by iMichka**
Upstream told us the patch was merged, but it does not seem
to be the case for 2.6.0, so the patch needs to stay.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like the build failure on Linux is because we still haven't migrated `depends_on "numpy" => :python` to the `numpy` in homebrew/core

**Comment by iMichka** [comment]
@sjackman circle.ci failed with

> ==> Installing orthofinder from homebrew/science
orthofinder: Unsatisfied dependency: scipy
Homebrew does not provide special Python dependencies; install with:
  `pip install scipy`
Error: An unsatisfied requirement failed this build.

**Comment by iMichka** [comment]
Maybe I can just skip the Linux bottle for the moment. One would still be able to build it by installing script through pip.

**Comment by sjackman** [comment]
`blast` built fine, and there's a bottle for it. It's actually `orthofinder` that's failing to build.
```
==> brew install orthofinder
==> Installing orthofinder from homebrew/science
orthofinder: Unsatisfied dependency: scipy
Homebrew does not provide special Python dependencies; install with:
  `pip install scipy`
Error: An unsatisfied requirement failed this build.
==> FAILED
```

**Comment by jonchang** [comment]
Right, we need to move things to the new `scipy` formula in core.

**Comment by sjackman** [comment]
@iMichka You can merge this PR with the Linuxbrew bottle, and we can fix the `numpy` issues in reverse dependencies in a separate PR.

**Comment by iMichka** [comment]
Right, sorry for the noise, I did look to fast at this, and forgot to check for the bottles. I'll merge it. Thanks.

**Pull request closed without merging**
