### PR TITLE
bowtie2 2.3.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@sjackman looks like tophat is broken again.

**Comment by ilovezfs** [comment]
@BenLangmead any idea what the problem is here?

**Comment by BenLangmead** [comment]
Where do we look for an error message?
@ch4rr0

**Comment by ilovezfs** [comment]
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/195/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_tophat/

**Comment by BenLangmead** [comment]
Thanks we'll take a look.
@ch4rr0

**Comment by ch4rr0** [comment]
I am unsure why this is happening. I downloaded the bowtie2 package from the GitHub link that your brew script references, but ran into no failures.

$ PATH=$PATH:/tmp/bowtie2-2.3.2/ ./tophat -r 20 ../test_data/test_ref ../test_data/reads_1.fq ../test_data/reads_2.fq 

[2017-05-08 14:46:47] Beginning TopHat run (v2.1.1)
-----------------------------------------------
[2017-05-08 14:46:47] Checking for Bowtie
		  Bowtie version:	 2.3.2.0
[2017-05-08 14:46:47] Checking for Bowtie index files (genome)..
	Found both Bowtie1 and Bowtie2 indexes.
[2017-05-08 14:46:47] Checking for reference FASTA file
[2017-05-08 14:46:47] Generating SAM header for ../test_data/test_ref
[2017-05-08 14:46:47] Preparing reads
	 left reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
	right reads: min. length=75, max. length=75, 100 kept reads (0 discarded)
[2017-05-08 14:46:47] Mapping left_kept_reads to genome test_ref with Bowtie2 
[2017-05-08 14:46:47] Mapping left_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-05-08 14:46:47] Mapping left_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-05-08 14:46:47] Mapping left_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-05-08 14:46:47] Mapping right_kept_reads to genome test_ref with Bowtie2 
[2017-05-08 14:46:47] Mapping right_kept_reads_seg1 to genome test_ref with Bowtie2 (1/3)
[2017-05-08 14:46:47] Mapping right_kept_reads_seg2 to genome test_ref with Bowtie2 (2/3)
[2017-05-08 14:46:47] Mapping right_kept_reads_seg3 to genome test_ref with Bowtie2 (3/3)
[2017-05-08 14:46:47] Searching for junctions via segment mapping
[2017-05-08 14:46:47] Retrieving sequences for splices
[2017-05-08 14:46:47] Indexing splices
Building a SMALL index
[2017-05-08 14:46:48] Mapping left_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
[2017-05-08 14:46:48] Mapping left_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
[2017-05-08 14:46:48] Mapping left_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
[2017-05-08 14:46:48] Joining segment hits
[2017-05-08 14:46:48] Mapping right_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
[2017-05-08 14:46:48] Mapping right_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
[2017-05-08 14:46:48] Mapping right_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
[2017-05-08 14:46:48] Joining segment hits
[2017-05-08 14:46:48] Reporting output tracks
-----------------------------------------------
[2017-05-08 14:46:48] A summary of the alignment counts can be found in ./tophat_out/align_summary.txt
[2017-05-08 14:46:48] Run complete: 00:00:01 elapsed

**Comment by sjackman** [comment]
```
===> brew linkage --test tophat
Missing libraries:
  libboost_system-mt.so.1.63.0
  libboost_thread-mt.so.1.63.0
```
Looks like `tophat` bottle needs to be rebuilt for `boost` 1.64 on Linuxbrew.

**Comment by ilovezfs** [comment]
[tophat revision for boost 1.64.0](https://github.com/Homebrew/homebrew-science/pull/5617)

**Comment by ilovezfs** [comment]
@BenLangmead @ch4rr0 to reproduce this, you need OS X 10.11 with Xcode 8.2.1, and the Command Line Tools not installed, or if both Xcode 8.2.1 and the Command Line Tools are installed, you need to set `SDKROOT` to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`

**Comment by ilovezfs** [comment]
@BenLangmead @ch4rr0 @sjackman I've shipped it with the workaround for now. Note that it will fail to build for any users who have only Xcode, but not the CLT.

**Comment by ch4rr0** [comment]
I don't think that's supposed to work -- at least according to StackOverflow: http://stackoverflow.com/questions/39224905/how-do-i-install-xcode-8-without-updating-macos.

**Comment by ilovezfs** [comment]
@ch4rr0 it most certainly is supposed to work. Xcode 8 is the version of Xcode you will get on 10.11 by default from the Mac App Store. See prior discussion of the topic here:
https://github.com/Homebrew/brew/issues/1550

**Comment by BenLangmead** [comment]
What fail to build?  Bowtie 2 or TopHat?

**Comment by ilovezfs** [comment]
The Bowtie 2 build succeeds with Xcode 8, but it doesn't actually work properly when called by the top hat test. This problem should be bisectable, since it was not present in 2.3.0.

**Pull request closed without merging**
