### PR TITLE
harvest-tools 1.2 (update)

### PR DESCRIPTION
**Pull request by tseemann**
Had to add in new dependency to get it to build (capnp).

### CODE REVIEW

**Comment by tseemann** [comment]
Any idea why capnp fails on mountain-lion but is ok on the rest?

```
checking for capnp/common.h... no
configure: error: Cap'n Proto headers not found.
```

**Comment by tseemann** [comment]
Upstream author admits bug: https://github.com/marbl/harvest-tools/issues/7

**Comment by iml** [comment]
You can try applying that commit as a patch, referencing the above issue.
```
patch do
  url "https://github.com/marbl/harvest-tools/commit/c20b1a4.diff"
  sha256 ""
end

**Comment by tseemann** [comment]
I'm restarting this one.

**Pull request closed without merging**
