### PR TITLE
graph-tool: use libboost_python3

### PR DESCRIPTION
**Pull request by itcarroll**
There may be a more appropriate way to link with libboost_python3 when necessary, but this worked for me. Addresses #2613.

### CODE REVIEW

**Comment by itcarroll** [comment]
@tdsmith You seem to be one of the experts on boost-python dependency. I'm not sure if this relates to the test failure, but I'm getting that `brew info graph-tool --with-python3` seems insensitive to whether or not boost-python was poured from bottle (i.e. not using `with-python3`).

**Comment by tdsmith** [comment]
What are you seeing and what did you expect to see?

**Comment by itcarroll** [comment]
With the bottled version of boost-python, `brew info graph-tool --with-python3` shows the dependency for boost-python as satisfied. I expect it to show the dependency is not satisfied with this option, because `brew install graph-tool --with-python3` depends on the boost-python3 library.

**Comment by tdsmith** [comment]
Ah, the `info` icon isn't that smart. The correct behavior should happen on `install`. The test failure looked like a bot error; I wouldn't have expected this change to affect the build since it's only activated by an optional dependency.

**Comment by itcarroll** [comment]
You're right, `install` catches the option.

**Comment by itcarroll** [comment]
I think the test result is a bot fail. Compile error is:

    fatal error: error in backend: IO failure on output stream.

Can't tell where to file an issue...

**Comment by tdsmith** [comment]
I think the bot is running out of disk space.

**Comment by tdsmith** [comment]
Pulled; thanks very much for your contribution to Homebrew!

**Comment by ToferC** [comment]
Sorry - I just tried to install graph-tools via Homebrew and hit this issue with Python 3.  I've upgraded all packages and am using boost 1.58.0 and graph-tool 2.2.44 on a mac OS X Mavericks.

Is the fix above part of keg/science yet?  If not, can you advise how I can get the build working?  Thanks!

This is the error:

Python 3.4.2 (default, Oct 30 2014, 21:11:49) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/graph_tool/__init__.py", line 102, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python3.4/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.4/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/lib/libboost_python.dylib
  Expected in: flat namespace
 in /usr/local/lib/libboost_python.dylib

Python 2.7 works fine.

**Comment by itcarroll** [comment]
The fix was integrated. Did you use the --with-python3 flag? I'm not sure whether you have to manually re-install dependencies (like boost-python) --with-python3 or whether brew does that for you.

**Comment by sandrofsousa** [comment]
I'm facing the same problem even though using the last formulae. The correction commented here is in the script but the ```libboost_python3.dylib``` is missing. Looks like homebrew is ignoring the ```--with-python3``` option.

**Comment by itcarroll** [comment]
@sandrofsousa I think your assessment is correct (that with-python3 isn't getting passed to the boost-python dependency) but I don't know enough ruby to confirm/fix. If you reinstall `boost-python --with-python3 --c++11` and then `graph-tool --with-python3`, does it work?

**Comment by mkhorton** [comment]
Just had this issue myself, can confirm that itcarrol's reinstallation instructions work for anyone else who has this issue (on OS X 10.11.6, Python 3.5.2)

**Pull request closed without merging**
