### PR TITLE
getdp (fix)

### PR DESCRIPTION
**Pull request by schoeps**
now using always the correct executable in the tests. This fixes the bug observed in pull request #2630 (Petsc 3.6.1).

### CODE REVIEW

**Comment by davydden** [comment]
```
#    error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
```
i suppose this PR has to wait until https://github.com/Homebrew/homebrew-science/pull/2630 is merged and the bottles are updated...

**Comment by dpo** [comment]
Yes. I presume `gmsh` will have to get bumped too.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
