### PR TITLE
plr 8.3.0.17

### LINKED ISSUE #5289: plr is broken
`brew test plr` is failing on the bot:

```
==> /usr/local/opt/postgresql/bin/psql -p 55561 -d test --command CREATE EXTENSION plr;
ERROR:  incompatible library "/usr/local/lib/postgresql/plr.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.5.
STATEMENT:  CREATE EXTENSION plr;
ERROR:  incompatible library "/usr/local/lib/postgresql/plr.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.5.
Error: homebrew/science/plr: failed
```

### PR DESCRIPTION
**Pull request by jonchang**
Fixes #5289. CC @tdsmith

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
R bottles weren't published, lol.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Circle ci fails with:
> ==> make DESTDIR=/tmp/plr-20170323-51140-t6y8ie/plr-REL8_3_0_17/stage PG_CONFIG=/home/linuxbrew/.linuxbrew/opt/postgresql/bin/pg_config install
.
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/plr/8.3.0.17/lib
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/plr/8.3.0.17/share/doc/plr/postgresql/extension
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/plr/8.3.0.17/share/postgresql/extension
Error: Empty installation
==> FAILED

**Pull request closed without merging**
