### PR TITLE
raxml 8.2.8 (new version)

### PR DESCRIPTION
**Pull request by jonchang**
Add MPI version (Linux only) and a better test.

### CODE REVIEW

**Comment by jonchang** [comment]
Updated for v8.2.8.

**Comment by jonchang** [comment]
Sorry to be a bother, but could I get this reviewed please? @sjackman @dpo

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Sure, the tests failed, but the logs expired, so I'm rerunning the tests.
Do you have access to a Mac for testing?

**Comment by jonchang** [comment]
I have no idea why the tests on Travis are timing out. From my machine:

```
 $ time brew test raxml
Testing homebrew/science/raxml
==> Using the sandbox
==> raxmlHPC-PTHREADS -f a -m GTRGAMMA -p 12345 -x 12345 -N 100 -s aln.phy -n test -T 2

real	0m6.998s
user	0m12.229s
sys	0m0.290s
```

**Comment by sjackman** [comment]
`Elapsed time 12 min 4 sec`, so I don't think it timed out.
https://travis-ci.org/Homebrew/homebrew-science/jobs/118087016

**Comment by sjackman** [comment]
Wait, Travis times out after ten minutes with no output, so yes, it does look like it's timing out.

**Comment by sjackman** [comment]
Let's see what the BrewTestBot gives.

**Comment by sjackman** [comment]
Merged. Nice work, Jon. Thanks!

**Pull request closed without merging**
