### PR TITLE
Updating SYMPHONY

### PR DESCRIPTION
**Pull request by tkralphs**
This just updates to the latest version of SYMPHONY and removes the fails_with, since SYMPHONY now builds with clang.

### CODE REVIEW

**Comment by dpo** [comment]
````
Error validating server certificate for 'https://projects.coin-or.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.coin-or.org
 - Valid: from Fri, 11 Apr 2014 20:44:41 GMT until Tue, 11 Apr 2017 20:44:41 GMT
 - Issuer: http://certs.godaddy.com/repository/, GoDaddy.com, Inc., Scottsdale, Arizona, US
 - Fingerprint: e7:5b:e2:82:44:7f:ef:52:8b:e2:07:b0:d9:b4:27:0c:0e:64:11:56
(R)eject, accept (t)emporarily or accept (p)ermanently? svn: E175002: Unable to connect to a repository at URL 'https://projects.coin-or.org/svn/Data/miplib3/stable/1.2/air03.gz'
svn: E175002: OPTIONS of 'https://projects.coin-or.org/svn/Data/miplib3/stable/1.2/air03.gz': Server certificate verification failed: issuer is not trusted (https://projects.coin-or.org)
````

**Comment by tkralphs** [comment]
I updated the pull request. I had already been thinking that "make fulltest" was overkill. That is quite a length test now and is more than what the average user is going to want to run (or wait for). The "make fulltest" is what was trying to download additional files and caused the problem you reported. I also removed --enable-dependency-linking since this now default.

**Comment by dpo** [comment]
Thanks! Would you mind squashing your commits?

**Comment by tkralphs** [comment]
I'm still not exactly a git guru, despite having used it a lot and having read many explanations of various aspects of git on stackoverflow and elsewhere (does the learning curve ever end?). There seem to be a lot of ways of squashing commits and I think I managed it but I'm not entirely clear on why the commits that I squashed still appear as part of this pull request. Let me know if this does the trick.

**Comment by dpo** [comment]
Now you have even more commits :). The problem is that you merged, and so your commits show tons of files updated. The easiest at this point would be to create a fresh branch and re-submit your combined updated as a single commit. Sorry for the hassle.

**Comment by tkralphs** [comment]
Ugh :). I wish I understood git. The more I read, the less I understand. I only merged because git said I had to in order to push :)! I guess switching to a different branch gets around that. I'll try to fix it up.

**Comment by tkralphs** [comment]
OK, I submitted another cleaner pull request #1783. Closing this one.

**Pull request closed without merging**
