### PR TITLE
timblserver (latest) (new formula)

### PR DESCRIPTION
**Pull request by fbkarsdorp**
server of TiMBL

### CODE REVIEW

**Comment by dpo** [comment]
I'm still getting a similar error on Mavericks. I'll restart the build bot so you can look at the output.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
There's no longer a `timbl` formula in `homebrew-science`. Should this be closed out? Or can it work with different dependencies?

**Comment by apjanke** [comment]
Oops, nevermind; my local Git repo was messed up.

**Comment by dpo** [comment]
This is currently at version 6.4.8: https://github.com/LanguageMachines/timbl/releases. Please open a new pull request if still interested in adding this to homebrew/science.

**Pull request closed without merging**
