### PR TITLE
libsequence 1.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
FAIL: FastaExplicitIO
FAIL: FastaIO
```
test failures on 10.11 and 10.10

**Comment by molpopgen** [comment]
(I'm the developer, btw.)  The "make check" doesn't pass on Travis for reasons I do not understand.  It works fine on my El Capitan machines.  I'll push changes to 1.9.1 to try to investigate it, but the unit tests rely on some data files, which seems to be the hangup.

**Comment by molpopgen** [comment]
@ilovezfs Use a command like this to run the unit tests of Travis/OS X: 

https://github.com/molpopgen/libsequence/blob/dev/.travis.yml#L44

I have no idea why the "make check" fails on Travis/OS X, but it is a "won't fix", as I cannot reproduce it anywhere else.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
