### PR TITLE
Plink2: Use brewed zlib and OpenBLAS.

### LINKED ISSUE #1957: plink2 1.90b3 -  fatal error: cblas.h: No such file or directory
@saketkc - error log below for Linuxbrew on recently new recipe plink2. 

It can't find ```cblas.h``` which was installed by the ```openblas``` (I can see it in BREW/include).

My guess is a successful compile is probably using a system openblas rather than the Brew one, which I don't have installed?

Probably needs a compile option ```-I$BREW/include``` ?

```
==> Installing plink2 from homebrew/homebrew-science
==> Using a fortran compiler found at /bin/gfortran.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/chrchang/plink-ng/archive/v1.90b3.tar.gz
Already downloaded: /root/.cache/Homebrew/plink2-1.90b3.tar.gz
==> Verifying plink2-1.90b3.tar.gz checksum
tar xf /root/.cache/Homebrew/plink2-1.90b3.tar.gz
==> ./plink_first_compile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  557k  100  557k    0     0   210k      0  0:00:02  0:00:02 --:--:--  209k
<snip>
zlib-1.2.8/zutil.c
zlib-1.2.8/zutil.h
Checking for shared library support...
Building shared library libz.so.1.2.8 with /usr/bin/gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o adler32.o adler32.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o crc32.o crc32.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o deflate.o deflate.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o infback.o infback.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o inffast.o inffast.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o inflate.o inflate.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o inftrees.o inftrees.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o trees.o trees.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o zutil.o zutil.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o compress.o compress.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o uncompr.o uncompr.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o gzclose.o gzclose.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o gzlib.o gzlib.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o gzread.o gzread.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -isystem/bio/linuxbrew/include  -c -o gzwrite.o gzwrite.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/adler32.o adler32.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/crc32.o crc32.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/deflate.o deflate.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/infback.o infback.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/inffast.o inffast.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/inflate.o inflate.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/inftrees.o inftrees.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/trees.o trees.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/zutil.o zutil.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/compress.o compress.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/uncompr.o uncompr.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/gzclose.o gzclose.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/gzread.o gzread.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/gzlib.o gzlib.c
/usr/bin/gcc -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DPIC -c -o objs/gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o -L. libz.a
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip minigzip.o -L. libz.a
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example64 example64.o -L. libz.a
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip64 minigzip64.o -L. libz.a
/usr/bin/gcc -shared -Wl,-soname,libz.so.1,--version-script,zlib.map -Os -w -pipe -march=core2  -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o libz.so.1.2.8 adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxbrew/lib 
rm -f libz.so libz.so.1
ln -s libz.so.1.2.8 libz.so
ln -s libz.so.1.2.8 libz.so.1
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o examplesh example.o -L. libz.so.1.2.8
/usr/bin/gcc -Os -w -pipe -march=core2  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzipsh minigzip.o -L. libz.so.1.2.8
g++ -Wall -O2 plink.c plink_assoc.c plink_calc.c plink_cluster.c plink_cnv.c plink_common.c plink_data.c plink_dosage.c plink_family.c plink_filter.c plink_glm.c plink_help.c plink_homozyg.c plink_lasso.c plink_ld.c plink_matrix.c plink_misc.c plink_set.c plink_stats.c SFMT.c dcdflib.c pigz.c yarn.c -o plink -L/usr/lib64/atlas -llapack -lcblas -latlas -lm -lpthread -L. zlib-1.2.8/libz.so.1.2.8
In file included from plink_glm.h:4:0,
                 from plink_dosage.h:4,
                 from plink.c:34:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_assoc.c:7:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_calc.c:77:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_cluster.c:4:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_glm.h:4:0,
                 from plink_dosage.h:4,
                 from plink_dosage.c:5:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_stats.h:4:0,
                 from plink_family.c:5:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_stats.h:4:0,
                 from plink_filter.c:4:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_glm.c:6:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_lasso.c:4:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_glm.h:4:0,
                 from plink_ld.c:5:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_matrix.c:3:0:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_stats.h:4:0,
                 from plink_misc.c:4:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
In file included from plink_stats.h:4:0,
                 from plink_stats.c:3:
plink_matrix.h:57:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
make: *** [plink] Error 1
==> Formula
Tap: homebrew/homebrew-science
```
Path: /bio/linuxbrew/Library/Taps/homebrew/homebrew-science/plink2.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew.git
HEAD: a81d1ab4c53cbbc6ad6f80c024f94d09ee4893c0
Last commit: 2 days ago
HOMEBREW_PREFIX: /bio/linuxbrew
HOMEBREW_CELLAR: /bio/linuxbrew/Cellar
CPU: 72-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 2.0.0-p598 => /usr/bin/ruby
Perl: /bin/perl => /usr/bin/perl
Python: /bin/python => /usr/bin/python2.7
Ruby: /bin/ruby => /usr/bin/ruby
Java: 1.7.0_75
==> ENV
CC: /usr/bin/gcc
CXX: /usr/bin/g++
OBJC: /usr/bin/gcc
OBJCXX: /usr/bin/g++
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/bio/linuxbrew/include
LDFLAGS: -L/bio/linuxbrew/lib -Wl,-rpath,/bio/linuxbrew/lib
MAKEFLAGS: -j72
CMAKE_PREFIX_PATH: /bio/linuxbrew
PKG_CONFIG_LIBDIR: /bio/linuxbrew/lib/pkgconfig
PATH: /bio/perl5/bin:/bio/linuxbrew/bin:/bio/perl5/bin:/bio/linuxbrew/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/bio/linuxbrew/Library/ENV/scm

Error: plink2 1.90b3 did not build
```

### PR DESCRIPTION
**Pull request by dpo**
Fixes #1957.

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
````
Error: No available formula for zlib 
````
???

**Comment by tdsmith** [comment]
`homebrew/dupes/zlib`; we should try to use system zlib on OS X.

**Comment by dpo** [comment]
Oh thanks. It seems this formula requires zlib 1.2.8 though.

**Comment by sjackman** [comment]
> Oh thanks. It seems this formula requires zlib 1.2.8 though.

Please include that information in the formula in a comment.

**Pull request closed without merging**
