### PR TITLE
vtk 7.1.0

### PR DESCRIPTION
**Pull request by iMichka**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@iMichka any idea what the current status of fixing the audit failure is?

**Comment by iMichka** [comment]
Yes. My patch is awaiting to get reviewed/merged since months: https://gitlab.kitware.com/vtk/vtk/merge_requests/1713

I feel a little bit left alone here ... there seems to be no momentum do get this going. The patch would be for 7.1.0 anyway as I just rebased it on the latest master. Maybe you could put a small comment too on the merge request.

I mean, it the patch is not the way to solve this and VTK upstream do not want to merge it, they should tell. But for the moment its stuck at the first "review" step. Not sure how I can make more pressure here, I do not want to upset people too. We are all open source maintainers and time is precious. But I lost a lot of time writing that patch too :)

**Comment by iMichka** [comment]
But in the meantime we can still merge this as there is a workaround in the formula for this problem.

The only error I could see in the build failures is on the Travis build:
> /opt/python/2.7.10/lib/libpython2.7.a ../../lib/libvtksys-7.1.so.1 -ldl -Wl,-rpath,/tmp/vtk-20161125-18572-1ct592c/VTK-7.1.0/build/lib: 
/usr/bin/ld: /opt/python/2.7.10/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/opt/python/2.7.10/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libvtkWrappingPython27Core-7.1.so.1] Error 1
make[2]: Leaving directory `/tmp/vtk-20161125-18572-1ct592c/VTK-7.1.0/build'
make[1]: *** [Wrapping/PythonCore/CMakeFiles/vtkWrappingPythonCore.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

On my mac I do not have this Python installed (/opt/python/2.7.10), so there may be something weird on the Travis setup.

**Comment by iMichka** [comment]
BTW do not worry about the PCL bottles, I made another PR for PCL that removes the qt4 option, so bottles can be built once #4650 is merged.

**Comment by jonchang** [comment]
Thanks for the version bump @iMichka. Please keep us posted if and when upstream accepts your patch.

**Pull request closed without merging**
