### PR TITLE
nanoflann 1.2.3 (new formula)

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

~~Comments:~~
~~- The included unit tests are self-contained and really quick to build and run, so they're being invoked in the test section~~

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman the normal bottle issues again that I can't seem to avoid :(
```
torsten$ brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/6139
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-science/pull/6139.patch
######################################################################## 100.0%
==> Applying patch
Applying: nanoflann 1.2.3 (new formula)
==> Patch closes issue #6139
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-6139.patch
######################################################################## 100.0%
==> Applying patch
Applying: nanoflann 1.2.3 (new formula)
Applying: nanoflann: add 1.2.3 bottle.
==> Publishing on Bintray: nanoflann 1.2.3
{"files":0}
==> Patch changed:
 nanoflann.rb | 39 +++++++++++++++++++++++++++++++++++++++
 1 file changed, 39 insertions(+)
==> Verifying bottles published on Bintray
Verifying bottle: nanoflann-1.2.3.sierra.bottle.tar.gz
Waiting on Bintray............................................................................................................................................................................................................................................................................................................Error: Failed to find published nanoflann bottle at https://homebrew.bintray.com/bottles-science/nanoflann-1.2.3.sierra.bottle.tar.gz!
```

**Comment by jonchang** [comment]
@tseemann looks like bottles never got uploaded or they expired. Rerunning CI should fix things.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Sérgio!

**Comment by SergioRAgostinho** [comment]
👍 Thank you for your continued work.

FYI: @jlblancoc nanoflann is on homebrew now, in case you want to include the info on the project's Readme.md.

**Comment by jlblancoc** [comment]
@SergioRAgostinho Thanks!

I'm not an OSX user so I can't try this myself... Please, confirm to me if [these instructions](https://github.com/jlblancoc/nanoflann/commit/7c395f894731b49fe1bd40e16ca5bbb9a7817d71) are enough. 

Cheers!

**Comment by SergioRAgostinho** [comment]
It might require an additional step. I'll file the PR with the changes and let's proceed with the conversaiton there.

**Pull request closed without merging**
