### PR TITLE
omcompiler 1.11.0

### PR DESCRIPTION
**Pull request by SimplyDanny**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by SimplyDanny** [comment]
Since I have no possibility to test the Formula on Yosemite, I decided to use `depends_on :macos => :el_capitan`.

**Comment by iMichka** [comment]
What was the build failure on Yosemite? It's annoying to get a version bump but loose Yosemite support due to that. But this is probably okay, people on Yosemite will need to roll back manually to the old version ...

**Comment by ilovezfs** [comment]
:-1: to dropping Yosemite unless upstream explicitly says they no longer want to support it.

**Comment by StefanD986** [comment]
@SimplyDanny Was there a specific reason why the (optional) `boost` dependency was removed?

**Comment by SimplyDanny** [comment]
@iMichka As far as I can remember there was a problem with the makefile. Unfortunately, I'm not experienced enough to see how to fix it only with some terminal output and without testing. I remove the `depends_on :macos` line to obtain the output of the build process again.

@StefanD986 Boost is only needed if one wants to build the C++ simulation runtime additionally. The OMCompiler instructions claim that `./configure --with-cppruntime` is all one needs to do so. Actually, this is only correct for the `./configure` in the main OpenModelica repository, not for OMCompiler exclusively. That's the reason why I removed it.

**Comment by SimplyDanny** [comment]
Closing the PR since there is a newer version of OMCompiler running on all supported macOS versions in #6421.

**Pull request closed without merging**
