### PR TITLE
arrow++ 0.1.3

### PR DESCRIPTION
**Pull request by miguelarauj1o**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

**PLEASE, DO NOT MERGE YET.**

Arrow++ needs [bazel](https://github.com/tetsuok/arowpp#software-requirements) to be installed properly. So, I need to figure out how to do this.

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for your contribution.

This failed with:
> ==> ./configure --prefix=/usr/local/Cellar/arow++/0.1.3
Failed to execute: ./configure

**Comment by miguelarauj1o** [comment]
@iMichka, I already know that.
Arrow++ needs bazel, as I said above. How I can include bazel? `depends_on "bazel" => :build`
Also, `def install` function needs to be modified.

Can you help me to get this work done?
I need some instructions here.

**Comment by fxcoudert** [comment]
Thanks @miguelarauj1o for your contribution!

**Comment by fxcoudert** [comment]
Look at [this formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/buildifier.rb) which build with bazel as an example.

**Comment by miguelarauj1o** [comment]
@fxcoudert, thanks!

**Pull request closed without merging**
