### PR TITLE
maq: fix compilation

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> ==> brew install gcc
==> SKIPPING: homebrew/science/maq
homebrew/science/maq cannot be built with any available compilers.
Install GNU's GCC
  brew install gcc

...

@ilovezfs I also tried with `depends_on "gcc@6`, and it refuses to build a mac bottle (but builds locally for me). Is this a bug or done on purpose?

**Comment by ilovezfs** [comment]
@iMichka you can do this if you want to keep it https://github.com/Homebrew/homebrew-science/blob/master/gfan.rb#L8

**Comment by iMichka** [comment]
Thanks for the hint. Let's do that. This still had around 50 installations in 1 year ...

**Comment by jonchang** [comment]
I got it to build with this patch. @iMichka you could incorporate them and submit them upstream perhaps?

```diff
diff --git a/get_pos.c b/get_pos.c
index d1a1b72..3b4a837 100644
--- a/get_pos.c
+++ b/get_pos.c
@@ -5,7 +5,7 @@
 #include "assemble.h"
 
 /** fill the rolling buffer */
-inline void assemble_fill_buffer(gzFile fpin, rolling_buf_t *ab)
+void assemble_fill_buffer(gzFile fpin, rolling_buf_t *ab)
 {
 	if (gzeof(fpin) || (ab->is_rounded == 1 && ab->head == ab->tail)) return; // the buffer is full
 	int n_records, n_bytes;
diff --git a/stdhash.hh b/stdhash.hh
index eaf98af..16cd1a3 100644
--- a/stdhash.hh
+++ b/stdhash.hh
@@ -412,7 +412,7 @@ public:
 	inline bool insert(const keytype_t &key) {
 		__lh3_hash_base_class<keytype_t>::rehash();
 		hashint_t i;
-		int ret = direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
+		int ret = this->direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
 		if (ret == 0) return true;
 		if (ret == 1) { ++(this->n_size); ++(this->n_occupied); }
 		else ++(this->n_size); // then ret == 2
@@ -493,7 +493,7 @@ public:
 	inline bool insert(const keytype_t &key, const valtype_t &val) {
 		rehash();
 		hashint_t i;
-		int ret = direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
+		int ret = this->direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
 		vals[i] = val;
 		if (ret == 0) return true;
 		if (ret == 1) { ++(this->n_size); ++(this->n_occupied); }
@@ -503,7 +503,7 @@ public:
 	inline bool insert(const keytype_t &key, valtype_t **q) {
 		rehash();
 		hashint_t i;
-		int ret = direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
+		int ret = this->direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
 		*q = vals + i;
 		if (ret == 0) return true;
 		if (ret == 1) { ++(this->n_size); ++(this->n_occupied); }
```

**Comment by iMichka** [comment]
@jonchang Thanks for finding out. I'll report this upstream, and I'll also move the patch to the formula-patch repo. Should be able to do this today.

**Comment by iMichka** [comment]
Patch submitted upstream, and I opened a PR in formula-patches: https://github.com/Homebrew/formula-patches/pull/159

I'll rebase this and add the patch from formula-patches.

**Comment by iMichka** [comment]
```
==> homebrew/science/maq
  bottle do
    cellar :any_skip_relocation
    sha256 "1fc8d9fab4cbb08339f60a492c89b1dac77d497960fa708300583e0139e5fa5d" => :sierra
    sha256 "df5f1a65cbf4ddab278c0aef92539a3d5c4daa636d48437744e4ecc53532746b" => :el_capitan
    sha256 "221ba0ea3e2a535e62c197e9c6590bf7eb960aaf9ca00d63a646c9d76677fca3" => :yosemite
  end
[master 885b65c4] maq: update 0.7.1_1 bottle.
 1 file changed, 4 insertions(+), 5 deletions(-)
git push --force git@github.com:BrewTestBot/homebrew-science.git master:master :refs/tags/pr-6039
To github.com:BrewTestBot/homebrew-science.git
 + 484e9145...885b65c4 master -> master (forced update)
 - [deleted]           pr-6039
Error: unknown keyword: extra_args
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Homebrew/utils/curl.rb:11:in `curl_args'
... 
```

See https://jenkins.brew.sh/job/Homebrew%20Bottles/7906/console

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Bottle problem should be fixed with: https://github.com/Homebrew/brew/pull/3018

**Comment by iMichka** [comment]
Just in case somebody wonders, I modified the linux sha by mistake in the PR, and realised that when pulling the bottles. So I rebased/edited the PR before pushing it, so that change did not make it to master.

**Pull request closed without merging**
