### PR TITLE
travisCI: Revert to test-bot testing strategy

### PR DESCRIPTION
**Pull request by saketkc**
This commit reverts to the test-bot based testing strategy,
drifting away from strategy used in #1679 as it did not
build PRs. The only downside being it will also test
changes in files which are not formulae(such as .travis.yml)
but it is safe to assume, these will not change as frequently.

See #1716

### CODE REVIEW

**Comment by dpo** [comment]
Were you able to test it? I wish the test-bot build could be verbose. How do we get the log in case of failure?

**Comment by saketkc** [comment]
This currently dumps the last 3Mb of the log. Would that be sufficient?

**Comment by dpo** [comment]
If the `test-bot` script does a verbose build, yes, that's probably enough. The Travis limit is 4Mb I believe.

**Comment by saketkc** [comment]
I have updated it. It's a bit more intelligent now. However, the script just compares the difference between current commit and it's parent, so if you want to build each of your commit, you need to push one commit at a time.

See https://github.com/saketkc/homebrew-science/pull/7

**Comment by dpo** [comment]
We'll improve this as we go. Thanks for your hard work!

**Comment by saketkc** [comment]
For some reason, the PRs do build. But github doesn' show them. I do not know why.
https://travis-ci.org/Homebrew/homebrew-science/pull_requests

**Pull request closed without merging**
