### PR TITLE
SuiteSparse: include path to TBB

### LINKED ISSUE #2648: suite-sparse: fails on ubuntu 14.04
_From @ahundt on August 11, 2015 21:16_

I'm not sure if this is the right place to put this issue due to the particulars of linuxbrew since this is a `homebrew-science` package, but `brew install suite-sparse` failed on ubuntu 14.04 as follows:

https://gist.github.com/50ee22b1ca6d754caed9

_Copied from original issue: Homebrew/linuxbrew#510_

### PR DESCRIPTION
**Pull request by dpo**
- preserve ENV.cflags
- audit warnings

Fixes #2648.

### CODE REVIEW

**Comment by davydden** [comment]
works fine on `kubuntu` (just installed on my colleague's machine), otherwise there is indeed an issue with `tbb`. Hope it get's merged soon.

**Comment by dpo** [comment]
@ahundt Any news?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by ahundt** [comment]
sorry I won't have a chance for a while, I no longer have access to the environment I had when I posted the issue and it will be a little while before I finish creating a new one

**Comment by ahundt** [comment]
seems to work!

**Pull request closed without merging**
