### PR TITLE
openimageio 1.7.7

### PR DESCRIPTION
**Pull request by JCount**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`? __*CAVEAT*__

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

-----
### This currently is a **WIP**. 

`cmake 3.6.2` (the current stable) cannot find `boost 1.62.0` the way it needs to, causing the entire build of this PR and prior versions of the formula to fail.

However, `cmake`'s `devel` (3.7.0-rc1) and `HEAD` versions have the necessary `boost` support.
Therefore, it should be possible to compile this using either of those, barring any insidious bugs.

-----
Few minor changes compared to the previous version:
- ~~Default build mode is now C++11, added a (deprecated) option for continuing to build using C++03, however support for C++03 will be dropped at some point.~~
- Added option for building with `jpeg-turbo` over `jpeg`; is supposed to provide improved speed
- ~~Enabled flag so it explicitly builds using clang's libc++ by default, CMakeLists.txt includes a sanity check to ensure that clang is being used. (May not be necessary, I am happy to remove it seems wrong/unnecessary etc.)~~

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@JCount I think this doesn't need new CMake. Built fine here with 3.6.2.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@JCount Thanks for doing the upgrade! :100:

**Comment by JCount** [comment]
@ilovezfs Huh, I wonder why I was running into issues with `cmake 3.6.2`. Well, I am glad I was mistaken.

**Comment by dpo** [comment]
@JCount Many thanks for your contribution! If you're feeling energized, feel free to help close [a dozen issues](https://github.com/Homebrew/homebrew-science/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20opencv3) by updating `opencv3` ;-).

**Pull request closed without merging**
