### PR TITLE
bioformats-5.1.5

### PR DESCRIPTION
**Pull request by rleigh-dundee**
New upstream release.
This release will build with Boost 1.59 which is pending merge into homebrew.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
Would it be possible for anyone with access to restart the failing travis jobs; one is a timeout for some reason, the other I'm unsure about.

**Comment by dpo** [comment]
The Linux build failed because of `cmake`. I restarted the OSX 10.9 and 10.10 jobs.

**Comment by rleigh-dundee** [comment]
@dpo Thanks, looks like it failed again unfortunately.  All the homebrew builds passed; not sure why 10.10 times out with travis when 10.9 and 10.11 are fine.

**Comment by dpo** [comment]
I need to restart the bot now because bottling failed.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Thanks for your patience.

**Pull request closed without merging**
