### PR TITLE
elemental: revision for open-mpi

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
-- Checking C++ support for "nullptr": works
-- Checking C++ support for "rvalue_references"
-- Checking C++ support for "rvalue_references": works
-- Checking C++ support for "sizeof_member"
-- Checking C++ support for "sizeof_member": works
-- Checking C++ support for "static_assert"
-- Checking C++ support for "static_assert": works
-- Checking C++ support for "variadic_templates"
-- Checking C++ support for "variadic_templates": works
CMake Error at external/cmake/FindPackageHandleStandardArgs.cmake:194 (message):
  Unknown keywords given to FIND_PACKAGE_HANDLE_STANDARD_ARGS(): "1"
Call Stack (most recent call first):
  external/cmake/FindCXXFeatures.cmake:163 (find_package_handle_standard_args)
  cmake/tests/CXX.cmake:1 (include)
  CMakeLists.txt:296 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/elemental-20160825-45369-18oft55/Elemental-0.86-rc1/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/elemental-20160825-45369-18oft55/Elemental-0.86-rc1/build/CMakeFiles/CMakeError.log".
==> Formula
Tap: homebrew/science
Path: /usr/local/Library/Taps/homebrew/homebrew-science/elemental.rb
==> Configuration
```

**Comment by dpo** [comment]
@poulson

**Comment by poulson** [comment]
This issue was fixed in Git HEAD of Elemental several months ago and was due to some CMake helper functions in Elemental's `cmake/` subdirectory becoming standardized into CMake and then changing. Simply removing the duplicate/obsolete files fixes the issue.

My recommendation would be to simply switch to Git HEAD. I have learned the painful lesson of the importance of maintaining maintenance branches for each release and will be doing so with all future releases.

**Comment by ilovezfs** [comment]
@poulson HEAD:
```
- Performing Test EL_HAVE_GMP - Success
-- Found MPFR: /usr/local/include (Required is at least version "3.1.0") 
-- Performing Test EL_HAVE_MPFR
-- Performing Test EL_HAVE_MPFR - Success
-- Found MPC: /usr/local/include (Required is at least version "1.0.0") 
-- Performing Test EL_HAVE_MPC
-- Performing Test EL_HAVE_MPC - Success
-- Including /usr/local/include, /usr/local/include, and /usr/local/include to add support for GMP, MPFR, and MPC
-- Searching for previously installed ParMETIS
-- Could NOT find ParMETIS (missing:  PARMETIS_LIBRARY PARMETIS_INCLUDE_DIR PARMETIS_TEST_RUNS) 
-- Will pull ParMETIS from https://github.com/scibuilder/parmetis.git
-- Including /usr/local/Cellar/elemental/HEAD-05f8445_1/libexec/include for external ParMETIS
-- Prepending /tmp/elemental-20160826-89309-c5snqc/external/pmrrr/include for PMRRR's headers
-- Prepending /tmp/elemental-20160826-89309-c5snqc/external/suite_sparse/include for ElSuiteSparse headers
-- Configuring incomplete, errors occurred!
See also "/tmp/elemental-20160826-89309-c5snqc/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/elemental-20160826-89309-c5snqc/build/CMakeFiles/CMakeError.log".
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/elemental/HEAD-05f8445_1/libexec -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_Fortran_COMPILER= -DMPI_C_COMPILER=/usr/local/bin/mpicc -DMPI_CXX_COMPILER=/usr/local/bin/mpicxx -DMPI_Fortran_COMPILER=/usr/local/bin/mpif90 -Wno-dev -DINSTALL_PYTHON_PACKAGE=OFF -DCMAKE_BUILD_TYPE=Release -DEL_HYBRID=OFF -DMATH_LIBS=-framework\ Accelerate -DBUILD_METIS=OFF -DMETIS_INCLUDE_DIRS=/usr/local/opt/metis/include -DMETIS_LIBRARIES=-L/usr/local/opt/metis/lib\ -lmetis -DBUILD_PARMETIS=ON -DEL_TESTS=ON -DEL_EXAMPLES=ON
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by ilovezfs** [comment]
@poulson this got it back on its feet, so a new release (we can't really just ship HEAD) may be the way to go. But it looks like a new release of parmetis might be needed too since I had to build that from head as well. Also, there was a file conflict between parmetis and metis because the head spec of parmetis would need to be adapted to use our metis or conflicts_with's added.

So we may want to just patch the CMake situation directly until that's all sorted out.

```
diff --git a/elemental.rb b/elemental.rb
index 82e4477..4a31c71 100644
--- a/elemental.rb
+++ b/elemental.rb
@@ -24,7 +24,9 @@ class Elemental < Formula
 
   head do
     url "https://github.com/elemental/Elemental.git"
-    depends_on "metis"
+#    depends_on "metis"
+    depends_on "parmetis"
+    depends_on "scalapack"
   end
 
   option "without-check", "Skip build time tests (not recommended)"
@@ -35,6 +37,7 @@ class Elemental < Formula
   depends_on "openblas"  => :optional
   depends_on "qt5"       => :optional
   depends_on "scalapack" => :optional
+  depends_on :fortran
 
   needs :cxx11
 
@@ -82,7 +85,7 @@ class Elemental < Formula
     args += ["-DMANUAL_METIS=ON",
              "-DMETIS_ROOT=#{Formula["metis"].opt_prefix}",
              "-DMETIS_LIBS=-L#{Formula["metis"].opt_lib} -lmetis",
-            ] if build.devel?
+            ] unless build.stable?
 
     # Building against our own ParMETIS seems borderline impossible
     # because of the mess in parmetislib.h.
diff --git a/parmetis.rb b/parmetis.rb
index 88bfaab..28dac3c 100644
--- a/parmetis.rb
+++ b/parmetis.rb
@@ -1,10 +1,32 @@
 class Parmetis < Formula
   desc "MPI-based library for graph/mesh partitioning and computing fill-reducing orderings"
   homepage "http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview"
-  url "http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz"
-  sha256 "f2d9a231b7cf97f1fee6e8c9663113ebf6c240d407d3c118c55b3633d6be6e5f"
   revision 4
 
+  head "https://github.com/scibuilder/parmetis.git"
+
+  stable do
+    url "http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz"
+    sha256 "f2d9a231b7cf97f1fee6e8c9663113ebf6c240d407d3c118c55b3633d6be6e5f"
+
+    # Do not build the METIS 5.* that ships with ParMETIS.
+    patch :DATA
+
+    # Bug fixes from PETSc developers. Mirrored because the SHA-256s get
+    # invalidated every time Bitbucket updates the Git version they use.
+    patch do
+      # From: https://bitbucket.org/petsc/pkg-parmetis/commits/82409d68aa1d6cbc70740d0f35024aae17f7d5cb/raw/
+      url "https://raw.githubusercontent.com/Homebrew/patches/f104fbb1e09402798cbbc06d2f695d85398c0c89/parmetis/commit-82409d68.patch"
+      sha256 "0349f5bc19a2ba9fe9e1b9d385072dabe59262522bd7cf66f26c6bc31bbb1b86"
+    end
+
+    patch do
+      # From: https://bitbucket.org/petsc/pkg-parmetis/commits/1c1a9fd0f408dc4d42c57f5c3ee6ace411eb222b/raw/
+      url "https://raw.githubusercontent.com/Homebrew/patches/f104fbb1e09402798cbbc06d2f695d85398c0c89/parmetis/commit-1c1a9fd0.patch"
+      sha256 "baec5e1fa6bb4f6c59e3ede564485e0ad743f58c9875fd65cb715b5c14a491b5"
+    end
+  end
+
   bottle do
     cellar :any
     sha256 "d54a239c0e9a43c283a44c5de26bf743232228385c0cc9fc451214c1aca555a0" => :el_capitan
@@ -14,34 +36,26 @@ class Parmetis < Formula
 
   # METIS 5.* is required. It comes bundled with ParMETIS.
   # We prefer to brew it ourselves.
-  depends_on "metis"
+#  depends_on "metis"
 
   depends_on "cmake" => :build
   depends_on :mpi => :cc
 
-  # Do not build the METIS 5.* that ships with ParMETIS.
-  patch :DATA
-
-  # Bug fixes from PETSc developers. Mirrored because the SHA-256s get
-  # invalidated every time Bitbucket updates the Git version they use.
-  patch do
-    # From: https://bitbucket.org/petsc/pkg-parmetis/commits/82409d68aa1d6cbc70740d0f35024aae17f7d5cb/raw/
-    url "https://raw.githubusercontent.com/Homebrew/patches/f104fbb1e09402798cbbc06d2f695d85398c0c89/parmetis/commit-82409d68.patch"
-    sha256 "0349f5bc19a2ba9fe9e1b9d385072dabe59262522bd7cf66f26c6bc31bbb1b86"
-  end
-
-  patch do
-    # From: https://bitbucket.org/petsc/pkg-parmetis/commits/1c1a9fd0f408dc4d42c57f5c3ee6ace411eb222b/raw/
-    url "https://raw.githubusercontent.com/Homebrew/patches/f104fbb1e09402798cbbc06d2f695d85398c0c89/parmetis/commit-1c1a9fd0.patch"
-    sha256 "baec5e1fa6bb4f6c59e3ede564485e0ad743f58c9875fd65cb715b5c14a491b5"
-  end
 
   def install
-    ENV["LDFLAGS"] = "-L#{Formula["metis"].lib} -lmetis -lm"
+    if build.stable?
+      ENV["LDFLAGS"] = "-L#{Formula["metis"].lib} -lmetis -lm"
 
-    system "make", "config", "prefix=#{prefix}", "shared=1"
-    system "make", "install"
-    pkgshare.install "Graphs" # Sample data for test
+      system "make", "config", "prefix=#{prefix}", "shared=1"
+      system "make", "install"
+      pkgshare.install "Graphs" # Sample data for test
+    else
+      mkdir "build" do
+        system "cmake", "..", *std_cmake_args
+	system "make"
+	system "make", "install"
+      end
+    end
   end
 
   test do
```

**Comment by poulson** [comment]
I am planning to write a distributed Hessenberg QR algorithm this weekend so that the upcoming release to nor depend on ScaLAPACK for any functionality anymore. Ideally I can do the same for a nodal bisection at some point...Managing these legacy dependencies has become a nightmare due to the fragmentation resulting from the lack of a maintainer.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew uses scalapack
homebrew/science/abinit                  homebrew/science/petsc                 
homebrew/science/mumps                   homebrew/science/trilinos              
Josephs-MacBook-Pro:~ joe$
```

Maybe you can get them to adopt your new code too!

**Comment by goxberry** [comment]
@ilovezfs Would it be possible to put the CMake patches you proposed in a PR? Unless there's something particular to my setup, all three versions of Elemental available for building with Homebrew fail to build. Of these, HEAD is closest to working (I get a test error, which I am debugging at the moment).

**Comment by goxberry** [comment]
@ilovezfs I found the patch I needed in the Elemental mailing list. It needed some minor work, but it's in #4390, if that helps this PR.

**Comment by dpo** [comment]
Closing in favor of #4390.

**Pull request closed without merging**
