### PR TITLE
nextflow 0.17.1

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by UniqMartin** [comment]
Sorry for bothering you @pditommaso, but can you rebase your commit on top of the most recent `master` and update this PR by pushing the rebased commit here?

There's nothing wrong with your submission, but I made a mistake when working on the integration with Travis CI and now the build appears as successful, although the formula wasn't even built. If you could do the above, that would help me to verify that the fix I pushed since then really solves the issue. Thanks!

**Comment by pditommaso** [comment]
Just done.

**Comment by UniqMartin** [comment]
It worked! Thanks a lot for the help and the fast response! :+1:

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by pditommaso** [comment]
Tests are successful

**Pull request closed without merging**
