### PR TITLE
nonpareil 2.4.01

### PR DESCRIPTION
**Pull request by lmrodriguezr**

### CODE REVIEW

**Comment by lmrodriguezr** [comment]
The v2.4.01 is essentially identical to v2.4, but removes unnecessary large files from the test directory. Is there a reason why the build would fail? All the other changes are simply stylistic to conform with `audit --strict`.

**Comment by dpo** [comment]
Should #2253 be closed?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by lmrodriguezr** [comment]
brew pull --clean https://github.com/Homebrew/homebrew-science/pull/2280 works for me, but it fails for the bot. I ran brew update before testing. Any idea on what the problem is?

**Comment by dunn** [comment]
Looks like it needs to be rebased.

**Comment by lmrodriguezr** [comment]
Should I redo it in a new pull request?

**Comment by dunn** [comment]
You can do it here and `git push -f` also.

**Comment by lmrodriguezr** [comment]
Superseded by #2567.

**Pull request closed without merging**
