### PR TITLE
octave: fix java binding

### LINKED ISSUE #1899: octave --without-java not working
When I install octave with the options `brew install octave --without-java` it still seems to look for Java 6 which I don't have on my system and just terminates.

### PR DESCRIPTION
**Pull request by xu-cheng**
Fixes #1899 (hopefully) 

Before the patch
```
$ otool -L /usr/local/bin/octave
/usr/local/bin/octave:
	/usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
```

After the patch
```
$ otool -L /usr/local/bin/octave
/usr/local/bin/octave:
	/usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
```

But I'm not fully sure this fixes all the problems.

cc @spundun @dpo @lpil

BTW @dpo I cannot build octave without specifying `--without-docs`. It will complain cannot finding TeX, although I have MacTeX installed(octave cannot find it because you remove the `depends_on :tex`).

### CODE REVIEW

**Comment by dpo** [comment]
Sorry, I didn't do that: https://github.com/Homebrew/homebrew-science/commit/b37cf60a21631cf3fc490b37871a634fb2308b46
@iml

**Comment by xu-cheng** [comment]
> Sorry, I didn't do that

Sorry my bad, I forget to check the git log.

**Comment by iml** [comment]
Strange, it should only need `tex2dvi` and `tex2pdf`. According to the MacPorts [portfile](https://trac.macports.org/browser/trunk/dports/math/octave/Portfile), only texinfo is required. I tested it locally after nuking my TeX distribution, and the bots seemed to build bottles with docs. Does this happen in `./configure`?

**Comment by dpo** [comment]
@xu-cheng Are we happy with this?

**Comment by xu-cheng** [comment]
I would like someone without Apple Java installed(I don't know how to uninstall it on my Mac) to do the test. Also maybe hear some feedback from @spundun, does this solve his problem?

**Comment by spundun** [comment]
Oh, interesting. Should I try to do a straight-up `brew install octave` and see if the java issue is gone?

I'll try that right now.

**Comment by dpo** [comment]
You'll want to try `brew install https://raw.githubusercontent.com/xu-cheng/homebrew-science/octave-java/octave.rb`.

**Comment by spundun** [comment]
Nope! Still the same behavior

```
$ brew uninstall octave
Uninstalling /usr/local/Cellar/octave/3.8.1_1...
$ brew install octave
==> Installing octave from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/octave-3.8.1_1.yosemi
Already downloaded: /Library/Caches/Homebrew/octave-3.8.1_1.yosemite.bottle.4.tar.gz
==> Pouring octave-3.8.1_1.yosemite.bottle.4.tar.gz
==> Caveats

gnuplot's Qt terminal is supported by default with the Octave GUI.
Use other gnuplot graphics terminals by setting the environment variable
GNUTERM in ~/.octaverc, and building gnuplot with the matching options.

  setenv('GNUTERM','qt')    # Default graphics terminal with Octave GUI
  setenv('GNUTERM','x11')   # Requires XQuartz; install gnuplot --with-x
  setenv('GNUTERM','wxt')   # wxWidgets/pango; install gnuplot --wx
  setenv('GNUTERM','aqua')  # Requires AquaTerm; install gnuplot --with-aquaterm

  You may also set this variable from within Octave.


The Octave GUI is experimental and not enabled by default. To use it,
use the command-line argument "--force-gui"; e.g.,
    octave --force-gui

==> Summary
🍺  /usr/local/Cellar/octave/3.8.1_1: 2089 files,  50M
$ octave
No Java runtime present, requesting install.
$ which octave
/usr/local/bin/octave
$ ls -ln /usr/local/bin/octave
lrwxr-xr-x  1 501  20  35 Apr 10 11:01 /usr/local/bin/octave -> ../Cellar/octave/3.8.1_1/bin/octave
$ 
```

**Comment by xu-cheng** [comment]
@spundun You need to try `brew install https://raw.githubusercontent.com/xu-cheng/homebrew-science/octave-java/octave.rb --build-from-source` to test it.

**Comment by spundun** [comment]
Still the same behavior.

```
$ brew uninstall octave
Uninstalling /usr/local/Cellar/octave/3.8.1_1...
$ brew install https://raw.githubusercontent.com/xu-cheng/homebrew-science/octave-java/octave.rb
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles-science/octave-3.8.2.yosemite
######################################################################## 100.0%
==> Pouring octave-3.8.2.yosemite.bottle.tar.gz
==> Caveats

gnuplot's Qt terminal is supported by default with the Octave GUI.
Use other gnuplot graphics terminals by setting the environment variable
GNUTERM in ~/.octaverc, and building gnuplot with the matching options.

  setenv('GNUTERM','qt')    # Default graphics terminal with Octave GUI
  setenv('GNUTERM','x11')   # Requires XQuartz; install gnuplot --with-x
  setenv('GNUTERM','wxt')   # wxWidgets/pango; install gnuplot --wx
  setenv('GNUTERM','aqua')  # Requires AquaTerm; install gnuplot --with-aquaterm

  You may also set this variable from within Octave.


The Octave GUI is experimental and not enabled by default. To use it,
use the command-line argument "--force-gui"; e.g.,
    octave --force-gui

==> Summary
🍺  /usr/local/Cellar/octave/3.8.2: 2111 files,  55M
$ octave
No Java runtime present, requesting install.
$ which octave
/usr/local/bin/octave
$ ls -ln /usr/local/bin/octave
lrwxr-xr-x  1 501  20  33 Apr 10 11:06 /usr/local/bin/octave -> ../Cellar/octave/3.8.2/bin/octave
$ 

```

**Comment by spundun** [comment]
@xu-cheng  `--build-from-source` option worked last time also, no? I will try again.

**Comment by spundun** [comment]
no wait ... last time `--no-java` worked. Trying `--build-from-source` this time.

**Comment by spundun** [comment]
It did not work. Getting the same error when installed using `brew install https://raw.githubusercontent.com/xu-cheng/homebrew-science/octave-java/octave.rb --build-from-source`

**Comment by xu-cheng** [comment]
@spundun What's the output of `otool -L /usr/local/bin/octave`

**Comment by spundun** [comment]
```
$ otool -L /usr/local/bin/octave
/usr/local/bin/octave:
	/usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
$ 
```

**Comment by xu-cheng** [comment]
So stopping octave linking to system Java framework doesn't solve the problem. I suggest reporting this issue to octave as it's a upstream issue rather than homebrew one. Close this PR, since it doesn't fix anything.

**Comment by carandraug** [comment]
Hi @xu-cheng . Could you please open a bug report upstream then with what the problem is? https://savannah.gnu.org/bugs/?func=additem&group=octave

**Comment by jordigh** [comment]
And also check it's not an existing bug, please.

**Comment by carandraug** [comment]
In case anyone finds this again, the bug report upstream was open now at https://savannah.gnu.org/bugs/index.php?47096

**Pull request closed without merging**
