### PR TITLE
nextflow 0.25.2

### PR DESCRIPTION
**Pull request by pditommaso**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
> homebrew/science/nextflow:
>  * Stable: version 0.25.2 is redundant with version scanned from URL

You can remove the `version` line. This is now correctly and automatically detected by homebrew.

**Comment by pditommaso** [comment]
done

**Comment by iMichka** [comment]
Ok, this will need linuxbrew 1.2.3, I hope I can merge this soon: https://github.com/Linuxbrew/brew/pull/415

Then we can rebuild the Linux bottles.

**Comment by pditommaso** [comment]
Any action is needed on my side ?

**Comment by iMichka** [comment]
No, normally not. I'll trigger the build again manually as soon as it is ready.

**Comment by jonchang** [comment]
Thanks @pditommaso! This has been merged.

**Pull request merged**
