### PR TITLE
nextflow 0.21.1

### PR DESCRIPTION
**Pull request by pditommaso**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
The bot can't download the package
```
==> brew fetch --retry homebrew/science/nextflow --force
==> FAILED
==> Fetching nextflow from homebrew/science
==> Downloading http://www.nextflow.io/releases/0.21.1/nextflow
==> Retrying download
==> Downloading http://www.nextflow.io/releases/0.21.1/nextflow
Error: Failed to download resource "nextflow"
Download failed: http://www.nextflow.io/releases/0.21.1/nextflow
```
Locally, I get
```
$ wget http://www.nextflow.io/releases/0.21.1/nextflow
--2016-07-29 19:31:48--  http://www.nextflow.io/releases/0.21.1/nextflow
Resolving www.nextflow.io... 54.192.127.17, 54.192.127.58, 54.192.127.131, ...
Connecting to www.nextflow.io|54.192.127.17|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-07-29 19:31:49 ERROR 403: Forbidden.
```

**Comment by pditommaso** [comment]
Fixed

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Paolo!

**Comment by pditommaso** [comment]
Thanks to you, to maintain this awesome project!

**Pull request closed without merging**
