### PR TITLE
cutadapt 1.11 (new formula)

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
@tmozgach thanks for doing this! i don't know why it never worked for me.  when this is accepted i'll remove it from my tap.

**Comment by sjackman** [comment]
Thanks, Torsten and Tanya! Merged.

**Comment by sjackman** [comment]
@tmozgach Please add this formula to the ORCA image.
@tseemann Any other formula from your repo that you think should be moved to Homebrew/science?

**Comment by janstrauss1** [comment]
Could someone of the more experienced folks update the cutadapt formula in homebrew/science to the current v1.14?
Many thanks in advance!

**Comment by sjackman** [comment]
@tmozgach Can you please update `cutadapt` to 1.14?

**Comment by tseemann** [comment]
@sjackman I'll start a new issue about migrating stuff from my repo, with a checklist perhaps.

**Pull request closed without merging**
