### PR TITLE
blast 2.6.0-ver2

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by ponomarevsy** [comment]
Much appreciated, Sir! This is most likely a blast-related issue... sadly, I don't see any log files under /path-to-rmblast/ncbi-blast-2.6.0+-src/c++/, so I can't tell you more than this: "make install" for rmblast gives "make[1]: *** [install-toolkit] Error 1 make[1]"

**Comment by iMichka** [comment]
You can test this by using:
> brew pull https://github.com/Homebrew/homebrew-science/pull/6257

Let's wait to see if your bots can build this. I tested locally on mac and the patch can be applied. If the build is green I will merge that version update.

**Comment by vszakats** [comment]
@iMichka You can upgrade/secure protocols for these two URLs:
```diff
diff --git a/blast.rb b/blast.rb
index d895e049..dc2e8dbf 100644
--- a/blast.rb
+++ b/blast.rb
@@ -1,10 +1,10 @@
 class Blast < Formula
   desc "Basic Local Alignment Search Tool"
-  homepage "http://blast.ncbi.nlm.nih.gov/"
+  homepage "https://blast.ncbi.nlm.nih.gov/"
   # doi "10.1016/S0022-2836(05)80360-2"
   # tag "bioinformatics"
 
-  url "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-src.tar.gz"
+  url "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-src.tar.gz"
   mirror "ftp://ftp.hgc.jp/pub/mirror/ncbi/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-src.tar.gz"
   version "2.6.0"
   sha256 "0510e1d607d0fb4389eca50d434d5a0be787423b6850b3a4f315abc2ef19c996"
```

**Comment by iMichka** [comment]
Actually I want to give up on this issue. I have no time for this. Upstream needs to release a proper release that we can ship; or somebody from the community needs to step up and work on this.

**Comment by iMichka** [comment]
BTW thanks for letting me know :)

**Comment by ponomarevsy** [comment]
That is fine, Michka. Built executables for rmblast seem to work well, it was just the installation step that failed. I have no problem with you closing this ticket. Thanks anyway!

**Pull request closed without merging**
