### PR TITLE
cufflinks 2.2.1: Build with up-to-date boost

### PR DESCRIPTION
**Pull request by sjackman**
Build with boost rather than homebrew/versions/boost155
See https://github.com/cole-trapnell-lab/cufflinks/issues/3#issuecomment-131521318

Add desc

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2880/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_Homebrew_science_cufflinks/
```
clang++ -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -arch x86_64 -O3  -DNDEBUG  -pthread -I/usr/local/include -I/usr/local/include -I/usr/local/opt/eigen/include/eigen3 -c -o bundles.o bundles.cpp
In file included from abundances.cpp:16:
In file included from ./abundances.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:265:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__bit_reference:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:627:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:273:33: error: no matching constructor for initialization of 'boost::shared_ptr<void>'
            : first(__p.first), second(__p.second) {}
                                ^      ~~~~~~~~~~
/usr/local/include/boost/serialization/shared_ptr_helper.hpp:182:37: note: in instantiation of function template specialization 'std::__1::pair<const void *const, boost::shared_ptr<void> >::pair<const void *, boost::shared_ptr<const EmpDist> >' requested here
            result = m_o_sp->insert(std::make_pair(oid, s));
                                    ^
```

**Comment by sjackman** [comment]
No luck. Perhaps after boost 1.59.0 is merged. See https://github.com/Homebrew/homebrew/pull/42960

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
c.f. #3118.

**Pull request closed without merging**
