### PR TITLE
SolexaQA++ 3.1.7.1 (new formula)

### PR DESCRIPTION
**Pull request by lmrodriguezr**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by lmrodriguezr** [comment]
Yikes! On it.

**Comment by lmrodriguezr** [comment]
Both TravisCI and CircleCI are complaining about the extra dependency "unzip", do you know why is that? The proposed formula doesn't require unzip.

**Comment by iMichka** [comment]
@sjackman I think as soon as there is a zip file that is downloaded, Linuxbrew will install unzip.
In that case the audit should probably not complain?

> homebrew/science/solexaqa++:
>  * Dependency 'unzip' may be unnecessary as it is provided by macOS; try to build this formula without it.

**Comment by sjackman** [comment]
Oh, interesting. Yes, it probably shouldn't complain. That warning only occurs for new formula though, so I'm inclined to ignore it. You won't see that warning again once this PR is merged. A PR to Linuxbrew/brew would be welcome if you're inclined to fix it.

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
