### PR TITLE
datamash 1.1.0

### PR DESCRIPTION
**Pull request by agordon**

### CODE REVIEW

**Comment by dpo** [comment]
Somehow the brew bot can't download the source:
```
==> brew fetch --retry homebrew/science/datamash --build-bottle --force
==> FAILED
==> Fetching datamash from homebrew/science
==> Downloading http://ftpmirror.gnu.org/datamash/datamash-1.1.0.tar.gz
==> Downloading from http://ftp.heanet.ie/mirrors/gnu/datamash/datamash-1.1.0.tar.gz
==> Retrying download
==> Downloading http://ftpmirror.gnu.org/datamash/datamash-1.1.0.tar.gz
==> Downloading from http://ftp.heanet.ie/mirrors/gnu/datamash/datamash-1.1.0.tar.gz
Error: Failed to download resource "datamash"
Download failed: http://ftp.heanet.ie/mirrors/gnu/datamash/datamash-1.1.0.tar.gz
```

**Comment by agordon** [comment]
Thanks for the quick check.
I uploaded this new version only yesterday to the GNU server ( http://ftp.gnu.org/gnu/datamash/ ) , perhaps the gnu mirrors haven't had a chance to pick it up yet.
Is it possible to wait couple of days and re-run the checks?

**Comment by dpo** [comment]
No problem. Strange thing is Travis didn't have that problem.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
