### PR TITLE
Parmetis 4.0.3 (fix)

### PR DESCRIPTION
**Pull request by davydden**
added bugfixes from PETSc developers.

### CODE REVIEW

**Comment by davydden** [comment]
don't know why, but it seems the patch is applied to a wrong place even though the lines to patch have not changed. Any ideas what could be misleading the patch?

**Comment by davydden** [comment]
here's a first patch if I re-do it manually
```
diff --git a/libparmetis/xyzpart.c b/libparmetis/xyzpart.c
index 307aed9..3a2c289 100644
--- a/libparmetis/xyzpart.c
+++ b/libparmetis/xyzpart.c
@@ -111,7 +111,7 @@ void IRBinCoordinates(ctrl_t *ctrl, graph_t *graph, idx_t ndims, real_t *xyz,
       /* determine bucket counts */
       iset(nbins, 0, lcounts);
       for (j=0, i=0; i<nvtxs;) {
-        if (cand[i].key < emarkers[j+1]) {
+        if (cand[i].key <= emarkers[j+1]) {
           lcounts[j]++;
           i++;
         }
@@ -158,7 +158,7 @@ void IRBinCoordinates(ctrl_t *ctrl, graph_t *graph, idx_t ndims, real_t *xyz,
 
     /* assign the coordinate to the appropriate bin */
     for (j=0, i=0; i<nvtxs;) {
-      if (cand[i].key < emarkers[j+1]) {
+      if (cand[i].key <= emarkers[j+1]) {
         bxyz[cand[i].val*ndims+k] = j;
         i++;
       }
```
which looks identical to the one from PETSc with an exception of the header which includes commit info...

**Comment by davydden** [comment]
there must be something wrong with patching mechanism in Homebrew as this patch got applied both to the right place (lines 117 and 158) and to the wrong place (there are lines with the same code further down the file => thus offset message). 

If I apply the same patch as download from PETSc in interactive mode by `patch -p1 < /path/to/patch.txt`, the result (`git diff | pbcopy`) is good:
```
diff --git a/libparmetis/xyzpart.c b/libparmetis/xyzpart.c
index 307aed9..3a2c289 100644
--- a/libparmetis/xyzpart.c
+++ b/libparmetis/xyzpart.c
@@ -111,7 +111,7 @@ void IRBinCoordinates(ctrl_t *ctrl, graph_t *graph, idx_t ndims, real_t *xyz,
       /* determine bucket counts */
       iset(nbins, 0, lcounts);
       for (j=0, i=0; i<nvtxs;) {
-        if (cand[i].key < emarkers[j+1]) {
+        if (cand[i].key <= emarkers[j+1]) {
           lcounts[j]++;
           i++;
         }
@@ -158,7 +158,7 @@ void IRBinCoordinates(ctrl_t *ctrl, graph_t *graph, idx_t ndims, real_t *xyz,
 
     /* assign the coordinate to the appropriate bin */
     for (j=0, i=0; i<nvtxs;) {
-      if (cand[i].key < emarkers[j+1]) {
+      if (cand[i].key <= emarkers[j+1]) {
         bxyz[cand[i].val*ndims+k] = j;
         i++;
       }
```
so it must be the Homebrew way of applying patches. @tdsmith any ideas?

**Comment by dpo** [comment]
Don't think anything's wrong with patching but the bot was confused with something else here. I restarted the build.

**Comment by dpo** [comment]
```
==> Verifying parmetis--patch-d72c9a656a33b6715cc1601a4a1a89944da00e9911b4ab2d3908d41a32dee31b checksum
Error: SHA256 mismatch
Expected: d72c9a656a33b6715cc1601a4a1a89944da00e9911b4ab2d3908d41a32dee31b
Actual: 11b909a346f4dd8ec73b17ecb0c7215524e3793e252c749bb3199e83fa294597
```

**Comment by davydden** [comment]
that's weird, it works for me... could you please try it from `raw` formula in the PR?

**Comment by davydden** [comment]
never-mind.  It is all good with Homebrew patches. It was my fault. I somewhat put the same sha256 to two patches, that explains why it tried to apply the same one as it actually never downloaded the second one. Embarrassing.

**Comment by davydden** [comment]
now patches apply clean:
```
==> Patching
patching file CMakeLists.txt
patching file libparmetis/xyzpart.c
patching file libparmetis/xyzpart.c
```

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
