### PR TITLE
r: configure with-cairo explicitly

### LINKED ISSUE #1890: R installation does not include the cairo graphics devices
After installing R ([r.rb](https://github.com/Homebrew/homebrew-science/blob/master/r.rb)), I found that I was missing files necessary for the cairo-based graphics (like the `svg` function).

It seems that they need to be installed separately with `make cairodevices` as described [here](http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Building-the-cairo-devices-files). Currently there is no option to do this with the Homebrew formula. I don't know any Ruby or how to use make, but I feel like this should be possible; I'm sure it was just overlooked.

### PR DESCRIPTION
**Pull request by iml**
Move ACCELERATE cflag into accelerate conditional.

Fixes #1890.

### CODE REVIEW

**Comment by iml** [comment]
Neither adding pango or --with-cairo seems to affect the bottle.

@dpo @sjackman FYI just a warning with the new bottle host. If you want to test out a bottle download it directly from bot.brew.sh, don't use `brew pull` because the tarball for that revision will be set by Binary and can't be overwritten (for good reason, but different from how SF was set up).

**Comment by sjackman** [comment]
Is this the error message you see if this happens? I'm having a lot of trouble with bottling https://github.com/Homebrew/homebrew-science/pull/1887 Can you take a look?

```
❯❯❯ brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/1887
…
==> Publishing on Bintray:
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ Mac\ OS\ X\ 10.10.2) --silent --fail -usjackman:973ef1b3ee7523408c1560e26cabed69e47be029 -X POST https://api.bintray.com/content/homebrew/bottles-science/plink2/3..bottle/publish
```

**Comment by iml** [comment]
No, I see a shasum mismatch when there's a conflicting file. Looking at the URL, it looks like the issue is the version which is currently `stable 3`. Maybe the space in there messes things up, but the version needs to be set properly.

**Comment by iml** [comment]
@sjackman Seems to be a weird bug in bottle but I'll need to look more closely at it later:
```ruby
>> f = Formula["plink2"]
=> #<Formula plink2 (stable) /Library/Caches/Homebrew/Formula/plink2.rb>
>> bottle = Bottle.new(f, f.bottle_specification)
=> #<Bottle:0x007fdc82a20560 @name="plink2", @resource=#<Resource:0x007fdc82a20538 @name=nil, @url="https://homebrew.bintray.com/bottles/plink2-3..bottle.tar.gz", @version=#<PkgVersion:0x007fdc82a19990 @version="3", @revision=0>, @mirrors=[], @specs={}, @checksum=nil, @using=nil, @download_strategy=CurlBottleDownloadStrategy, @owner=#<Formula plink2 (stable) /Library/Caches/Homebrew/Formula/plink2.rb>>, @prefix="/usr/local", @cellar="/usr/local/Cellar", @revision=0>
>> Bintray.version(bottle.url)
=> "3..bottle"
>> f = Formula["r"]
=> #<Formula r (stable) /usr/local/Library/Taps/homebrew/homebrew-science/r.rb>
>> bottle = Bottle.new(f, f.bottle_specification)
=> #<Bottle:0x007fdc82a634f0 @name="r", @resource=#<Resource:0x007fdc82a634c8 @name=nil, @url="https://homebrew.bintray.com/bottles-science/r-3.1.3.yosemite.bottle.tar.gz", @version=#<PkgVersion:0x007fdc82a50468 @version="3.1.3", @revision=0>, @mirrors=[], @specs={}, @checksum=#<Checksum:0x007fdc82a48948 @hash_type=:sha256, @hexdigest="ded0eb716b80d099999b61b4c2b54fc51f5b3097bdb7c0934cf0b6dbc8366f8f">, @using=nil, @download_strategy=CurlBottleDownloadStrategy, @owner=#<Formula r (stable) /usr/local/Library/Taps/homebrew/homebrew-science/r.rb>>, @prefix="/usr/local", @cellar="/usr/local/Cellar", @revision=0>
>> Bintray.version(bottle.url)
=> "3.1.3"

**Comment by sjackman** [comment]
Good sleuthing. Thanks, Ian.

**Pull request closed without merging**
