### PR TITLE
paraview: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> * Dependency 'qt5' was renamed; use new name 'qt'.
>  * Dependency 'qt5' is an alias; use the canonical name 'qt'.

**Comment by iMichka** [comment]
@sjackman XML:Parser does not get installed because of:
> /usr/bin/ld: cannot find -lexpat
Expat is installed, but probably not found. Already seen such an error?

**Comment by sjackman** [comment]
```
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/home/linuxbrew/.linuxbrew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"2.44\" -DXS_VERSION=\"2.44\" -fPIC "-I/home/linuxbrew/.linuxbrew/Cellar/perl/5.24.1/lib/perl5/5.24.1/x86_64-linux-thread-multi/CORE"   Expat.c
rm -f ../blib/arch/auto/XML/Parser/Expat/Expat.so
LD_RUN_PATH="/home/linuxbrew/.linuxbrew/lib" cc  -shared -O2 -fstack-protector Expat.o  -o ../blib/arch/auto/XML/Parser/Expat/Expat.so 	\
	   -lexpat  	\
	  
/usr/bin/ld: cannot find -lexpat
collect2: error: ld returned 1 exit status
make[1]: *** [../blib/arch/auto/XML/Parser/Expat/Expat.so] Error 1
make[1]: Leaving directory `/home/linuxbrew/.cpan/build/XML-Parser-2.44-LUb0QS/Expat'
make: *** [subdirs] Error 2
  TODDR/XML-Parser-2.44.tar.gz
  /usr/bin/make -- NOT OK
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
```
https://travis-ci.org/Homebrew/homebrew-science/builds/232924598#L6090

**Comment by sjackman** [comment]
@iMichka It looks to me as though `postinstall` is not run in any particular build environment. Do you think wrapping the `perl` postinstall, which installs `XML::Parser`, in `with_build_environment` work/help?

**Comment by iMichka** [comment]
I do not know the details, but to me it looks like the postinstall did run, but it failed.

**Comment by sjackman** [comment]
>> It looks to me as though postinstall is not run in any particular build environment.

> I do not know the details, but to me it looks like the postinstall did run, but it failed.

I meant that the `postinstall` is run, but it's run in neither `ENV.std` nor `ENV.super`, just the regular `brew` environment. I'm thinking that adding `with_build_environment` to the `postinstall` of `perl` may help. Does that make sense to you?

**Comment by sjackman** [comment]
`qt@5.7` in Linuxbrew/core has the same issue. I'm looking into it at https://github.com/Linuxbrew/homebrew-core/pull/2660

**Comment by iMichka** [comment]
@sjackman I pushed the mac bottles, because the revision bump is needed. There were no Linux bottles here so no real harm done. I'm following the qt5 topic on Linuxbrew, we can continue the discussion there. I'll come back to the paraview Linux bottles later.

For the `with_build_environment` in the post install, worth a try. I do not really know that part of the code so not sure I'm the most comptent on that topic.

**Pull request closed without merging**
