### PR TITLE
Tophat: 2.1.1

### PR DESCRIPTION
**Pull request by philippbayer**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

This updates the version and fixes minor complaints of `brew audit`.

On my system, the old TopHat 2.0.14 does not compile with the new GCC from linuxbrew, as the included seqAn is too old (see [this discussion](https://groups.google.com/d/msg/tuxedo-tools-users/M7Z9zLuu8o4/t5RKJKnT4pAJ)). Newer versions of TopHat come with a newer seqAn which fixes this issue.

### CODE REVIEW

**Comment by philippbayer** [comment]
Errors are:

```
Error: 1 problem in 1 formula

homebrew/science/tophat:
  * Non-executables were installed to "/usr/local/Cellar/tophat/2.1.1/bin"
    The offending files are:
      /usr/local/Cellar/tophat/2.1.1/bin/intervaltree
      /usr/local/Cellar/tophat/2.1.1/bin/sortedcontainers
```

I don't see this one with my `brew audit`.

In `brew test`: 

```
2016-05-13 05:00:20] Preparing reads
	[FAILED]
Error running 'prep_reads'
  Reason: image not found
```

That one again doesn't happen on my system, several threads see this error under MacOS, very strange

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
No test error when I build this from source locally

**Comment by tdsmith** [comment]
`intervaltree` and `sortedcontainers` are both Python packages and it is not clear to me what they're doing in bin

**Comment by tdsmith** [comment]
tophat-fusion-post uses intervaltree and intervaltree uses sortedcontainers; intervaltree should move to a vendored directory and we should wrap tophat-fusion-post.

**Pull request closed without merging**
