### PR TITLE
Lighter 1.1.1 (update)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
Tag me when you merge this PR (or any bioinformatics PR), and I'll add the Linuxbrew bottle.

**Comment by tseemann** [comment]
@sjackman my brew pull failed?

```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/4064
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-science/pull/4064.patch
==> Applying patch
Applying: Lighter 1.1.1 (update)
==> Patch closes issue #4064
Warning: Nonstandard bump subject: Lighter 1.1.1 (update)
Warning: Subject should be: lighter 1.1.1
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-science/compare/linuxbrew:master...pr-4064.patch
==> Applying patch
Applying: edirect: Use a versioned URL, add head
fatal: sha1 information is lacking or useless (edirect.rb).
error: could not build fake ancestor
Patch failed at 0001 edirect: Use a versioned URL, add head
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.
```

**Comment by ilovezfs** [comment]
No it's a local problem with your repo. Do you have HOMEBREW_DEVELOPER=1 set in your environment? Autoupdate might be getting you tangled in knots if you don't.

**Comment by ilovezfs** [comment]
@tseemann I :ship:'d it :)

**Comment by tseemann** [comment]
@ilovezfs No I don't have that set - I recently migrated everything to a separate `linuxbrew` user and didn't correctly set up the environment. Thank you!

**Pull request closed without merging**
