### PR TITLE
geant4 10.3.2

### PR DESCRIPTION
**Pull request by equal-l2**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?~~
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?~~
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by equal-l2** [comment]
Would anyone review this PR?

**Comment by iMichka** [comment]
Waiting for the mac bottles to be built, but looks good

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@equal-l2 Thanks for your contribution

The Linux bottle could not be uploaded, it is way too big (500 MB); the binaries/libraries in there would need to be stripped. I have no time to work on that, if somebody wants to do it I can review a pull request for that later.

**Pull request closed without merging**
