### PR TITLE
LibBi 1.3.0

### PR DESCRIPTION
**Pull request by sbfnk**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

Version bump. Removed patches that have been merged into the new version. Made runtime dependency on automake explicit.

### CODE REVIEW

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
The `test` step failed with:

```
==> /usr/local/Cellar/libbi/1.3.0/bin/libbi sample @test.conf
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.8.18
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.18
		  Configured on: Tue Dec 13 23:28:29 GMT 2016
		  Configured by: brew@Yosemite.local
		 Configure mode: production
		    Host system: x86_64-apple-darwin14.5.0
	      Uname information: Darwin Yosemite.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /usr/local/Cellar/hdf5/1.8.18

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang ( Apple LLVM version 7.0.2 )
                         CFLAGS: 
                      H5_CFLAGS:  
                      AM_CFLAGS: 
                       CPPFLAGS: 
                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/usr/include -I/usr/local/opt/szip/include
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/usr/lib -L/usr/local/opt/szip/lib
 	 	Extra libraries: -lsz -lz -ldl -lm 
 		       Archiver: ar
 		 	 Ranlib: ranlib
 	      Debugged Packages: 
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: yes
                   C++ Compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ ( Apple LLVM version 7.0.2 )
                      C++ Flags: 
                   H5 C++ Flags:  
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib),szip(encoder)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
Bye...
Error: homebrew/science/libbi: failed
Failed executing: /usr/local/Cellar/libbi/1.3.0/bin/libbi sample @test.conf
```

**Comment by ilovezfs** [comment]
netcdf needs a revision bump

**Comment by ilovezfs** [comment]
Should be good once https://github.com/Homebrew/homebrew-science/pull/4735 is :green_apple: and merged.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Linux timed out so we'll just stick with macOS bottles. Thanks @sbfnk @ilovezfs!

**Pull request closed without merging**
