### PR TITLE
flexbar 3.0.3 (new formula)

### PR DESCRIPTION
**Pull request by jonchang**
~Supercedes~Supersedes #4142.

CC @nextgenusfs @tseemann

### CODE REVIEW

**Comment by jonchang** [comment]
Linux bottles are blocked by https://github.com/Linuxbrew/brew/pull/294.

**Comment by sjackman** [comment]
Linuxbrew now has `needs :cxx14`.

**Comment by iMichka** [comment]
Closing this PR as it is superseded by #5264

**Comment by iMichka** [comment]
Err no I didn't mean to close this. @jonchang Could you revive this PR?

**Comment by tseemann** [comment]
Thank you @jonchang for finishing what I couldn't - appreciated!

**Pull request closed without merging**
