### PR TITLE
gubbins 2.2.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tseemann** [comment]
Fails when I try to build it locally....  i'll wait for the bottle:
```
OMEBREW_VERSION: 1.2.8-6-gd07cc2d
ORIGIN: https://github.com/Linuxbrew/brew.git
2017-09-05 10:55:53 +1000

python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/home/linuxbrew/.linuxbrew/Cellar/gubbins/2.2.2/libexec/vendor
--single-version-externally-managed
--record=installed.txt

Failed to import the site module
Error processing line 1 of /home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/site-packages/bd2k_python_lib-1.14a1.dev37-py3.6-nspkg.pth:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/../Cellar/python3/3.6.2/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

**Comment by ilovezfs** [comment]
Hmm .. maybe try `pip2 uninstall reprlib` and then see if it still blows up?

**Comment by tseemann** [comment]
@ilovezfs but  the formula is installing a private version of every python module right?  if it conflicts with a another module installed by brew pip then this is a problem?

**Comment by ilovezfs** [comment]
That doesn't answer the question I asked.

**Comment by ilovezfs** [comment]
You can try adding `ENV.delete("PYTHONPATH")` to the beginning of `def install`

**Pull request closed without merging**
