### PR TITLE
FastTree 2.1.8 (new version + build options + DOI + SHA256)

### PR DESCRIPTION
**Pull request by tseemann**
Update: 25th March 2015

Morgan Price emailed to let me know that the above described changes, along with some others, have been incorporated into version 2.1.8 of FastTree. It’s available from the usual place. The increased precision is not enabled in the precompiled binaries, e.g. it’s still necessary to build with -DUSE_DOUBLE, but the precompiled binary supplies some helpful warning messages to let users know if their data may be in the danger zone:

WARNING! This alignment consists of closely-related and very-long sequences.
This version of FastTree may not report reasonable branch lengths!
Consider recompiling FastTree with -DUSE_DOUBLE.
For more information, visit http://www.microbesonline.org/fasttree/#BranchLen

### CODE REVIEW

**Comment by tseemann** [comment]
Do I need to add "fails_with llvm" ?
```
==> llvm-gcc -O3 -finline-functions -funroll-loops -Wall -DOPENMP -fopenmp -o FastTree FastTree-2.1.8.c -lm
Undefined symbols for architecture x86_64:
  "___builtin_expect", referenced from:
      _TopHitJoin.omp_fn.1 in cc3thfF4.o
      _SetAllLeafTopHits.omp_fn.3 in cc3thfF4.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
==> Formula
```

**Comment by iml** [comment]
Yes. I think the `:openmp` collection should blacklist `:llvm` though so I've submitted that upstream. I'm guessing the older OpenMP spec supported by llvm-gcc causes problems.

**Comment by tseemann** [comment]
@iml Thanks once again - that solved the problem. Looks like it's ready to merge!

**Comment by iml** [comment]
Thanks @tseemann

**Pull request closed without merging**
