### PR TITLE
cufflinks: bump revision for boost

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
```
g++-4.8 -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -O3  -DNDEBUG  -pthread   -I/home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3 -c -o differential.o differential.cpp
In file included from abundances.h:26:0,
                 from differential.cpp:20:
biascorrection.h:18:39: fatal error: boost/tr1/unordered_map.hpp: No such file or directory
```
https://travis-ci.org/Homebrew/homebrew-science/builds/268147053#L2465

**Comment by jonchang** [comment]
I think boost may have removed tr1 since it's about a decade old and C++11 does everything it was supposed to do. It might be possible to just directly replace that include with `boost/unordered_map.hpp`

**Comment by ilovezfs** [comment]
>It might be possible to just directly replace that include with boost/unordered_map.hpp

Yes that works.

**Comment by sjackman** [comment]
Thanks, Jon and Joe.
@tmozgach Can you please update this PR to use `inreplace` to change `boost/tr1/unordered_map.hpp` to `boost/unordered_map.hpp`?

**Comment by tmozgach** [comment]
@sjackman the following error because of new version of `boost`:
```
/home/linuxbrew/.linuxbrew/include/boost/archive/detail/iserializer.hpp:107: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
```

**Comment by iMichka** [comment]
@tmozgach New Linux boost bottles were pushed. Could you rebase this and try again? Thanks.

**Comment by tmozgach** [comment]
@sjackman could you please merge?

**Comment by sjackman** [comment]
Merged. Thanks, Tanya!

**Pull request closed without merging**
