### PR TITLE
vcftools 0.1.15: fix installation path of perl modules

### PR DESCRIPTION
**Pull request by mythosil**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### Summary

The previous revision installs its perl modules to the wrong directory, `/usr/local/Celler/vcftools/0.1.15/usr/local/Celler/vcftools/0.1.15/lib/perl5/site_perl`.
We have to specify **relative** path to `--with-pmdir` option.

### CODE REVIEW

**Comment by iMichka** [comment]
> Error: 1 problem in 1 formula
homebrew/science/vcftools:
>  * revisions should only increment by 1

Revision should be 1, not 2. When there is no revision it is considered as 0.

**Comment by mythosil** [comment]
Sorry, stupid mistake. I fixed it.

**Comment by iMichka** [comment]
@mythosil Thanks for your contribution!

**Comment by tseemann** [comment]
@mythosil Thank you SO much for fixing this. I didn't have time when i noticed it, and it broke my pipelines, so i just downgraded at the time. Much appreciated!

**Pull request closed without merging**
