### PR TITLE
htslib 1.3

### PR DESCRIPTION
**Pull request by ge11232002**

### CODE REVIEW

**Comment by ge11232002** [comment]
I don't understand the test result. Why it is testing nanopolish?

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by iml** [comment]
It tests all the dependents of htslib, although nanopolish doesn't actually use brew htslib. The failures are probably unrelated to this new version.

**Comment by iml** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
