### PR TITLE
added needed dependency htslib because of tabix

### PR DESCRIPTION
**Pull request by StephanJanosch**
PR because of missing dependency

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks you for your contribution to Homebrew.

This does not seem to be a build dependency? Does vcftools run without it?

**Comment by iMichka** [comment]
Just for ref, #4774 is about updating to v0.1.14, but this is a different topic.

**Comment by StephanJanosch** [comment]
vcf-concensus needs tabix. It fails with a not so easy to read error message of tabix is missing. It's a perl script. So you won't see a build dependency.

**Comment by iMichka** [comment]
Thanks for the explanation.

Per http://docs.brew.sh/Formula-Cookbook.html, could you rewrite this as?:
`depends_on "htslib" => :run`
so we make clear that this a runtime dependency.

Per http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html, take the opportunity to update the commit message:
- First line should be `vcftools: add htslib runtime dependency`

You sort of took a shortcut here by removing all the pull request template, which was there to remind you to follow the submitting conventions.

Please add a line in the commit message too, describing why we need htslib (because of tabix). This helps in case somebody looks at the git log later.

You can `git commit --amend` your changes and push them to GitHub with `git push --force` to have only a single commit.

**Comment by StephanJanosch** [comment]
> You sort of took a shortcut here by removing all the pull request template

Sorry for that, but I was super busy that day. And I am still super busy. I had the choice of simply doing it with my minimal git knowledge or not to do it. Let's see when I will have time for this.

**Comment by iMichka** [comment]
I took over in #5261 and added the dependency. Closing here.

**Pull request closed without merging**
