### PR TITLE
shogun: revision for readline

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
```
[  1%] Performing download step (download, verify and extract) for 'GoogleMock'
cd /tmp/shogun-20161011-90721-1lo5w12/shogun-4.1.0/build/GoogleMock/src && /usr/local/Cellar/cmake/3.6.2/bin/cmake -P /tmp/shogun-20161011-90721-1lo5w12/shogun-4.1.0/build/GoogleMock/src/GoogleMock-stamp/download-GoogleMock.cmake
-- downloading...
       src='http://googlemock.googlecode.com/files/gmock-1.7.0.zip'
       dst='/tmp/shogun-20161011-90721-1lo5w12/shogun-4.1.0/third_party/GoogleMock/gmock-1.7.0.zip'
       timeout='10 seconds'
error: downloading 'http://googlemock.googlecode.com/files/gmock-1.7.0.zip' failed
  status_code: 22
  status_string: "HTTP response code said error"
  log:
  --- LOG BEGIN ---
    Trying 74.125.133.82...
Connected to googlemock.googlecode.com (74.125.133.82) port 80 (#0)
GET /files/gmock-1.7.0.zip HTTP/1.1
Host: googlemock.googlecode.com
User-Agent: curl/7.43.0
Accept: */*

The requested URL returned error: 404 Not Found
Closing connection 0

  --- LOG END ---
```

**Comment by ilovezfs** [comment]
Yeah it inappropriately mooching off of protobuf before the protobuf3 upgrade. There's also a problem with the libraries where it's getting confused between the static and dynamic hdf5 and manually adding the library to the list lets it build.

**Comment by dpo** [comment]
It's looking for the CMake files from HDF5, but we don't seem to install them.

**Comment by ilovezfs** [comment]
I wonder if switching the hdf5 build to use cmake instead of autotools fixes that.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
👍

**Pull request closed without merging**
