### PR TITLE
openimageio: Fix python installation path

### PR DESCRIPTION
**Pull request by skycaptain**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

Issues #4413.

### CODE REVIEW

**Comment by iMichka** [comment]
@skycaptain The commit you had was OK. No need to add the other changes. I am currently testing this.

**Comment by iMichka** [comment]
For this to work, you will need to add "revision 1", so that new bottles are built. If you don't do that the change will only be valid for source builds.

**Comment by skycaptain** [comment]
I guess that I should rebase first to include changes made in #5937.

**Comment by iMichka** [comment]
Yes, you can, but it is not necessary as we cherry-pick the commit on top of master for the builds and for the merge.

**Comment by skycaptain** [comment]
That's why a asked beforehand 😁

**Comment by iMichka** [comment]
Yes, sorry. I forgot that if you touched these lines, you would get a conflict :)

**Comment by iMichka** [comment]
@skycaptain Thanks for your contribution!

**Pull request closed without merging**
