### PR TITLE
atlas: new formula

### PR DESCRIPTION
**Pull request by dpo**
### Have you:
- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?
- [X] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by sjackman** [comment]
Does `atlas` provide `libblas.so` and `liblapack.so`?

**Comment by dpo** [comment]
I believe it does now, but they won't build on OSX. It also seems `atlas` doesn't build on any bot OS. Perhaps this should be abandoned.

**Comment by sjackman** [comment]
```
==> make
..............................Error: SIGTERM
The system is going down for power off NOW!
```
https://travis-ci.org/Homebrew/homebrew-science/jobs/124308968#L628

>  Elapsed time 58 min 1 sec

I think it hit the one-hour cap. How long is `atlas` expected to take to build? I guess the parameter optimization takes a long time. I wonder if there's a configure option to tell it to do a faster parameter optimization. I'm also okay with abandoning it and using `openblas`.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by schoeps** [comment]
@dpo: compiling takes on my machine (recent i7 macbook pro) forever. I know that compiling atlas is lengthy but >24h seems to be insane...

**Comment by dpo** [comment]
It takes a long time for me as well (though not 24h). I think the OSX install procedure is still quite new. I haven't had time to investigate.

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Comment by danfulop** [comment]
Is there an ATLAS formula or not? I'm interested in it for Linuxbrew.

**Comment by sjackman** [comment]
No, I'm afraid there is not.

**Comment by sjackman** [comment]
You can try the formula in this PR though, if you like.
```sh
brew install https://raw.githubusercontent.com/dpo/homebrew-science/85ceb50d7f30ba86696d0ae0f0f9855b504f0f42/atlas.rb
```

**Comment by danfulop** [comment]
Thanks @sjackman!  I'm asking in relation to this issue https://github.com/Linuxbrew/homebrew-core/issues/5033

**Pull request closed without merging**
