### PR TITLE
igv: Correct SHA256

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
@jrobinso Did the IGV 2.3.93 tarball change?
The SHA-256 of the tarball changed from `28128097f7e503e64c20e3a60049dec101deb67c69091d13a9824ece1fa33603` to `3b63201b1bda073dc3abfcbfd7ebda0feb35e9632e9aff454f669e7231fea811` some time between 2017-05-13 and now 2017-05-19.

**Comment by jrobinso** [comment]
Its possible, the tag was accidentally removed during some 3.0 branch
cleanup (I was on the wrong branch),  then reapplied to what I thought was
the same commit, and rebuilt.   I don't explicitly build or control these
tarballs,  so I don't know what would happen in that case.   In any event
content should be the same, but timestamp might differ,  or its also
possible I goofed.

What is the "homebrew" connection to IGV?   Is this some alternate
distribution system?   I know nothing about this,  it would be nice if the
developers of this tool,  if that's what it is, would reach out to us and
at least let us know what they are doing.

**Comment by sjackman** [comment]
Hi, Jim. Homebrew is a package manager for macOS. The IGV package for Homebrew allows a user of Homebrew to install IGV using `brew install homebrew/science/igv`.

When I said tarball, I meant the file `IGV_2.3.93.zip`. Sorry, I should have been more clear.
https://www.broadinstitute.org/igv/projects/downloads/IGV_2.3.93.zip

It looks as though this file originally appeared some time before 2017-05-13, and was later changed on 2017-05-15. Just wanted to check that the change was intentional, if so, this PR updates the SHA-256 of that file.

**Comment by jrobinso** [comment]
OK,  yes, it was intentional, I originally applied the tag to a 3.0 test
branch,  not far diverged from 2.3.93 but wrong nonetheless.   I probably
should have just deleted 2.3.93 and applied a new tag, 2.3.94,  and will do
so next time.   Are you the maintainer for homebrew/science/igv?   We like
to track these things,  for grant reporting mainly.  I know Illumina and TF
distribute IGV, didn't know about this one.

Sorry for the confusion.

**Comment by sjackman** [comment]
No worries at all, Jim. Homebrew/science is maintained collectively by a team, and yes, I'm one of the maintainers.

**Comment by sjackman** [comment]
@tmozgach Thanks for the fix, Tanya!

**Comment by jrobinso** [comment]
OK, good to know,  we'll list it in our reports.

**Pull request merged**
