### PR TITLE
AdapterRemoval 2.2.0

### PR DESCRIPTION
**Pull request by MikkelSchubert**
New formula for AdapterRemoval.

Summary: 
AdapterRemoval v2 is a major revision of AdapterRemoval v1, which introduces (i) striking improvements in throughput, through the use of single instruction, multiple data (SIMD; SSE1 and SSE2) instructions and multi-threading support, (ii) the ability to handle datasets containing reads or read-pairs with different adapters or adapter pairs, (iii) simultaneous demultiplexing and adapter trimming, (iv) the ability to reconstruct adapter sequences from paired-end reads for poorly documented data sets, and (v) native gzip and bzip2 support.
http://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-016-1900-2
### Have you:
- [x ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by MikkelSchubert** [comment]
The checks appear to have during the audit due to a problem with the build system:

    Error: GitHub API rate limit exceeded for 208.78.110.199. (But here's the good news: 
    Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    Try again in 40 minutes 44 seconds, or create a personal access token:
      https://github.com/settings/tokens/new?scopes=&description=Homebrew
    and then set the token as: HOMEBREW_GITHUB_API_TOKEN

**Comment by tseemann** [comment]
@BrewStatusBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by MikkelSchubert** [comment]
I just realized that the formula I initially pushed was an older version (2.1.6), while I had intended to submit a pull request for a version which does not require performing the install step manually (you can now set PREFIX for 'make install'), namely 2.1.7, as per the title. I have corrected this now and apologize for the mistake.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@MikkelSchubert v2.2.0 is out. Would like to give this again a try? There are no logs anymore for the old builds, so I do not know over what problems you stumbled.

**Comment by MikkelSchubert** [comment]
From what I remember, there were no technical issues (other than the build server being throttled), but the repository did not meet the notability requirements (times star'd / forked). 

Cheers

**Comment by iMichka** [comment]
This rule has been softened up a little bit for homebrew science. Being published is also enough.

Could you bump the version number to v2.2.0, so that we can review this again?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Thanks for contributing @MikkelSchubert! This has been added to Homebrew.

**Pull request closed without merging**
