### PR TITLE
clfft 2.12.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dpo** [comment]
Don't understand why the test output is
```
(0.000000, 0.000000) (1.000000, 3.000000) (2.000000, 6.000000) (3.000000, 9.000000) (4.000000, 12.000000) (5.000000, 15.000000) (6.000000, 18.000000) (7.000000, 21.000000) (8.000000, 24.000000) (9.000000, 27.000000) (10.000000, 30.000000) (11.000000, 33.000000) (12.000000, 36.000000) (13.000000, 39.000000) (14.000000, 42.000000) (15.000000, 45.000000) 
```
on the bot while I get
```
(120.000000, 360.000000) (-128.656143, 16.218718) (-65.941124, -4.686291) (-43.918537, -12.027153) (-32.000000, -16.000000) (-24.036289, -18.654572) (-17.941124, -20.686291) (-12.773895, -22.408699) (-8.000000, -24.000000) (-3.226101, -25.591299) (1.941124, -27.313709) (8.036289, -29.345428) (16.000000, -32.000000) (27.918537, -35.972847) (49.941124, -43.313709) (112.656143, -64.218719)
```
locally...

**Comment by tseemann** [comment]
@ilovezfs is this a `g++` versus `clang` issue?    I can't build it on Linux. I assume `-framework OpenCL` is  special option.

**Comment by jonchang** [comment]
Yeah, I don't know if there's openCL for Linux. Is there an option to disable openCL that we could use by default on Linux?

**Comment by ilovezfs** [comment]
@jonchang there's https://github.com/pocl/pocl I guess ...

**Comment by ilovezfs** [comment]
This problem appears to be specific to Sierra unfortunately.

**Comment by ilovezfs** [comment]
Reported upstream: https://github.com/clMathLibraries/clFFT/issues/181

**Comment by ilovezfs** [comment]
Closing this since it's an upstream issue and upstream has not responded.

**Comment by ilovezfs** [comment]
The problem turned out to be that Homebrew CI currently runs in virtual machines. On bare metal, the fft results are as expected.

**Pull request closed without merging**
