### PR TITLE
harvest-tools 1.2

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by tseemann** [comment]
Arrggh :(

```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/4101
==> Fetching patch
Patch: https://github.com/Homebrew/homebrew-science/pull/4101.patch
==> Applying patch
Applying: harvest-tools 1.2
==> Patch closes issue #4101
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-4101
```

**Comment by ilovezfs** [comment]
Yeah, downstream build view is in the red:

https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5579/downstreambuildview/

https://bot.brew.sh/job/Homebrew%20Bottles/56608/

https://bot.brew.sh/job/Homebrew%20Bottles/56608/console

The reason is
```
curl -I --silent --fail --output /dev/null https://homebrew.bintray.com/bottles-science/harvest-tools-1.2.el_capitan.bottle.1.tar.gz
Error: harvest-tools-1.2.el_capitan.bottle.1.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles-science/harvest-tools/view#files
Build step 'Execute shell' marked build as failure
```

So you have to login to bintray and delete the preexisting ones here:
https://bintray.com/homebrew/bottles-science/harvest-tools/view#files

Then go to https://bot.brew.sh/job/Homebrew%20Bottles/56608/ and click the rebuild button

**Comment by ilovezfs** [comment]
>"delete the preexisting ones"

Note that by that I only mean the latest ones with the colliding version. Of course you do not want to delete any of the older ones.

**Comment by tseemann** [comment]
@ilovezfs i think i've messed things up - it seems there was already a 1.2 that was submitted outside my original pull request. I'm a bit confused. I'll make a revision.

**Comment by ilovezfs** [comment]
@tseemann it's probably just you having already run pull --bottle at some point. There's no need for a revision *and you should not use one* if 1.2 was never commuted to master. Do you have access on bintray? You just need to remove the offending bottles.

**Comment by ilovezfs** [comment]
You should be using `pkgshare` not `share` here. Otherwise it just dumps random things in /usr/local/share which is undesirable.

**Comment by tseemann** [comment]
@ilovezfs i was actually the one who created the `pkgshare` method after I noticed the same issue ;-) But this was an old pull request that pre-dated that and I forgot to fix it. Thanks for checking these things and letting me know!

**Comment by ilovezfs** [comment]
@tseemann test timed out because you also need to change it from share -> pkgshare in the test do block.

**Comment by ilovezfs** [comment]
@tseemann you also need to remove the revision :)

**Comment by ilovezfs** [comment]
@tseemann did u have a chance to fix the test?

**Comment by tseemann** [comment]
@ilovezfs ok, trying again. i've made a lot of hijinks on this one!

**Comment by ilovezfs** [comment]
@tseemann ok looks fine except that you need to put the original bottle block back in. You basically should never alter a bottle block unless you're removing it and replacing it with ` bottle :unneeded` or the like.

**Comment by ilovezfs** [comment]
Looks like this actually doesn't change anything, so closing.

**Pull request closed without merging**
