### PR TITLE
YAHA 0.1.83 (update version + compile from src + OS X support)

### PR DESCRIPTION
**Pull request by tseemann**
Previously was Linux only and binary.

### CODE REVIEW

**Comment by tseemann** [comment]
This worked on Linux. Any OSX ideas?

```
g++ -fpermissive -Wall -O3 -D COMPILE_USER_MODE -D BUILDNUM=83 -MMD -MP -c src/GraphPath.cpp -o obj/GraphPath.o
src/FileHelpers.c:21:10: fatal error: 'stdio_ext.h' file not found
#include <stdio_ext.h>
         ^
gcc -Wall -O3 -D COMPILE_USER_MODE -D BUILDNUM=83 -MMD -MP -std=gnu99 -c src/Index.c -o obj/Index.o
gcc -Wall -O3 -D COMPILE_USER_MODE -D BUILDNUM=83 -MMD -MP -std=gnu99 -c src/Query.c -o obj/Query.o
1 error generated.
make: *** [obj/FileHelpers.o] Error 1
make: *** Waiting for unfinished jobs....
src/Query.c:22:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^
1 error generated.
```

**Comment by tseemann** [comment]
Seems "sys/sysinfo.h" maybe a Linux-only kernel header:

http://compgroups.net/comp.unix.programmer/sys-sysinfo.h-no-such-file-or-directory/539480

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@sjackman @iml  Any ideas what this (new to me) error is?

```
=> Applying patch
Applying: YAHA 0.1.83 (update version + compile from source)
==> Patch closes issue #2373
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ OS\ X\ 10.10.3) --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-2373
```

**Comment by iml** [comment]
It didn't build any bottles, since it's Linux-only.

**Comment by sjackman** [comment]
Use `brew pull foo` rather than `brew pull --bottles foo`

**Comment by sjackman** [comment]
Care to open an issue upstream asking for Mac support?

**Comment by tseemann** [comment]
Thank you @iml and @sjackman - I had forgotten it was Linux only. That explains it. D'oh!

**Pull request closed without merging**
