### PR TITLE
Update armadillo to 5.000.0

### PR DESCRIPTION
**Pull request by zeeMonkeez**

### CODE REVIEW

**Comment by iml** [comment]
The test fails because the format of `arma_version` changed to 5.0.0 for some reason.

**Comment by dpo** [comment]
Thanks. Could you please squash your commits?

**Comment by iml** [comment]
Sorry for not being clear, I think you can leave off the version and ignore the test. The failure is really a false-positive because the arma_versions are defined as integers not strings. Thanks!

**Comment by zeeMonkeez** [comment]
Seems like we would not want the test to fail? I did ask Conrad Sand, author of armadillo, about the inconsistent version strings, but haven't received a response yet.
Guess this problem will go away once three-figure minor versions are reached again ...

**Comment by zeeMonkeez** [comment]
ugh, I don't understand the failure message.

**Comment by saketkc** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
SEems like a bot issue. I'm having the same in #2113.

**Comment by saketkc** [comment]
It doesn't seem to be picking up `test this please` also, right?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
