### PR TITLE
BUG: disable thread local storage

### LINKED ISSUE #6411: "flint" compiled with HAVE_TLS is not usable
### Indicate troubleshooting steps taken

- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x ] Checked that a similar issue hasn't already been filed?
- [ x ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

When using the "flint" library to build a subproject, the generated "config.h" has `HAVE_TLS` set to "enabled." However, attempts to use the "flint" library fail with an error that "thread local storage is not supported for the current target." I think the solution to this problem to to pass `--disable-tls` to `configure`. Are others okay with this?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### PR DESCRIPTION
**Pull request by xoviat**
Closes #6411. Hopefully I have done the right thing here, as I'm not that familiar with ruby and the contributing guidelines are strict.

### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
Hopefully.
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
I don't understand this part, as there seems to be no "revision" section. Please help?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
Hi @xoviat, thanks for figuring out this bug and contributing to Homebrew! You'll need to add a `revision 1` line above the `head` statement so that our users will be prompted to upgrade. Feel free to ping me if you need any help with this.

**Comment by jonchang** [comment]
Also, the commit statement should read `flint: disable thread local storage`

**Comment by xoviat** [comment]
Aside from the commit message, is that okay?

**Comment by jonchang** [comment]
Yup, this is good to merge once tests pass. I can squash the commits and edit the message, no big deal. Just tips for your future contributions to Homebrew ;)

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by xoviat** [comment]
Jenkins failure seems related to `git` (not related to this).

**Comment by jonchang** [comment]
Thanks for contributing to Homebrew @xoviat! This has been merged.

**Comment by xoviat** [comment]
Thanks!

**Pull request closed without merging**
