### PR TITLE
Octave: fix hdf5 library

### PR DESCRIPTION
**Pull request by schoeps**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### What's new?
- ensure that the correct hdf5 library is used

### CODE REVIEW

**Comment by schoeps** [comment]
I would like to make `fltk` recommended (instead optional) but then I would have to specify `--devel` since fltk-1.3.3 does not work on recent Mac OS X. Objections?

**Comment by dpo** [comment]
The trouble is that `fltk --devel` isn't bottled. That'll prevent `octave` from being bottled I believe.

**Comment by schoeps** [comment]
Even worse, I realized that you cannot ask for `--devel` similarly as for other options... so, I will wait until the next official fltk release :(

**Comment by dpo** [comment]
Good point. Thanks!

**Pull request closed without merging**
