### PR TITLE
strelka 1.0.14 (new formula)

### PR DESCRIPTION
**Pull request by brunogrande**
added Strelka, somatic variant caller (for SNVs and indels)

### CODE REVIEW

**Comment by brunogrande** [comment]
## Linux Build
I'm not sure why the Linux build stalls on `make install` for Strelka. Any ideas? I didn't run into this issue when installing on a local Linux machine. I'll test it out on other Linux machines. 

## OS X Build
From what I can tell, the issue with the OS X build is an incompatibility between the version of samtools redistributed with Strelka (v0.1.14, I believe) and clang. I added a fails_with for clang, but installing all of GNU gcc on OS X seems overkill for a minor compiling issue. I've come across potential solutions that might resolve the samtools compilation error. I'll need help though integrating these workarounds into the formula. 

### Potential Workarounds
* Add `-std=gnu89` flag to clang command during compilation ([source 1](https://github.com/smithlabcode/methpipe/issues/16), [source 2](http://clang.llvm.org/compatibility.html#inline))
* Change inline functions to static ([source](https://github.com/lh3/samtools/issues/15))
* If worse comes to worst, install latest GNU gcc

**Comment by dpo** [comment]
Isn't it possible to have `depends_on "samtools"`? The error on 10.9 is quite mysterious. I'll restart that and the Linux builds.

**Comment by dpo** [comment]
```
gcc -g -Wall -O2  -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o -Lbcftools  libbam.a -lbcf  -lm -lz
Undefined symbols for architecture x86_64:
  "_lseek64", referenced from:
      _knet_seek in libbam.a(knetfile.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by jonchang** [comment]
@brunogrande 

OS X doesn't have `lseek64`, please check if Homebrew is building on OS X and use `inreplace` to substitute the call to `lseek64` with plain `lseek`. Culprit appears to be in `strelka/redist/samtools-0.1.18_no_tview/knetfile.c`

**Comment by iMichka** [comment]
Closing here as there was no activity since some time now. If somebody really needs this a new PR can be opened.

**Pull request closed without merging**
