### PR TITLE
octave 4.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
CC @schoeps @dpo @houtanb

### CODE REVIEW

**Comment by schoeps** [comment]
You are super fast! 👍 The release is not even announced yet.

Shall we add this patch https://savannah.gnu.org/support/download.php?file_id=38902 from https://savannah.gnu.org/bugs/?49053 to fix qt5 plotting issues?

By the way: I still see crashes when exiting octave. Do you guys see that, too?

**Comment by ilovezfs** [comment]
@schoeps 

I don't think I'm able to reproduce the crash on exit.

>Shall we add this patch https://savannah.gnu.org/support/download.php?file_id=38902 from https://savannah.gnu.org/bugs/?49053 to fix qt5 plotting issues?

Sure, but it doesn't seem to apply successfully:
```
==> Verifying octave-4.2.0.tar.lz checksum
==> Downloading https://savannah.gnu.org/bugs/download.php?file_id=38206
Already downloaded: /Users/joe/Library/Caches/Homebrew/octave--patch-8307cec2b84fe546c8f490329b488ecf1da628ce823301b6765ffa7e6e292eed.php
==> Verifying octave--patch-8307cec2b84fe546c8f490329b488ecf1da628ce823301b6765ffa7e6e292eed.php checksum
==> Downloading https://savannah.gnu.org/support/download.php?file_id=38902
==> Downloading from https://savannah.gnu.org/file/retina_scale_hg_patch.diff?file_id=38902
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.0-126-g484e3e0 (Macintosh; Intel macOS 10.11.6) curl/7.43.0 https://savannah.gnu.org/file/retina_scale_hg_patch.diff?file_id=38902 -C 0 -o /Users/joe/Library/Caches/Homebrew/octave--patch-d56eff94f9f811845ba3b0897b70cba43c0715a0102b1c79852b72ab10d24e6c.php.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3728  100  3728    0     0   6096      0 --:--:-- --:--:-- --:--:--  6101
==> Verifying octave--patch-d56eff94f9f811845ba3b0897b70cba43c0715a0102b1c79852b72ab10d24e6c.php checksum
==> Patching
==> Applying download.php
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/octave--patch-20161115-65211-1vax6bi/download.php
patching file libgui/src/octave-dock-widget.cc
Hunk #1 succeeded at 55 with fuzz 2 (offset 2 lines).
==> Applying download.php
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/octave--patch-20161115-65211-1q6vz52/download.php
patching file libgui/graphics/GLCanvas.cc
patching file libinterp/corefcn/gl-render.cc
Hunk #2 succeeded at 3482 (offset -39 lines).
Hunk #3 FAILED at 3587.
Hunk #4 succeeded at 3775 (offset -39 lines).
1 out of 4 hunks FAILED -- saving rejects to file libinterp/corefcn/gl-render.cc.rej
patching file libinterp/corefcn/graphics.cc
Hunk #1 FAILED at 6285.
Hunk #2 FAILED at 8074.
Hunk #3 succeeded at 9232 (offset -33 lines).
2 out of 3 hunks FAILED -- saving rejects to file libinterp/corefcn/graphics.cc.rej
patching file libinterp/corefcn/graphics.in.h
Hunk #1 succeeded at 6044 (offset -9 lines).
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
ErrorDuringExecution: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/octave--patch-20161115-65211-1q6vz52/download.php
```

**Comment by schoeps** [comment]
It does probably only apply to the new development branch. I will have a look today or tomorrow.

**Comment by ilovezfs** [comment]
Yep, does apply to HEAD
```
==> Applying download.php
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/octave--patch-20161115-65460-8k7o2h/download.php
patching file libgui/src/octave-dock-widget.cc
Hunk #1 succeeded at 55 with fuzz 2 (offset 2 lines).
==> Applying download.php
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/octave--patch-20161115-65460-1zmei0/download.php
patching file libgui/graphics/GLCanvas.cc
patching file libinterp/corefcn/gl-render.cc
Hunk #2 succeeded at 3550 (offset 29 lines).
Hunk #3 succeeded at 3655 (offset 29 lines).
Hunk #4 succeeded at 3843 (offset 29 lines).
patching file libinterp/corefcn/graphics.cc
patching file libinterp/corefcn/graphics.in.h
Hunk #1 succeeded at 6054 (offset 1 line).
```

**Comment by ilovezfs** [comment]
@schoeps There's a bug in the patch. `<QApplication.h>` should just be `<QApplication>`

This should work for both stable and head:
```
diff --git a/octave.rb b/octave.rb
index 46129f0..c5bc02f 100644
--- a/octave.rb
+++ b/octave.rb
@@ -133,6 +133,13 @@ class Octave < Formula
   depends_on "portaudio"           => :optional
   depends_on :java                 => ["1.6+", :optional]
 
+  # Fix bug #49053: retina scaling of figures
+  # see https://savannah.gnu.org/bugs/?49053
+  resource "retina-scaling-patch" do
+    url "https://savannah.gnu.org/support/download.php?file_id=38902"
+    sha256 "d56eff94f9f811845ba3b0897b70cba43c0715a0102b1c79852b72ab10d24e6c"
+  end
+
   # If GraphicsMagick was built from source, it is possible that it was
   # done to change quantum depth. If so, our Octave bottles are no good.
   # https://github.com/Homebrew/homebrew-science/issues/2737
@@ -149,6 +156,14 @@ class Octave < Formula
     ENV.prepend_path "PATH", Formula["texinfo"].bin
     ENV["FONTCONFIG_PATH"] = "/opt/X11/lib/X11/fontconfig"
 
+    resource("retina-scaling-patch").stage do
+      inreplace "download.php" do |s|
+        s.gsub! "#include <QApplication.h>", "#include <QApplication>"
+        s.gsub! "__fontsize_points__", "fontsize_points" if build.stable?
+      end
+      system "patch", "-p1", "-i", Pathname.pwd/"download.php", "-d", buildpath
+    end
+
     # basic arguments
     args = ["--prefix=#{prefix}"]
     args << "--enable-dependency-tracking"
```

**Comment by schoeps** [comment]
Works for me, also plotting seems to be ok. Thanks a lot. I'd say you merge quickly such that we can claim that we had a stable Octave 4.2. release before the official announcement :)

**Comment by ilovezfs** [comment]
@schoeps shipped!

**Comment by houtanb** [comment]
Thanks for your work @ilovezfs

**Pull request closed without merging**
