### PR TITLE
VTK --with-qt5 should depend on pyqt5

### PR DESCRIPTION
**Pull request by fran6co**
It should use pyqt5 for qt5

### CODE REVIEW

**Comment by fran6co** [comment]
I have no idea why this is failing.

**Comment by fran6co** [comment]
@BrewTestBot test this please

**Comment by iml** [comment]
That's more of a warning; it needs to be patched upstream. Using `depends_on :python` means python bindings in the current bottles are linked against Homebrew python.

**Comment by dpo** [comment]
https://github.com/Homebrew/homebrew-science/pull/2765#issuecomment-142336362

**Pull request closed without merging**
