### PR TITLE
mlpack 1.0.12

### PR DESCRIPTION
**Pull request by saketkc**

### CODE REVIEW

**Comment by dpo** [comment]
Are you a `mlpack` user? Do you have an opinion on #1374?

**Comment by saketkc** [comment]
I am pretty new. Thanks for pointing that out. It builds fine on my system, because probably I do have `hdf5` installed.

Let's wait for the build to finish. I can update the formula accordingly. And since github no longer shows us travis status, it is here: https://travis-ci.org/Homebrew/homebrew-science/builds/47860631

**Comment by saketkc** [comment]
The failure on jenkins is due to flloating point precision. I will report that upstream.

**Comment by saketkc** [comment]
And yes, that `hdf5` issue is persistent too

**Comment by dpo** [comment]
Looks like it should be added to `armadillo`.

**Comment by saketkc** [comment]
I will send a new one, for `armadillo` first.

**Comment by saketkc** [comment]
Looks like it is going to require fixing couple of packages, first of them being `arpack-ng`:
https://travis-ci.org/saketkc/homebrew-science/builds/47992713#L349

**Comment by dpo** [comment]
Ah, I think we have to `apt-get install libblas-dev liblapack-dev` on the Linux bot, no?

**Pull request closed without merging**
