### PR TITLE
SCAMP 2.0.4: New formula

### PR DESCRIPTION
**Pull request by mwcraig**
This pull request adds scamp, used to calibrate both positions and magnitudes (brightnesses) of objects in astronomical images.

There are a number of patches; all but one modify the code to use the Accelerate framework for linear algebra instead of ATLAS. One modification fixes a bug in the released version of scamp.

All of the modifications have been reported via email to the upstream maintainer. 

In the interests of complete disclosure, as far as I can tell `make check` doesn't actually do anything in scamp.

Please let me know if there are changes that need to be made before merging.

### CODE REVIEW

**Comment by mwcraig** [comment]
The changes I made should fix the build errors. Apologies that the `test do` block doesn't actually do a very useful test.

**Comment by dpo** [comment]
Were the patched submitted upstream?

**Comment by mwcraig** [comment]
Yes; I expect the patch for the segfault will be included in a future release (though time between releases is very long for this software) but the patches to use the Accelerate framework instead of ATLAS may never be integrated.

**Comment by iml** [comment]
Can you squash these to a single commit, that will also trigger a new build.

**Comment by mwcraig** [comment]
@iml --squashed, but didn't seem to trigger the new build...

**Comment by iml** [comment]
I think the bots have been disabled for today.

**Comment by iml** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
