### PR TITLE
Petsc 3.6.3 (update)

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by DomT4** [comment]
This timed out at least 4 times in a row at 2 hours a piece, chewing up the CI for 7+ *hours*.

screen shot 2015-10-23 at 17 28 54

Can a Science maintainer please check this is ready, bump your timeout when the CI is less backed up and reschedule this then, Thanks. Let's try and get it passed in one build so we're not losing nearly a 1/3rd of a day of CI time needlessly.

**Comment by dpo** [comment]
@DomT4 Sorry about this. Many science formulae take a long time and in fact typically time out.

@davydden please test the builds on your fork on Homebrew/science (enable Travis-CI on it) before submitting. Don't forget to rebase so you have the new `.travis.yml`.

**Comment by davydden** [comment]
@dpo do you want me to drop this 2d5844c3f715c0fd95d11d2f50cad687890de10a commit ? but then formulae which use petsc won't pass tests.

**Comment by davydden** [comment]
bump

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
This isn't going to build until we fix MPI...

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
