### PR TITLE
BEDOPS 2.4.6

### PR DESCRIPTION
**Pull request by alexpreynolds**
* Document style changes that improve mobile device support
* Support for RepeatMasker annotation output and GVF formats in `convert2bed`
* Bug fix in `convert2bed` for GFF and GTF formats
* General document typo fixes
* 19M reduction in repository size

### CODE REVIEW

**Comment by dpo** [comment]
There's no need to remove the `bottle` section. It will be replaced by the bot.

**Comment by alexpreynolds** [comment]
Hi Dominique,

When I tested the changes to the bedops.rb recipe before submitting it, it crashed on the bottle section. (Perhaps because no bottles were yet made from the new version or some other issue?) 

Once I removed the bottle section, the recipe worked and so I was able to submit it for a pull request.

Is there a way to test the recipe that skips the bottle section?

Regards,
Alex

**Comment by dpo** [comment]
You would want to `brew install bedops --build-from-source`.

**Comment by alexpreynolds** [comment]
Thanks -- it might be helpful to add a note about this option to the Formula Cookbook instructions, e.g., at:

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#test-the-formula

I often find I have to relearn how to do this each time, so I end up needing to look up the instructions for the process.

-Alex

**Comment by dpo** [comment]
Ok. Would you mind fixing up your PR and restore the old `bottle` section? Otherwise it looks like you made more changes than you actually did.

**Comment by sjackman** [comment]
The bottle SHA mismatch should have been only a warning. Can you post the issue that you had?

**Pull request closed without merging**
