### PR TITLE
openblas: Fix library symlinks

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?
- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
But it doesn't work on OSX. The symlinks aren't part of the bottle.

**Comment by sjackman** [comment]
It works for me on Mac:
```
❯❯❯ ls -l openblas/0.2.18_2/lib                            master ⬆
total 85912
drwxr-xr-x  3 sjackman  _lpoperator       102 13 Jun 13:39 cmake
lrwxr-xr-x  1 sjackman  _lpoperator        17 13 Jun 13:39 libblas.dylib -> libopenblas.dylib
lrwxr-xr-x  1 sjackman  _lpoperator        17 13 Jun 13:39 liblapack.dylib -> libopenblas.dylib
lrwxr-xr-x  1 sjackman  _lpoperator        34 13 Jun 13:39 libopenblas.a -> libopenblas_sandybridgep-r0.2.18.a
lrwxr-xr-x  1 sjackman  _lpoperator        38 13 Jun 13:39 libopenblas.dylib -> libopenblas_sandybridgep-r0.2.18.dylib
-r--r--r--  1 sjackman  _lpoperator  24915488 13 Jun 13:39 libopenblas_sandybridgep-r0.2.18.a
-r--r--r--  1 sjackman  _lpoperator  19053168 13 Jun 13:39 libopenblas_sandybridgep-r0.2.18.dylib
```

**Comment by sjackman** [comment]
There's some kind of spurious error on Yosemite. I'll attempting to rebuild it now.

**Comment by sjackman** [comment]
Confirmed that the symlinks exist in the bottle too:
```
❯❯❯ tar tf openblas-0.2.18_2.el_capitan.bottle.tar.gz |grep dylib
openblas/0.2.18_2/lib/libblas.dylib
openblas/0.2.18_2/lib/liblapack.dylib
openblas/0.2.18_2/lib/libopenblas.dylib
openblas/0.2.18_2/lib/libopenblasp-r0.2.18.dylib
```

**Pull request closed without merging**
