### PR TITLE
insighttoolkit 4.9.0

### PR DESCRIPTION
**Pull request by iMichka**
VTK 7 is compatible with python 3

### CODE REVIEW

**Comment by iMichka** [comment]
Please merge this only when VTK has been upgraded to VTK 7; see #3286

**Comment by iMichka** [comment]
I update the formula:
- removed ```revision 1``. Brew audit told me to do this. No clue why, the documentations also does not explain what revision number a version bump should have. Maybe ```revision 0``` ?
- added the VTK dependency even no python bindings are used.

**Comment by dpo** [comment]
We simply remove the `revision` when upgrading to a new version.

**Comment by iMichka** [comment]
statismo was looking for ITK 4.8.1 dylibs. I updated the statismo revision to force a rebuild of statismo too.

**Comment by iMichka** [comment]
Ok this is still failing due to statismo. Don't know if I should have touched that revision number.

Seems that the step ```brew uses --recursive homebrew/science/statismo``` is triggered, but ```brew uninstall``` has already been run, which means the insighttoolkit bottle has been deleted. It could be a bug in the build process ?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
I moved the statismo revision bump to a separate PR: #3344

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Thanks !

**Pull request closed without merging**
