### PR TITLE
Skewer 0.1.124 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
This program implements a novel dynamic programming algorithm dedicated to the task of adapter trimming and it is specially designed for processing illumina paired-end sequences.

### CODE REVIEW

**Comment by dpo** [comment]
Any chance to convince the skewer guys to make a release?

**Comment by tseemann** [comment]
@dpo We are trying to get @replimoc to tag a release:  https://github.com/relipmoc/skewer/issues/18

**Comment by tseemann** [comment]
@dpo Despite the github tag, it still has official version in the docs and for the corresponding binary downloads. I know you prefer not to have binary downloads, so I spent the time to get this source formula working. Can you accept it in the meantime please? 

(It's a dependency for my other brew formulae)

**Comment by tseemann** [comment]
@dpo Can you remove the "needs response" tag please? It's ready to go.

**Comment by dpo** [comment]
I'm a bit uneasy merging something that doesn't have a release. I'll leave it to @sjackman.

**Comment by sjackman** [comment]
I much prefer having GitHub tagged releases, but I'm okay with using the hash of the most recent stable release when the upstream authors have given it a version number.

**Pull request closed without merging**
