### PR TITLE
octave: texi2dvi is shipped with OS X

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by schoeps** [comment]
Are you sure? Where is it? I did not find texinfo on my Yosemite.

**Comment by tdsmith** [comment]
Yeah, I don't see it, either! I haven't installed mactex on this system yet.

**Comment by dpo** [comment]
It's not on my Mavericks system either.

**Comment by dpo** [comment]
Unless it's only comprised of `texi2dvi`, etc., which I do have in `/usr/bin`

**Comment by schoeps** [comment]
Ok, sorry for beeing too fast; also on Yosemite:
```
/usr/bin/texi2dvi --version
texi2dvi (GNU Texinfo 4.8) 1.34
```

**Comment by xu-cheng** [comment]
Sorry I thought texinfo is shipped becuase texi2dvi. But in the same time, it seems that octave only needs texi2dvi

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@xu-cheng 
```
brew audit --strict octave
==> brew style octave
== octave.rb ==
W: 69: 44: Use parentheses in the method call to avoid confusion about precedence.
C:122: 48: Put one space between the method name and the first argument.

1 file inspected, 2 offenses detected

==> audit problems
homebrew/science/octave:
 * `stable block`(line 17) should be put before `bottle block`(line 9)
 * `caveats method`(line 181) should be put before `test block`(line 177)
 * Formula should have a desc (Description).

Error: 3 problems in 1 formula
```

Also, can you change the formula to work better with Linux? `if OS.linux?` etc
```
    args << "--with-x=no"     # We don't need X11 for Mac at all
```

**Comment by dpo** [comment]
@xu-cheng What's happening with this one?

**Comment by xu-cheng** [comment]
Bot says this is good to merge.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Strange. Now it's failing:
```
libtool: link: warning: library `/usr/local/Cellar/graphicsmagick/1.3.21/lib/libGraphicsMagick++.la' was moved.
../libtool: line 7486: cd: @@HOMEBREW_CELLAR@@/graphicsmagick/1.3.21/lib: No such file or directory
libtool: link: warning: cannot determine absolute directory name of `@@HOMEBREW_CELLAR@@/graphicsmagick/1.3.21/lib'
grep: @@HOMEBREW_CELLAR@@/graphicsmagick/1.3.21/lib/libGraphicsMagick.la: No such file or directory
/usr/local/opt/gnu-sed/bin/gsed: can't read @@HOMEBREW_CELLAR@@/graphicsmagick/1.3.21/lib/libGraphicsMagick.la: No such file or directory
libtool: link: `@@HOMEBREW_CELLAR@@/graphicsmagick/1.3.21/lib/libGraphicsMagick.la' is not a valid libtool archive
```

**Comment by xu-cheng** [comment]
@dpo Should be fixed now.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
More bottle problems.

**Comment by dpo** [comment]
`brew pull --bottle` downloads a bottle named `octave-3.8.2_1.mavericks.bottle.1.tar.gz` but `brew fetch --force-bottle` wants to download `octave-3.8.2_1.mavericks.bottle.tar.gz` (without the trailing `.1`), which doesn't exist. Any idea what's going on?

**Comment by xu-cheng** [comment]
@dpo Here is what you should do in this situation:

1. Goto the CI job page. In this case, it's http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2633/
2. Click `Downstream build view` on the left. You will see the status of bottle uploading. If it failed, you can click it and to see the log where it's wrong. Usually there are published bottles existed and requires you to delete them manually.
3. After solving this out, you can re-run the uploading job.

When I wrote this, I notice you have fixed the problem. Anyway, I hope this is helpful.

**Comment by dpo** [comment]
I went through this exercise a few times now and there's just some mismatch between the bottle names. Please see if you're able to merge this.

**Comment by xu-cheng** [comment]
Works fine for me. Merged

**Comment by dpo** [comment]
Does `brew fetch --force-bottle octave` work for you?

**Comment by xu-cheng** [comment]
Yes it works for me.

**Pull request closed without merging**
