### PR TITLE
Update armadillo (and revbump mlpack)

### PR DESCRIPTION
**Pull request by LogicalKnight**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
Wonder why Travis thinks homebrew/x11 doesn't exist:
```
==> Tapping homebrew/python
fatal: repository 'homebrew/x11' does not exist
```

**Comment by dpo** [comment]
```
==> brew audit homebrew/science/mlpack
Error: 1 problem in 1 formula
homebrew/science/mlpack:
  * Can't find dependency "txt2man".
==> FAILED
```

It looks like `txt2man.rb` was demoted to [the boneyard](https://github.com/Homebrew/homebrew-boneyard/blob/master/txt2man.rb) by @ilovezfs.

**Comment by dpo** [comment]
Since `txt2man` was optional anyways, let's just remove it from the formula.

**Comment by LogicalKnight** [comment]
@dpo No problem. I'll update the PR.

**Comment by LogicalKnight** [comment]
@dpo Updated! Let me know if there's anything else.

**Comment by dpo** [comment]
@LogicalKnight Thanks!

**Pull request closed without merging**
