### PR TITLE
gnuastro 0.2 (new formula)

### PR DESCRIPTION
**Pull request by mindriot101**
Add a new package: gnuastro

The GNU Astronomy Utilities (Gnuastro) is an official GNU package
consisting of various programs and library functions for the
manipulation and analysis of astronomical data.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

Currently the test only runs one of the programs because I am not familiar with the program enough to add a better test. Hopefully this will come with time.

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
The failure on Linux is the following:
> ==> brew linkage --test homebrew/science/gnuastro
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8

Can you try to add the jpeg dependency to see if it helps (`depends_on "jpeg" unless OS.mac?) ?

**Comment by mindriot101** [comment]
> Can you try to add the jpeg dependency to see if it helps (depends_on "jpeg" unless OS.mac?) ?

Just pushed this change into the formula, waiting for the checks to run

**Comment by mindriot101** [comment]
The current build fails the audit step, which states:

> * Stable: Please use "https://ftpmirror.gnu.org" instead of https://ftp.gnu.org/gnu/gnuastro/gnuastro-0.2.tar.gz

however when I run the audit command (`brew audit --online --new-formula ./gnuastro.rb`) it passes with no errors. If I swap the URL as per the build job output, it fails asking to switch the url back. How is this to be resolved?

Summary:

OS | Required url
-----|----
macos | https://ftp.gnu.org/gnu/gnu/gnuastro/gnuastro-0.2.tar.gz
linux | https://ftpmirror.gnu.org/gnu/gnuastro/gnuastro-0.2.tar.gz

**Comment by iMichka** [comment]
We will follow the mac OS audit. Linux lags sometimes behind; they did probably not merge the latest brew code, so that the rules are the old ones on linuxbrew.

**Comment by mindriot101** [comment]
are you happy to merge this even though the tests are failing then?

**Comment by iMichka** [comment]
@mindriot101 Don't worry about the url test on Linux. The test needs an update which will happen later. The correct test is the mac OS test.

I merged this. Thanks for your contribution!

**Pull request closed without merging**
