### PR TITLE
seqdb 0.2.1

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### Updates to existing formula: have you
- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
This happens sometimes - when you run it manually some tools return 0 but don't within brew build system. Any ideas why this would be?

```
Error: homebrew/science/seqdb: failed
<0> expected but was
<127>.
```

**Comment by apjanke** [comment]
Needs a rebase on `master`, looks like.

**Comment by iMichka** [comment]
@tseemann could you rebase this?

**Comment by iMichka** [comment]
Superseded by #5927

**Pull request closed without merging**
