### PR TITLE
Vigra 1 11 0

### PR DESCRIPTION
**Pull request by aw1621107**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
Thanks for your patch @aw1621107. It looks like the dependent formula `enblend-enfuse` needs a revision bump. Once `brew linkage` passes this should be ready to merge.

```
failed: brew linkage --test enblend-enfuse

        Missing libraries:
  /usr/local/opt/vigra/lib/libvigraimpex.5.dylib
```

**Comment by aw1621107** [comment]
Sorry, somehow missed this. What do you mean by a revision bump?

**Comment by jonchang** [comment]
Please consult the "revisions" section of the [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md). You'll need to add a `revision` line to the formula. An example can be seen in `vtk.rb`.

**Comment by jonchang** [comment]
Thanks @aw1621107!

**Pull request closed without merging**
