### PR TITLE
tbl2asn 25.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes https://github.com/Homebrew/homebrew-binary/issues/350.

### CODE REVIEW

**Comment by yzhzu** [comment]
it works, thank you very much

**Comment by ilovezfs** [comment]
You're welcome

**Comment by sjackman** [comment]
Thanks, Joe! When you merge an updated for a bioinformatics formula (or any formula with a Linuxbrew bottle) can you tag me so that I can update the Linuxbrew bottle?

**Comment by ilovezfs** [comment]
You're welcome. Will do!

**Pull request closed without merging**
