### PR TITLE
vtk: fix linking to python

### LINKED ISSUE #3401: vtk crashes when brewed python is installed
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [n/a] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

After PR #3313 (see also discussion there), which leads vtk to link to system python when it is available, makes it impossible to have vtk coexist with brewed python without segfaulting. This is true both even if one forces building from source.

Scenario 1 (everything works with system python and no brewed python):
- start with no brew python and no brew vtk
- `which python` => `/usr/bin/python`
- `brew install vtk --with-python`
- `mkdir -p /Users/lantiga/Library/Python/2.7/lib/python/site-packages`
  `echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/lantiga/Library/Python/2.7/lib/python/site-packages/homebrew.pth`
- `python -c "import vtk"`
  => Ok

Scenario 2 (brew gets the bottled version, which links against system python, even when brewed python is installed, leading to a segfault):
- start with no brew python and no vtk
- `brew install python`
- `which python` => `/usr/local/bin/python`
- `brew install vtk --with-python`
- `python -c "import vtk"` => `Fatal Python error: PyThreadState_Get: no current thread. Abort trap: 6`

Scenario 3 (building vtk from source doesn't solve the problem, as cmake picks up system python even when brewed python is available and comes first in PATH):
- start with no brew python and no vtk
- `brew install python`
- `which python` => `/usr/local/bin/python`
- `brew install vtk --with-python --build-from-source`
- `python -c "import vtk"` => `Fatal Python error: PyThreadState_Get: no current thread. Abort trap: 6`

As an aside: - `/usr/bin/python -c "import vtk"` => Ok

To confirm, in Scenario 3:
`otool -L /usr/local/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so`
gives

```
/usr/local/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so:
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkCommonCorePython27D-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkWrappingPython27Core-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkCommonCore-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtksys-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Another nuisance: anyone who got vtk 6.3 through brew --with-python in the past also got brewed python, which means that they now will see python crashing when they upgrade.

### PR DESCRIPTION
**Pull request by iMichka**
### Have you:
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### Updates to existing formula: have you
- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

This closes #3401

The patch was merged upstream. The actual patch used here is a slightly
modified version as the code had diverged between vtk 7.0.0 and the current HEAD

### CODE REVIEW

**Comment by iMichka** [comment]
Please do not merge.

The change was reverted as it introduced 2 regressions which were not caught by the VTK buildbots. I will resubmit this change once I get that sorted out with the VTK team.

**Comment by tdsmith** [comment]
:+1:; thanks for your work on this.

**Comment by iMichka** [comment]
@tdsmith one regression was fixed (I hope), it is being currently tested. I will start working on the second one but that may take time (I'll be on holidays for 3 weeks).

The patch was resubmitted here: https://gitlab.kitware.com/vtk/vtk/merge_requests/1713

As before, please do not merge this one until the real patch is merged upstream. Thanks

**Comment by iMichka** [comment]
@tdsmith @ilovezfs @dpo This is good to be reviewed now. Patch has been merged upstream.

**Comment by jonchang** [comment]
Thanks @iMichka! It's a relief to get that postinstall hack out of there. Thanks for your hard work.

**Pull request closed without merging**
