### PR TITLE
htslib 1.6

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew test --verbose circlator
==> FAILED
Testing homebrew/science/circlator
/usr/bin/sandbox-exec -f /tmp/homebrew20170929-27855-fqjrqe.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/circlator.rb --verbose
==> /usr/local/Cellar/circlator/1.5.1/bin/circlator test outdir
WARNING: SPAdes version 3.11.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
WARNING: SPAdes version 3.11.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
WARNING: SPAdes version 3.11.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
Traceback (most recent call last):
  File "/usr/local/Cellar/circlator/1.5.1/bin/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/tasks/all.py", line 169, in run
    a.run()
  File "/usr/local/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/assemble.py", line 176, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/usr/local/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/assemble.py", line 145, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.127.ylpa3air
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.117.4k9tvzrr
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.107.b7_j_2m5
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.97.wchbyth5
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.87.x6cr2j79
  /private/tmp/circlator-test-20170929-27856-1tkk4ud/outdir/OUT/03.assemble.tmp.spades.77.b6t520o9
The reason why should be in the spades.log file in each directory.
Error: homebrew/science/circlator: failed
<0> expected but was
<1>.```

**Comment by tseemann** [comment]
@ilovezfs that ain't my bug... something is wrong with circle/travis... why is it building spades and circlator, which have nothing to do whatsoever with htslib ?

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew deps --tree circlator
homebrew/science/circlator
├── python3
│   ├── readline
│   ├── sqlite
│   │   └── readline
│   ├── gdbm
│   ├── openssl
│   └── xz
├── bwa
├── mummer
├── prodigal
├── samtools
│   └── htslib
│       └── xz
└── spades
```

**Comment by tseemann** [comment]
@ilovezfs ok, @sjackman has just informed me that test-bot actually runs brew test X on all (bottled) X that depend on htslib. I was unaware of this. 

So now I have to fix bugs in circlator first?

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics circlator
install events in the last 30 days for circlator
=====================================================================================================
1 | homebrew/science/circlator                                                          | 3 | 100.00%
=====================================================================================================
Total                                                                                   | 3 |    100%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$ brew formula-analytics htslib
install events in the last 30 days for htslib
=====================================================================================================
1 | homebrew/science/htslib                                                           | 801 | 100.00%
=====================================================================================================
Total                                                                                 | 801 |    100%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$ 
```
So I'm going with: no.

**Comment by tseemann** [comment]
So how I/we proceed in this case?

(I do use `circlator` but I use the `pip` version rather than brew)

**Comment by ilovezfs** [comment]
We :see_no_evil:

**Comment by tseemann** [comment]
I'll actually have a look at `circlator` and see what I can do first.

**Comment by ilovezfs** [comment]
I've shipped this. You should rebase the samtools PR now :)

**Pull request closed without merging**
