### PR TITLE
opencascade: turn on debug mode; update to 6.9.1

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/Homebrew/homebrew-science/issues/2764 and issues reported in [deal.ii google group](https://groups.google.com/forum/?fromgroups=#!topic/dealii/UG8yiMT6VcU)

### CODE REVIEW

**Comment by dpo** [comment]
```
==> Downloading from http://www.opencascade.com/user/login?destination=system/files/occt/OCC_6.9.1_release/opencascade-6.9.1.tgz
Warning: Formula reports different SHA256: f92659ae3fb09c28233fb9178bc24fd2aab6776f6d9ea2479c3bdfe6296b873f
Downloaded to: /Library/Caches/Homebrew/opencascade-6.9.1.tgz
SHA1: 704cf7b504e74afd2fe05e9e6c78a6c78739af20
SHA256: d59c2177f32a9caa2627492df85cf7683afce8a82289d5413a2a29178c0705f1
```

**Comment by dpo** [comment]
The URL seems to be erroneous.

**Comment by davydden** [comment]
Damn it! It seems they redirect to login-page from this one as well... I will drop the update then...

**Comment by dpo** [comment]
Does that mean it's no longer possible to download the source without a login and password? That would be bad news.

**Comment by davydden** [comment]
You can download `6.9.0`, but I could not find a way to download `6.9.1` without logging... Indeed, very bad news. Why would anyone go for such distribution strategy?!.

**Comment by dpo** [comment]
The `sundials` folks did the same.

**Comment by davydden** [comment]
another one:

> The job exceeded the maxmimum time limit for jobs, and has been terminated.

**Comment by dpo** [comment]
It was successful and produced bottles though. Merging right now.

**Comment by davydden** [comment]
i guess i don't understand travis output then, or something has changed...

**Pull request closed without merging**
