### PR TITLE
opencv3: revision for jpeg

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-science/issues/6075

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is 👍 for Mac

**Comment by sjackman** [comment]
I've merged PR Linuxbrew/brew#453, which fixes this bug in Linuxbrew/brew.
I've triggered a rebuild of CircleCI.

**Comment by sjackman** [comment]
CircleCI succeeded. Once the bottle has transferred to Bintray (max 5 minutes), you can merge this PR.

**Comment by fxcoudert** [comment]
Totally fails for me 😖

```
[fx:/usr … Homebrew/Library/Taps/homebrew/homebrew-science] master ± brew pull-bottle https://github.com/Homebrew/homebrew-science/pull/6093
Start commit: 716037e696ed23b1ee2e19810d6b0f018d649c04
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-science/pull/6093.patch
==> Applying patch
Applying: opencv3: revision for jpeg
==> Patch closes issue #6093
==> Fetching patch (bottle commit)
Patch: https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-6093.patch
==> Applying patch
Applying: opencv3: revision for jpeg
Applying: opencv3: update 3.2.0_1 bottle.
==> Publishing on Bintray: opencv3 3.2.0_1
{"files":0}
==> Patch changed:
 opencv3.rb | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
==> Verifying bottles published on Bintray
Verifying bottle: opencv3-3.2.0_1.sierra.bottle.tar.gz
Error: Failed to find published opencv3 bottle at https://homebrew.bintray.com/bottles-science/opencv3-3.2.0_1.sierra.bottle.tar.gz (302 )!
Mac commit: e6e7821ed09a1be424330df9697311e19facad0c
HEAD is now at 716037e6 vtk: migrate to homebrew/core
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-science/pull/6093.patch
==> Applying patch
Applying: opencv3: revision for jpeg
==> Patch closes issue #6093
Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Homebrew/1.3.1\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.12.6)\ curl/7.54.0 --progress-bar --fail --silent --fail -o /dev/null -I https://github.com/LinuxbrewTestBot/homebrew-science/compare/Homebrew:master...pr-6093
Error: Failure while executing: /usr/local/bin/brew pull-linux --bottle https://github.com/Homebrew/homebrew-science/pull/6093
```

**Pull request closed without merging**
