### PR TITLE
anvio 2.4.0

### PR DESCRIPTION
**Pull request by ozcan**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by meren** [comment]
Dear all, 

We are about to run a rather big workshop and we would like our users to install the new version of anvi'o through Homebrew, our favorite method.

We couldn't release this version as soon as possible for technical reasons, and being only days away from the workshop I will have to make other arrangements to make sure the users have everything installed in time to avoid logistics issues.

I apologize for this question as I can imagine how busy you are, but any insight would be most welcome regarding whether I should wait for this PR to go through or start thinking about another recipe for users to follow :)

Thanks for everything, and best wishes.

**Comment by tseemann** [comment]
```
Command "/home/linuxbrew/.linuxbrew/Cellar/anvio/2.4.0/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-z371jx0f-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ddd9o265-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/anvio/2.4.0/libexec/include/site/python3.6/scipy" failed with error code 1 in /tmp/pip-z371jx0f-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/anvio/2.4.0/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-z371jx0f-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ddd9o265-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/anvio/2.4.0/libexec/include/site/python3.6/scipy" failed with error code 1 in /tmp/pip-z371jx0f-build/

```

**Comment by meren** [comment]
I don't understand this SciPy error either :/ It happens only on Linux.

**Comment by meren** [comment]
Hey Torsten,

Quick question if you have a sec: does the "build error" tag indicate that this should be fixed before the PR is merged?

The problem with SciPy and Linux is beyond our control (and is [not new](https://github.com/Homebrew/homebrew-science/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Aozcan%20)), yet it is making all the Mac users out there unable to access to the new version through Homebrew.

Any guidance is most welcome, and thanks for your time.

**Comment by ozcan** [comment]
Hello,
Unfortunately I can not get this working on linuxbrew. Instead of using numpy and scipy packages on pypi as a resource, I tried using the version available on homebrew. 
When I add `depends_on "numpy"`, It compiles but can not import that module later because it compiles with python2.
When I add `depends_on "numpy" => "with-python3"` or try from command line `brew install numpy --with-python3` it fails with `Import Error: no module named setuptools`

I am open to suggestions.
Thank you very much,

**Comment by jonchang** [comment]
Try `depends_on "openblas" unless OS.mac?`. Since `anvio` uses Python 3 it can't `depends_on "scipy"` and needs to build it in a virtualenv with pip3. On macOS `scipy` can link against Apple's Accelerate framework but on Linux no such thing exists. So you need to bring in `openblas` for your linalg library.

**Comment by ozcan** [comment]
Hi @jonchang,
Thank you very much for the help. I have added `depends_on "openblas"` and `ENV["BLAS"] = #{HOMEBREW_PREFIX}/lib`, it found required libraries and started compiling but then it failed with [ruby exception](https://gist.github.com/ozcan/b5b8f3dd8e9b5dff0c2a066c5a62ef60#file-03-pip-L1504-L1538). It looks like its related with `-R` parameter, do you have any idea what may be caused this?

Thank you very much,
Ozcan

**Comment by jonchang** [comment]
Hmm, this bug looks familiar. Can you edit `$(brew --repo)/Library/Homebrew/shims/linux/super/cc` and edit line 189-194 to look like:

```ruby
when /^-R(.+)?/
  # -R is not the correct way to pass rpaths to the linker
  val = chuzzle($1) || enum.next
  path = canonical_path(val)
  wl = "-Wl," unless mode == :ld
  args << "#{wl}-rpath=" if keep?(path)
```

and try again?

**Comment by ozcan** [comment]
Hi @jonchang,

I could finally able to compile it successfully with your helps. I will update the formula once your pull request to Linuxbrew is merged.

Thank you very much,

**Comment by sjackman** [comment]
> Since anvio uses Python 3 it can't depends_on "scipy" and needs to build it in a virtualenv with pip3. 

numpy and scipy now include support for python3 thanks to @ilovezfs 's recent PR https://github.com/Homebrew/homebrew-core/pull/16335 `numpy, scipy: make :python3 recommended`

**Comment by ozcan** [comment]
Hi @sjackman,
I have fixed the formula, now it uses homebrew version of scipy, numpy as you suggested and it compiles on linuxbrew too. Do I need to change anything else to get this pr merged?

**Comment by sjackman** [comment]
Odd that it fails on TravisCI but succeeds on CircleCI. I'm okay with ignoring this unusual failure, unless someone has the time to look into it.
```
ImportError: dynamic module does not define module export function (PyInit_multiarray)
```
https://travis-ci.org/Homebrew/homebrew-science/builds/261552230#L4240

**Comment by sjackman** [comment]
I triggered a rebuild on TravisCI just in case it was somehow a transient error, though it doesn't look like it based on the message.

**Comment by ozcan** [comment]
Hi @sjackman,
I agree, the error is very odd. I could not reproduce this on my local with clean installation of ubuntu. I do not think users will be affected from this. so If you can merge that would be good.
Thank you very much,

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Homebrew-Science, and sticking with this PR!

**Comment by meren** [comment]
Thank you very much for your guidance and help, @sjackman!

**Comment by sjackman** [comment]
Thank you for your contribution!

**Pull request closed without merging**
