### PR TITLE
octave 4.2 (rc2)

### PR DESCRIPTION
**Pull request by schoeps**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### Comments

There are several open octave issues, e.g. #4305 and #4220. This might be a good time to start debugging for 4.2.

### CODE REVIEW

**Comment by dpo** [comment]
Build fails on Sierra because of Qt5.

**Comment by schoeps** [comment]
Let's see whether octave 4.2 will be ready before Qt 5.7.1... the later is sadly on hold, as mentioned in https://github.com/Homebrew/homebrew-core/pull/2087

**Comment by ilovezfs** [comment]
You should not disable the GUI. Qt5 Sierra support will be out shortly. It's already in Qt5 head. If you're eager to ship this before that, you can just add a maximum os requirement of 10.11 if build.with? qt5. I can point you to an example if you need one.

**Comment by schoeps** [comment]
@ilovezfs Are you sure? I tried to compile the qt-dev-branches 5.6.2 and 5.7.1 but qtconnectivity, qtwebengine and qtwebview are still failing. If I disable them, then qt compiles but qscintilla2 fails (2.9.3 and 2.9.4.dev) with
```
./Qsci/qscidocument.h:56:37: note: passing argument to parameter 'qsb' here
    void display(QsciScintillaBase *qsb, const QsciDocument *from);
```
... and I thought that everything will be better with qt5 :(

**Comment by ilovezfs** [comment]
>@ilovezfs Are you sure? I tried to compile the qt-dev-branches 5.6.2 and 5.7.1 but qtconnectivity, qtwebengine and qtwebview are still failing.

CC @JakePetroules any idea why that would be?

**Comment by jakepetroules** [comment]
I probably fixed a few of those failures in one branch or another. Post the actual build errors here and we can tell you where the fixes will be present or will fix them if they haven't been already.

**Comment by schoeps** [comment]
@JakePetroules I don't mind which branch. Can you give me a link to some working `qt5.rb` (e.g. a gist)? I would like to use it for debugging `Qscintilla2.rb` and `octave.rb` on Sierra.

**Comment by ilovezfs** [comment]
@dpo shall we pull this as-is since it will fix the readline thing? Then @schoeps can make additional changes subsequently in a follow-up if needed ...

**Comment by schoeps** [comment]
it's a release candidate but it's probably becoming the final version (no errors have been mentioned so far).

**Comment by ilovezfs** [comment]
@schoeps so maybe we can pull this as-is, then you can open another one dropping the rc label and making any additional changes if needed?

**Comment by ilovezfs** [comment]
@schoeps alternatively I can just revision bump the existing formula and you can take your time on this one.

**Comment by schoeps** [comment]
@ilovezfs sounds good. In particular I hope to enable the GUI again :)

**Comment by dpo** [comment]
Yes, let's pull!

**Comment by dpo** [comment]
👍

**Comment by ilovezfs** [comment]
Done!

@schoeps you're awesome! Thanks for this upgrade. Looking forward to the next PR hehe

**Comment by houtanb** [comment]
Following the discussion on #4366 , can this commit be reverted? Octave 4.2 has not officially been released hence it's not correct to force everyone to the unstable version of Octave regardless of whether or not any bugs have been reported in it.

@schoeps I'm very glad you've done the work here and have readied Octave to be installed via homebrew. I just feel that this work should be merged once Octave 4.2.0 is officially released an not before.

**Comment by schoeps** [comment]
I understand your concerns as you can tell by the comments above. However, Octave 4.0.3 has many problems and known bugs (the list is much longer than the one for 4.2). We fixed some issues by backporting but it's getting worse and worse. There are even some unsolved riddles for example when compiling the docs. Octave 4.2rc2 is more stable than 4.0 and it's supposed to be released in September...

I started this pr to be prepared for 4.2. However, we decided to jump the gun a bit since Octave needed an update anyway. You can still keep the old one by pinning it.

We should really not put any further effort in Octave 4.0.3....

**Comment by dpo** [comment]
@houtanb Don't forget you can always build from source with `brew install -s`.

**Comment by houtanb** [comment]
@schoeps, @dpo ok, thanks for your explanation.

**Comment by jakepetroules** [comment]
@schoeps I don't know which qt5.git will fix the Sierra build, that's updated automatically but to the best of my knowledge, 5.6.2, 5.7.1, and 5.8.0 should all build on Sierra when they are released (soon). If not, we'll fix it in the subsequent patch releases.

**Comment by ilovezfs** [comment]
@schoeps I think this fixes qscintilla2 if you'd like to try it:

https://gist.github.com/ilovezfs/dff9d68264e513419e8830a804acb0b5

**Comment by ilovezfs** [comment]
@schoeps yeah octave gui built on 10.12 with Xcode 8 with the above patch :)

**Comment by schoeps** [comment]
@ilovezfs cool! which qt5 did you use?

**Comment by ilovezfs** [comment]
@schoeps I patch 5.6.1 with

http://code.qt.io/cgit/qt/qtconnectivity.git/patch/?id=462323dba4f963844e8c9911da27a0d21e4abf43

+

http://code.qt.io/cgit/qt/qtbase.git/patch/?id=77a71c32c9d19b87f79b208929e71282e8d8b5d9

+

```
diff -ru qt-everywhere-opensource-src-5.7.0.original/qtwebengine/src/3rdparty/chromium/base/mac/sdk_forward_declarations.h qt-everywhere-opensource-src-5.7.0/qtwebengine/src/3rdparty/chromium/base/mac/sdk_forward_declarations.h
--- qt-everywhere-opensource-src-5.7.0.original/qtwebengine/src/3rdparty/chromium/base/mac/sdk_forward_declarations.h	2016-05-26 21:53:47.000000000 +0800
+++ qt-everywhere-opensource-src-5.7.0/qtwebengine/src/3rdparty/chromium/base/mac/sdk_forward_declarations.h	2016-10-05 18:53:52.000000000 +0800
@@ -15,6 +15,7 @@
 #import <CoreWLAN/CoreWLAN.h>
 #import <ImageCaptureCore/ImageCaptureCore.h>
 #import <IOBluetooth/IOBluetooth.h>
+#import <CoreBluetooth/CoreBluetooth.h>
 #include <stdint.h>
 
 #include "base/base_export.h"
```

However, https://github.com/Homebrew/homebrew-core/pull/5619 seems to work too.

**Comment by ilovezfs** [comment]
@schoeps yes, I can confirm that the qt 5.7.0 PR also successfully builds `--with-qt5`

**Comment by ilovezfs** [comment]
@schoeps looks like the qscintilla2 patch is holding up under further testing by others. See https://github.com/sqlitebrowser/sqlitebrowser/issues/776

**Comment by schoeps** [comment]
@ilovefs I have also started to play around but I still fail to compile qt5 (.7 and .6). Debugging is time consuming since compilation takes more than one coffee. Thanks for sharing.

**Comment by ilovezfs** [comment]
@schoeps if you come on IRC I can help you debug if you'd like. freenode #machomebrew
(https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew)

**Comment by schoeps** [comment]
Thanks for the invitation but I managed (not sure how. I deparallized qt5 and made some other small modifications). Qscintilla build fine. Now testing octave.

**Comment by ilovezfs** [comment]
@schoeps Cool. I assume you needed to use the qscintilla2 patch, right?

**Comment by schoeps** [comment]
@ilovezfs yes, your qscintilla2 patch was necessary. I applied it to the stable 2.9.3.

**Comment by ilovezfs** [comment]
Cool. If you have time, that might be worth mentioning here: https://www.riverbankcomputing.com/pipermail/qscintilla/2016-October/001160.html

Strength in numbers …

**Comment by schoeps** [comment]
@ilovezfs mail written and GNU Octave successfully compiled with GUI. I suggest that we ship `qscintilla2.rb` with your patch once `qt5.rb` is working again. I am afraid riverbankcomputing might not be very fast.

**Comment by ilovezfs** [comment]
@schoeps Thanks! Yes, I agree about not waiting on riverbank. I wish they'd join GitHub ...

**Comment by ilovezfs** [comment]
@schoeps Qt5 5.6.1 bottle for Sierra: shipped. Xcode 8 fix for qscintilla2 and qscintilla2 Sierra bottle: shipped. So you should now have the pieces for restoring the Octave GUI. Note that in the formula you should use

`depends_on "foo" => :optional` instead of

`depends_on "foo" if build.with? "foo"`

The "with-foo" option is automatically created if you use `=> :optional` and any of your customized option descriptions at the top will be used if present. A default description is provided otherwise. Once you have `depends_on "foo" => :optional`, you can then use `if build.with? "foo"` and `if build.without? "foo"` with other `depends_on` statements for other formulae. Note that there is a gotcha with those, which is that the `depends_on "foo" => :optional` must appear in the formula before the use of `if build.with? "foo"` or `if build.without? "foo"` will be functional. So
```
depends_on "qt5" => :optional
depends_on "qscintilla2"     if build.with? "qt5"
```

is valid.

```
depends_on "qscintilla2"     if build.with? "qt5"
depends_on "qt5" => :optional
```
is not valid.

**Comment by schoeps** [comment]
Thanks! I will immediately verify that `brew install octave --with-gui` is working. However, I am considering to not reenable the GUI. Maintaining it is a mess and the qt5 version is still buggy (several retina bugs).

Regarding you comments: is there a specific reason besides beautification (which is arguable)?  I personally find the current way cleaner (particularly since most case are not one package per switch).

**Comment by ilovezfs** [comment]
> is there a specific reason besides beautification (which is arguable)

Yes. The brew options system barely understands things as it is, and when unbound options are used to wrap depends_on statements, they get hidden from several of the commands.

**Comment by schoeps** [comment]
@ilovezfs Could you compile octave with QScintilla2? It's not working for me:

```
checking for the QScintilla library for Qt 5... no
.
.
.
configure: WARNING: QScintilla library not found; disabling built-in Qt GUI editor
```

**Comment by ilovezfs** [comment]
@schoeps sure I'll give it a try.

**Comment by ilovezfs** [comment]
@schoeps BTW, if I had to guess ... did you reinstall the rev-deps of qt5 after downgrading to 5.6.1?

**Comment by ilovezfs** [comment]
@schoeps looks like it's fine
```
iMac-TMP:~ joe$ brew linkage octave
System libraries:
  /System/Library/Frameworks/AGL.framework/Versions/A/AGL
  /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
  /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
  /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
  /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libcurl.4.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/fftw/lib/libfftw3.3.dylib (fftw)
  /usr/local/opt/fftw/lib/libfftw3_threads.3.dylib (fftw)
  /usr/local/opt/fftw/lib/libfftw3f.3.dylib (fftw)
  /usr/local/opt/fftw/lib/libfftw3f_threads.3.dylib (fftw)
  /usr/local/opt/fltk/lib/libfltk.1.3.dylib (fltk)
  /usr/local/opt/fltk/lib/libfltk_gl.1.3.dylib (fltk)
  /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib (fontconfig)
  /usr/local/opt/freetype/lib/libfreetype.6.dylib (freetype)
  /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib (gcc)
  /usr/local/opt/gl2ps/lib/libgl2ps.1.dylib (gl2ps)
  /usr/local/opt/graphicsmagick/lib/libGraphicsMagick++.12.dylib (graphicsmagick)
  /usr/local/opt/graphicsmagick/lib/libGraphicsMagick.3.dylib (graphicsmagick)
  /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (homebrew/science/arpack)
  /usr/local/opt/glpk/lib/libglpk.40.dylib (homebrew/science/glpk)
  /usr/local/opt/hdf5/lib/libhdf5.10.dylib (homebrew/science/hdf5)
  /usr/local/opt/metis/lib/libmetis.dylib (homebrew/science/metis)
  /usr/local/Cellar/octave/4.2.0-rc2/lib/octave/4.2.0-rc2/liboctave.4.dylib (homebrew/science/octave)
  /usr/local/Cellar/octave/4.2.0-rc2/lib/octave/4.2.0-rc2/liboctgui.2.dylib (homebrew/science/octave)
  /usr/local/Cellar/octave/4.2.0-rc2/lib/octave/4.2.0-rc2/liboctinterp.4.dylib (homebrew/science/octave)
  /usr/local/opt/qhull/lib/libqhull.7.dylib (homebrew/science/qhull)
  /usr/local/opt/qrupdate/lib/libqrupdate.1.dylib (homebrew/science/qrupdate)
  /usr/local/opt/suite-sparse/lib/libamd.2.4.6.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libcamd.2.4.6.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libccolamd.2.9.6.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libcholmod.3.0.11.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libcolamd.2.9.6.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libcxsparse.3.1.9.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libsuitesparseconfig.4.5.3.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/suite-sparse/lib/libumfpack.5.7.6.dylib (homebrew/science/suite-sparse)
  /usr/local/opt/veclibfort/lib/libvecLibFort.dylib (homebrew/science/veclibfort)
  /usr/local/opt/libsndfile/lib/libsndfile.1.dylib (libsndfile)
  /usr/local/opt/libtool/lib/libltdl.7.dylib (libtool)
  /usr/local/opt/pcre/lib/libpcre.1.dylib (pcre)
  /usr/local/opt/portaudio/lib/libportaudio.2.dylib (portaudio)
  /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore (qt5)
  /usr/local/opt/qt5/lib/QtGui.framework/Versions/5/QtGui (qt5)
  /usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (qt5)
  /usr/local/opt/qt5/lib/QtOpenGL.framework/Versions/5/QtOpenGL (qt5)
  /usr/local/opt/qt5/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (qt5)
  /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (qt5)
  /usr/local/opt/readline/lib/libreadline.7.dylib (readline)
Possible undeclared dependencies:
  homebrew/science/metis
  libsndfile
  libtool
  portaudio
iMac-TMP:~ joe$ mdutil -t /usr/local/opt/qt5/lib/QtOpenGL.framework/Versions/5/QtOpenGL
/usr/local/Cellar/qt5/5.6.1-1/lib/QtOpenGL.framework/Versions/5/QtOpenGL
```

Do you have qt4 linked by any chance? Or perhaps didn't rebuild pyqt5?

**Comment by schoeps** [comment]
but it's not linked against QScintilla!

**Comment by ilovezfs** [comment]
Indeed... I'll look under the hood.

**Comment by ilovezfs** [comment]
@schoeps the problem is `m4/acinclude.m4` assumes
```
  ## Check for Qt libraries
  case "$qt_version" in
    4)
      QT_MODULES="QtCore QtGui QtNetwork QtOpenGL"
      octave_qscintilla_libnames=qscintilla2
    ;;
    5)
      QT_MODULES="Qt5Core Qt5Gui Qt5Network Qt5OpenGL Qt5PrintSupport"
      octave_qscintilla_libnames="qscintilla2-qt5 qt5scintilla2"
    ;;
    *)
      AC_MSG_ERROR([Unrecognized Qt version $qt_version])
    ;;
  esac
```

But qscintilla2 built with qt5 by brew still has the name
```
-r--r--r--  1 joe  admin  2458228 Oct 11 09:10 libqscintilla2.12.0.2.dylib
lrwxr-xr-x  1 joe  admin       27 Jul 25 07:13 libqscintilla2.12.0.dylib -> libqscintilla2.12.0.2.dylib
lrwxr-xr-x  1 joe  admin       27 Jul 25 07:13 libqscintilla2.12.dylib -> libqscintilla2.12.0.2.dylib
lrwxr-xr-x  1 joe  admin       27 Jul 25 07:13 libqscintilla2.dylib -> libqscintilla2.12.0.2.dylib
```

so the question is why Octave assumes it will have a different name and if that indeed should be the case. Maybe a bug in the qscintilla2 formula that undermines the legitimate assumption Octave is making?

In any case, if I fix the configure script manually, it finds it fine.

**Comment by schoeps** [comment]
@ilovezfs Shoot. I was aware of this, I think I even reported it upstream (so it might be fixed in `--HEAD`). Locally, I have symlinks from `libqsci*.dylib` to `libqsci*-qt5.dylib` but I made a typo :( 

Many linux distributions use `libqsci*-qt5.dylib` to allow parallel installation of qt4 and qt5 versions. If this kind of problem occurs more frequently, then we could create symlinks in the qscintilla2 formula...

**Comment by ilovezfs** [comment]
@schoeps No problem! Yeah it would be good to check if it's "fixed" in HEAD, since the commit that fixes it, if it exists, could go in a `patch do` block.

**Comment by schoeps** [comment]
@ilovezfs I still have issues with qscintilla. I tried to add:

`inreplace "m4/acinclude.m4", "qscintilla2-qt5 qt5scintilla2", "qscintilla2"`

What did you do?

**Comment by ilovezfs** [comment]
did you autoreconf or bootstrap after updating the m4?

**Comment by schoeps** [comment]
I did but the formula overwrote it since I played with --HEAD :) You find my test formula at https://raw.githubusercontent.com/schoeps/homebrew-science/octave/octave.rb. I already changed the dependecies to `:recommended`.

**Comment by ilovezfs** [comment]
@schoeps did you get it working with qt5 5.6.2?

**Comment by schoeps** [comment]
No, neither octave nor gnuplot but I could not spend much time on it.

**Comment by ilovezfs** [comment]
ok, I'll take a look :)

**Comment by schoeps** [comment]
You may want to start with https://raw.githubusercontent.com/schoeps/homebrew-science/octave/octave.rb for octave.

Gnuplot seemed to find qt5 with the following fragment but then it did not compile (and I had to do something else...)
 ```
   # Qt5 requires c++11 (and the other backends do not care)
    if build.with? "qt5"
      ENV.cxx11
      qt5 = Formula["qt5"]
      ENV["QT_CFLAGS"] = "-I#{qt5.opt_include} -I#{qt5.opt_include}/QtNetwork -I#{qt5.opt_include}/QtWidgets -I#{qt5.opt_include}/QtGui -I#{qt5.opt_include}/QtCore"
      ENV["QT_LIBS"] = "-F#{qt5.opt_lib} -framework QtWidgets -framework QtGui -framework QtCore"
    end
```

**Comment by ilovezfs** [comment]
OK thanks

**Comment by ilovezfs** [comment]
@schoeps OK, for gnuplot it needs to be
```
      ENV["QT_CFLAGS"]="-I#{qt5.opt_include} -I#{qt5.opt_include}/QtNetwork -I#{qt5.opt_include}/QtSvg -I#{qt5.opt_include}/QtPrintSupport -I#{qt5.opt_include}/QtWidgets -I#{qt5.opt_include}/QtGui -I#{qt5.opt_include}/QtCore"
      ENV["QT_LIBS"]="-F#{qt5.opt_lib} -framework QtNetwork -framework QtSvg -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore"
```
and then it builds.

**Comment by schoeps** [comment]
@ilovezfs yeah, I was lacking at least QtSvg, that was what I suspected, too :) Will you make a PR?

How is octave doing? Thanks!

**Comment by ilovezfs** [comment]
@schoeps you can apply this diff to config.status and then run `./config.status`.
https://gist.githubusercontent.com/ilovezfs/d7e8cbf55fcafbc6f097a7ec6e2c1ba5/raw/cdde5f49ccbb298aab85d02d6dd3d73132eb307f/gistfile1.txt and that lets it build, but that's obviously ridiculous.

Basically the Octave acinclude.m4 is quite broken, and doesn't actually let you use QT_CFLAGS and QT_LIBS instead of pkg-config even though it purports to.

**Comment by ilovezfs** [comment]
@schoeps are you on 10.11 or 10.12?

**Comment by schoeps** [comment]
@ilovezfs 10.12 (I should have waited :)

I confirm that gnuplot works. I will try Octave later (shall we propose your changes to acinclude.m4 upstream?).

**Comment by ilovezfs** [comment]
@schoeps I mentioned to @jakepetroules that a large number of downstream projects are broken by Qt's removal of the pkg-config files in https://codereview.qt-project.org/#/c/140954/. Ideally, I'd like to see those files put back rather than chasing around every downstream project that is now broken (as we discover them one by one since the Qt 5 PRs only test the preexisting builds, and don't attempt rebuilds) as a result to come up with individual fixes one by one.

We've been masking the problem by partially reverting https://codereview.qt-project.org/#/c/140954/ and I may end up restoring that hack in the next Qt5 build, but it's not really OK for Homebrew to indefinitely be reverting intentional upstream changes, which is what's been going on now for almost a year.

Note that the removal of the pkg-config files doesn't make any sense since they *are* still installed for the corresponding `.dylib` files if you do a `-no-framework` build of Qt 5. So you end up having to choose between breaking all downstream projects that require pkg-config files or breaking all downstream projects that require a framework build.

I'm not sure I want to open another Pandora's box and switch to a `-no-framework` build, since that will almost certainly break downstream applications not just downstream build systems. However, for your local testing purposes, a `-no-framework` build will work out of the box with gnuplot and octave.

I asked about 10.11 vs. 10.12 because I have a `-no-framework` 10.12 bottle built that I can upload somewhere if you want it so that you can avoid another lengthy build.

If you want to build it yourself,

```
diff --git a/Formula/qt5.rb b/Formula/qt5.rb
index acda21b..351a7b8 100644
--- a/Formula/qt5.rb
+++ b/Formula/qt5.rb
@@ -115,6 +115,7 @@ class Qt5 < Formula
       inreplace ".gitmodules", /.*status = obsolete\n((\s*)project = WebKit\.pro)/, "\\1\n\\2initrepo = true"
     end
 
+    args << "-no-framework"
     system "./configure", *args
     system "make"
     ENV.j1
```

**Comment by schoeps** [comment]
@schoeps Thanks! Don't bother, I can do one more qt build :)

However, I suggest we do the following: 
1. we ship gnuplot with your qt5 fix such that there is at least one decent plotting backend (for octave and other tools)
2. the octave GUI remains disabled for now. Octave 4.2 is delayed anyway since the Debian release schedule was relaxed. I will try to fix Octave for qt5 once the 4.2 release is close (hopefully qt5 has been stabilised until then). 

I have the feeling that I (we) recently burned a lot of time by fixing stuff that was broken again the next day.

**Comment by ilovezfs** [comment]
@schoeps I disagree. I think I'll just stick the Homebrew hack back in and ship 5.7.0. Then we can continue with the original plan.

**Comment by schoeps** [comment]
@ilovezfs You are persostent :-D Ok, if you give me a working qt5.x.x, I will keep working on a new pr for octave.

**Comment by ilovezfs** [comment]
@schoeps after doing https://github.com/Homebrew/homebrew-core/pull/4869 it's all just a walk in the park now :)

**Pull request closed without merging**
