### PR TITLE
sspace-longread: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> Warning: Formula reports different SHA256: 15db83ed199ec2a7023c3453e0d22d3eecbb99587d3d62729224504563ddda8f
Downloaded to: /Users/brew/Library/Caches/Homebrew/sspace-longread-1-1.php
SHA256: b0fa6c8c953679f347c7b55603ab9bdee3b37bb1b6518c541641243bfcf430b5

Yeah ...

**Comment by ilovezfs** [comment]
The URL "http://www.baseclear.com/download.php?file_id=1786" does not exactly scream "I am a stable URL"

**Comment by ilovezfs** [comment]
Looks like getting the tarball requires registration of some kind: https://www.baseclear.com/genomics/bioinformatics/basetools/SSPACE-longread

**Comment by iMichka** [comment]
@sjackman you initially added that one.

> In principal the basic version of SSPACE-LongRead is free for academics, upgrades are available against a small additional fee. Commercial users need in any case to pay for a license, the exact fee depends on the size of the institution (number of employees) and the type of usage (R&D or commercial services). For more information about licenses and premium packages please contact us at info@baseclear.com.

Analytics say 0 download since analytics time started (if I correctly understand of that analytics page is working ...). I would be in favour of dropping this.

**Comment by sjackman** [comment]
> I would be in favour of dropping this.

I'm fine with that.

**Comment by iMichka** [comment]
Superseded by #5083

**Pull request closed without merging**
