### PR TITLE
bcftools 1.6

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
@ilovezfs i think i made a mistake in the rebase for this one, sorry.  it seems to have `htslib.rb` in it as well.   any advice / git-fu to get me out of this mess?

**Comment by ilovezfs** [comment]
```
git rebase -i upstream/master
```
and delete the line for the one you don't want.

**Comment by ilovezfs** [comment]
oh you put it in one commit.

Then
```
git checkout origin/master -- Formula/htslib.rb
git commit --amend
```

**Comment by tseemann** [comment]
Argh, it's the same old macOS problem that we can't figure out:
```
Undefined symbols for architecture x86_64:
  "_bcf_get_format_values", referenced from:
      _process in GTsubset-ca19a5.o
  "_bcf_hdr_destroy", referenced from:
      _destroy in GTsubset-ca19a5.o
  "_bcf_hdr_dup", referenced from:
      _init in GTsubset-ca19a5.o
  "_bcf_hdr_id2int", referenced from:
      _init in GTsubset-ca19a5.o
  "_bcf_unpack", referenced from:
      _process in GTsubset-ca19a5.o
  "_hts_readlist", referenced from:
      _init in GTsubset-ca19a5.o
  "_hts_version", referenced from:
      _version in version-bc8688.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by sjackman** [comment]
The fix to the undefined symbols is here:
https://github.com/samtools/bcftools/issues/684
https://github.com/samtools/bcftools/commit/2384efbad7f55fcede759db2c7344aa2fd4e4c10#diff-b67911656ef5d18c4ae36cb6741b7965R151

**Comment by ilovezfs** [comment]
The truth is revealed!

**Comment by sjackman** [comment]
Superseded by PR https://github.com/Homebrew/homebrew-science/pull/6510

**Pull request closed without merging**
