### PR TITLE
octave 3.8.2

### PR DESCRIPTION
**Pull request by jawshooah**
https://savannah.gnu.org/bugs/?41337 was fixed in 3.8.2, so the corresponding patch is no longer needed.

### CODE REVIEW

**Comment by jawshooah** [comment]
@BrewTestBot Test this please

**Comment by tdsmith** [comment]
dynare needs to be rebuilt against new octave; can you add a commit to this PR that bumps dynare's revision?

**Comment by jawshooah** [comment]
@tdsmith Will that work?

**Comment by iml** [comment]
I'll pull this in with #2022 tomorrow or this weekend.

**Pull request closed without merging**
