### PR TITLE
OpenFST 1.5.1 (update)

### PR DESCRIPTION
**Pull request by stevenbedrick**

### CODE REVIEW

**Comment by dpo** [comment]
```
==> brew test --verbose opengrm-thrax
==> FAILED
Testing homebrew/science/opengrm-thrax
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160217-17543-1u4aqb7-0.sb /Users/brewadmin/Homebrew/Cellar/ruby187/1.8.7-p374_1/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/opengrm-thrax.rb --verbose
==> thraxmakedep example.grm
==> make
thraxcompiler --input_grammar=byte.grm --output_far=byte.far
dyld: Library not loaded: /usr/local/opt/openfst/lib/fst/libfstfar.1.dylib
  Referenced from: /usr/local/bin/thraxcompiler
  Reason: image not found
```
`opengrm-thrax` needs to be bumped.

**Comment by dpo** [comment]
See #3320

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by stevenbedrick** [comment]
Yeah, it turns out that all of the OpenFST-related things (openfst, opengrm-ngram, and opengrm-thrax) all will need to be updated simultaneously, as the new version of openfst broke some compatibility. The original authors are working on an update to opengrm-ngram that should be out sometime next week, so I'll do an omnibus pull request updating the relevant recipes once that happens.

**Comment by dpo** [comment]
Ok, thank you!

**Comment by stevenbedrick** [comment]
Somehow I managed to screw up my entire fork. I'm going to re-fork, re-make the changes, and then re-pull-request.

**Pull request closed without merging**
