### PR TITLE
graph-tool: Bump version to 2.2.44

### PR DESCRIPTION
**Pull request by count0**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
The build seems to fail pretty comprehensively on 10.9: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2452/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_Homebrew_science_graph_tool/ -- have you seen this before?

**Comment by count0** [comment]
@tdsmith No. What version of numpy was used?

**Comment by tdsmith** [comment]
1.6.2.

**Comment by tdsmith** [comment]
The build was successful on 10.10, where numpy is 1.8.0rc1.

**Comment by count0** [comment]
Yes, numpy 1.6 is way too old. There was an API change at version 1.7.

**Comment by tdsmith** [comment]
Okay, thanks!

**Comment by tdsmith** [comment]
Closed by 9e6a394. Thanks again for the PR.

**Pull request closed without merging**
