### PR TITLE
suite-sparse 4.5.3

### PR DESCRIPTION
**Pull request by syarra**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by syarra** [comment]
How do I test locally a new formula?

**Comment by dpo** [comment]
`brew install`, `brew test -v` and `brew audit --strict --online`.

**Comment by dpo** [comment]
The apparent failures are due to the dependents that need to be bumped (octave, dealii, etc.) That can be done in separate PRs.

**Comment by syarra** [comment]
When testing locally using `brew test -v suite-sparse.rb`
I get 
````
Error: Testing requires the latest version of homebrew/science/suite-sparse
````

**Comment by dpo** [comment]
You have to install first.

**Comment by dpo** [comment]
It seems it's just `octave` that will need to be rebuilt. @schoeps Is there a way to tell `octave` to link against the non-versioned `suite-sparse` libraries so it doesn't break on minor version upgrades?

**Comment by schoeps** [comment]
I will find out. However, there will be anyway a octave revision 2 soon because I want to include transfig.

**Pull request closed without merging**
