### PR TITLE
testing `depends_on :java => "1.8"`

### PR DESCRIPTION
**Pull request by randy3k**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@randy3k `depends_on :java => "1.8"` automatically passes CI on Jenkins currently because Java 8 is not installed, and an unsatisfied requirement is an automatic pass.

**Comment by randy3k** [comment]
@ilovezfs Thanks. I explained my observation in https://github.com/Homebrew/homebrew-science/pull/6393

**Comment by ilovezfs** [comment]
@randy3k in any case, the right path forward is to fix it so it works with Java 9 ;)

**Comment by randy3k** [comment]
I will report to RStudio development team or try to fix it by myself.

**Comment by ilovezfs** [comment]
:+1: thanks.

**Pull request closed without merging**
