### PR TITLE
trinity 2.2.0 [WIP]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
`brew test trinity` fails

```
❯❯❯ brew test trinity -v                    trinity
Testing homebrew/science/trinity
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160411-41053-8jgq9e.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /Users/sjackman/.homebrew/Library/Homebrew -- /Users/sjackman/.homebrew/Library/Homebrew/test.rb /Users/sjackman/.homebrew/Library/Taps/homebrew/homebrew-science/trinity.rb -v
==> /usr/local/Cellar/trinity/2.2.0/bin/Trinity --no_distributed_trinity_exec --bypass_java_version_check --seqType fq --max_memory 1G --SS_lib_type RF --left reads.left.fq.gz,reads2.left.fq.gz --right reads.right.fq.gz,reads2.right.fq.gz
Trinity version: v2.2.0
-ERROR: couldn't parse latest version tag info from github: {
  "message": "API rate limit exceeded for 142.103.205.100. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}


Monday, April 11, 2016: 16:53:09	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/util/support_scripts/ExitTester.jar 0
Monday, April 11, 2016: 16:53:09	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/util/support_scripts/ExitTester.jar 1
Monday, April 11, 2016: 16:53:09	CMD: mkdir -p /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir
Monday, April 11, 2016: 16:53:09	CMD: mkdir -p /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

Converting input files. (in parallel)Monday, April 11, 2016: 16:53:09	CMD: gunzip -c /private/tmp/trinity20160411-41054-ofnmpf/reads.left.fq.gz | /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/fastool/fastool --rev --append /1 --to-fasta >> left.fa 2> /private/tmp/trinity20160411-41054-ofnmpf/reads.left.fq.gz.readcount 
Monday, April 11, 2016: 16:53:09	CMD: gunzip -c /private/tmp/trinity20160411-41054-ofnmpf/reads.right.fq.gz | /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/fastool/fastool --append /2 --to-fasta >> right.fa 2> /private/tmp/trinity20160411-41054-ofnmpf/reads.right.fq.gz.readcount 
-conversion of 30575 from FQ to FA format succeeded.
Monday, April 11, 2016: 16:53:09	CMD: gunzip -c /private/tmp/trinity20160411-41054-ofnmpf/reads2.left.fq.gz | /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/fastool/fastool --rev --append /1 --to-fasta >> left.fa 2> /private/tmp/trinity20160411-41054-ofnmpf/reads2.left.fq.gz.readcount 
-conversion of 30575 from FQ to FA format succeeded.
-conversion of 30575 from FQ to FA format succeeded.
Monday, April 11, 2016: 16:53:09	CMD: gunzip -c /private/tmp/trinity20160411-41054-ofnmpf/reads2.right.fq.gz | /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/fastool/fastool --append /2 --to-fasta >> right.fa 2> /private/tmp/trinity20160411-41054-ofnmpf/reads2.right.fq.gz.readcount 
-conversion of 30575 from FQ to FA format succeeded.
Monday, April 11, 2016: 16:53:10	CMD: touch left.fa.ok right.fa.ok
Monday, April 11, 2016: 16:53:10	CMD: cat left.fa right.fa > both.fa
Monday, April 11, 2016: 16:53:10	CMD: touch both.fa.ok
-------------------------------------------
----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

* Running CMD: /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/jellyfish/bin/jellyfish count -t 2 -m 25 -s 151378888  both.fa
* Running CMD: /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/jellyfish/bin/jellyfish dump -L 1 mer_counts.jf > jellyfish.kmers.fa
* Running CMD: /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/trinity-plugins/jellyfish/bin/jellyfish histo -t 2 -o jellyfish.kmers.fa.histo mer_counts.jf
----------------------------------------------
--------------- Inchworm ---------------------
-- (Linear contig construction from k-mers) --
----------------------------------------------

* Running CMD: /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/Inchworm/bin//inchworm --kmers jellyfish.kmers.fa --run_inchworm -K 25 -L 25 --monitor 1   --num_threads 2  --PARALLEL_IWORM  > /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/inchworm.K25.L25.fa.tmp
* Running CMD: mv /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/inchworm.K25.L25.fa.tmp /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/inchworm.K25.L25.fa
Monday, April 11, 2016: 16:53:17	CMD: touch /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/inchworm.K25.L25.fa.finished
* Running CMD: /Users/sjackman/.homebrew/Cellar/trinity/2.2.0/util/misc/fasta_filter_by_min_length.pl /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/inchworm.K25.L25.fa 100 > /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100
* Running CMD: bowtie-build -q /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100 /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100
* Running CMD: bash -c " set -o pipefail; bowtie -a -m 20 --best --strata --threads 2  --chunkmbs 512 -q -S -f /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100 both.fa  | samtools view -@ 2 -F4 -Sb - | samtools sort -m 268435456 -@ 2 -no - - > /private/tmp/trinity20160411-41054-ofnmpf/trinity_out_dir/chrysalis/iworm.bowtie.nameSorted.bam" 
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 339 sequences.
# reads processed: 122300
# reads with at least one reported alignment: 106970 (87.47%)
# reads that failed to align: 15330 (12.53%)
Reported 107198 alignments to 1 output stream(s)
[sam_read1] reference '' is recognized as '*'.
[main_samview] truncated file.
Trinity run failed. Must investigate error above.
Error: homebrew/science/trinity: failed
Failed executing: /usr/local/Cellar/trinity/2.2.0/bin/Trinity --no_distributed_trinity_exec --bypass_java_version_check --seqType fq --max_memory 1G --SS_lib_type RF --left reads.left.fq.gz,reads2.left.fq.gz --right reads.right.fq.gz,reads2.right.fq.gz
/Users/sjackman/.homebrew/Library/Homebrew/formula.rb:1481:in `block in system'
/Users/sjackman/.homebrew/Library/Homebrew/formula.rb:1418:in `open'
/Users/sjackman/.homebrew/Library/Homebrew/formula.rb:1418:in `system'
/Users/sjackman/.homebrew/Library/Taps/homebrew/homebrew-science/trinity.rb:61:in `block in <class:Trinity>'
/Users/sjackman/.homebrew/Library/Homebrew/formula.rb:1327:in `block in run_test'
/Users/sjackman/.homebrew/Library/Homebrew/extend/fileutils.rb:36:in `mktemp'
/Users/sjackman/.homebrew/Library/Homebrew/formula.rb:1323:in `run_test'
/Users/sjackman/.homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/Users/sjackman/.homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by sjackman** [comment]
@iml @tseemann @saketkc Any thoughts on this `trinity` / `bowtie` / `samtools` error?
```
[sam_read1] reference '' is recognized as '*'.
[main_samview] truncated file.
```

**Comment by sjackman** [comment]
See #3527

**Comment by ilovezfs** [comment]
@sjackman @iml @tseemann @saketkc I managed to track the test failure down to bad output from `bowtie`, which is fixed by building with gcc, applying [this patch](https://github.com/BenLangmead/bowtie/pull/25), or both: https://github.com/Homebrew/homebrew-science/pull/3540

I also removed the bundled dependencies for the ones that exist already in the tap. One of them was `samtools`, which was causing the conflict error, so no need for the `conflict_with` after all.

**Comment by sjackman** [comment]
Thanks, Joe!

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-science/pull/3547

**Pull request closed without merging**
