### PR TITLE
cmor: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by jonchang** [comment]
Build failed due to sha256 mismatch. It looks like upstream retagged a release and it looks like it was just a change to the README?

**Comment by iMichka** [comment]
Reported upstream, waiting for an answer.

**Comment by iMichka** [comment]
Tag was moved. I updated the sha256.

**Comment by iMichka** [comment]
Linux fails with:
> fatal: Not a git repository (or any of the parent directories): .git
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
TARGET: linux-gnu
checking for gcc... gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/cmor-20170512-64052-fr3rvi/cmor-CMOR-3.2.3':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by iMichka** [comment]
Ignoring:
> * Dependency netcdf should not use option with-fortran

**Pull request closed without merging**
