### PR TITLE
rate4site 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by benjaminjack**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

A tool for calculating site-specific evolutionary rates from an amino-acid multiple sequence alignment.

### CODE REVIEW

**Comment by tdsmith** [comment]
I am concerned that the Terms of Use do not give us permission to redistribute this software: http://www.tau.ac.il/~itaymay/cp/terms.html

**Comment by benjaminjack** [comment]
Is it possible to distribute it as build-only, without precompiled bottles? I don't know what homebrew's policies on these things are.

**Comment by benjaminjack** [comment]
The license included with the source code itself is the GNU GPL. It shouldn't be a problem to redistribute. See the file named "COPYING" in this source code tarball:

ftp://rostlab.org/rate4site/rate4site-3.0.0.tar.gz

**Comment by tdsmith** [comment]
Ugh, hilarious.

The formula looks great in any case! Nice test.

**Comment by benjaminjack** [comment]
So what is the policy in the case of conflicting licenses like this? In other words, will this eventually be merged?

**Comment by tdsmith** [comment]
I wanted to see if Shaun would comment but I'll go ahead and pull; thanks for following up.

**Pull request closed without merging**
