### PR TITLE
nextflow 0.15.3

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by dpo** [comment]
Seems like the `post-install` is trying to create `~/.nextflow`, which Homebrew isn't allowing:
```
mkdir: /Users/brew/Jenkins/science/version/mavericks/home/.nextflow/framework/0.15.3: Operation not permitted
```

**Comment by pditommaso** [comment]
Is this a new constraint? This formulate always worded in this way in the past.

When launching nextflow the very first time it will download some missing dependencies. So I guess won't solve the problem just pre-creating that folder.  

Any clue how it could be managed by Homebrew?

**Comment by tdsmith** [comment]
It's new enforcement of an old policy. Ideally, nextflow could be convinced to look for these downloads in the Cellar, or else users will just have to deal with this on first run.

**Comment by pditommaso** [comment]
I think the latter it the best option, but as a consequence of that it could no longer be possible to execute as part of [the embedded test](https://github.com/Homebrew/homebrew-science/pull/2688/files#diff-ad1708add11038ef59eb319d119c1183L31)

**Comment by tdsmith** [comment]
$HOME is set to a temporary path during test, so the test might be a little slower but it should be fine if the downloaded resources aren't huge.

**Comment by pditommaso** [comment]
@tdsmith That would work. But if so is trying the following create this directory: 

    /Users/brew/Jenkins/science/version/mavericks/home/.nextflow/framework/0.15.3

And not in the temporary `HOME` folder ?

**Comment by tdsmith** [comment]
That is not a child of the temporary HOME; I guess HOME isn't overridden during post-install.

**Comment by pditommaso** [comment]
@tdsmith I see. Thus it should be enough to remove the `post-install` because it will download the required deps automatically in the `test` step. 

I will give it a try. Tx

**Comment by pditommaso** [comment]
@tdsmith OK, fixed. Thanks!

**Pull request closed without merging**
