### PR TITLE
viennarna 2.3.1

### PR DESCRIPTION
**Pull request by twogee**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by twogee** [comment]
Closes issue #4854 
Thanks for guidance!

**Comment by iMichka** [comment]
The mac build failed with:

>  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/viennarna/lib/python2.7/site-packages/_RNA.so

This is quite known problem. Here is some documentation.
http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

The linking flags need to be adapted somewhere in the upstream code (they need to be ```-undefined dynamic_lookup```, the link I gave explains it all).

Do you feel up to report this upstream and try to get their code updated?

**Comment by twogee** [comment]
I will give it a try.

**Comment by RaumZeit** [comment]
This is ViennaRNA Package upstream @ViennaRNA
We just released version 2.3.2 of the ViennaRNA Package about a minute ago. Unfortunately just before I got note of this particular problem. I've already created a patch that will take care of passing
```
-undefined dynamic_lookup
```
as linker flags for the python extension. But it will only be officially available with the next version.
I suggest that for the time being you could patch interfaces/Python/Makefile replacing the line
```
_RNA_la_LDFLAGS = -avoid-version -module -shared -export-dynamic -shrext $(PYTHON2_SO) $(PYTHON2_LDFLAGS)
```
by something like
```
_RNA_la_LDFLAGS = -avoid-version -module -bundle -undefined dynamic_lookup -export-dynamic -shrext $(PYTHON2_SO) 
```
This should do the trick...

**Comment by iMichka** [comment]
@RaumZeit Thanks for the reactivity. We can live with a patch for some time, it's not a problem.

The ultimate test will be to run (to check if the solution works):
> otool -L /usr/local/opt/viennarna/lib/python2.7/site-packages/_RNA.so

There should be no mention of the Python library path in the output.

If this is OK, @twogee, you will need to create a new pull request containing the patch here:
https://github.com/Homebrew/formula-patches
Just create a new folder in that project and add the diff in a .patch file.

Once the patch is merged, you can update your formula by adding a patch block. See the patch documentation here: http://docs.brew.sh/Formula-Cookbook.html

Don't hesitate if you have question, I can guide you through this but it should be pretty easy.

**Comment by twogee** [comment]
Sorry about the break; I'll try 2.3.3, see #4917

**Comment by iMichka** [comment]
No problem. Thanks. We can continue the discussion in the other pull request. Closing here.

**Pull request closed without merging**
