### PR TITLE
vsearch 1.8.1 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
The aim of this project is to create an alternative to the USEARCH tool developed by Robert C. Edgar (2010). The new tool should:

have open source code with an appropriate open source license
be free of charge, gratis
have a 64-bit design that handles very large databases and much more than 4GB of memory
be as accurate or more accurate than usearch
be as fast or faster than usearch

### CODE REVIEW

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by audy** [comment]
First build error on `brew audit` was due to GitHub rate limiting ([log](https://travis-ci.org/Homebrew/homebrew-science/jobs/88885898#L300)). Try rebuilding?

**Comment by tseemann** [comment]
@audy any idea what went wrong this time?

**Comment by audy** [comment]
@tseemann did the build finish? I still see it in queue.

**Comment by audy** [comment]
yay!

**Pull request closed without merging**
