### PR TITLE
prinseq 0.20.4 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by tseemann** [comment]
I'm not sure why i'm getting checksum mismatches.

```
   ==> Fetching prinseq from homebrew/science
==> Downloading https://downloads.sourceforge.net/projects/prinseq/files/standalone/prinseq-lite-0.20.4.tar.gz
==> Downloading from https://sourceforge.net/publish/
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://sourceforge.net/publish/ -C 0 -o /Users/brew/Library/Caches/Homebrew/prinseq-0.20.4.tar.gz.incomplete --silent
Downloaded to: /Users/brew/Library/Caches/Homebrew/prinseq-0.20.4.tar.gz
SHA256: b1037c2728062ba6de1035d234e05e1d3f7b3190f5212a479c8b3200cc728202
==> Verifying prinseq-0.20.4.tar.gz checksum
==> Retrying download
==> Downloading https://downloads.sourceforge.net/projects/prinseq/files/standalone/prinseq-lite-0.20.4.tar.gz
==> Downloading from https://sourceforge.net/publish/
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://sourceforge.net/publish/ -C 0 -o /Users/brew/Library/Caches/Homebrew/prinseq-0.20.4.tar.gz.incomplete --silent
Warning: Formula reports different SHA256: 5ce599136a6db70289526c80693e46e136a90861ba00cf2a63f16e0a9e9b1c6c
Downloaded to: /Users/brew/Library/Caches/Homebrew/prinseq-0.20.4.tar.gz
SHA256: 88735402171229ff12886d85c8f166d43cde195166f1adf47b17c89c825c4fca
==> Verifying prinseq-0.20.4.tar.gz checksum
```

**Comment by ilovezfs** [comment]
because the URL is wrong. You want https://downloads.sourceforge.net/project/prinseq/standalone/prinseq-lite-0.20.4.tar.gz and 9b5e0dce3b7f02f09e1cc7e8a2dd77c0b133e5e35529d570ee901f53ebfeb56f

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@tseemann 

On small audit failure on mac OS. If you rebase and push, we will be able to see the Linux builds too.

> homebrew/science/prinseq:
  * C: 3: col 3: http://prinseq.sourceforge.net/ should be `https://prinseq.sourceforge.io/`

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
