### PR TITLE
alembic 1.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@ilovezfs sha256 has changed. Don't know how, this is a tar.gz directly from GitHub.
Maybe they moved the git tag to a different commit?

**Comment by iMichka** [comment]
Ok so after a discussion here https://github.com/alembic/alembic/issues/104, we need:

- the new sha256
- a fails with HDF5 + MPI
- comment out the make test step. I tested it locally and it works. Please add a comment somewhere that the hdf5 option can be dropped in the next version and the make test step added back.

HDF5 is used for their legacy file format. It is useful if some people want to still convert their old files to the new format. But it is not needed anymore.

Once this is merged, the formula will be ready for hdf5 1.10.0.

**Comment by ilovezfs** [comment]
@iMichka PR refreshed.

**Comment by iMichka** [comment]
@ilovezfs Cool, I didn't realize it just missed the mpi flags. Thanks.

**Pull request closed without merging**
