### PR TITLE
itensor 2.1.1

### PR DESCRIPTION
**Pull request by kyungminlee**
I've also written a new test to check linear algebra library linkage.

### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [X] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

### CODE REVIEW

**Comment by ilovezfs** [comment]
This should be noted as the latest release: https://github.com/ITensor/ITensor/releases/latest

**Comment by kyungminlee** [comment]
I got confused for a minute. Version 2.1.1 is the latest version, according to the [ITensor webpage](http://itensor.org/index.html) and [Changelog](http://itensor.org/docs.cgi?page=changelog#v2.1.1). It seems that the maintainer did not update the releases on the repo for some reason.

**Comment by kyungminlee** [comment]
I got confused for a minute. Yes I agree. v2.1.1 should be marked as the latest release.

**Comment by jonchang** [comment]
Thanks @kyungminlee! I've merged this update.

**Pull request closed without merging**
