### PR TITLE
links 1.1: New formula

### PR DESCRIPTION
**Pull request by warrenlr**
initial links.rb formula

### CODE REVIEW

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by sjackman** [comment]
@warrenlr The filename `links.rb` conflicts with [`links.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/links.rb) of the [Links](http://links.twibright.com/) web browser. It'll need a different name. Thoughts? `links-scaffolder.rb` perhaps?

**Comment by sjackman** [comment]
Here's an updated formula. When you update this pull request, please make these changes.

```ruby
class LinksScaffolder < Formula
  homepage "http://www.bcgsc.ca/platform/bioinfo/software/links"
  # doi "10.1101/016519"
  # tag "bioinformatics"

  url "http://www.bcgsc.ca/platform/bioinfo/software/links/releases/1.1/links_v1-1.tar.gz"
  version "1.1"
  sha1 "b817bba5b1087bbbadcc151d213312e3cd1867eb"

  def install
    bin.install "LINKS"
    chmod 0644, "LINKS-readme.txt"
    doc.install "LINKS-readme.txt"
    prefix.install "test"
  end

  test do
    assert_match "LINKS", shell_output("#{bin}/LINKS")
  end
end
```

```diff
diff --git a/links-scaffolder.rb b/links-scaffolder.rb
index 1a2851b..fc1a034 100644
--- a/links-scaffolder.rb
+++ b/links-scaffolder.rb
@@ -1,7 +1,7 @@
-class Links < Formula
+class LinksScaffolder < Formula
   homepage "http://www.bcgsc.ca/platform/bioinfo/software/links"
-  #doi "10.1101/016519"
-  #tag "bioinformatics"
+  # doi "10.1101/016519"
+  # tag "bioinformatics"
 
   url "http://www.bcgsc.ca/platform/bioinfo/software/links/releases/1.1/links_v1-1.tar.gz"
   version "1.1"
@@ -9,11 +9,12 @@ class Links < Formula
 
   def install
     bin.install "LINKS"
+    chmod 0644, "LINKS-readme.txt"
     doc.install "LINKS-readme.txt"
     prefix.install "test"
   end
 
   test do
-    system "LINKS |grep LINKS"
+    assert_match "LINKS", shell_output("#{bin}/LINKS")
   end
 end
```

**Comment by warrenlr** [comment]
@sjackman not too sure how to edit pull request

**Comment by sjackman** [comment]
Make the changes. Use `git add links.rb` to stage the changes. Use `git mv links.rb links-scaffolder.rb` to rename the file. Use `git commit --amend` to modify the commit. Use `git show` to check that the commit looks good.  Use `git push --force` to update the pull request.

**Comment by warrenlr** [comment]
@sjackman:
Username for 'https://github.com': rwarren@bcgsc.ca
Password for 'https://rwarren@bcgsc.ca@github.com': 
remote: Permission to Homebrew/homebrew-science.git denied to rwarren@bcgsc.ca.
fatal: unable to access 'https://github.com/Homebrew/homebrew-science.git/': The requested URL returned error: 403

I have insufficient privileges

**Comment by sjackman** [comment]
You can't push directly to Homebrew-science, but you can push to [your fork of it](https://github.com/warrenlr/homebrew-science/commit/818903f83744adf217966e1ab4360ad74a37fa1b). Your default remote (usually called `origin`) is homebrew-science. Do you have any other remotes set up? You can list them using `git remote -v`. You can add your fork as a remote named `warenlr` like so:
`git remote add warenlr https://github.com/warrenlr/homebrew-science.git`

**Comment by sjackman** [comment]
Then use `git push warrenlr warrenlr-patch-1 --force` to update your patch, which is named `warrenlr-patch-1`.

**Comment by sjackman** [comment]
Duplicate of #2015

**Pull request closed without merging**
