### PR TITLE
pymol: Depends on freeglut numpy for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI
```
==> Installing homebrew/science/pymol dependency: python
Error: /home/linuxbrew/.linuxbrew/opt/gpatch not present or broken
Please reinstall gpatch. Sorry :(
==> FAILED
```
https://travis-ci.org/Homebrew/homebrew-science/builds/200408355#L3488

That's a weird error. `brew` fetches `gpatch` but then doesn't install it!?
https://travis-ci.org/Homebrew/homebrew-science/builds/200408355#L826
https://travis-ci.org/Homebrew/homebrew-science/builds/200408355#L879

Looks like the requirements are being properly fulfilled.

**Comment by sjackman** [comment]
Possibly some crazy interaction between `pymol`
`depends_on "python" => "with-tcl-tk"`
and `python`
`if build.with? "tcl-tk"; patch do`

**Comment by sjackman** [comment]
```
==> python -s setup.py install --bundled-pmw --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/pymol/1.8.2.1/libexec/bin --install-lib=/home/linuxbrew/.linuxbrew/Cellar/pymol/1.8.2.1/libexec/lib/python2.7/site-packages
.
Last 150 lines from /home/travis/.cache/Homebrew/Logs/pymol/01.python:
2017-02-11 00:22:49 +0000
python
-s
setup.py
install
--bundled-pmw
--install-scripts=/home/linuxbrew/.linuxbrew/Cellar/pymol/1.8.2.1/libexec/bin
--install-lib=/home/linuxbrew/.linuxbrew/Cellar/pymol/1.8.2.1/libexec/lib/python2.7/site-packages
fatal: Not a git repository (or any of the parent directories): .git
svn: E155007: '/tmp/pymol-20170211-16135-pqy6qp/pymol' is not a working copy
numpy not available
Traceback (most recent call last):
  File "setup.py", line 266, in <module>
    glut = posix_find_lib(['glut', 'freeglut'], lib_dirs)
  File "setup.py", line 49, in posix_find_lib
    raise IOError('could not find any of ' + str(names))
IOError: could not find any of ['glut', 'freeglut']
```
https://travis-ci.org/Homebrew/homebrew-science/builds/200539307#L3677

```
numpy not available
IOError: could not find any of ['glut', 'freeglut']
```

**Comment by sjackman** [comment]
TravisCI
```
g++-4.8: error: unrecognized command line option ‘-Qunused-arguments’
/usr/bin/g++-4.8 -pthread -Os -w -pipe -march=core2 -Qunused-arguments -isystem/home/linuxbrew/.linuxbrew/include -std=c++0x -fPIC -D_PYMOL_LIBPNG -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -D_PYMOL_FREETYPE -DNO_MMLIBS -D_PYMOL_NUMPY -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/include -Icontrib/uiuc/plugins/molfile_plugin/src -I/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/numpy/core/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/tcl-tk/include -I/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/include/python2.7 -c layer1/P.cpp -o build/temp.linux-x86_64-2.7/layer1/P.o -Wno-write-strings -Wno-unused-function -Wno-char-subscripts -ffast-math -funroll-loops -O3 -fcommon
error: command '/usr/bin/g++-4.8' failed with exit status 1
g++-4.8: error: unrecognized command line option ‘-Qunused-arguments’
```
https://travis-ci.org/Homebrew/homebrew-science/builds/200544099#L4145

**Comment by iMichka** [comment]
@sjackman I did not see your PR, I opened another one here: https://github.com/Homebrew/homebrew-science/pull/5483

I can take over some of your changes, and try to investigate this.
We may need to have python built with tcl-tk by default anyway, per #5470

**Comment by sjackman** [comment]
Great. Thanks, Michka.
Superseded by #5483.

**Pull request closed without merging**
