### PR TITLE
samtools 1.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
```
configure: error: zlib development files not found
```
```ruby
unless OS.mac?
  depends_on "ncurses"
  depends_on "zlib"
end
```

**Comment by sjackman** [comment]
The two errors on Linux are not caused by this PR.

```
brew install gmap-gsnap
make check
# FAIL:  2
```
https://travis-ci.org/Homebrew/homebrew-science/builds/230120405#L5020

```
==> brew linkage --test mir-prefer
Unwanted system libraries:
  libncurses.so.5
  libtinfo.so.5
==> FAILED
```
https://travis-ci.org/Homebrew/homebrew-science/builds/230120405#L7311

**Comment by sjackman** [comment]
On macOS
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/234/version=sierra/

`brew test circlator` fails.
```
circlator.assemble.Error: Error running SPAdes.
```

`brew linkage --test trinity` fails.
```
Missing libraries:
  /usr/local/lib/gcc/6/libgcc_s.1.dylib
  /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  /usr/local/opt/gcc/lib/gcc/6/libstdc++.6.dylib
```

These both succeed on Linux.

**Comment by ilovezfs** [comment]
The `circlator` error is actually a `spades` error:
```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/spades/3.10.1/bin/spades
  Reason: image not found
```
So looks like `spades` needs a revision bump.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-science/pull/5616

**Comment by ilovezfs** [comment]
@sjackman any idea what the Linux failure here is?

**Comment by sjackman** [comment]
See above https://github.com/Homebrew/homebrew-science/pull/5610#issuecomment-300021702

`gmap-gsnap`: `make check` fails. I believe that issue has come up before. We could troubleshoot ourselves or contact the upstream author. Likely not related to this PR.

`mir-prefer` source contains precompiled binaries. Not related to this PR.

**Comment by sjackman** [comment]
I created a PR to add `ncurses@5` to Linuxbrew: https://github.com/Linuxbrew/homebrew-core/pull/2625

**Comment by ilovezfs** [comment]
@sjackman 

>See above #5610 (comment)

@jonchang already addressed that in https://github.com/Homebrew/homebrew-science/pull/5610/commits/59906c7e402b57963c29b512837f70be46cbe4dd

**Comment by sjackman** [comment]
Except for the two unrelated failures of `kollector` and `mir-prefer`, this PR is succeeding on Linux, yes?

**Comment by sjackman** [comment]
I've opened PR #5624 to fix the issue with `mir-prefer`.

**Comment by sjackman** [comment]
I've merged PR #5624, which fixes the issue with `mir-prefer`.

**Comment by sjackman** [comment]
The `mir-prefer` issue is resolved. That's good. The `gmap-gsnap` `make check` failure remains.

**Comment by ilovezfs** [comment]
Shipped despite the gmap-gsnap issue :sob:

**Comment by sjackman** [comment]
Argh. There's an open PR to fix the `gmap-gsnap` issue. `make check` needs `ENV.deparallelize`
Original issue: https://github.com/Homebrew/homebrew-science/pull/5110
PR https://github.com/Homebrew/homebrew-science/pull/5435

**Pull request closed without merging**
