### PR TITLE
blasr: build with MPI if HDF5 was.

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@sjackman @tseemann Is this reasonable? I'm getting undefined MPI symbols when I try to build `blasr` because my `hdf5` was built `--with-mpi`.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Hmm. I believe the Homebrew policy is that the default options of a package should not depend on the state of the system. I think this should instead print an error message if `hdf5` was built with `mpi` but `blasr` is not being built with `mpi`.

`blasr` itself does not use `hdf5` at all, does it? It's frustrating that the build options of a package that uses `hdf5` should change depending on how `hdf5` was built.

**Comment by sjackman** [comment]
I'm :-1: on this particular patch, because I don't think the `blasr` formula should know anything about `mpi`, but the problem does need to be addressed.

**Comment by iMichka** [comment]
It seems that there is no consensus on this for moment. I do not know if it's still open for discussion, but I will just close this PR for the time being, to clean up a little bit the PR list.

BTW blasr can't be build anymore, see #4254

**Pull request closed without merging**
