### PR TITLE
netcdf: fixes Homebrew/homebrew-science#4843

### PR DESCRIPTION
**Pull request by lesserwhirls**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?

This PR does not introduce any new errors.

- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Hi. Thanks for your contribution. You will need to bump the revision to 1, so that new bottles are built.

**Comment by lesserwhirls** [comment]
Sorry about forgetting that - I didn't see a revision value in the original ruby file, so I was a little confused.

**Comment by ilovezfs** [comment]
depending on curl => "with-openssl" is not really an acceptable practice except under extraordinary circumstances. are we sure there's no other solutions here?

**Comment by lesserwhirls** [comment]
It looks like it is possible to import the certificates into the keychain app, and `SecureTransport` will use it. The particular certs I was using when I found this issue expire every three days, which is a little bit of a pain. There appears to be a bug that's been reported to Apple dealing with using certs specified by a path (as opposed to certs in the keychain app), but I am not sure what the status is:

https://github.com/curl/curl/issues/976#issuecomment-241797370

@petemoore, have you had any correspondence with Apple regarding the `SecureTransport` bug report you made?

**Comment by petemoore** [comment]
Hi @lesserwhirls,

I've been advised by Apple Engineering that my bug (27968953) was a duplicate of bug 27968221, and my bug was promptly closed by Apple on 8 Sep 2016. Unfortunately, I do not currently have access to bug 27968221, so I've no idea what the status is. :/

Today I have asked for access to bug 27968221 from my closed bug 27968953. I'll let you know if I get it. Otherwise, you might be able to request access to these two bugs too.

I could not see obvious contact information to reach Apple to discuss the matter directly.

**Comment by petemoore** [comment]
For reference, the contents of bug 27968953  that I raised:

## Summary
When curl is built with OpenSSL, the SSL_CERT_FILE environment variable when set is interpreted as the CA certificate file to use. However, the curl that Apple ships is built with SecureTransport rather than OpenSSL transport, yet still attempts to use this SSL_CERT_FILE, which results in failure for the command to complete.

This causes problems when a system has more than one version of curl installed, and one requires a certificate bundle, and therefore e.g. sets the SSL_CERT_FILE environment variable e.g. in the user profile. The native version of curl on OS X then consistently fails.

I raised this bug originally against curl in https://github.com/curl/curl/issues/976 but it seems this might be a problem with SecureTransport instead.

## Steps to Reproduce
1. curl -L https://curl.haxx.se/ca/cacert.pem > ~/cacert.pem

2a. curl --cacert ~/cacert.pem -I https://storage.googleapis.com/golang/go1.7.src.tar.gz
 * OR *
2b. SSL_CERT_FILE=~/cacert.pem /usr/bin/curl -I https://storage.googleapis.com/golang/go1.7.src.tar.gz


## Expected Results
Result from step 2a/2b should instead be:
```
HTTP/1.1 200 OK
X-GUploader-UploadID: AEnB2UplWlz4rniGH-7K0_WwhXYZci9pdEYGrZDSyEwTLv9X3rgeLfEDM2NLPZdQ_9slzjYOD8jaRDtNBDnk3Onswn0M05lVIA
Expires: Tue, 23 Aug 2016 09:52:59 GMT
Date: Tue, 23 Aug 2016 08:52:59 GMT
Cache-Control: public, max-age=3600
Last-Modified: Mon, 15 Aug 2016 23:20:30 GMT
ETag: "a30c3bd1a7fcc6a48acfb74936a19b4c"
x-goog-generation: 1471303230615000
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 14091954
Content-Type: application/x-gzip
x-goog-hash: crc32c=B1onUw==
x-goog-hash: md5=oww70af8xqSKz7dJNqGbTA==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 14091954
Server: UploadServer
Alternate-Protocol: 443:quic
Alt-Svc: quic=":443"; ma=2592000; v="35,34,33,32,31,30"
```
## Actual Results
Result from step 2a/2b is actually:
```
curl: (51) SSL: certificate verification failed (result: 5)
```
## Version
Apple OS X El Capitan Version 10.11.6
```
pmoore@Petes-iMac:~ $ uname -a
Darwin Petes-iMac.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

**Comment by lesserwhirls** [comment]
Just a note on this PR: adding the certificates to the KeyChain app no longer works (not sure why). It looks like the only option, at this point, for using netCDF with authorization/authentication is to make sure curl is built with openssl support.

**Comment by iMichka** [comment]
I am pretty new to the openssl problems on mac, I hope I will be clear and I don't mixup things here, but we decided that we will not accept this PR.

We will not add the `with-openssl` flag. For multiple reasons.
- We prefer to use the curl provided by mac. The curl provided by homebrew is keg-only, so to be used only in last resort or only if you really know what you are doing.
- We want to reduce the numbers of optional flags that get called like this to reduce rebuild times. There is even a buildbot check for this now which will complain about you doing this.

Your options here are:
- let the netcdf devs add support for `SecureTransport`?
- tweak you certificates configuration? Get the bug fixed in Apple's curl?
- carry that patch around and rebuild your stack with it, but this is up to you to keep this working for later

**Pull request closed without merging**
