### PR TITLE
SuperLU_dist: Explict MPI compilers, tests.

### PR DESCRIPTION
**Pull request by dpo**
Also remove unnecessary "require formula".

This makes it possible to build SuperLU_dist against MPICH.

### CODE REVIEW

**Comment by dpo** [comment]
@saketkc Travis is again trying to build `gcc`. Any idea why? Also it looks like Linuxbrew will pick up an existing install of MPI, so we should consider `apt-get install`ing either OpenMPI or MPICH to speed things up.

**Comment by saketkc** [comment]
I will take a look.

**Comment by dpo** [comment]
Thanks!

**Comment by saketkc** [comment]
This is due to https://github.com/Homebrew/homebrew-science/blob/master/travisCI/travis.sh#L50

**Comment by dpo** [comment]
What's the solution? `| grep -v gcc`?

**Comment by dpo** [comment]
Or we should ask the Travis guys for a much larger timeout.

**Comment by saketkc** [comment]
Give me a day. I think we can make it more intelligent.

**Comment by saketkc** [comment]
@dpo: https://travis-ci.org/saketkc/homebrew-science/builds/48125625
Does this look good?

See Lines 328-333

**Comment by saketkc** [comment]
Sorry, not there yet.

**Pull request closed without merging**
