### PR TITLE
Bump graph-tool version to 2.7

### PR DESCRIPTION
**Pull request by count0**

### CODE REVIEW

**Comment by count0** [comment]
Friendly bump on this. Despite what is shown above, it seems like all tests have passed.

**Comment by dpo** [comment]
Seems like El Capitan doesn't want to build this. I'll try and restart it.

**Comment by count0** [comment]
The build fails for el capitan because of sparsehash. See Homebrew/homebrew#41087.

**Comment by dpo** [comment]
OK, at least now there's an error message.

**Comment by dpo** [comment]
There was an issue uploading the bottles. Trying again.

**Pull request closed without merging**
