### PR TITLE
parallel-netcdf: revision for gcc

### PR DESCRIPTION
**Pull request by fxcoudert**
Following the GCC 7.1.0 release and merge into core, revision bumps for formulas that depend on `:fortran`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@fxcoudert 
> * fully scope test shell_output calls e.g. shell_output "#{bin}/ncmpidump"

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@fxcoudert I hijacked your pull request, rebased and fixed the audits.

**Pull request closed without merging**
