### PR TITLE
openblas 0.2.19

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by schoeps** [comment]
Suite sparse depends only optionally on openblas, why the rev bump?

**Comment by ilovezfs** [comment]
due to the Linux bottle.

**Comment by schoeps** [comment]
Ok! I was afraid that `arpack`, `qrupdate` and `octave` need bumps too

**Comment by ilovezfs** [comment]
We may want to do that as well for the sake of Linux users for whom it's recommended to be nice.

**Comment by ilovezfs** [comment]
looks like ceres solver needed a revision bump with the last eigen upgrade but didn't get one :(

**Comment by ilovezfs** [comment]
ceres-solver revision for eigen: https://github.com/Homebrew/homebrew-science/pull/4209

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
`dlib` should probably only depend on `openblas` on Linux.

**Comment by dpo** [comment]
See #4212.

**Comment by ilovezfs** [comment]
@dpo what is the underlying reason for avoiding (or at least always making optional) openblas on macOS? It seems to have caused a tedious split between the macOS and Linux side of a bunch of formulae. If that difference is mandatory, maybe we need to handle this via a requirement so that it can be satisfied in one way on macOS and another way on Linux without causing a bunch of cumbersome divergences in the formulae.

**Comment by dpo** [comment]
@ilovezfs OpenBLAS is an implementation of the BLAS and LAPACK subroutines (they are basic linear algebra kernels used by most scientific libraries for performance). OSX/macOS ships with Apple's own implementation (the Accelerate framework, formerly the vecLib framework). That's why `openblas` is `keg_only`.

It's important to note that parts of Apple's Accelerate are buggy. The bugs, which affect Fortran programs that call real single precision or complex subroutines in Accelerate, are fixed by `veclibfort` which is a thin library that wraps Accelerate. For that reason, certain formulae require `veclibfort` on OSX (e.g., `superlu`). Here, we didn't just want to use OpenBLAS all the time because Accelerate's often faster (e.g., https://github.com/xianyi/OpenBLAS/issues/533).

There's been an attempt at a BLAS requirement that's been abandoned and that I've been meaning to revive: https://github.com/Homebrew/homebrew-science/pull/2889

**Comment by ilovezfs** [comment]
@dpo any idea why octave didn't pour from the bottle? That's weird ...

Once it decided not to pour from the bottle, I see it had some trouble with the mirrors, but I have no idea why it decided to do a source build in the first place.

Also, locally I'm seeing
```
Integrated test scripts:

  liboctave/array/Array.cc-tst ................................ PASS     18/18  
  liboctave/array/CMatrix.cc-tst ..............................panic: Segmentation fault: 11 -- stopping myself...
make[1]: *** [check] Segmentation fault: 11
make: *** [check] Error 2
```

Building from HEAD resulted in the same segmentation fault. Incidentally I had to depend_on :tex for the octave HEAD build to work, so https://github.com/Homebrew/homebrew-science/issues/3669 seems to be on to something.

Building with openblas seems to have avoided the segmentation fault, but still results in
```
Summary:

  PASS     12968
  FAIL        29
  XFAIL       27
  SKIPPED     79
```
but at least the build finishes and the test block passes.

**Comment by dpo** [comment]
I'm really not sure why the source build. I'll cc @schoeps who might have seen those seg faults. I'm not observing them locally.

**Comment by schoeps** [comment]
I have no clue why the bottle is broken. This is rather a homebrew issue, right?

I will check whether Octave needs a ":tex" dependency, however for `--HEAD` this is not necessary and you can just install with `--without-docs` (the old stable version did not distinguish between online help and pdf documentation).

Regarding the seg fault: I have seen this when using Appleblas without veclibfort. Can you check if you have veclibfort in place? I typically prefer openblas but it comes with some other drawbacks. I would love to have Atlas (reminder for @dpo :) and a nicer dependency treatment, e.g. ":blas"...

**Comment by ilovezfs** [comment]
@schoeps it looks like the formula passes `"--disable-docs"` not `"--without-docs"` so that could be why/

**Comment by schoeps** [comment]
`brew install --without-docs` is correct for homebrew, it will trigger `./configure ... --disable-docs` for the configuration of octave. Sorry if I was not clear.

**Comment by ilovezfs** [comment]
@schoeps ah, ok. then it sounds like we need to add
```
depends_on :tex if build.with? "docs"
```

**Comment by ilovezfs** [comment]
>Can you check if you have veclibfort in place? 

yep

**Comment by dpo** [comment]
>  I would love to have Atlas (reminder for @dpo :)

https://github.com/Homebrew/homebrew-science/pull/3571 works for me locally but the bot doesn't like it.

> and a nicer dependency treatment, e.g. ":blas"...

I'm on it. It would be a major improvement.

**Comment by ilovezfs** [comment]
>I'm on it. It would be a major improvement.

@dpo I was thinking about it and wondering if we should use openblas for the bottles.

**Comment by dpo** [comment]
@ilovezfs That would add an extra dep and would somehow go against Homebrew's policy of not duplicating software already shipped with OSX/macOS, wouldn't it? Also, OpenBLAS remains slower in a number of cases.

**Comment by ilovezfs** [comment]
@dpo Not in terms of how requirements are handled. For example, for the :python requirement, we use the "python" formula for bottling but allow the system python to satisfy the requirement when the user is doing a source build. In order to block a bottle from using the "python" formula but still make python a build option, you can use a `without-python` option that isn't bound to any `:python` requirement. If it doesn't need to be an option, but is always used by the build, then the `:python` requirement isn't specified at all since python will be available from the system anyway.

The goal would be to use that as a way to make the sure the macOS and Linux formulae/bottles remain in sync in terms of revision bumps for openblas. But just a thought.

**Comment by dpo** [comment]
@ilovezfs I see what you mean. It's a good idea and we should discuss more if/how it could work. One issue is that the libraries don't even have the same name. On OSX, you can link with the blas and lapack using either `-framework vecLib`, `-framework Accelerate` or `-lblas -llapack`. Those are all the same thing. On Linux, you typically use `-lblas -llapack`. But sometimes, they have different names, such as `libf77blas`. If you're using ATLAS on either OSX or Linux, you must add `-latlas` to the mix. And in OpenBLAS, `-lopenblas` gives you both blas and lapack together. I'm not even talking about the proprietary ones such as MKL or ACML.

**Comment by ilovezfs** [comment]
@schoeps you were right!!!

>Can you check if you have veclibfort in place?

The answer turns out to be "no" just as you suspected because there's a case sensitivity bug (I'm using Case-sensitive Journaled HFS+ on that box) in the homebrew/science `octave` formula that caused the library not to be found!

```
-        args << "--with-blas=-L#{Formula["veclibfort"].opt_lib} -lveclibFort"
+        args << "--with-blas=-L#{Formula["veclibfort"].opt_lib} -lvecLibFort"
```
and voilà it works, no segfault. Usually I don't see case sensitivity bugs in homebrew/science due to the diligence with maintaining Linux (and hence case-sensitive ext4) compatibility, but since vecLibFort isn't used on Linux, it's now clear how this bug crept in.

**Comment by schoeps** [comment]
great 👍  Thanks for spotting. However, I am sorry because it's most probably me who is guilty :) Will you fix it? or shall we wait for Octave 4.2 (I have already a working formula).

**Comment by ilovezfs** [comment]
@schoeps I will fix it today. It can be committed directly without re-bottling or revision bumping.

>However, I am sorry because it's most probably me who is guilty

You are forgiven and held :innocent:.

>I have already a working formula

Yeah HEAD seems to build fine, but it's been insisting on a `:tex` dependency. Have you tried it with MacTex not installed?

**Comment by ilovezfs** [comment]
@schoeps I have just merged https://github.com/Homebrew/homebrew-science/pull/4304 which changes it to lvecLibFort

**Comment by speedcell4** [comment]
So, do you plan to merge this pull request? I am using Linuxbrew and got error when installing OpenBLAS.

**Comment by ilovezfs** [comment]
We need to decide if we're revision bumping the reverse dependencies that are only non-optional on Linux. CC @sjackman @dpo

**Comment by dpo** [comment]
I vote for bumping. The BLAS requirement isn't ready. Too busy lately.

**Comment by ilovezfs** [comment]
@dpo yeah, I think that's probably the right call since the Linux users need the revision bump, and I don't think we really want the versions of formulae on macOS and Linux to diverge even if it's just the revisions diverging (although maybe there is precedent for that?).

**Comment by dpo** [comment]
I can't recall formulas being out of sync for osx and linux, but it might have happened.

**Comment by sjackman** [comment]
The Mac and Linux versions should stay in sync if at all possible. Makes life simpler.

**Comment by ilovezfs** [comment]
Someone who can actually test these revision bumps on Linuxbrew will need to do this one, I'm afraid.

**Pull request closed without merging**
