### PR TITLE
butterflow: fix failure to resolve python modules

### PR DESCRIPTION
**Pull request by dthpham**
The bottled butterflow package is broken (import errors) because it's not picking up the `cv2.so` extension module located in `$(brew --prefix)/lib/python2.7/site-packages` (see: dthpham/butterflow#10). This is fixed by adding that directory to `PYTHONPATH`.

### CODE REVIEW

**Comment by tdsmith** [comment]
Good catch; this had worked for me because my system Python was configured to search Homebrew's site-packages. Let's use:
```ruby
ENV.prepend_path "PYTHONPATH", Formula["opencv"].opt_lib/"python2.7/site-packages"
```
instead -- we don't want to create the path if it doesn't exist and we only want to pick up opencv.

**Comment by dthpham** [comment]
Thanks, that's a much better approach. I have updated the formula with that path.

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
Thanks for the PR!

**Pull request closed without merging**
