### PR TITLE
Jpeg revisions for sumo, pcl

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-science/issues/6075

### CODE REVIEW

**Comment by fxcoudert** [comment]
`vtk` needs to go separately because it takes too long on CircleCI

**Comment by fxcoudert** [comment]
This is 👍 on Mac

**Comment by fxcoudert** [comment]
Had to manually create the commit for pcl Linuxbrew, but here we go!

**Comment by sjackman** [comment]
@fxcoudert I don't see a published bottle for this version of `pcl` 1.8.0_8.
https://bintray.com/linuxbrew/bottles-science/pcl/#files
I've reverted the Linuxbrew bottle a5a6084f947022affd7046b0d9a143a32afb070f

**Pull request closed without merging**
