### PR TITLE
update r-gui (and tweak xcode dependency)

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by psibre** [comment]
This also resolves the issue discussed in homebrew/brew#1448.

**Comment by psibre** [comment]
I assume the [CI failure on linux](https://travis-ci.org/Homebrew/homebrew-science/jobs/173822959) related to the fact that Xcode is only available for macOS?

**Comment by hardywu** [comment]
this build will abort the r-gui instance if you type anything that causes error.

```R
> test
Error: object 'test' not found

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Merged. Thanks @psibre!

**Pull request closed without merging**
