### PR TITLE
New formula : Cryptoverif 1.21

### PR DESCRIPTION
**Pull request by beurdouche**

### CODE REVIEW

**Comment by beurdouche** [comment]
@dpo @xu-cheng :
I am resurrecting  this formula, updated it and it now passes `brew install` and `brew audit` successfully.
Still, it does not pass the merging checks. Is it possible that I have a problem locally ?

**Comment by dpo** [comment]
When I try to execute the tests, I get lots of messages of the form
```
PROTOCOL undeniable-sig.ocv  /usr/local/Cellar/cryptoverif/1.21/tests/test: line 20: tests/otest2015.09.26-12_47_26: No such file or directory
/usr/local/Cellar/cryptoverif/1.21/tests/test: line 21: tests/otest2015.09.26-12_47_26: No such file or directory
awk: can't open file oexamples/undeniable-sig.ocv
 source line number 1
OK
/usr/local/Cellar/cryptoverif/1.21/tests/test: line 75: tests/sum-otest2015.09.26-12_47_26: No such file or directory
```
I guess the `oexamples` folder is in the wrong place?!

**Comment by beurdouche** [comment]
@dpo, thanks ! I fixed the issue of the `./test` executable, it wasn't the one used to test the formula though. Do you have any indications why it fails to merge ?

**Comment by beurdouche** [comment]
@dpo, the `brew doctor` step in the CI is now the only one failing but I don't think the formula causes this. Bug ?

**Comment by beurdouche** [comment]
@dpo, @xu-cheng : finally \o/ ! Thank you both for the help

**Comment by dpo** [comment]
Thanks!

**Pull request closed without merging**
