### PR TITLE
New version of MOOSE (3.1.2)

### PR DESCRIPTION
**Pull request by dilawar**
Homebrew/homebrew-science#5835 become too messy.

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by dilawar** [comment]
@BrewTestBot Test this again please.

**Comment by dilawar** [comment]
I was wondering if we can delete this formulae from homebrew-science? We have now started maintaining our own tap here https://github.com/BhallaLab/homebrew-moose/tree/master .

**Comment by iMichka** [comment]
Hi. Removal from homebrew-science is fine. Could you open a pull request for that?

**Comment by iMichka** [comment]
Just to be clear, for people reading this: homebrew-science is being phased out and all formulae will be removed end of December. So if people want to take care of formulae in their own tap; they are welcome to do so.

**Pull request closed without merging**
