### PR TITLE
getdp: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by schoeps** [comment]
I think one should add a python dependency. At least on my machine I cannot compile getdp without it...

**Comment by iMichka** [comment]
Let's wait for the builds to come back. We will see what needs to be done :)

**Comment by iMichka** [comment]
Rebased on master because `slepc` was updated.

**Comment by iMichka** [comment]
Linux build will need scalapack bottles first: #5699
Ignoring the remaining mac audits for the moment.

@schoeps Please open a new issue and fill out the issue template if you think that the Python dependency is really needed. Thanks.

**Pull request closed without merging**
