### PR TITLE
bowtie 1.2.1.1

### PR DESCRIPTION
**Pull request by heuermh**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by heuermh** [comment]
@iMichka @ianml I gave this a try but am ready to give up.  I don't really know how to do Perl stuff in homebrew.  Let me know if you'd like me to squash commits at any point.

**Comment by iMichka** [comment]
I think you are on the right way.

You can shorten the install block by writing something like this:
```
resources.each do |r|
  r.stage do
    system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
    system "make", "install"
  end
end
```

Then remove the `unless OS.mac?` in the test block; I think you need to set the path for OS X too.

I tested this and hit another perl module which is also missing (for OS X): `Mac::PropertyList`.

I think that making these changes should get you going.
You can use `brew test bowtie` locally to test your formula.

**Comment by iMichka** [comment]
The Linux builds are already green; waiting for the mac build. Once everything is green, please squash all the commits. It looks already really good.

**Comment by heuermh** [comment]
Thanks @iMichka!  Rebased and squashed.

**Comment by iMichka** [comment]
@heuermh Thanks for your contribution! Really nice work cleaning that up and finding out all the perl dependencies!

**Comment by tmozgach** [comment]
brew test for Ubuntu fails with error:
```
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/bowtie/test.01.perl:

FASTA-continuous 1 (fw:1, sam:1)
References:
>0
AGCATCGATCAGTATCTGA
Operating system identified as: 'Linux'. Native driver can not be loaded: Error loading Sys::Info::Driver::Linux::Device::CPU: Can't locate Unix/Processors.pm in @INC (you may need to install the Unix::Processors module)
```
After installing additional stuff:
```
cpanm -i Unix::Processors
```
It works.

**Comment by iMichka** [comment]
@tmozgach Unix::Processors is vendored with the formula. Can you check it is installed somewhere under `*/Cellar/bowtie/1.2.1.1/libexec` ? If yes, you should make sure the files are in your path. I do not use perl stuff, maybe @sjackman can give more details how this is supposed to work.

**Comment by sjackman** [comment]
@tmozgach Are you seeing that test failure with `bowtie` 1.2.1.1?

**Comment by tmozgach** [comment]
@sjackman just checked, yes, it fails with above error.

**Comment by sjackman** [comment]
```sh
❯❯❯ tar tf ~/.cache/Homebrew/bowtie-1.2.1.1.x86_64_linux.bottle.tar.gz | grep Processors
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/auto/Unix/Processors/
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/auto/Unix/Processors/Processors.so
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/auto/Unix/Processors/.packlist
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/Unix/Processors/
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/Unix/Processors/Info.pm
bowtie/1.2.1.1/libexec/PerlLib/x86_64-linux-gnu-thread-multi/Unix/Processors.pm
bowtie/1.2.1.1/libexec/vendor/man/man3/Unix::Processors.3pm
bowtie/1.2.1.1/libexec/vendor/man/man3/Unix::Processors::Info.3pm
```
The `Unix::Processors` module is installed in `bowtie`, so it's failing to load for some reason.

**Comment by heuermh** [comment]
The platform specificity of that module did give me pause, perhaps it might make sense to force the generic implementation (Sys::Info::Driver::Unknown I guess)?

**Pull request closed without merging**
