### PR TITLE
r 3.2.5

### PR DESCRIPTION
**Pull request by amoeba**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?

  Minor offenses raised, same as always.

- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by amoeba** [comment]
See release announcement for more details: https://stat.ethz.ch/pipermail/r-announce/2016/000601.html

3.2.5 is essentially the same as the last version, 3.2.4-revised, and was rolled out because of compatibility issues due to the `-revised` part of the previous version.

**Comment by dpo** [comment]
```
==> /usr/local/Cellar/littler/0.2.3_4/bin/littler -e 'print(pi)'
cannot find system Renviron
Fatal error: unable to open the base package
```

**Comment by amoeba** [comment]
Hey @dpo I wonder if this is just because the littler package is outdated. The brew version is 0.2.3_4 but 0.3.0 is the latest, https://github.com/eddelbuettel/littler/releases

**Comment by amoeba** [comment]
Is this formula ready to be merged or do I need to do some extra work? Happy to roll my sleeves up just not sure what needs done.

**Comment by tdsmith** [comment]
This should be fine. @BrewTestBot test this please

**Comment by amoeba** [comment]
Thanks @tdsmith. For my education, what is the link between this formula and littler? I can't figure out why this formula is dependent on littler in the first place. And is it a link the formula needs?

**Comment by tdsmith** [comment]
The relationship is the other way around; littler depends on r, and we test the dependents of packages when we upgrade them. I made some changes to littler so that it should not actually break when we bump r but it's still flaky on the test bot.

**Comment by tdsmith** [comment]
Also my changes didn't work. :p Oh well. Thanks for the r bump! I'll handle littler.

**Comment by amoeba** [comment]
Ah, that makes sense. Thanks for taking the time to explain!

**Pull request closed without merging**
