### PR TITLE
zoltan: migrate to boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew boneyard-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@sjackman @dpo it looks like this is already included with `trilinos` now, no?

>Zoltan v3.83 was released in January 2016 as part of Trilinos v12.6. This release includes only minor software changes. See more details below. 

(http://www.cs.sandia.gov/Zoltan/#ZOLTAN383)

```
iMac-TMP:~ joe$ brew link --overwrite --dry-run trilinos
Would remove:
/usr/local/include/Zoltan_config.h -> /usr/local/Cellar/zoltan/3.83_1/include/Zoltan_config.h
/usr/local/include/lbi_const.h -> /usr/local/Cellar/zoltan/3.83_1/include/lbi_const.h
/usr/local/include/zoltan.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan.h
/usr/local/include/zoltan_align.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_align.h
/usr/local/include/zoltan_comm.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_comm.h
/usr/local/include/zoltan_comm_cpp.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_comm_cpp.h
/usr/local/include/zoltan_cpp.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_cpp.h
/usr/local/include/zoltan_dd.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_dd.h
/usr/local/include/zoltan_dd_cpp.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_dd_cpp.h
/usr/local/include/zoltan_eval.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_eval.h
/usr/local/include/zoltan_mem.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_mem.h
/usr/local/include/zoltan_timer.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_timer.h
/usr/local/include/zoltan_timer_cpp.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_timer_cpp.h
/usr/local/include/zoltan_types.h -> /usr/local/Cellar/zoltan/3.83_1/include/zoltan_types.h
```

**Comment by dpo** [comment]
@ilovezfs Yes, it's part of Trilinos (actually, Trilinos uses Zoltan2 I think). I always thought people might require Zoltan alone (Trilinos has a huge footprint). But maybe not.

**Comment by ilovezfs** [comment]
@DomT4 do you mind checking the analytics on zoltan vs trilinos. I have no idea if it's worth keeping zoltan as a separate formula with a conflicts_with or not.

**Comment by DomT4** [comment]
Did nobody give you access to the analytics? I think everyone who requested access got it. If you didn't & you want it, might be worth giving Mike a ping when he's back around.

`zoltan` is on 39 "known" installations, `trilinos` on 234.

**Comment by ilovezfs** [comment]
@DomT4 I think I have access, but I've not explored its innards yet. 39 hmmm ... I suppose probably at least half of them wouldn't mind the larger trilinos footprint so :skull: seems likely here lol

**Comment by DomT4** [comment]
Essentially, most of the time you want (after login) Behaviour => Events => Top Events => install. Then bash your search term into the box. That's been about 95% of my usage so far 😄.

**Pull request closed without merging**
