### PR TITLE
pykep 1.3.9

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
> * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/core/_core.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/planet/_planet.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/sims_flanagan/_sims_flanagan.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/util/_util.so

Reported upstream: https://github.com/esa/pykep/issues/57

**Comment by iMichka** [comment]
@ilovezfs We have a patch (only the CMakeLists.txt file): https://github.com/esa/pykep/commit/351b628bf404ed53b3ae3e06eb8bdc56dc1deb11

I'll let you add this to a stable/do block :)

**Comment by iMichka** [comment]
BTW I tested the patch locally and it works.

**Comment by darioizzo** [comment]
Is the CMake BUILD_SPICE option On ? If possible it would be nice to have it on so that PyKEP gets compiled with more features.

**Comment by ilovezfs** [comment]
@darioizzo @iMichka looks like we had some trouble on Travis:
```
cd /tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/build/tests && /home/linuxbrew/.linuxbrew/bin/g++-5    -I/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/include/python2.7 -I/home/linuxbrew/.linuxbrew/include  -Os -w -pipe -march=core2 -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11 -DNDEBUG   -o CMakeFiles/lambert_test.dir/lambert_test.cpp.o -c /tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/tests/lambert_test.cpp
[ 67%] Linking CXX executable main
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/main.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/bin/g++-5   -Os -w -pipe -march=core2 -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11 -DNDEBUG  -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib CMakeFiles/main.dir/main.cpp.o  -o main -rdynamic src/libkeplerian_toolbox_static.a -lboost_date_time-mt -lboost_serialization-mt 
src/libkeplerian_toolbox_static.a(epoch.cpp.o): In function `unsigned short boost::date_time::month_str_to_ushort<boost::gregorian::greg_month>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
epoch.cpp:(.text._ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xac): undefined reference to `boost::gregorian::greg_month::get_month_map_ptr[abi:cxx11]()'
src/libkeplerian_toolbox_static.a(gtoc5.cpp.o): In function `boost::archive::detail::iserializer<boost::archive::text_iarchive, kep_toolbox::planet::base>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const':
gtoc5.cpp:(.text._ZNK5boost7archive6detail11iserializerINS0_13text_iarchiveEN11kep_toolbox6planet4baseEE16load_object_dataERNS1_14basic_iarchiveEPvj[_ZNK5boost7archive6detail11iserializerINS0_13text_iarchiveEN11kep_toolbox6planet4baseEE16load_object_dataERNS1_14basic_iarchiveEPvj]+0x44): undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
src/libkeplerian_toolbox_static.a(gtoc5.cpp.o): In function `boost::archive::detail::oserializer<boost::archive::text_oarchive, kep_toolbox::planet::base>::save_object_data(boost::archive::detail::basic_oarchive&, void const*) const':
gtoc5.cpp:(.text._ZNK5boost7archive6detail11oserializerINS0_13text_oarchiveEN11kep_toolbox6planet4baseEE16save_object_dataERNS1_14basic_oarchiveEPKv[_ZNK5boost7archive6detail11oserializerINS0_13text_oarchiveEN11kep_toolbox6planet4baseEE16save_object_dataERNS1_14basic_oarchiveEPKv]+0x5a): undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
src/libkeplerian_toolbox_static.a(gtoc5.cpp.o): In function `boost::archive::detail::oserializer<boost::archive::binary_oarchive, kep_toolbox::planet::base>::save_object_data(boost::archive::detail::basic_oarchive&, void const*) const':
gtoc5.cpp:(.text._ZNK5boost7archive6detail11oserializerINS0_15binary_oarchiveEN11kep_toolbox6planet4baseEE16save_object_dataERNS1_14basic_oarchiveEPKv[_ZNK5boost7archive6detail11oserializerINS0_15binary_oarchiveEN11kep_toolbox6planet4baseEE16save_object_dataERNS1_14basic_oarchiveEPKv]+0x5b): undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
src/libkeplerian_toolbox_static.a(gtoc5.cpp.o): In function `boost::archive::detail::iserializer<boost::archive::binary_iarchive, kep_toolbox::planet::base>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const':
gtoc5.cpp:(.text._ZNK5boost7archive6detail11iserializerINS0_15binary_iarchiveEN11kep_toolbox6planet4baseEE16load_object_dataERNS1_14basic_iarchiveEPvj[_ZNK5boost7archive6detail11iserializerINS0_15binary_iarchiveEN11kep_toolbox6planet4baseEE16load_object_dataERNS1_14basic_iarchiveEPvj]+0x45): undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [main] Error 1
make[2]: Leaving directory `/tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/build'
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Linking CXX executable lambert_test
cd /tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/build/tests && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/lambert_test.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/bin/g++-5   -Os -w -pipe -march=core2 -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11 -DNDEBUG  -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib CMakeFiles/lambert_test.dir/lambert_test.cpp.o  -o lambert_test -rdynamic ../src/libkeplerian_toolbox_static.a -lboost_date_time-mt -lboost_serialization-mt 
make[2]: Leaving directory `/tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/build'
[ 68%] Built target lambert_test
make[1]: Leaving directory `/tmp/pykep-20170218-17072-1q23334/pykep-1.3.9/build'
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
Shipped despite the travis unhappiness.

**Pull request closed without merging**
