### PR TITLE
Moving dgtal from homebrew to homebrew/science

### PR DESCRIPTION
**Pull request by dcoeurjo**
Adding DGtal 0.8 to homebrew/science (from homebrew/homebrew)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Travis fails while building boost... this has nothing to do with this formula (beside the fact that boost is required).
For the brew-test-bot, it seems that it hasn't built the last commit of my PR. I don't know what's wrong here.

**Comment by saketkc** [comment]
Ignore travis. The test-bot failure is due to audit issues:
```
Error Message

failed: brew audit dgtal --strict
Stacktrace

        ==> brew style dgtal
== /usr/local/Library/Formula/dgtal.rb ==
C:  1:  9: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C:  4: 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C:  5:  7: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C:  6:  8: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C:  7:  8: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 15: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 16: 18: Do not use semicolons to terminate expressions.
C: 16: 67: Do not use semicolons to terminate expressions.
C: 18: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 19: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 20: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 21: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 22: 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 25: 21: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 25: 38: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 26: 21: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 26: 41: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 43: 46: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 44: 48: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 45: 52: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 46: 48: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 47: 49: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 48: 81: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C: 50: 11: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.

1 file inspected, 24 offenses detected
Error: 3 problems in 1 formulae

==> audit problems
dgtal:
 * A `test do` test block should be added
 * `require 'formula'` is now unnecessary
 * Use `system "make", "install"` instead of `system "make install"` 


```

**Comment by dcoeurjo** [comment]
Ok but all audit issues have been fixed in the second commit (https://github.com/dcoeurjo/homebrew-science/commit/067b230d3f85e0eceb3bc5da3d840dcf95967e80)

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
The formula is still in core. I think that's the one being audited.

**Comment by dcoeurjo** [comment]
oh I see... what is the workflow to migrate formula between taps ? Should I 'PR' a removal in core first ?

**Comment by dcoeurjo** [comment]
Related PR in homebrew/homebrew https://github.com/Homebrew/homebrew/pull/37094)

**Pull request closed without merging**
