### PR TITLE
Fix nlopt HEAD build

### LINKED ISSUE #3838: nlopt upstream changed its build system to cmake.
### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue:

nlopt upstream has changed its build system to cmake (instead of configure), so the HEAD option will not work. hope someone could fix this.

### PR DESCRIPTION
**Pull request by Moisan**
This should close #3838. The test still passes when building without the HEAD option but the version testing inside the test fails with the HEAD option. 

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
I can successfully build HEAD but the test isn't very good. It fails for HEAD:
```
$ brew test nlopt --HEAD
Testing homebrew/science/nlopt
==> Using the sandbox
==> /usr/bin/clang++ test.cpp -I/usr/local/Cellar/nlopt/HEAD-3343118_2/include -L/usr/local/Cellar/nlopt/HEAD-3343118_2/lib -lnlopt_cxx -o test
Error: homebrew/science/nlopt: failed
<"2.5.0"> expected but was
<"HEAD-3343118">.
```
It would be great if you could change the test to something more meaningful and NLOPT related.

**Comment by Moisan** [comment]
BrewTestBot fails on `brew uses homebrew/science/nlopt`. I don't think my commit is responsible for this.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Thank you!

**Pull request closed without merging**
