### PR TITLE
bCALM 1 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
de Bruijn CompAction in Low Memory

(needed for upcoming BGREAT package)

### CODE REVIEW

**Comment by tseemann** [comment]
This fails on Mountain Lion only, a C++ library thing. 
Maybe needs "-stdlib=libc++" ?
Or "fails_with :clang" ?

```
./ograph.h:7:10: fatal error: debug.cpp'array' file not found:7:10: fatal error: 'unordered_map' file not found
lm.cpp
:7:10: fatal error: main.cpp'unordered_map' file not found:7:10: fatal error: 
'unordered_map' file not found#include <array>
         ^

**Comment by tdsmith** [comment]
I'd try adding `ENV.libcxx` to the top of `install`.

There's sample input in the README: https://github.com/Malfoy/bcalm#input

**Comment by tseemann** [comment]
The sample input in the docs still fails: https://github.com/Malfoy/bcalm/issues/3
I'll try the ENV.libcxx first.

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Pull request closed without merging**
