### PR TITLE
SDSL-Lite 2.0.3 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
As requested by @sjackman at https://github.com/Homebrew/homebrew-science/issues/3039

**PROBLEM**

I can not get the test to succeed, even though if I manually run the command it works fine!
I just can't figure out what the ruby error is:

```
torsten$ brew test ./sdsl-lite.rb
Testing homebrew/science/sdsl-lite
==> Using the sandbox
==> /usr/bin/clang++ -std=c++11 -stdlib=libc++ -o /private/tmp/sdsl-lite20160409-50607-1qbeyzm/fm-index -I/u
Last 15 lines from /Users/torsten/Library/Logs/Homebrew/sdsl-lite/01.clang++:
2016-04-09 10:54:47 +1000

/usr/bin/clang++ -std=c++11 -stdlib=libc++
-o
/private/tmp/sdsl-lite20160409-50607-1qbeyzm/fm-index
-I/usr/local/opt/sdsl-lite/include
/usr/local/Cellar/sdsl-lite/2.0.3/share/sdsl-lite/examples/fm-index.cpp
-L/usr/local/opt/sdsl-lite/lib
-lsdsl
-ldivsufsort
-ldivsufsort64

Error: homebrew/science/sdsl-lite: failed
Failed executing: /usr/bin/clang++ -std=c++11 -stdlib=libc++ -o /private/tmp/sdsl-lite20160409-50607-1qbeyzm/fm-index -I/usr/local/opt/sdsl-lite/include /usr/local/Cellar/sdsl-lite/2.0.3/share/sdsl-lite/examples/fm-index.cpp -L/usr/local/opt/sdsl-lite/lib -lsdsl -ldivsufsort -ldivsufsort64
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/sdsl-lite.rb:28:in `block in <class:SdslLite>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:36:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

### CODE REVIEW

**Comment by sjackman** [comment]
Resolved the above `test` failure by changing `ENV.cxx` to `*ENV.cxx.split`.

**Comment by sjackman** [comment]
The TestBot is failing with this error:
```
Falling back to patching base and 3-way merge...
Auto-merging sdsl-lite.rb
CONFLICT (add/add): Merge conflict in sdsl-lite.rb
error: Failed to merge in the changes.
```

Can you try a squash and rebase?

**Comment by tseemann** [comment]
@sjackman Sorry - I seem to have got my branch into a total mess that I don't seem to be able to get myself out of...

**Comment by sjackman** [comment]
Hi, Torsten. Can you move this branch `sdsl-lite_2.0.3` to your fork `tseemann/homebrew-science`?

**Comment by tseemann** [comment]
Moved to here: https://github.com/Homebrew/homebrew-science/pull/4100

**Pull request closed without merging**
