### PR TITLE
Update R formula to version 3.2.0

### PR DESCRIPTION
**Pull request by amoeba**
This commit updates the R formula to version 3.2.0, codename "Full of Ingredients", released April 16, 2015.

See release announcement for more details on the release as well as a changelog: http://article.gmane.org/gmane.comp.lang.r.general/319442

### CODE REVIEW

**Comment by amoeba** [comment]
I see the 4 failed tests but am not sure what (if anything) to do. The updated formula builds and runs without issues on my local Yosemite-based system.

**Comment by dpo** [comment]
It works here too on Mavericks. I'll restart the build because something went wrong with the Mavericks build.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@mikemcquaid Any idea what went wrong with the Mavericks build here?

**Comment by mikemcquaid** [comment]
@dpo Just a random failure.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
>   * Building R using the included versions of zlib, bzip2, xz and
     PCRE is deprecated: these are frozen (bar essential bug-fixes)
     and will be removed for R 3.3.0.

It's probably correct to add xz and pcre dependencies; configure may need flags to actually use them?

**Comment by tdsmith** [comment]
Opened #2116; looking for system libs is on by default.

**Pull request closed without merging**
