### PR TITLE
URL updates

### PR DESCRIPTION
**Pull request by tschoonj**
Just changing the URLs of a couple of software package I distribute...

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tschoonj thanks. standard commit subject line for this would be `foo: update url` I'll fix them in post.

**Comment by tschoonj** [comment]
Ok, thanks!

**Comment by ilovezfs** [comment]
@tschoonj :rocket:'d thanks for the updates! Maybe you can get certbot/let's encrypt SSL certs for that box! :)

**Comment by tschoonj** [comment]
I am trying! I am in the process of moving all my projects to Cloudfront but I cannot seem to register an SSL certificate with Amazon Route 53 because I want to keep my domain's WHOIS details private 😄

**Comment by ilovezfs** [comment]
Someone Somewhere
123 Lane Road
The Nowherelands, Villageville, 123456

**Pull request closed without merging**
