### PR TITLE
CLARK 1.1 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
Clark is a versatile, fast and accurate sequence classification method, especially useful for metagenomics and genomics applications. It is freely available at http://clark.cs.ucr.edu/.

### CODE REVIEW

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@lml I don't understand any of the Jenkins errors, and they only occur on Mountain Lion?
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1423/

**Comment by iml** [comment]
Probably just a temporary failure on the tail end of the bots being taken offline.

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by tseemann** [comment]
@sjackman Looks good to go.

**Comment by sjackman** [comment]
Thanks, Torsten.

**Pull request closed without merging**
