### PR TITLE
snp-sites: rename and update to 2.2.0

### PR DESCRIPTION
**Pull request by andrewjpage**

### CODE REVIEW

**Comment by tseemann** [comment]
```
./configure: line 3030: syntax error near unexpected token `CHECK,check'
./configure: line 3030: `PKG_CHECK_MODULES(CHECK,check >= 0.8.2,have_check="yes",'
```

**Comment by andrewjpage** [comment]
It loooks like it built without any issues, but there an error which looks unrelated:

```
Error: GitHub API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Try again in 25 minutes 58 seconds, or create a personal access token:

  https://github.com/settings/tokens/new?scopes=&description=Homebrew

and then set the token as: HOMEBREW_GITHUB_API_TOKEN
```

**Comment by tseemann** [comment]
@sjackman We need your help!

The submitter @andrewjpage has *renamed* the formula as part of the update pull request. (underscore vs dash, to make it consistent with the new .deb package name)

This cause problems with `brew pull --bottle` show below:

```
==> Applying patch
Applying: update to version 2.2.0 and rename repo
Using index info to reconstruct a base tree...
A	snp_sites.rb
Falling back to patching base and 3-way merge...
CONFLICT (rename/delete): snp-sites.rb deleted in e85dc0c066f1b751878fd93819e4c080abc7146d and renamed in update to version 2.2.0 and rename repo. Version update to version 2.2.0 and rename repo of snp-sites.rb left in tree.
Failed to merge in the changes.
Patch failed at 0001 update to version 2.2.0 and rename repo
The copy of the patch that failed is found in:
   /usr/local/Library/Taps/homebrew/homebrew-science/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.
```

**Comment by dpo** [comment]
You need to update `formula_renames.json`.

**Comment by sjackman** [comment]
Thanks, Dominique.

It looks like upstream used to call it `snp_sites` and have renamed it. Ergh.

**Comment by tseemann** [comment]
@sjackman @dpo 

i'm worried i've broken homebrew-science...

I added the rename to the JSON file, then pulled this in, and it told me to run brew migrate, which I did, then it installed fine. I pushed it but now I see this email:

https://travis-ci.org/Homebrew/homebrew-science/builds/116100001

**Comment by sjackman** [comment]
The only error message I see is:
```
Error: GitHub API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 23 minutes 31 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: HOMEBREW_GITHUB_API_TOKEN
==> FAILED
```
https://travis-ci.org/Homebrew/homebrew-science/jobs/116100002#L768-L772

**Comment by sjackman** [comment]
So everything is fine, I think.

**Comment by tseemann** [comment]
@andrewjpage  @sjackman I don't understand how to get this pull request through the `brew pull` system :(

**Comment by sjackman** [comment]
The BrewTestBot build expired.

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@tseemann @sjackman Any chance you could review this and decide whether to pull or close?

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Superseded by #4545

**Pull request closed without merging**
