### PR TITLE
trinity 2.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
- version bump to 2.2.0
- verify the test now works with patched bowtie
- unbundle deps we already have
- removes the < gcc 5 restriction

### CODE REVIEW

**Comment by ilovezfs** [comment]
@sjackman I updated this PR to try re-enabling the java requirement so we can see if that's ok too.

**Comment by sjackman** [comment]
https://travis-ci.org/Homebrew/homebrew-science/jobs/123418976#L329-L332
```
==> SKIPPING: homebrew/science/trinity
Java 1.7+ is required to install this formula.
You can download from:
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
```

Installing either the host's JDK or `brew install jdk` should avoid this skip.

**Comment by sjackman** [comment]
`JavaRequirement` should have a `default_formula "jdk"` on Linux.

**Comment by ilovezfs** [comment]
@sjackman https://github.com/Linuxbrew/linuxbrew/pull/1074

**Comment by ilovezfs** [comment]
@sjackman any changes you'd like or does this look good to go?

**Comment by ilovezfs** [comment]
@sjackman If I first pull #3556, it now passes Linux test-bot:
```
==> brew --env
==> brew config
==> brew tests
==> brew tests --no-compat
==> brew readall --aliases --syntax
==> brew update-test
==> brew uses homebrew/science/trinity
==> brew fetch --retry bowtie homebrew/dupes/unzip htslib jdk jellyfish samtools sphinx-doc trimmomat
ic xz
==> brew fetch --retry homebrew/science/trinity --build-bottle
==> brew install --only-dependencies --verbose --build-bottle homebrew/science/trinity
==> brew install --verbose --build-bottle homebrew/science/trinity
==> brew audit homebrew/science/trinity
==> brew bottle --verbose --rb homebrew/science/trinity
==> brew bottle --merge --write --no-commit ./trinity-2.2.0.x86_64_linux.bottle.rb
==> brew uninstall --force homebrew/science/trinity
==> brew uninstall --force homebrew/dupes/unzip sphinx-doc xz
==> brew install ./trinity-2.2.0.x86_64_linux.bottle.tar.gz
==> brew test --verbose homebrew/science/trinity
==> brew uninstall --force homebrew/science/trinity
==> brew uninstall --force bowtie htslib jdk jellyfish samtools trimmomatic```

**Comment by sjackman** [comment]
:+1: Thanks, Joe.

**Pull request closed without merging**
