### PR TITLE
hdf5: update source tarball dowload link

### PR DESCRIPTION
**Pull request by fish2000**
### Have you:

- [✔️] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [✔️] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [✔️] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [✔️] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [❌ (n/a)] Removed the `revision` line, if any, when bumping the version number?
- [❌ (n/a)] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [✔️] Not altered the `bottle` section?
- [✔️] Checked that the tests still pass?

The site structure of hdfgroup.org – including all the old resource links, e.g. those to source tarball release downloads – has been overhauled.

This PR updates the link to the HDF5 source – the version is still 1.8.17; the hash value of the bzipped tarball is unchanged.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
does anyone know why the bots have been canceled during the builds ?  Is it a jenkins problem or a issue with the formula (ping @ilovezfs ) ?

(a lot of formulas depend on hdf5 and cannot be upgraded without this fix)

**Comment by ilovezfs** [comment]
@dcoeurjo if it's just a URL change we do not need to rebuild the bottles.

**Comment by ilovezfs** [comment]
@dcoeurjo merged!

**Comment by ilovezfs** [comment]
@fish2000 Thanks for your contribution to Homebrew science!

**Comment by fish2000** [comment]
@ilovezfs anytime, glad to help out 👍🏽

**Pull request merged**
