### PR TITLE
pocl 0.14

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
I know that the test block is missing, I need to find a clever thing to test here. But I want first to see if this correctly builds everywhere.

**Comment by iMichka** [comment]
> Error: Failed to download resource "hwloc"
Download failed: https://linuxbrew.bintray.com/bottles-science/hwloc-1.11.7.x86_64_linux.bottle.tar.gz

@ilovezfs you uploaded that a few days ago. Seems the linux bottle did not get uploaded to bintray.

**Comment by ilovezfs** [comment]
Weird. It's fixed now (I manually clicked "publish" in Bintray GUI).

**Comment by iMichka** [comment]
@ilovezfs Thanks that worked. Is the test block audit gone?

**Comment by ilovezfs** [comment]
test block audit only shows up on `--strict`

**Comment by iMichka** [comment]
Right. I had a look at their first example, which already involves 3 different files and a lot of code. Skipping this for now. My goal was just to remove the llvm34 dep, which ended in updating the formula. Writing a test can be done by whoever knows more about pocl :)

**Pull request closed without merging**
