### PR TITLE
Official 2.1.1 release of libSBOL

### PR DESCRIPTION
**Pull request by bbartley**
Hello, this is the official 2.1.1 release of libSBOL, a library that supports reading and writing files in the Synthetic Biology Open Language (SBOL) data standard for computer-aided design for biotechnology and synthetic biology

### Have you:

- [ x ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ x ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ x ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ x ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ x ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Thanks. This is way better. Please do not modify the bottle section, just leave it as is, per http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

Our merge script will update it accordingly. Please add `revision 1`, so that new bottles are built, and people get the updated version.

- make your changes
- `git add .`
- `git commit --amend`
- `git push --force <yourforkName> libsbol-fix

This will update this pull request without adding a new commit. Thanks

**Comment by bbartley** [comment]
Hi, looks like integration tests are passing on Mac.  It fails on Linux when using old version of g++.  Is it acceptable?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Yes we can ignore the linux builds for the moment. We are migration from travis to circleci for this, and it is not mandatory.

I just saw that you made a new tag, which is OK too. But in that case for the formula, it is a normal version bump, so no need to update the revision. So the line `revision 1` can be removed. This is only used when the version does not change but bottles need to be rebuild. Here the version changes; so bottles get rebuild anyway.

So just that one change; that you can update as you just did, and we will be good to go.

**Comment by bbartley** [comment]
OK done. Thanks for the pointers!

**Comment by iMichka** [comment]
@bbartley This has been merged. Thanks for your contribution.

**Pull request closed without merging**
