### PR TITLE
Prodigal 2.6.2 (update)

### PR DESCRIPTION
**Pull request by tseemann**
Now supports translation table 25, needed for Prokka 1.12 (upcoming)

### CODE REVIEW

**Comment by iml** [comment]
Please leave the bottle block in, otherwise it will be re-inserted in some weird place, especially if there are empty lines around.

**Comment by tseemann** [comment]
I don't understand the fail message: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1629/

**Comment by dpo** [comment]
@mikemcquaid Sorry to bother you but this keeps happening.

**Comment by mikemcquaid** [comment]
@dpo Yes, it's a Jenkins bug, we can't do anything about it. You need to just retry the build.

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@tseemann Only maintainers can do that.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@mikemcquaid I didn't realise only maintainers could do the test mantra. I guess new commits to pull requests are meant to trigger it anway.

The build failed because return code 9 instead of 0. But on Linux I get 0. Can't figure it out. Trying a different test.

**Pull request closed without merging**
