### PR TITLE
g2o: remove optional qt and libqglviewer options

### PR DESCRIPTION
**Pull request by iMichka**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

See #4595 for the transition to qt5

This optional qt dependency is not used
at all by the formula (at least for the moment).

### CODE REVIEW

**Comment by iMichka** [comment]
Maybe @adrelino or @RainerKuemmerle can comment on this. Homebrew is removing qt4, and it is not clear to me why g2o needs qt at a first look (and if does, is there a flag to set for qt5?).

**Comment by iMichka** [comment]
See also #4625

**Comment by iMichka** [comment]
Travis failed because it picked up the wrong commit, or it did not re-run when I pushed my modifications.

**Comment by drmaj** [comment]
When will this finally be merged into master?

**Comment by iMichka** [comment]
I do not know, I'm not doing the merges, but I guess as soon as possible. These options are broken/deprecated, so they need to be removed. Why are you asking?

**Comment by drmaj** [comment]
Trying to build a SLAM library on mac that uses g2o. Is there a way that I can use your commit instead of master?

**Comment by jonchang** [comment]
Thanks @iMichka. I'm going to hold off on deciding about #4625 until I can investigate why it was boneyarded.

@drmaj this has been merged, but in the future you can pass a URL to `brew install`; the "raw" link for the file is what you want.

**Pull request closed without merging**
