### PR TITLE
libsbml 5.11.0 (new formula)

### PR DESCRIPTION
**Pull request by mythosil**
LibSBML is a free, open-source programming library
to help you read, write, manipulate, translate, and validate
SBML files and data streams.

### CODE REVIEW

**Comment by mythosil** [comment]
opening a new PR #1844

**Comment by dpo** [comment]
Thanks. We're just waiting for the brew bot to upload the bottles.

**Comment by dpo** [comment]
@mikemcquaid Any idea why the bottles for this PR aren't making it to the brew bot repository?

**Comment by mikemcquaid** [comment]
There's a known issue with bottling new taps formulae. I'll fix it ASAP.

**Comment by dpo** [comment]
Thanks @mikemcquaid !

**Comment by mikemcquaid** [comment]
This should be fixed as-of https://github.com/Homebrew/homebrew/commit/be5dafdc363454cace3bab286a14f64946f28b9e.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
