### PR TITLE
upgrade anvio version to 2.2.2, switch from python2 to python3

### PR DESCRIPTION
**Pull request by ozcan**
Change log is [here](https://github.com/merenlab/anvio/releases/tag/v2.2.1)
- switched from python2 to python3
- added new python dependencies, and some version changes for exists dependencies

### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Is this python3-only now? The default is still Python2 on homebrew, so if python2 is still there, that should be the default. But you can add both options to the formula. There are multiple formula doing this.

**Comment by ozcan** [comment]
@iMichka, yes this formula is python3-only, we dropped python2 support

**Comment by iMichka** [comment]
@ozcan I'm fine with that. We need more people doing such bold moves with python3.

I ignored the build failures on Linux, it has been broken before. If you want you can have a look at the errors and try to fix these, but it is not mandatory.

**Comment by iMichka** [comment]
And thanks for you contribution!

**Pull request closed without merging**
