### PR TITLE
Scalapack (update)

### PR DESCRIPTION
**Pull request by davydden**
output the summary of tests to the user

### CODE REVIEW

**Comment by dpo** [comment]
Is this really useful? The build fails as soon as a test fails, and the detailed results may be found in `~/Library/Logs/Homebrew/scalapack`.

**Comment by davydden** [comment]
I am not sure that the build will fail if some tests fail in general. Did you experience that? 
If they fail to compile - this is one story, however if the output of the test fails against some blessed output - the build will happily go on, IMHO.

**Comment by dpo** [comment]
At least for `scalapack` I'm sure the build fails if a single test fails. Sometimes building `--with-shared-libs` is enough to make it fail.

**Comment by davydden** [comment]
ok. did not know that.

**Pull request closed without merging**
