### PR TITLE
Updated nextflow to version 0.12.0

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by sjackman** [comment]
Fails to install on Mac. Likely a non-portable usage of `dirname` in `nextflow -download`. Please fix.

```
Error Message

failed: brew install ./nextflow-0.12.0.yosemite.bottle.tar.gz
Stacktrace

        ==> Installing nextflow from Homebrew/homebrew-science
==> Pouring nextflow-0.12.0.yosemite.bottle.tar.gz
==> /usr/local/Cellar/nextflow/0.12.0/bin/nextflow -download
/usr/local/Cellar/nextflow/0.12.0/bin/nextflow
-download

usage: dirname path
usage: mkdir [-pv] [-m mode] directory ...
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nextflow`
==> Summary
/usr/local/Cellar/nextflow/0.12.0: 2 files, 12K
```

**Comment by pditommaso** [comment]
Does the tests run on multiple OSX versions or only on Yosemite ?

**Comment by pditommaso** [comment]
I've noticed that is failing on all three Mac platforms (Yosemite, Mountain lion, Mavericks) but the nextflow download script has not changed recently.

So, I'm supposing that something is changed in Homebrew. May this be related ?
https://gist.github.com/jacknagel/84756bdd38b596a882d6

**Comment by sjackman** [comment]
Yosemite, Mavericks and Mountain Lion. See [BrewTestBot](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/711/).

**Comment by pditommaso** [comment]
I've tested on my laptop and it worked fine 

    $ brew --version
    0.9.5

    $ brew install --verbose --debug homebrew/science/nextflow
    /usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-science/nextflow.rb
    ==> Installing nextflow from homebrew/homebrew-science
    /usr/libexec/java_home --failfast --version 1.7+
    /usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-science/nextflow.rb
    /usr/libexec/java_home --failfast --version 1.7+
    ==> Downloading http://www.nextflow.io/releases/v0.12.0/nextflow
    /usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.9.5) http://www.nextflow.io/releases/v0.12.0/nextflow -C 0 -o /Library/Caches/Homebrew/nextflow-0.12.0.incomplete
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  7366  100  7366    0     0  38298      0 --:--:-- --:--:-- --:--:-- 38364
    ==> Verifying nextflow-0.12.0 checksum
    ==> Patching
    ==> Cleaning
    Fixing /usr/local/Cellar/nextflow/0.12.0/bin/nextflow permissions from 644 to 555
    ==> Finishing up
    ln -s ../Cellar/nextflow/0.12.0/bin/nextflow nextflow
    ==> /usr/local/Cellar/nextflow/0.12.0/bin/nextflow -download

          N E X T F L O W
          Version 0.12.0 build 2581
          last modified 07-01-2015 14:28 UTC (15:28 CEST)
          http://nextflow.io

    ==> Summary
    🍺  /usr/local/Cellar/nextflow/0.12.0: 2 files, 12K, built in 14 seconds

**Comment by sjackman** [comment]
I'd suggest adding `set -eu` to the top of the `nextflow` shell script. It would help troubleshooting. `-x` is also useful.

```
        -e  Exit immediately if a command exits with a non-zero status.
        -u  Treat unset variables as an error when substituting.
        -x  Print commands and their arguments as they are executed.
```

**Comment by sjackman** [comment]
This error `usage: mkdir [-pv] [-m mode] directory ...` suggests that `NXF_PATH` is null.

**Comment by pditommaso** [comment]
It makes no sense because `NXF_PATH` depends on `NXF_BIN` that default to a predefined value. 

https://github.com/nextflow-io/nextflow/blob/master/nextflow#L164

However I've added a `-x` in the post script section to try to understand what's wrong.

**Comment by sjackman** [comment]
`nextflow -version` fails.

```
==> bash -x /usr/local/Cellar/nextflow/0.12.0/bin/nextflow -download
+ rm -rf /Users/brew/Jenkins/workspace/Homebrew Science Pull Requests/version/yosemite/home/.nextflow/framework/0.12.0
+ /usr/local/Cellar/nextflow/0.12.0/bin/nextflow -version
usage: dirname path
usage: mkdir [-pv] [-m mode] directory ...
+ exit 64
```

**Comment by sjackman** [comment]
I'm going to merge this PR, because it works for me on my box. I can't say why it doesn't work on the BrewTestBot.

**Pull request closed without merging**
