### PR TITLE
Jpeg revision: vigra, astrometry-net, dlib, enblend-enfuse

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-science/issues/6075

### CODE REVIEW

**Comment by iMichka** [comment]
The `enblend-enfuse` test fails on mac:

``` 
==> Verifying enblend-enfuse--test_image-08.png checksum
==> /usr/local/Cellar/enblend-enfuse/4.2_2/bin/enblend basn4a08.png basn4a08.png
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/vigra/lib/libvigraimpex.11.dylib
  Reason: image not found
Error: homebrew/science/enblend-enfuse: failed
```

On Linux enblend-enfuse fails to build due to problems with `vigra` too. Weird ...

`astronometry-net` is known to be broken on Linux, so you can ignore that: #6079

**Comment by fxcoudert** [comment]
Adding `vigra` to that series

**Comment by fxcoudert** [comment]
This is 👍 on mac. @iMichka can you advise of the Linux status, and merge if possible? (I don't really remember how to merge linux bottles, and I don't really understand the CircleCI & Travis output.)

**Comment by iMichka** [comment]
It's ok on Linux too, I'll merge it. It's tricky because one of the Linux bottle was not build, so there will be an error. I want try the `--warn-on-publish-failure` flag to see if this helps.

**Comment by iMichka** [comment]
I am currently working on merging this, I need to fix a bug in Linuxbrew first I think. And there is the bug with the curl download strategy that needs to be fixed too #3026.

Part of the bottles have already been published.

**Comment by iMichka** [comment]
I published the bottles manually and built the needed commits for Linux, as there were already a bunch of published bottles and I wanted to get this merged before going to bed, to leave this in a clean state.

**Pull request closed without merging**
