### PR TITLE
butterflow 0.1.5 (new formula)

### PR DESCRIPTION
**Pull request by dthpham**
A tool that lets you make slow motion and smooth motion videos from the command line.

### CODE REVIEW

**Comment by dthpham** [comment]
Travis build is failing because `gcc-4.9.2` fails to build.

**Comment by saketkc** [comment]
Yes, it's a known issue. I am unable to build your formula on linux because `opencv` seems to be broken at the moment.

**Comment by dpo** [comment]
Should this be in science or in core?

**Comment by dthpham** [comment]
@dpo I submitted this to core before but it was rejected because of a dependency to homebrew-science: https://github.com/Homebrew/homebrew/pull/34205.

**Comment by dpo** [comment]
@dthpham Ok I see thanks.

**Pull request closed without merging**
