### PR TITLE
OCE-0.17

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by jconley** [comment]
can't see the build output (404), however it builds on my local, but `brew test oce

**Comment by jconley** [comment]
can't see the bot build output (404), however it builds on my local, but `brew test oce` fails as it now prints a warning that CASROOT cannot be found.  I set CASROOT=/usr/local/opt/oce (see opencascade formula caveats), however, it looks for files in CASROOT/src/DrawResources, which do not get installed.  should probably contact the oce team or look for a cmake option that will install these. (i went to inspect, but my ccmake crashes for some reason)

opencascade installs these under /usr/local/Cellar/opencascade/6.8.0/src:
DrawResources
SHMessage
Shaders
StdResource
TObj
Textures
UnitsAPI
XSMessage
XSTEPResource
XmlOcafResource

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by luzpaz** [comment]
@iml does @BrewTestBot need the submitted PR to be updated ?

**Comment by iml** [comment]
It looks like the bot hits a test failure, perhaps the same as mentioned by @jconley? That should be addressed.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
````
==> brew test --verbose Homebrew/science/oce				 FAILED
Testing oce
Error: oce: failed
test returned false
````

**Comment by dpo** [comment]
@lupaz, please remove the obsolete `require "formula"` and replace the test with
````
"1\n"==`CASROOT=#{share}/oce-#{version} #{bin}/DRAWEXE -b -c \"pload ALL\"`
````
It works here.

**Comment by jconley** [comment]
@lupaz i would also add caveats similar to [opencascade](https://github.com/Homebrew/homebrew-science/blob/master/opencascade.rb#L82) if CASROOT is now needed.

**Comment by luzpaz** [comment]
"Build has been executing for 25 min on master"

**Comment by dpo** [comment]
Thanks!

**Pull request closed without merging**
