### PR TITLE
getdp: rebuild against PETSc 3.7

### PR DESCRIPTION
**Pull request by dpo**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] ~~Written a sensible test? (The best test is to compile and run a sample program.)~~

### Updates to existing formula: have you

- [ ] ~~Removed the `revision` line, if any, when bumping the version number?~~
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
Build error is already on issue tracker: https://onelab.info/trac/getdp/ticket/31

**Comment by schoeps** [comment]
Indeed "--HEAD" works. I made patches backporting the changes, see https://gist.github.com/schoeps/53365da617aa6cfac332d0a19235215f

**Comment by dpo** [comment]
Thanks! Testing right now. It built for me locally.

**Comment by dpo** [comment]
Thanks @schoeps !

**Pull request closed without merging**
