### PR TITLE
paml: also install mcmctree and infinitesites

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@jonchang Can you squash your commits into a single commit please?

Something like: ```git checkout path-8 ; git rebase -i HEAD~2 ; edit 2nd pick to squash ; git push```

**Comment by jonchang** [comment]
Squashed and force-pushed.

**Comment by jonchang** [comment]
@tseemann PS: please comment on my PR for velvet optimiser :smile:

**Pull request closed without merging**
