### PR TITLE
links-scaffolder 1.5: Change sha256

### PR DESCRIPTION
**Pull request by warrenlr**
Updated sha256

### CODE REVIEW

**Comment by sjackman** [comment]
Hi, Warren. It's best to give the software a new version number if you change the tarball, even for a minor change. I'd suggest changing the version number to `1.5.1` if it's a small change. [Semantic Versioning](http://semver.org/) is a good read on this topic.

**Comment by warrenlr** [comment]
Hi Shaun,
Is it possible to keep v1.5 for this release (no changes made to the code) ?  It is tied to a manuscript in review and I am reluctant to change the version until a decision has been reached.
Thanks,
Rene




________________________________________

**Comment by sjackman** [comment]
Done. Was it a documentation change?

**Comment by warrenlr** [comment]
yes, minor changes to the readme as per reviewer's request.
________________________________________

**Pull request closed without merging**
