### PR TITLE
deal.II (add test block)

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by dpo** [comment]
Locally, I get an error similar to the bot:
```
dyld: Library not loaded: /usr/local/lib/libpmpi.12.dylib
  Referenced from: /usr/local/lib/libp4est-1.1.dylib
  Reason: image not found
```
For an unknown reason, the bot refers to `libmpi`, but on my machine the error says `libpmpi`.

**Comment by davydden** [comment]
on my system it is linked against `/usr/local/lib/libmpi.12.dylib`. I guess i need to bump the revision.

**Comment by davydden** [comment]
https://github.com/Homebrew/homebrew-science/pull/2931

**Comment by davydden** [comment]
urhg, those missing libraries...
```
dyld: Library not loaded: /usr/local/lib/libhdf5_hl.9.dylib
  Referenced from: /usr/local/opt/slepc/real/lib/libslepc.3.6.1.dylib
  Reason: image not found
```

I will create shortly a PR on SLEPc with `test` block, so the it will be rebuilt...

**Comment by davydden** [comment]
see https://github.com/Homebrew/homebrew-science/pull/2939

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
i would merge trilinos first (with updated bottles)

**Comment by davydden** [comment]
it seems bot time limit got smaller.... :-( now it's not enough for deal.ii either.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
I think you forgot to add a revision number.

**Comment by dpo** [comment]
Actually, it's ok because your PR won't change the bottles. I tried it locally and I'm getting
```
$ brew test dealii
Testing homebrew/science/dealii
==> Using the sandbox
==> cmake .
==> make release
Last 15 lines from /Users/dpo/Library/Logs/Homebrew/dealii/02.make:
-- Generating done
-- Build files have been written to: /tmp/dealii20151228-49812-198war1/step-3
Scanning dependencies of target step-3
[ 50%] Building CXX object CMakeFiles/step-3.dir/step-3.cc.o
make[6]: *** No rule to make target `/usr/local/lib/libpike-blackbox.dylib', needed by `step-3'.  Stop.
```

**Comment by davydden** [comment]
@dpo did you re-build it or tried with bottles? Bottles should be changed as last time they were poured for other versions of Trilinos/PETSc....

**Comment by dpo** [comment]
I see. So we do need to rebuild bottles.

**Comment by dpo** [comment]
It would be good if you could add a revision number then.

**Comment by davydden** [comment]
> The job exceeded the maxmimum time limit for jobs, and has been terminated.

**Comment by davydden** [comment]
the last test is fixed in https://github.com/Homebrew/homebrew-science/pull/3155

**Comment by davydden** [comment]
@BrewTestBot test this please

**Comment by davydden** [comment]
it seems it worked...

**Comment by dpo** [comment]
Excellent. Thank you!

**Pull request closed without merging**
