### PR TITLE
gridss 0.11.7 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by tseemann** [comment]
```
Error: 1 problem in 1 formula
homebrew/science/gridss:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

Argghh

**Comment by dpo** [comment]
Don't worry about that if the software is useful and used.

**Comment by tseemann** [comment]
@dpo there was talk of removing this requirement, as we don't judge non-github tools!

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to add a comment in this issue. Thanks!

**Pull request closed without merging**
