### PR TITLE
insighttoolkit: bump

### LINKED ISSUE #3164: insighttoolkit bottle has stale HDF5 dependency
The insighttoolkit bottle for El Capitan links to /usr/local/opt/hdf5/lib/libhdf5_cpp.10.dylib, but hdf5 now provides /usr/local/opt/hdf5/lib/libhdf5_cpp.11.dylib, resulting in the following error message when trying to dlopen:

```
loaded: /usr/local/opt/hdf5/lib/libhdf5_cpp.10.dylib
  Referenced from: /usr/local/opt/insighttoolkit/lib/libITKIOHDF5-4.8.1.dylib
  Reason: image not found
```

### PR DESCRIPTION
**Pull request by dpo**
Fixes #3164.

### CODE REVIEW

**Comment by dpo** [comment]
Build failure on 10.10:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl_ext.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers/CGLTypes.h:75:15: error: missing ',' between enumerators
        kCGLPFAStereo OPENGL_ENUM_DEPRECATED(10_0, 10_11)        =   6,
                     ^
                     , 
```
https://travis-ci.org/Homebrew/homebrew-science/jobs/99627566#L1561

**Comment by dpo** [comment]
@iMichka Any ideas? I get the same error with other software on 10.10.

**Comment by iMichka** [comment]
Hi

never saw the error before. I did not rebuild since some weeks on 10.10. If the error is there with other software it may be a more general problem. Maybe try with/without CLT ?

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
