### PR TITLE
RepeatScout: add mirror url

### PR DESCRIPTION
**Pull request by nextgenusfs**
Download url was broken, added mirror url hosted at RepeatMasker

### CODE REVIEW

**Comment by dpo** [comment]
Looks good, thanks. Let's see if it builds!

**Comment by dpo** [comment]
The download fails every time. The RepeatScout home page has a different link: http://bix.ucsd.edu/repeatscout/RepeatScout-1.0.5.tar.gz

**Comment by nextgenusfs** [comment]
Okay, I will try that, so just edit and then do another PR?

**Comment by dpo** [comment]
What you did is good.

**Comment by dpo** [comment]
Merged. Thank you!

**Comment by sjackman** [comment]
🍼🐧

**Pull request closed without merging**
