### PR TITLE
opencv3 3.2.0 bump version

### LINKED ISSUE #4758: Update opencv3 to OpenCV 3.2, it has been released today
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### PR DESCRIPTION
**Pull request by Schultzer**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

~- [ ] Written a sensible test? (The best test is to compile and run a sample program.)~

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
~- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?~
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

This closes #4758 #4598 #4104

### CODE REVIEW

**Comment by 0x00b1** [comment]
OpenCV introduced an `OPENCV_ENABLE_NONFREE` CMake variable. Would you mind adding a `--with-nonfree` (or `--without nonfree`) option?

**Comment by Schultzer** [comment]
@0x00b1 ready for 👀 
I'm not sure if this is best pratice with brew formula, but as I understand these modules are in the contribution repo.
[surf-in-opencv3](http://answers.opencv.org/question/114718/surf-in-opencv3/) 
[opencv_contrib](https://github.com/opencv/opencv_contrib/blob/master/README.md)

**Comment by Schultzer** [comment]
@jonchang The understandig I have of that matter is pretty basic 
`"Build utility applications (used for example to train classifiers)"`



[`OCV_OPTION(BUILD_opencv_apps        "Build utility applications (used for example to train classifiers)" (NOT ANDROID AND NOT WINRT) IF (NOT APPLE_FRAMEWORK) )`](https://github.com/opencv/opencv/blob/master/CMakeLists.txt#L235)

frankly I'm not sure about this but from my understanding its a no when it is Apple framework so not sure if it's only compitible with linux and non Apple framework.

but maybe @kuchi got a better understanding of this matter.

**Comment by kuchi** [comment]
The `"Build utility applications (used for example to train classifiers)"` option is now somewhat useful as of version 3.2 since they now have an interactive camera calibration application. So this may be useful to some people.

**Comment by Schultzer** [comment]
@kuchi 
Does this work on Apple hardware? 
If so have you testet it?  (should we add test for it?)
I have no objection adding this option as long as it works on Apple hardware.

**Comment by kuchi** [comment]
@Schultzer yes, the apps work on my system 10.12.2. Though since it's installed as a keg_only they are not on the path, they are only in /usr/local/Cellar/opencv3/3.2.0/bin/ and not linked to /usr/local/bin. Does opencv3 really need to be a keg_only? I guess this was done to allow opencv and opencv3 to be installed at the same time?

One thing I have noticed, if I install with the `with-python3` option, it does not seem to work in python3. If I run python3, then type` import cv2`, I get `ImportError: No module named 'cv2'`. But it does work in python 2 for me. I'm not sure how to fix that. Any ideas?

**Comment by Schultzer** [comment]
@kuchi
I don't think `ImportError: No module named 'cv2'` is related.
Did you link opencv3 python3.?

It might look like this:
`ls /usr/local/Cellar/opencv3/3.2.0/lib/python3.6/site-packages/cv2.cpython-35m-darwin.so`

I leave this decision to @jonchang and the homebrew maintainers. (I have know idea of what is best practice in these situations)

**Comment by jonchang** [comment]
Ok since this finally went through the CI queue I'm just going to merge this version bump. Thanks for your help everyone! 

@Schultzer please file a follow up pull request to revision bump `visp`
@kuchi please file a follow up pull request to add the new utility applications as an option. Feel free to also file an issue regarding the python 3 incompatibility.

**Pull request closed without merging**
