### PR TITLE
samtools 1.6

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
I think this failed because it needs `htslib 1.6` to be packaged first 
```
bam_sort.c:43:27: fatal error: htslib/hts_os.h: No such file or directory
```
which is submitted as https://github.com/Homebrew/homebrew-science/pull/6361

**Comment by tseemann** [comment]
@ilovezfs this is new to me. I'll change the symlink in the repo.

```
Error: 2 problems in 1 formula
homebrew/science/samtools:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases
      ln -s ../samtools.rb samtools@1.6
  * Formula has invalid versioned aliases:
      homebrew/science/samtools@1.5
```

**Comment by ilovezfs** [comment]
Just use `git mv` to rename it.

**Comment by tseemann** [comment]
@ilovezfs i thought we fixed this with the `git mv` ?

```
Error: 2 problems in 1 formula
homebrew/science/samtools:
  * Formula has other versions so create a versioned alias:
      cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases
      ln -s ../samtools.rb samtools@1.6
  * Formula has invalid versioned aliases:
      samtools@1.6
==> FAILED
```

**Comment by sjackman** [comment]
@BrewTestBot Test this please.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/Homebrew/homebrew-science/pull/6509

**Pull request closed without merging**
