### PR TITLE
Mhap

### PR DESCRIPTION
**Pull request by sjackman**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman - can we will this in?  it has 2 commits instead of the usual squashed 1 ?

**Comment by sjackman** [comment]
There's one commit for MHAP 1.6, though I didn't bother to bottle it, and one commit for MHAP 2.0.

**Comment by sjackman** [comment]
The bottle expired on Bintray. Rebuilding.

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Merged MHAP 2.0

**Pull request closed without merging**
