### PR TITLE
clfft 2.6.1

### PR DESCRIPTION
**Pull request by John-Colvin**
A few extra changes:
* Don't build the examples any more, otherwise they get installed in "${bin}/examples"
* actually test the client

### CODE REVIEW

**Comment by dpo** [comment]
Would it make sense to ask `cmake` to install the binaries to `libexec` and only link the actual executables in `bin`?

**Comment by John-Colvin** [comment]
why? I thought ```libexec``` was for executable dependencies that aren't meant for using directly?

**Comment by dpo** [comment]
It allows you to install the examples but only link actual executables in `bin` to avoid `brew audit` complaining. Several formulas use this trick, especially to keep `lib` clean. See, e.g., `asl.rb`.

**Comment by John-Colvin** [comment]
Ok, but why bother building the examples anyway? From an installation standpoint, they're just bloat.

**Comment by dpo** [comment]
Wouldn't a user want to look at them, and run them?

**Comment by John-Colvin** [comment]
As far as I can tell, the example sources aren't installed by cmake anyway even if they are built.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
The test is failing.

**Comment by John-Colvin** [comment]
test is a 404

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by John-Colvin** [comment]
The problem is this: clFFT is broken on CPUs. The only openCL device on the autotester is a CPU.

**Comment by dpo** [comment]
Thanks for investigating. Should this be reported upstream then?

**Comment by John-Colvin** [comment]
If I remember correctly, it's a relatively well-known long-standing bug in Apple's OpenCL implementation. clFFT are aware of it and I'm sure they've done their fair share of complaining to Apple.

**Comment by dpo** [comment]
Do I need anything special to test this locally? When I run the test on my machine (which has a gpu) I get
```
$ clFFT-client -g -x 192 -y 108 --inLayout 5 --outLayout 3
OPENCL_V_THROWERROR< CLFFT_DEVICE_NOT_AVAILABLE > (456): No devices available
clFFT error condition reported:
OPENCL_V_THROWERROR< CLFFT_DEVICE_NOT_AVAILABLE > (456): No devices available
```

**Comment by John-Colvin** [comment]
That's very odd. You shouldn't need anything extra, assuming your graphics card is supported by Apple's OpenCL implementation.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
See #3163 for version 2.8.0. Comments welcome.

**Comment by dpo** [comment]
Superseded by #3189.

**Pull request closed without merging**
