### PR TITLE
gmt 5.4.1

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by claudiodsf** [comment]
GMT 5.4.1 just came out. Would you mind updating this PR?

**Comment by seisman** [comment]
@claudiodsf Updated now.

**Comment by claudiodsf** [comment]
Both test fails are related to linuxbrew. Shall we ignore those and merge this PR?

**Comment by iMichka** [comment]
@seisman Thanks for your contribution.

I'm working on a fix for the Linux builds in a separate patch.

**Pull request closed without merging**
