### PR TITLE
ENH : enable openmp for openmeeg

### PR DESCRIPTION
**Pull request by agramfort**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

There is already a test but it's not specific to openmp

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

cc @iMichka

### CODE REVIEW

**Comment by agramfort** [comment]
@iMichka would it make sense to have openmp on by default or this is not recommended?

**Comment by iMichka** [comment]
It depends. If it is a feature that everybody may want to use, it should not be an option. Because this means people will need to recompile from source instead of using the pre-compiled binaries. Options are also often untested by the CI so compilation bugs are often hidden away from is when we bump version.

On the other side this "option" adds a dependency more, which may or may not be a good thing.

You could make it "recommended" if you think it is a sensible default. I am not an openmeeg user so I have no strong opinion here.

**Comment by agramfort** [comment]
in practice it gives huge speed ups as internal code is massively parallel.
With 4 real independent CPUs you get almost a 4x speed up. I would
therefore to make it default. It also reduce the chances of bugs with the
use of options.

let me try to turn it on by default.

**Comment by agramfort** [comment]
done

**Comment by iMichka** [comment]
@agramfort Thanks for your contribution!

**Pull request closed without merging**
