### PR TITLE
rstudio-server v1.1.383

### PR DESCRIPTION
**Pull request by randy3k**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by randy3k** [comment]
Not sure why travis build failed...

**Comment by ilovezfs** [comment]
This may help you with figuring out Java 9 compatibility: http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-May/012673.html

**Comment by randy3k** [comment]
It seems that linuxbrew was not able to pick up java 8 on circle ci although `jdk@8` was installed and `depends_on :java => "1.8"` is specified. But travis ci build worked, not sure why. 

Perhaps the linuxbrew crew knows the reason @sjackman @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
I don't work on Linuxbrew so please don't CC me for Linux issues, thanks.

**Comment by iMichka** [comment]
@randy3k this is a known problem: https://github.com/Linuxbrew/brew/issues/509
And nobody is currently working on this.

**Comment by sjackman** [comment]
I don't see any helpful error message in the build log other than this:
```
==> cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DRSTUDIO_USE_LIBCXX=Yes -DRSTUDIO_USE_SYSTEM_BOOST=Yes -DBOOST_ROOT=/home/linuxbrew/.linuxbrew/opt/boost -DBOOST_INCLUDEDIR=/home/linuxbrew/.linuxbrew/opt/boost/include -DBOOST_LIBRARYDIR=/home/linuxbrew/.linuxbrew/opt/boost/lib -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/rstudio-server/1.1.383/rstudio-server -DCMAKE_CXX_FLAGS=-I/home/linuxbrew/.linuxbrew/opt/openssl/include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DCMAKE_EXE_LINKER_FLAGS=-L/home/linuxbrew/.linuxbrew/opt/openssl/lib -L/home/linuxbrew/.linuxbrew/opt/boost/lib
.
==> make install
......
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/rstudio-server/02.make:

Total time: 4 seconds
src/gwt/CMakeFiles/gwt_build.dir/build.make:57: recipe for target 'gwt_build' failed
make[2]: *** [gwt_build] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/gwt/CMakeFiles/gwt_build.dir/all' failed
make[1]: *** [src/gwt/CMakeFiles/gwt_build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Do you figure that error is because it's not finding `java`?
https://circleci.com/gh/Homebrew/homebrew-science/6680

**Comment by sjackman** [comment]
Currently `brew` searches three places for the `java` executable:
1. `$JAVA_HOME/bin/java`
2. The `jdk` formula
3. The `PATH`

https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/java_requirement.rb#L64

It doesn't search the versioned `jdk@*` formulae. Longer term solution: you could submit a PR that modifies`brew` to search the versioned `jdk` formulae. Shorter term solution: you can set `JAVA_HOME` to `Formula["jdk@8"].prefix` You could also open an issue with upstream maintainers to ask that they add support for Java 9.

**Comment by randy3k** [comment]
the error occurred because it was using Java 9 instead of Java 8 though the requirement is specified. I can repeat the same error locally. For some reason, Travis was able to pick Java 8 up, maybe it picked the system Java?

**Comment by sjackman** [comment]
Try (untested)…
```ruby
ENV["JAVA_HOME"] = Formula["jdk@8"].prefix
```

**Comment by sjackman** [comment]
Homebrew/science is being deprecated at the end of this year. This formula is up for migration to Homebrew/core. See issue https://github.com/Homebrew/homebrew-science/issues/6331. You can if you like submit a "Migrate formula" PR to Homebrew/core. If you have the time and interest, feel free to submit any other formulae on this list to Homebrew/core.

Note that Homebrew/core supports only macOS, not Linux. Any Linux-specific bits of code should be removed from the formula when submitting to Homebrew/core. Once the formula is accepted into Homebrew/core, you can submit a separate PR to Linuxbrew/core to add back support for Linux. After that we'll continue to maintain the formula.

**Comment by randy3k** [comment]
closing this and submit directly to homebrew and linuxbrew core.

**Comment by sjackman** [comment]
Moved to PR https://github.com/Homebrew/homebrew-core/pull/20309

**Pull request closed without merging**
