### PR TITLE
xmi-msim: support for gsl 2.x

### PR DESCRIPTION
**Pull request by tschoonj**
See discussion with @ilovezfs in Homebrew/homebrew-core#4341

The build will fail until 4341 and the formula-patch PR are both merged in.

### CODE REVIEW

**Comment by ilovezfs** [comment]
does ` (share / "xmimsim").install "xmimsimdata.h5"` have to be at that specific path?

If not, I'd prefer
```
pkgshare.install "xmimsimdata.h5"
```
which will put it in share/"xmim-sim" instead.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@tschoonj any idea why `xmimsim-cl.so` isn't being installed as `xmimsim-cl.dylib`?

**Comment by tschoonj** [comment]
1. yes it has to be exactly in `share / "xmimsim"` as the path is hardcoded into the binaries

2. that's normal since `xmimsim-cl.so` is a plugin, not a shared library. The extension of plugins is meaningless, though both `.bundle` and `.so` are heavily used on OS X. Python uses `.so` for example on both Linux and OS X.

**Comment by ilovezfs** [comment]
@tschoonj OK. The url is
```
https://raw.githubusercontent.com/Homebrew/formula-patches/a810aca/xmi-msim/gsl-2.x.patch
```

https://raw.githubusercontent.com/Homebrew/formula-patches/a810aca/xmi-msim/gsl-2.x.patch

**Comment by ilovezfs** [comment]
Closes via

https://github.com/Homebrew/homebrew-science/commit/ecd51c87014594e923687ecd6cc08cce9882cd4d

and

https://github.com/Homebrew/homebrew-science/commit/31608b0b78df82bf5272c6deb3992391cc785a60

**Comment by ilovezfs** [comment]
@tschoonj Thanks for working on this today and I'll be looking forward to the new release whenever you're ready. Also, thanks so much for the advice on what to do with the 1.x series and for warning us to hold for a while on 2.x. It will be a much easier transition now due to your counsel.

:tada:

**Comment by tschoonj** [comment]
And I am very grateful to you! I am glad you taught me about the `hub` package: really cool stuff!

**Comment by ilovezfs** [comment]
@tschoonj yeah the hub command is awesome. Also, it's the backend for the new bump-formula-pr command and boneyard-formula-pr command:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/boneyard-formula-pr.rb

**Comment by tschoonj** [comment]
@ilovezfs Can I close this PR? It's merged in already right?

**Comment by ilovezfs** [comment]
@tschoonj done.

**Comment by tschoonj** [comment]
Thanks!

**Pull request closed without merging**
