### PR TITLE
root6: root6 6.08.02

### PR DESCRIPTION
**Pull request by equal-l2**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

Now supports Fortran and FFTW.

### CODE REVIEW

**Comment by equal-l2** [comment]
Building ROOT seems to take too much time, Travis has aborted.
Is there anything I can?

**Comment by henryiii** [comment]
I'd like to see this added, too, I was just about to change it myself.

**Comment by henryiii** [comment]
By the way, Travis has been having issues with it's Mac builds, that could be part of why it timed out.

**Comment by ilovezfs** [comment]
It's pretty typical for Travis to time out. FYI: https://github.com/Homebrew/homebrew-science/blob/master/.travis.yml#L2 ... we only have Travis testing Linux.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by equal-l2** [comment]
Ready to merge now.

**Comment by equal-l2** [comment]
@ilovezfs 
Is there any problem other than Travis timeout?

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Looks like this was bit by Homebrew/brew#1761.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Thanks @equal-l2!

**Pull request closed without merging**
