### PR TITLE
breseq 0.28.1

### PR DESCRIPTION
**Pull request by tseemann**
breseq is a computational pipeline for finding mutations relative to a reference sequence in short-read DNA re-sequencing data for microbial sized genomes. breseq is a command line tool implemented in C++ and R. It will compile and function on a variety of Unix platforms, including MacOSX. It reports single-nucleotide mutations, point insertions and deletions, large deletions, and new junctions supported by mosaic reads (such as those produced by new mobile element insertions) in an annotated HTML format.

### CODE REVIEW

**Comment by tseemann** [comment]
Hmm, it fails only on OS X 10.9  - any ideas?

```
Error: homebrew/science/breseq: failed
invalid byte sequence in US-ASCII
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:302:in `assert_match'
/usr/local/Library/Taps/homebrew/homebrew-science/breseq.rb:31:in `block in <class:Breseq>'
/usr/local/Library/Homebrew/formula.rb:1284:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1280:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by tseemann** [comment]
Here we go again:
```
Error: 1 problem in 1 formula
homebrew/science/breseq:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```
It is published and most people don't get it via github.

**Comment by ilovezfs** [comment]
Is there a programmatic way to check for a doi? If so, we can fix this with a pull request to modify the notability check to also include that as a valid way to fulfill the diagnostic.

**Comment by tseemann** [comment]
@ilovezfs at the moment the `doi` and `tag` attributes are commented out, but in practice @sjackman encourages us to use them, and we do. they are useful for generating links to the publications etc.  eventually they will be official I think.

**Comment by ilovezfs** [comment]
@tseemann we could just have audit grep the formula text in the mean time.

**Comment by tseemann** [comment]
@ilovezfs i assume this logic is in OSX homebrew core?

**Comment by sjackman** [comment]
Yep. It's at https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L602

**Pull request closed without merging**
