### PR TITLE
gdcm: add option to build static libraries

### PR DESCRIPTION
**Pull request by waldyrious**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by waldyrious** [comment]
I modeled this change on similar formulas, such as the [alpscore.rb](https://github.com/Homebrew/homebrew-science/blob/master/alpscore.rb) formula. Also, note that static build is the default configuration in GDCM's CMake setup -- should we update the formula to match that?

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Hi. Sorry for the delay. I think this can go in as-is, I think most thinks are build with shared libs in homebrew, at least the last formulas I saw.

Just want to see the output of the mac build, and this can be merged.

**Comment by iMichka** [comment]
@waldyrious Thanks for your contribution.

**Pull request closed without merging**
