### PR TITLE
clarify rJava caveat in r.rb

### PR DESCRIPTION
**Pull request by gwerbin**
Add a programmatic way to construct the `R CMD javareconf` command.

### CODE REVIEW

**Comment by tdsmith** [comment]
Is this right? Oracle JRE's shouldn't install anything to /System.

**Comment by tdsmith** [comment]
Nevermind, I see.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
```
       Error: 2 problems in 1 formula homebrew/science/r:
 * Use `depends_on :java` to set JAVA_HOME
 * Use `depends_on :java` to set JAVA_HOME
```

**Comment by gwerbin** [comment]
@tseemann I'm not sure I understand the error. It's just a caveat in the "info" section, not a requirement for R. I didn't want to start messing around with adding a `--with-homebrew-java` flag or something like that.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
