### PR TITLE
ome-files 0.4.0

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
### Have you:

- [*] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [*] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [*] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [*] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [N/A] Removed the `revision` line, if any, when bumping the version number?
- [N/A] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [*] Not altered the `bottle` section?
- [*] Checked that the tests still pass?

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Superseded by https://github.com/Homebrew/homebrew-science/pull/5964

**Comment by rleigh-codelibre** [comment]
Great, all tests are green.  Linuxbrew has improved since the previous attempt!

**Comment by rleigh-codelibre** [comment]
Are the changes proposed here OK, or are any changes required prior to merging?

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Thanks for contributing to Homebrew, @rleigh-codelibre, and sorry it took so long! This has been merged.

**Comment by rleigh-codelibre** [comment]
Thank you!

**Pull request closed without merging**
