### PR TITLE
astrometry-net 0.72

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by iMichka** [comment]
Duplicate of #5873, but feel free to take over if you have time :)

**Comment by jonchang** [comment]
Closing for https://github.com/Homebrew/homebrew-science/pull/6083

**Comment by iMichka** [comment]
@jonchang that was still version 0.70 on the other PR, and the Linux bottles didn't get built.

**Comment by jonchang** [comment]
Oh lol I'll reopen this one then

**Comment by iMichka** [comment]
Closing here, I'm taking over in #5873

**Pull request closed without merging**
