### PR TITLE
rapsearch2: bump revision for boost: error: call of overloaded advance

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
```
g++ -c -O3 -w  mergeUnit.cpp -o mergeUnit.o -I/home/linuxbrew/.linuxbrew/opt/boost/include
HashSearch.cpp: In member function ‘int CHashSearch::BuildDHash(const char*, std::string&, int, bool)’:
HashSearch.cpp:261:34: error: call of overloaded ‘advance(ITER&, uint)’ is ambiguous
    advance(itStop, unLeft+nRead+1);
```
https://travis-ci.org/Homebrew/homebrew-science/builds/268145896#L1670

**Comment by sjackman** [comment]
Looks like an ambiguity between `std::advance` and `boost::advance`, which is most likely an upstream bug.

**Comment by tmozgach** [comment]
@sjackman I see. I will report to the author and get rid of it from this image.

**Comment by tseemann** [comment]
@sjackman can you also add
```
+    chmod "a+r", "readme"
     doc.install "readme"
```
to resolve https://github.com/Homebrew/homebrew-science/issues/5797 too?

**Comment by iMichka** [comment]
Please rebase, so that the Linux bottles get built with gcc5. Thanks (https://github.com/Linuxbrew/homebrew-core/issues/4065)

**Comment by sjackman** [comment]
@tmozgach Can you please address Torsten's request (https://github.com/Homebrew/homebrew-science/pull/6201#issuecomment-325164163) and rebase this PR? Maybe it will build with `gcc-5`.

**Comment by tmozgach** [comment]
@sjackman I rebased that, but it doesn't work.

**Comment by iMichka** [comment]
And a second rebase is needed for boost 1.65.1

**Pull request closed without merging**
