### PR TITLE
amos: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman could you look at? It fails also without my changes. Any idea?

**Comment by sjackman** [comment]
TravisCI
```
Unwanted system libraries:
  libQt3Support.so.4
  libQtCore.so.4
  libQtGui.so.4
```
https://travis-ci.org/Homebrew/homebrew-science/builds/264563615?utm_source=github_status&utm_medium=notification

Succeeds on CircleCI, so merging.

**Comment by sjackman** [comment]
It currently fails to build on macOS
```
clang++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/CelMsg -I../../src/Slice -I../../src/Common -I../../src/AMOS -I../../src/GNU -I../../src/Foundation   -g -O2 -c -o genome-complexity-fast.o genome-complexity-fast.cc
genome-complexity-fast.cc:21:54: error: reference to 'hash' is ambiguous
typedef HASHMAP::hash_multimap<Mer_t, MerVertex_t *, hash<unsigned long> > MerTable_t;
                                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3171:29: note: candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct hash;
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/__hash:22:54: note: candidate found by name lookup is '__gnu_cxx::hash'
template <typename _Tp> struct _LIBCPP_TYPE_VIS_ONLY hash { };
                                                     ^
```
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1209/

That could be addressed in a separate PR.

**Comment by sjackman** [comment]
`fails_with :clang` may be enough to get it building on macOS.

**Comment by sjackman** [comment]
Thanks for this PR, Tanya. And good work on vendoring a PERL module. That's awesome!

**Comment by sjackman** [comment]
I accidentally merged the bottle from this PR without the commit that modified `amos`. I've merged it now in 939d58adaa6179b0c18b2b71ec24c6aa3ebecd7c

**Pull request closed without merging**
