### PR TITLE
GATK 3.6-6 (with SRA support)

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tseemann** [comment]
Arrgh, i've encountered the `kafka` bug .

```
Error Message

failed: brew uses homebrew/science/gatk
Stacktrace

        Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/kafka.rb:11: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/kafka.rb:14: syntax error, unexpected ===, expecting keyword_end
=======
   ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formula.rb:1196:in `block in each'
/usr/local/Library/Homebrew/formula.rb:1194:in `each'
/usr/local/Library/Homebrew/formula.rb:1194:in `each'
/usr/local/Library/Homebrew/cmd/uses.rb:46:in `select'
/usr/local/Library/Homebrew/cmd/uses.rb:46:in `uses'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
```

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
How does it know @sjackman  ?

`Error: You must first download GATK from
http://www.broadinstitute.org/gatk/download
to /Users/brew/Jenkins/pr-science/version/yosemite/home/Downloads/GenomeAnalysisTK-2.8-1.tar.bz2`

**Comment by sjackman** [comment]
The error is caused by an old buggy `gatk` formula that I attempted that was committed and then quickly deleted. See https://github.com/Homebrew/homebrew-science/pull/4428

**Comment by sjackman** [comment]
Superseded by #4426

**Pull request closed without merging**
