### PR TITLE
Petsc 3.6.1 (fix)

### PR DESCRIPTION
**Pull request by davydden**
Fix a bug introduced during the switch to Superlu43

### CODE REVIEW

**Comment by dpo** [comment]
Duh. Sorry about that. But I don't understand how in the world the build succeeded on the bot previously...

**Comment by davydden** [comment]
it succeeded because it built without `superlu`, so that part `if build.with?` never got executed.

**Comment by dpo** [comment]
But `superlu` was `:recommended`?!

**Comment by davydden** [comment]
well, it does not matter. `superlu43` got installed, but it never got into `if build.with? "superlu"` and effectively PETSc was configured without superlu.

**Comment by dpo** [comment]
That's right.

**Pull request closed without merging**
