### PR TITLE
vislcg3: revision for icu4c

### PR DESCRIPTION
**Pull request by dtrebbien**
See Homebrew/homebrew#46374

### CODE REVIEW

**Comment by dunn** [comment]
In the install block of vislcg3, add a patch for `CMakeLists.txt`:
```ruby
# Patch submitted to tino@didriksen.cc on 2015-11-27
inreplace "CMakeLists.txt", "share/emacs/site-lisp", elisp
```
I just sent that email, so don't worry about reporting upstream.

**Comment by dtrebbien** [comment]
New commit added containing your `inreplace` line and comment.  Locally, this fixes the `brew audit`.

**Comment by dtrebbien** [comment]
Because ucto depends on libfolia, I think that I will need to submit a different PR to bump ucto's revision.  I have removed the ucto-related commit from this PR.

**Comment by dtrebbien** [comment]
ping

**Comment by dunn** [comment]
(FYI I'm not part of @Homebrew/science so I'll let one of them merge this.)

**Pull request closed without merging**
