### PR TITLE
gmt: revision for netcdf

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by claudiodsf** [comment]
Pinging on this. Not sure about the travis error. This PR builds locally on my machine without any error (`brew install --build-bottle --verbose https://raw.githubusercontent.com/jonchang/homebrew-science/412fa485feca3bc5e7ceca7b26057ad28a39ab0c/gmt.rb`).

```
HOMEBREW_VERSION: 1.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 619791e83d2781dca1b675e20249a8aebe085c7c
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 26eda717a7ed5648ec367071c2b383dece8ff742
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/opt/ruby/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by ilovezfs** [comment]
@claudiodsf yes, if you check the git commit history for science you'll see we're working through these PRs for netcdf one at a time and it'll be done soon enough

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by claudiodsf** [comment]
The test fails again, with this error message:
```
CMake Error at cmake/modules/FindNETCDF.cmake:132 (message):
  Library found but netCDF-4/HDF5 format unsupported.  Do not configure
```
Looking at [this thread](http://gmt.soest.hawaii.edu/boards/1/topics/2230), it might be necessary to have HDF5 installed as well.

**Pull request closed without merging**
