### PR TITLE
Hdf5: Specify MPI compilers.

### PR DESCRIPTION
**Pull request by dpo**
Allows to build against MPICH.

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please.

**Comment by iml** [comment]
Perhaps we should consider building the Fortran and C++ bindings by default? I don't know of any side-effects.

**Comment by dpo** [comment]
I'm not really a user of `hdf5` so I'm not sure either. A few other formulas require the C++ bindings, but nobody requires Fortran it seems.
````
$ egrep "depends_on[ ]+[\'\"]hdf5[\'\"]" *.rb
alembic.rb:  depends_on "hdf5"
blasr.rb:  depends_on "hdf5" => "with-cxx"
blast.rb:  depends_on "hdf5"     => :optional
cdo.rb:  depends_on "hdf5"
cgns.rb:  depends_on 'hdf5' => :recommended
field3d.rb:  depends_on 'hdf5'
flann.rb:  depends_on "hdf5"
h5utils.rb:  depends_on 'hdf5'
insighttoolkit.rb:  depends_on 'hdf5' => [:recommended, "with-cxx"] + cxx11dep
libmatio.rb:  depends_on 'hdf5' => :optional
mathgl.rb:  depends_on 'hdf5'    => :optional
minc.rb:  depends_on 'hdf5'
moab.rb:  depends_on 'hdf5'
netcdf.rb:  depends_on "hdf5"
nexusformat.rb:  depends_on "hdf5" => (build.cxx11? ? "c++11" : :build)
octave.rb:  depends_on "hdf5"           => :recommended
openimageio.rb:  depends_on "hdf5" => "with-cxx"
openmeeg.rb:  depends_on 'hdf5'
paraview.rb:  depends_on "hdf5"
petsc.rb:  depends_on "hdf5"         => ["with-mpi", :recommended]
radx.rb:  depends_on "hdf5" => "with-cxx"
seqdb.rb:  depends_on 'hdf5'
shogun.rb:  depends_on 'hdf5' => :recommended
statismo.rb:  depends_on "hdf5" => :build
vigra.rb:  depends_on "hdf5" => :recommended
vtk.rb:  depends_on "hdf5" => :recommended
vtk5.rb:  depends_on "hdf5" => :recommended
````

**Comment by iml** [comment]
Yea the `with-cxx` deps will often cause this to be rebuilt from source. Can do it on another PR, though.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by iml** [comment]
@mikemcquaid please kill this: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/863/. Is it possible for a rebuild to stop an existing build on the same PR?

In any case these changes don't impact the bottle so we can skip the full test-bot process here.

**Pull request closed without merging**
