### PR TITLE
suite-sparse 4.5.4 and petsc 3.7.5

### PR DESCRIPTION
**Pull request by schoeps**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by schoeps** [comment]
Checks fail because I did not bump dependencies, e.g. `Library not loaded: /usr/local/opt/suite-sparse/lib/libsuitesparseconfig.4.5.3.dylib`. Shall I do that? How do I get a complete list of formulas that dependent on suite-sparse?

**Comment by ilovezfs** [comment]
```
brew uses suite-sparse
```
for the main list, and
```
brew uses --include-optional --include-build --recursive suite-sparse
```
for the full list including possibly irrelevant items.

**Comment by schoeps** [comment]
well, then I a add also the modification to octave and sundials (which were the reason for me to update suite-sparse)

**Comment by ilovezfs** [comment]
@schoeps yup. By the way, while I have your attention... I tried to build Octave with the development versions of pyqt5, qscintilla2, and sip, which are Qt 5.8 compatible, and Octave ends up dying during make check with core dumps. Commenting out make check then moves the crash to run time when I run `brew test octave`. So we have a problem :)

**Comment by schoeps** [comment]
Oh nooooo.... I was hoping for qt5.8 to make things better :) How do I test this? Is it sufficient to compile qt5, pyqt5, qscintilla2, and sip with --head or --devel?

**Comment by ilovezfs** [comment]
@schoeps you need the downloads from their site:
https://www.riverbankcomputing.com/software/pyqt/download5
https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5_gpl-5.8.dev1702091323.tar.gz

https://www.riverbankcomputing.com/software/qscintilla/download
https://www.riverbankcomputing.com/static/Downloads/QScintilla/QScintilla_gpl-2.10.dev1701211518.tar.gz

https://www.riverbankcomputing.com/software/sip/download
https://www.riverbankcomputing.com/static/Downloads/sip/sip-4.19.1.dev1702081834.tar.gz

And then the formula references have to be updated to use qt5 instead of qt@5.7.

**Comment by schoeps** [comment]
@ilovezfs Thanks. I will start playing. Let see if I can help. However, most octave developers (like me) do not care too much about the gui. We tend to use the cli interface for our computations and therefore the gui stuff is not very well maintained :(

**Comment by ilovezfs** [comment]
https://gist.github.com/ilovezfs/066e4e3213dc14ac16af842f19055798
https://gist.github.com/ilovezfs/136e723f61e916aac4e042437a478b22

@schoeps the versions are now outdated I think but that's what I had the last time I was poking at it.

**Comment by ilovezfs** [comment]
@schoeps looks like there was installation failure for octave on 10.11. https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/7213/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_science_octave/

**Comment by ilovezfs** [comment]
Pulled without the octave or getdp commits which I'll relocate to separate PRs.

**Comment by ilovezfs** [comment]
- [ ] getdp (https://github.com/Homebrew/homebrew-science/pull/5111)
- [ ] octave (https://github.com/Homebrew/homebrew-science/pull/5112)

**Pull request closed without merging**
