### PR TITLE
Pspp 0.10.2 update

### PR DESCRIPTION
**Pull request by carcus88**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by carcus88** [comment]
@dpo Whats does @BrewTestBot do? Is there some manual step I need to take to make it test this?

**Comment by dpo** [comment]
It restarts the test bot. Normally, no action is required on your part. I'll restart it again because it seems there was a problem.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
