### PR TITLE
biokanga 3.4.5 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
BioKanga - an integrated suite of high performance bioinformatics applications targeting the challenges of next generation sequencing analytics. Kanga is an acronym standing for 'K-mer Adaptive Next Generation Aligner' and is the primary application. This latest release (3.4.5) offers NGS QC, alignments, transcriptome DE, and enhanced de Novo assembly/scaffolding.

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1441/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_Homebrew_science_biokanga/
```
clang++ -DHAVE_CONFIG_H -I. -I.. -I../hdrs -I../ -I    -g -O2 -MT CSVFile.o -MD -MP -MF .deps/CSVFile.Tpo -c -o CSVFile.o CSVFile.cpp
In file included from CSVFile.cpp:19:
In file included from ././commhdrs.h:41:
In file included from ././conservlib.h:21:
././SfxArrayV2.h:307:2: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
```

**Comment by sjackman** [comment]
`fails_with :clang` perhaps?

**Comment by tseemann** [comment]
@BrewTestBot please test this

**Comment by sjackman** [comment]
@tseemann The BrewTestBot mantra must be exactly the phrase `@BrewTestBot test this please` in its comment.

**Comment by sjackman** [comment]
Pushing a revised patch also triggers a test cycle. The mantra's only necessary to kick off a second test without modifying the formula.

**Comment by sjackman** [comment]
```
g++-4.9 -DHAVE_CONFIG_H -I. -I.. -I../hdrs -I../ -I    -g -O2 -MT CSVFile.o -MD -MP -MF .deps/CSVFile.Tpo -c -o CSVFile.o CSVFile.cpp
In file included from ././conservlib.h:21:0,
                 from ./commhdrs.h:41,
                 from AlignValidate.cpp:19:
./././SfxArrayV2.h:307:2: error: 'pthread_spinlock_t' does not name a type
  pthread_spinlock_t m_hSpinLockBaseFlags; // used to serialise updates to base flags
  ^
```

**Comment by sjackman** [comment]
Hmm. No, luck. Can you open an issue with the upstream author?

**Comment by tseemann** [comment]
It seems that struct is not supported on OS X ?
http://stackoverflow.com/questions/8177031/does-mac-os-x-have-pthread-spinlock-t-type

**Comment by sjackman** [comment]
You could add a `LinuxRequirement` to this formula that is satisfied by `OS.linux?`
See https://github.com/Homebrew/homebrew-science/blob/master/allpaths-lg.rb#L1

**Comment by iMichka** [comment]
@sjackman Looking at this, it looks like a dead project.

- No new release since the one added here (3.4.5), which was published in 2014.
- Downloads/week are at 0 on the source forge page (though there were around 170 all in all).
- An attempt to move to GitHub, which didn't really succeed https://github.com/ste69r/Biokanga/issues/1

I would be in favour to drop this PR, until the project gets more interest/updates/momentum.

**Comment by sjackman** [comment]
@tseemann Would you like to move this PR to https://github.com/tseemann/homebrew-bioinformatics-linux ?

**Comment by iMichka** [comment]
Let's pass on this for the moment. Nothing is lost, if somebody wants to hack around, the content of this PR can be revived later.

**Pull request closed without merging**
