### PR TITLE
spades37 3.7.1 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
circlator, at least as of version 1.3.0, gives better results with
spades 3.7.1.

See https://github.com/Homebrew/homebrew-science/pull/4050.

### CODE REVIEW

**Comment by sjackman** [comment]
I would prefer not to accept this formula and instead work on the core Brew functionality to install arbitrary older versions of bottles. See https://github.com/Homebrew/brew-evolution/pull/6

**Comment by ilovezfs** [comment]
Yeah, that's pure pie in the sky to me at this point, but I'm happy if you're happy ;)

**Comment by sjackman** [comment]
Closing unless there's overwhelming support for this PR from other @Homebrew/science

**Comment by sjackman** [comment]
I spoke and acted too soon. See https://github.com/Homebrew/homebrew-science/pull/4050#issuecomment-239625864

**Comment by ilovezfs** [comment]
@sjackman based on https://github.com/sanger-pathogens/circlator/issues/72#issuecomment-239632498 it looks like your initial instinct to close this was correct.

**Comment by sjackman** [comment]
Martin (upstream author @martinghunt) says that using SPAdes 0.9.0 is fine.
https://github.com/sanger-pathogens/circlator/issues/72#issuecomment-239632498
> If it's a pain, go with 3.9.0.

**Pull request closed without merging**
