### PR TITLE
gnudatalanguage 0.9.7

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

CC @iMichka @tschoonj

### CODE REVIEW

**Comment by tschoonj** [comment]
This one is a major PITA. Would be surprised if it works without patching

**Comment by ilovezfs** [comment]
It at least appears to :)

```
98% tests passed, 4 tests failed out of 179
```

**Comment by tschoonj** [comment]
Have you tried launching it and generating a simple plot?

Something like:

````
TVSCL, DIST(100)
````

**Comment by tschoonj** [comment]
also, try this:

````
PLOT, INDGEN(100)
````

**Comment by ilovezfs** [comment]
screen shot 2017-02-03 at 8 26 06 am

**Comment by ilovezfs** [comment]
screen shot 2017-02-03 at 8 26 43 am

**Comment by tschoonj** [comment]
Praise jesus :bowing_man:  :smile:

**Comment by tschoonj** [comment]
Those failing tests: something to worry about?

**Comment by ilovezfs** [comment]
```
The following tests FAILED:
	 80 - test_execute.pro (Failed)
	 84 - test_fft_leak.pro (Failed)
	108 - test_image_statistics.pro (Failed)
	128 - test_obj_isa.pro (Failed)
```

**Comment by tschoonj** [comment]
Well, you may want to mention this on their SF bugtracker...

**Comment by ilovezfs** [comment]
Voilà: https://sourceforge.net/p/gnudatalanguage/bugs/716/

**Comment by ilovezfs** [comment]
Same failures with hdf5 1.8.18 as 1.10.0-patch1

**Pull request closed without merging**
