### PR TITLE
APE 2.2.1 (new formula)

### PR DESCRIPTION
**Pull request by davydden**
A tool for generating atomic pseudopotentials within a Density-Functional Theory framework.
An alternative to https://github.com/Homebrew/homebrew-science/pull/1774

### CODE REVIEW

**Comment by dpo** [comment]
Did you by any chance report the test failures upstream?

**Comment by davydden** [comment]
Yes. Tolerances for "almost-passed" tests will be tweaked.
The main developer also told that the failing test with big difference is due to an outdated "blessed" file which was obtained with libxc library before they fixed a bug.

**Comment by davydden** [comment]
Here's a relevant discussion on the mailing list:

http://www.tddft.org/pipermail/ape-users/2015-March/000244.html

**Comment by davydden** [comment]
what's that `build error`? I just run reinstall and it works fine on `Yosemite`. 
Could that be related to conflicts of names, i.e. there is another `ape` in the main Homebrew repo?

**Comment by dpo** [comment]
Sorry, let me restart the build.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@mikemcquaid The bot doesn't seem to be down but it's not picking up build requests.

**Comment by mikemcquaid** [comment]
@dpo The issue seems to be rerunning builds rather than not picking up PRs. I'll take a look.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
The build ran again.

**Comment by dpo** [comment]
Many thanks @mikemcquaid !

**Comment by xu-cheng** [comment]
This formula has conflicted name. Reverted in c275d1c3e803ceea7825e4d9e7b04ce8339759ef

**Comment by davydden** [comment]
didn't know about this policy, resubmitted with a different name.

**Comment by dpo** [comment]
Oops, sorry about that.

**Pull request closed without merging**
