### PR TITLE
dssp: revision 3 for boost

### PR DESCRIPTION
**Pull request by jonchang**
Created with `brew bump-revision-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
using C++11 https://gist.github.com/ilovezfs/b74d6c21c19c019a2e91a172569232b0
using Boost https://gist.github.com/ilovezfs/89b04ada4611d6733319db2eeca43f19

@sjackman do you have a preference?

**Comment by sjackman** [comment]
I prefer C++11.

**Comment by jonchang** [comment]
Shall I submit to formula-patches, update this PR, and notify upstream of a patch?

**Comment by iMichka** [comment]
@jonchang Please rebase for boost 1.65.1

**Pull request closed without merging**
