### PR TITLE
oce: fix Linux build

### PR DESCRIPTION
**Pull request by iMichka**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman 
> configure: error: GL/gl.h or OpenGL/gl.h is needed
on the circle build. I though adding mesa would have helped, but that is not enough. I can locally build it on my Ubuntu Xenial, but I have a lot of cruft installed :)

**Comment by sjackman** [comment]
The `mesa` bottle definitely includes `mesa/17.0.0/include/GL/gl.h`. Perhaps you'll have to point `cmake` to the correct directory, though I thought `std_cmake_args` should handle that.

**Comment by iMichka** [comment]
Failure on travis is:
> this isn't a Tk application

@sjackman seems TK has trouble launching on Travis. Don't know if there is a X-server running in that container. I think we can ignore this.

**Comment by sjackman** [comment]
```
==> brew test homebrew/science/oce --verbose
Testing homebrew/science/oce
==> CASROOT=/home/linuxbrew/.linuxbrew/Cellar/oce/0.18_1/share/oce-0.18 /home/linuxbrew/.linuxbrew/Cellar/oce/0.18_1/bin/DRAWEXE -v -c "pload ALL"
this isn't a Tk application
```
https://travis-ci.org/Homebrew/homebrew-science/builds/204378118#L6074

I'm okay ignoring this TravisCI test failure for now. It'd be great if someone had time to look into it.

**Pull request closed without merging**
