### PR TITLE
gfan: use gcc@5

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
If no use, no release since 2011 and does only build with specific version of the compiler, why keep it? https://github.com/Homebrew/homebrew-science/pull/4898

**Comment by ilovezfs** [comment]
Because we can?

**Comment by fxcoudert** [comment]
My bad, I am new and I thought there was a requirement in the project of integrating software that is at least reasonably maintained upstream (I see that even with GCC 5 the source needs patching) and build on some sort of "default" configuration.

**Comment by ilovezfs** [comment]
That's a better description of policy in core than in science.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@jonchang we have a brew test-bot bug that makes it impossible to use gcc@5. So we'll either need to disable the bottle here or wait till it's fixed. The problem doesn't affect local user installation, just test-bot.

**Comment by ilovezfs** [comment]
I've gone ahead and added an explicit bottle disable for now.

**Comment by jonchang** [comment]
Ok thanks! I was literally just trying to figure out why bottles weren't building for this.

**Pull request merged**
