### PR TITLE
anvio 2.3.1

### PR DESCRIPTION
**Pull request by ozcan**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
Linux builds are failing due to https://github.com/Linuxbrew/brew/pull/328. I'll try to fix up that PR and then get this merged.

**Comment by iMichka** [comment]
@ozcan you can ignore the 2 audit errors from the mac builds.

For Linux, I see that the fix mentioned by @jonchang has been merged. Can you rebase your branche and force-push it to your fork to trigger a new build?

**Comment by ozcan** [comment]
@iMichka I have rebased commits as you suggested but could not trigger the test bot

**Comment by iMichka** [comment]
Did you `git push --force <fork> master`?

**Comment by ozcan** [comment]
Yes, here are the exact commands I used from my shell history,

```
10087  git fetch Homebrew/master
10091  git checkout master
10096  git rebase Homebrew/master
10099  git push -f origin master
```

**Comment by iMichka** [comment]
What does your origin point to? (`git remove -v`) ?

I see that you were able to push 3 commits, so I do not understand why your rebase/push did not work.
You may also squash the commits to a single one (if possible).

**Comment by ozcan** [comment]
I have squashed commits to single commit, and here are my remotes,
```
git remote -v
Homebrew	https://github.com/Homebrew/homebrew-science.git (fetch)
Homebrew	https://github.com/Homebrew/homebrew-science.git (push)
origin	git@github.com:ozcan/homebrew-science.git (fetch)
origin	git@github.com:ozcan/homebrew-science.git (push)
```

**Comment by iMichka** [comment]
Looks good, the builds run again. As said before, we can ignore the 2 mac audit errors.

On Linux you are getting the following errors for both builds (during the scikit-learn installation):
> ImportError: dynamic module does not define module export function (PyInit_multiarray)

**Comment by ilovezfs** [comment]
>Looks good, the builds run again. As said before, we can ignore the 2 mac audit errors.

We can?

**Comment by iMichka** [comment]
> Looks good, the builds run again. As said before, we can ignore the 2 mac audit errors.
We can?

I don't know. For today yes, probably :) I think these should be addressed in a separate step. I mean, we need to ship separate python3 formula for scipy and numpy. Or vendor these here. But this can be discussed in #5470. I would like to have a more general plan on what to do here, and work on that during the next ... months :D

**Comment by ilovezfs** [comment]
Basically just need to use a numpy resource block instead of the formula.

**Comment by jonchang** [comment]
Is the concern about not vendoring e.g., `numpy` because it is not easy to build?

**Comment by ilovezfs** [comment]
It is trivial to build.

**Comment by iMichka** [comment]
> Is the concern about not vendoring e.g., numpy because it is not easy to build?

Somewhat. And we will need to vendor it 18 times, as I see it ...

**Comment by ilovezfs** [comment]
Yep. Or create a numpy-python3 formula. Since that doesn't exist, it needs to be vendored until such time as it does, if ever.

**Comment by ilovezfs** [comment]
Example: https://github.com/Homebrew/homebrew-core/pull/12900/files

**Comment by iMichka** [comment]
> Example: https://github.com/Homebrew/homebrew-core/pull/12900/files

Then let's do this :)

**Comment by jonchang** [comment]
Merged. Thanks @ozcan!

**Pull request closed without merging**
