### PR TITLE
trinity 2.3.1-beta (devel)

### PR DESCRIPTION
**Pull request by ilovezfs**
CC @sjackman

### CODE REVIEW

**Comment by sjackman** [comment]
I'm not inclined to add `devel` unless you yourself have a need for it or someone has requested it. I'm not particularly against it though. Looks good to me.

**Comment by ilovezfs** [comment]
@sjackman nope, I don't need it. This is just to dust it off and make sure it works before the new release actually ships. I already hit one issue in 2.3.0-prerelease, which upstream quickly fixed (https://github.com/trinityrnaseq/trinityrnaseq/issues/181), so with any luck 2.3.1-prerelease will soon be promoted.

**Comment by ilovezfs** [comment]
We can dig this PR up once 2.3.1 ships as stable.

**Comment by sjackman** [comment]
Superseded by #4629

**Pull request closed without merging**
