### PR TITLE
dynare: head build

### PR DESCRIPTION
**Pull request by houtanb**
Add support for building from head

### CODE REVIEW

**Comment by houtanb** [comment]
bump

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by houtanb** [comment]
@dpo if you recall, I think the test build fails because LaTeX is not installed on the testing machine....

**Comment by dpo** [comment]
@houtanb I don't think so. The `:tex` dependency is not activated by default in your formula. Currently the failed build is due to a download problem:
````
        ==> Fetching dynare from Homebrew/homebrew-science
==> Downloading https://www.dynare.org/release/source/dynare-4.4.3.tar.xz
==> Retrying download
==> Downloading https://www.dynare.org/release/source/dynare-4.4.3.tar.xz
Error: Failed to download resource "dynare"
Download failed: https://www.dynare.org/release/source/dynare-4.4.3.tar.xz
````

**Comment by saketkc** [comment]
We can switch to `http`: `http://www.dynare.org/release/source/dynare-4.4.3.tar.xz`

**Comment by houtanb** [comment]
Ok, let's hold off on this. We're renewing our certificate with globalsign. It should be fixed in a day or two.....

**Comment by houtanb** [comment]
Ok, the certificate has been set. @dpo, will brewbot test again if I write it?

@BrewTestBot test this please

**Comment by houtanb** [comment]
top

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@houtanb If you scroll down [the log](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/783/version=mountain_lion/console) there's a QZ factorization that failed on Mountain Lion. Any idea why that might be?

**Comment by houtanb** [comment]
@dpo It doesn't make sense to me that it would pass on yosemite and fail on mountain lion. Do you want me to change the test file to see if that will make it pass on mountain lion?

Also, it doesn't seem to have tested the head build.....

**Comment by dpo** [comment]
The bot doesn't test the head build, only the stable build. Thanks for your work!

**Comment by houtanb** [comment]
No idea why it would fail on one and not the other.....

Thanks for merging

**Pull request closed without merging**
