### PR TITLE
xmi-msim: generate xmimsim-db in postinstall

### PR DESCRIPTION
**Pull request by ilovezfs**
xmimsimdata.h5 is too big for Bintray
this will also speed up CI

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @tschoonj

**Comment by ilovezfs** [comment]
@tschoonj any idea why Mavericks takes 52 minutes, while Yosemite and El Capitan take 24 minutes?

**Comment by tschoonj** [comment]
Mavericks sucks? 😄

**Comment by ilovezfs** [comment]
@tschoonj shipped!

**Comment by ilovezfs** [comment]
Before
```
xmi-msim-5.0_5.el_capitan.bottle.tar.gz
1.07 GB
```

After
```
xmi-msim-5.0_6.el_capitan.bottle.tar.gz
2.29 MB
```

LOL

**Pull request closed without merging**
