### PR TITLE
Diamond 0.7.9 (updated version)

### PR DESCRIPTION
**Pull request by tseemann**
0.7.7 => 0.7.9

### CODE REVIEW

**Comment by tseemann** [comment]
Sigh. All I did was update the tarball/sha 2 sub-minor version. 
I only tested it on Linux and I have gcc-5.1 brew installed.
BOOST or cx11 issues?

```
g++ -o ../bin/diamond algo/blast/core/blast_encoding.o algo/blast/core/blast_stat.o algo/blast/core/blast_filter.o algo/blast/core/blast_util.o algo/blast/core/blast_message.o algo/blast/core/ncbi_erf.o algo/blast/core/blast_options.o algo/blast/core/ncbi_math.o algo/blast/core/blast_program.o algo/blast/core/ncbi_std.o algo/blast/core/blast_psi_priv.o algo/blast/core/raw_scoremat.o algo/blast/core/blast_query_info.o algo/blast/core/blast_seg.o main.o basic/options.o util/tinythread.o -L/usr/local/Cellar/boost/1.58.0/lib -lboost_thread-mt -lboost_system -lboost_timer -lboost_chrono -lboost_iostreams -lboost_program_options -lpthread -lz
Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in main.o
  "boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)", referenced from:
```

**Comment by tdsmith** [comment]
Yes, very likely related. Thanks for the PR!

**Comment by tseemann** [comment]
This PR was closed without merging?

**Comment by tdsmith** [comment]
It was merged in 0511a09.

**Pull request closed without merging**
