### PR TITLE
ceres-solver 1.13.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@sjackman any idea(s) what's up with the 🐧 builds here?

**Comment by dpo** [comment]
Problem is here: https://travis-ci.org/Homebrew/homebrew-science/builds/260613237#L2751

Related threads:
- https://github.com/ceres-solver/ceres-solver/issues/291
- https://groups.google.com/forum/#!msg/ceres-solver/zrHfuy4ITiY/NNwtq_rWAAAJ

I'll give it a go locally.

**Comment by sjackman** [comment]
The problem is likely that `glog` a dependency of `ceres-solver` is compiled with `gcc-4.8`, but `ceres-solver` is being compiled with `gcc-5`, and the two use different C++ ABI.

Here's a hack work-around for you that will likely work. We need a better fix ultimately.
https://github.com/Homebrew/homebrew-science/commit/db949c3ef88db85951b8f8347463b69a01ea2faa

**Comment by dpo** [comment]
Building `gflags` and `glog` with C++11 also works for me on linux. It may break something else though.

**Comment by sjackman** [comment]
> Building gflags and glog with C++11 also works for me on linux. It may break something else though.

Interesting. One possible fix is enabling C++11 on Linuxbrew by default for all formulae. It would require  rebottling lots of stuff, and I've got a a feeling would break lots of stuff. The ultimate plan is to migrate from bottling on Ubuntu 14 and GCC 4.8 with the old C++ ABI to Ubuntu 16 and GCC 5.3 with the new C++ ABI. That'll resolve this issue. I'd like to do that this year.

**Comment by dpo** [comment]
I also wonder if C++11 is really required to build `ceres-solver`.

**Comment by sjackman** [comment]
Probably not. `ceres-solver` depends on `suite-sparse`, which depends on `openblas`, which depends on `:fortran` provided by `gcc`, which is `gcc-5` on Linuxbrew. `ceres-solver` is built with the most recent available C++ compiler that is installed, namely `gcc-5`, and then fails to compile with `gcc-5` which uses a different boost ABI than gcc-4.8.

**Comment by ilovezfs** [comment]
https://github.com/ceres-solver/ceres-solver/commit/d72e19d9859722421b9cb23089354a5a967cba12

**Comment by dpo** [comment]
Apparently, there is a `CXX11=OFF` cmake option.

**Comment by sjackman** [comment]
Oh, well that could be simpler. Good find, Dominique!

**Comment by sjackman** [comment]
I'm glad that you got this working. Did you try the `CXX11=OFF` option?

**Comment by ilovezfs** [comment]
@sjackman no. It seems CI timed out on both Travis and Circle :(

**Comment by sjackman** [comment]
Both TravisCI and CircleCI timed out like so:
```
==> make test
..
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by ilovezfs** [comment]
@sjackman yeah … the macOS build is < 10 min on Jenkins

**Comment by sjackman** [comment]
Adding `timeout: 7200` to `circle.yml` may help, but not if it's completely stuck.
https://github.com/Linuxbrew/homebrew-core/blob/master/circle.yml#L82

**Pull request closed without merging**
