### PR TITLE
ClonalFrameML 1.7 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
ClonalFrameML, a software package that performs efficient inference of recombination in bacterial genomes.

### CODE REVIEW

**Comment by iml** [comment]
Can this be built from source?

**Comment by tseemann** [comment]
@lml Yes probably, but it is on googlecode only in SVN and I was hoping to avoid it until they migrated to github, 

Can you help me understand the Jenkins error?

````
Error Message
failed: brew test --verbose Homebrew/science/clonalframeml
Stacktrace
        Error: Testing requires the latest version of clonalframeml
```

**Comment by iml** [comment]
Not sure, but again the bots were having problems yesterday. They don't make it easy to get a URL but I think https://drive.google.com/uc?id=0B4J1jPwfCMKYVjF4ZVB3QlJ1UVE&export=download should work for the source zip?

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@sjackman looks good to go!

**Comment by sjackman** [comment]
Thanks, Torsten.

**Pull request closed without merging**
