### PR TITLE
vt 0.57 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
vt is a variant tool set that discovers short variants from Next Generation Sequencing data.

### CODE REVIEW

**Comment by tseemann** [comment]
"Test Result: No Failure" *confused*
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2387/

**Comment by iml** [comment]
With Jenkins errors you generally just have to wait and try again.

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by dpo** [comment]
@BrewTestBot test this please.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
```
Error: problem in /usr/local/Library/Taps/homebrew/homebrew-science/vt.rb
compile error
/usr/local/Library/Taps/homebrew/homebrew-science/vt.rb:18: syntax error, unexpected ')'
```

**Comment by iMichka** [comment]
Hi @tseemann. It seems there was another PR (#4238) were you added a new version of vt, that got merged with f8a2642f1de0ad73f1de06a857d8d22b9626f93b.

I do not know why this pull request was never closed, but I guess it has been forgotten. I will close this PR now, to keep the issue tracker clean. You can still comment here if you think this was not correct. Thanks

**Pull request closed without merging**
