### PR TITLE
hdf5: disable unsupported configure options by default.

### LINKED ISSUE #3054: hdf5: simple fortran example fails to run because of "--enable-unsupported" option
Installed `hdf5` with `--with-fortran`.

This very basic example (https://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/fortran/examples/h5_crtdat.f90) fails to run with the following errors:
```
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5F.c line 522 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1048 in H5F_open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'dsetf.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = a02
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5D.c line 165 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5D.c line 415 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5F.c line 774 in H5Fclose(): not a file ID
    major: Invalid arguments to routine
    minor: Inappropriate type
```

Removing the configure option `--enable-unsupported` (introduced in https://github.com/Homebrew/homebrew-science/commit/8047af58fc30ecc9f849faa2d84b54769c8b072a) fixes the issue.

### PR DESCRIPTION
**Pull request by dpo**
Fixes #3054.

### CODE REVIEW

**Comment by tdsmith** [comment]
Why does this work?

**Comment by dpo** [comment]
I'm not sure, I'm not a `hdf5` user. It's more of an experiment than a decisive fix.

**Comment by claudiodsf** [comment]
Do you think this can be merged? Or you're waiting for more testing?

**Comment by dpo** [comment]
Does this actually resolve your issue?

**Comment by claudiodsf** [comment]
Yep

**Comment by claudiodsf** [comment]
Pinging @iml to see it he's ok with this...

**Comment by claudiodsf** [comment]
No reply from @iml. Should we merge this?

**Pull request closed without merging**
