### PR TITLE
CUDA requirement

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Not sure why a `beagle` test fails. I can't reproduce locally.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
It looks as though these bottles weren't published:
https://bintray.com/homebrew/bottles-science/beagle/view#files
```
==> Fetching beagle from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/beagle-2.1.2.el_cap

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "beagle"
Download failed: https://homebrew.bintray.com/bottles-science/beagle-2.1.2.el_capitan.bottle.1.tar.gz
Warning: Bottle fetch failed: fetching the source.
```

**Comment by dpo** [comment]
Not sure I understand. I'm able to fetch the bottle:
```
$ brew fetch beagle
==> Fetching beagle from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/beagle-2.1.2.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
Downloaded to: /Users/dpo/Library/Caches/Homebrew/beagle-2.1.2.mavericks.bottle.1.tar.gz
SHA256: f1e1620257b47fee4b487e36cb9e3ae50a3c279f50c7ea25181fd4dd0bee2d6f
```

**Comment by sjackman** [comment]
I noticed the missing bottles 15 hours ago, and the rev 1 bottles were published 12 hours ago, so I noticed the issue in that three hour window that the bottles weren't published. I'm not sure why the lag, but it's unimportant, since it's resolved.

**Pull request closed without merging**
