### PR TITLE
scalapack: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
The test is taking more than 10 minutes to respond,
making the Linux CI fail. It is disabled to be
able to build bottles.

### CODE REVIEW

**Comment by iMichka** [comment]
```
homebrew/science/scalapack:
  * W: 44: col 32: Use parentheses in the method call to avoid confusion about precedence.
  * C: 55: col 15: Use ``mpirun -np 4 ./xsscaex | grep 'INFO code' | awk '{print $NF}'`.to_i.zero?` instead of ``mpirun -np 4 ./xsscaex | grep 'INFO code' | awk '{print $NF}'`.to_i == 0`.
  * C: 57: col 15: Use ``mpirun -np 4 ./xdscaex | grep 'INFO code' | awk '{print $NF}'`.to_i.zero?` instead of ``mpirun -np 4 ./xdscaex | grep 'INFO code' | awk '{print $NF}'`.to_i == 0`.
  * C: 59: col 15: Use ``mpirun -np 4 ./xcscaex | grep 'INFO code' | awk '{print $NF}'`.to_i.zero?` instead of ``mpirun -np 4 ./xcscaex | grep 'INFO code' | awk '{print $NF}'`.to_i == 0`.
  * C: 61: col 15: Use ``mpirun -np 4 ./xzscaex | grep 'INFO code' | awk '{print $NF}'`.to_i.zero?` instead of ``mpirun -np 4 ./xzscaex | grep 'INFO code' | awk '{print $NF}'`.to_i == 0`.
```

**Comment by iMichka** [comment]
Merged.

@sjackman This will allow to build Linux bottles for:
> homebrew/science/abinit
homebrew/science/dealii
homebrew/science/ipopt
homebrew/science/petsc
homebrew/science/trilinos
homebrew/science/cp2k
homebrew/science/getdp
homebrew/science/mumps
homebrew/science/slepc

**Comment by sjackman** [comment]
Nice! You can if you like to build bottles for Linux using
```sh
brew build-bottle-pr --keep-old abinit dealii ipopt petsc trilinos cp2k getdp mumps slepc
```

**Comment by iMichka** [comment]
I will have a look. Some of these do not build on mac, so it will need some time.

**Pull request closed without merging**
