### PR TITLE
arrayfire 3.3.2

### PR DESCRIPTION
**Pull request by ilovezfs**
vendor glew1 in since glew2 dropped glewmx support

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 any idea if the analytics data supports taking this one out back?

**Comment by tdsmith** [comment]
_i_ use arrayfire so let's keep it :D

**Comment by ilovezfs** [comment]
@tdsmith *is* the reverse dependency.

**Comment by tdsmith** [comment]
in any case package popularity is a classic long-tail distribution; _most_ packages in the homebrew ecosystem have only a handful of users, so i don't know what a useful cutoff would be

**Comment by ilovezfs** [comment]
>most packages in the homebrew ecosystem have only a handful of users

doesn't this imply most packages are dispensable? :)

**Comment by ilovezfs** [comment]
:green_apple: for Jenkins.

**Comment by tdsmith** [comment]
Maybe! But I expect many users will have a mixture of popular and unpopular packages installed; having unpopular packages provides a lot of value. Just... diffusely.

**Comment by dpo** [comment]
I also use arrayfire.

**Comment by ilovezfs** [comment]
two revdeps!

**Comment by ilovezfs** [comment]
@tdsmith :ship:?

**Pull request closed without merging**
