### PR TITLE
vips: Add optional dependancy - mozjpeg

### PR DESCRIPTION
**Pull request by privatmamtora**
Build vips with mozjpeg

### CODE REVIEW

**Comment by jcupitt** [comment]
Looks good, please merge. Thank you @privatmamtora

**Comment by dpo** [comment]
Please add a revision number `revision 1` below the header.

**Comment by privatmamtora** [comment]
@dpo Alright done

**Comment by dpo** [comment]
Just some minor audit warnings left:
```
==> brew audit Homebrew/science/vips					 FAILED
Error: 1 problem in 1 formula
homebrew/science/vips:
 * 6: Trailing whitespace was found
```

**Comment by privatmamtora** [comment]
@dpo Done. What next? Just wait?

**Comment by dpo** [comment]
Apparently there was a problem uploading the bottles. I asked the bot to try again.

**Pull request closed without merging**
