### PR TITLE
blast: 2.3.0

### PR DESCRIPTION
**Pull request by yesimon**
It seems like all relevant fixes/patches have been fixed in upstream version.

If you have a new boost installed concurrently, such as boost 1.60.0. You need to unlink boost and install `--without-check`, or else `./configure` will detect boost although the source doesn't support the refactored `Boost.Test` in newer Boosts.

### CODE REVIEW

**Comment by yesimon** [comment]
Referencing #2337

**Comment by tseemann** [comment]
For reference:
```
/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp:73:10: fatal error: 'boost/test/test_observer.hpp' file not found
#include <boost/test/test_observer.hpp>
         ^
1 error generated.
FAILED COMMAND:  /usr/local/Library/ENV/4.3/clang++  -stdlib=libc++ -std=gnu++11 -M  -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -m64  -D_MT -D_REENTRANT -D_THREAD_SAFE -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/ReleaseMT/inc -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/include   /private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp  | sed ...
Updating dependency information for /private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp.
/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp:73:10: fatal error: 'boost/test/test_observer.hpp' file not found
#include <boost/test/test_observer.hpp>
         ^
1 error generated.
FAILED COMMAND:  /usr/local/Library/ENV/4.3/clang++  -stdlib=libc++ -std=gnu++11 -M  -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -m64  -D_MT -D_REENTRANT -D_THREAD_SAFE -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/ReleaseMT/inc -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/include   /private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp  | sed ...
/usr/local/Library/ENV/4.3/clang++  -stdlib=libc++ -std=gnu++11 -c  -Wall -Wno-format-y2k -m64 -fpascal-strings   -O2 -Wno-deprecated-register -fno-common   -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -m64  -D_MT -D_REENTRANT -D_THREAD_SAFE -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/ReleaseMT/inc -I/private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/include   /private/tmp/blast20160302-92991-1oa6w87/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp -o test_boost.o 
```

**Comment by tseemann** [comment]
I should also state, that under Linux, I have never been able to install Brew `blast` unless I used these options: 

```
brew install blast --without-check --without-static
```

**Comment by yesimon** [comment]
On RHEL 6.7 with linuxbrew and system libc I didn't need to build `--without-static`. Is there a way to have the formula output suggestions/warnings?

**Comment by sjackman** [comment]
https://travis-ci.org/Homebrew/homebrew-science/jobs/113203907#L1028-L1030
```
In file included from /private/tmp/blast20160303-15356-1sjpx8d/ncbi-blast-2.3.0+-src/c++/src/corelib/test_boost.cpp:50:
/private/tmp/blast20160303-15356-1sjpx8d/ncbi-blast-2.3.0+-src/c++/include/corelib/test_boost.hpp:618:11: error: no matching constructor for initialization of 'boost::unit_test::ut_detail::auto_test_unit_registrar'
        : TParent(tc, exp_fail)
```

**Comment by tseemann** [comment]
I managed to compile it just by downloading and `./configure && make` which made static binaries, but this brew formula doesn't work.

As part of the config I noticed a bunch of things that `./configure` was picking up from my system environment rather than from Brew. Most of these aren't that important, but just in case:

* libgcrypt
* libgnutls
* krb5
* mysql

I also got these warnings:

```
checking Berkeley DB version (4.3 or newer required)...
configure: WARNING: Untested Berkeley DB version; may prove incompatible.
configure: WARNING: If so, please re-run this script with the flag --without-bdb.
checking for native Berkeley DB C++ wrappers (optional)... no
```

Also not sure why it found these over my Brew ones in the front of the PATH:

* checking for python... /bin/python

And this bug?

```
/tmp/ncbi-blast-2.3.0+-src/c++/src/build-system/configure: line 35065: : command not found
```

Here's what it said it found:

```
LIBRARIES:  build as static by default

FEATURES:   GCC MT LFS DLL unix WinMain Linux

PACKAGES:

  enabled:  UUID FUSE Z BZ2 PCRE GMP GMP GCRYPT GNUTLS OPENSSL KRB5 CURL MySQL BerkeleyDB PYTHON PYTHON27 PERL Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Spirit Boost.System Boost.Test.Included Boost.Thread OpenGL GLUT ICU EXPAT LIBXML LIBXSLT LIBEXSLT SQLITE3 VDB JPEG PNG TIFF XPM FreeType

  disabled: LocalZ LocalBZ2 LZO LocalPCRE NETTLE Sybase DBLib FreeTDS BerkeleyDB++ ODBC PYTHON25 PYTHON26 Boost.Filesystem Boost.Test C-Toolkit MESA GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus SABLOT Xerces Xalan Zorba SQLITE3ASYNC LocalVDB OECHEM SGE MUPARSER HDF5 UNGIF GIF FTGL MAGIC MIMETIC GSOAP AVRO Cereal MONGODB GMOCK
```

**Comment by yesimon** [comment]
@tseemann Did you also do `--without-check` ? When I first submitted this I also tried the SVN checkout, in which some things were fixed for boost 1.60 but others still didn't work, so it will probably be a few months before an official release has fixes for it.

**Comment by tseemann** [comment]
@yesimon I didn't use the brew formula, I just got the src and did vanilla configure and make - i'm not sure if it did the check by default.

Here is a hint from config.log:

```
CHECK_ARG=''
CHECK_OS_NAME='redhatenterpriseserver'
CHECK_TIMEOUT_MULT='1'
CHECK_TOOLS=''
TCHECK_CL=''
check=''
```

Here is the Boost stuff in the config output:
```
checking Boost version...
checking for Boost library name tag... -mt (autodetected)
checking for Boost.Regex... yes
checking for Boost.Spirit... yes
checking for Boost.System... yes
checking for Boost.Filesystem... no
checking for Boost.Iostreams... yes
checking for Boost.Program-Options... yes
checking for Boost.Test... included-only
checking for Boost.Thread... yes

enabled:  UUID FUSE Z BZ2 PCRE GMP GMP GCRYPT GNUTLS OPENSSL KRB5 CURL MySQL
 BerkeleyDB PYTHON PYTHON27 PERL **Boost.Iostreams Boost.Program-Options Boost.Regex
 Boost.Spirit Boost.System Boost.Test.Included Boost.Thread** OpenGL GLUT ICU EXPAT LIBXML
 LIBXSLT LIBEXSLT SQLITE3 VDB JPEG PNG TIFF XPM FreeType
```

**Comment by ilovezfs** [comment]
Closing since 2.3.0 was merged on 18 May: https://github.com/Homebrew/homebrew-science/commit/64c046e4a1807c5b94804625d15e631600948a34

**Pull request closed without merging**
