### PR TITLE
Kallisto 0.42.4

### PR DESCRIPTION
**Pull request by pmelsted**

### CODE REVIEW

**Comment by tseemann** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3470/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/pull___clean_https___github_com_Homebrew_homebrew_science_pull_2948/


 No Tags
 Test Result
 Previous Build
 Next Build
Failed

brew-test-bot.el_capitan.pull --clean https://github.com/Homebrew/homebrew-science/pull/2948

```
Failing for the past 1 build (Since Failed#3470 )
Took 1.7 sec.
add description
Error Message

failed: brew pull --clean https://github.com/Homebrew/homebrew-science/pull/2948
Stacktrace

        fatal: ref HEAD is not a symbolic ref
==> Applying patch
Applying: kallisto: requires c++11 kallisto 0.42.1
Using index info to reconstruct a base tree...
M	kallisto.rb
Falling back to patching base and 3-way merge...
Auto-merging kallisto.rb
CONFLICT (content): Merge conflict in kallisto.rb
Failed to merge in the changes.
Patch failed at 0001 kallisto: requires c++11 kallisto 0.42.1
The copy of the patch that failed is found in:
   /usr/local/Library/Taps/Homebrew/homebrew-science/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.
```

**Comment by tseemann** [comment]
@pmelsted Can you squash into 1 commit?
Also it doesn't work with > 1 cpu. It could be related to HDF5 needing to be compiled with `--with-mpi` ?

**Comment by pmelsted** [comment]
The HDF5 doesn't need any multithreaded options, we compile it specifically without mpi.

**Comment by tseemann** [comment]
Thanks Pall !

**Pull request closed without merging**
