### PR TITLE
GalSim: rename to Galsim to avoid clash in share.

### LINKED ISSUE #2577: Building gal-sim on 10.10.4 and it can't find FFTW3
```
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... 
Error: fftw file failed to link correctly
Check that the correct location is specified for FFTW_DIR

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at 
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ
```

I can't find anything relevant in the GalSim installation FAQ, and I can't figure out how to force HomeBrew to force scons to force the compiler to pass `-L/absolute/path/to/fftw/lib`.

Here's a [gist](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727) with:

  * [the output as seen in the terminal](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-gistfile1-txt)
  * [the scons output](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-01-scons)
  * [the scons config log](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-config-log)

I tried adding `ENV['LDFLAGS']='-L/Users/jlong/homebrew/Cellar/fftw/3.3.4_1/lib'` to the `gal-sim.rb` formula, but that didn't appear to be passed to the scons configure process, even though you can see it in the `LDFLAGS` in the scons output.

### PR DESCRIPTION
**Pull request by dpo**
Other changes:
- `desc` field
- remove obsolete `require "formula"`
- add path to certain dependencies to resolve an issue on 10.10
- install examples
- add tests.

Fixes #2577
Closes #2588

### CODE REVIEW

**Comment by josePhoenix** [comment]
No, this doesn't build, but it fails with a different error from #2577:
```
$ brew install -v galsim
==> Installing galsim from homebrew/homebrew-science
/usr/bin/env python -c import pyfits
/usr/bin/env python -c import numpy
/usr/bin/env python -c import nose
/usr/bin/env python -c import pyfits
/usr/bin/env python -c import numpy
/usr/bin/env python -c import nose
==> Downloading https://github.com/GalSim-developers/GalSim/archive/v1.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/galsim-1.2.0.tar.gz
==> Verifying galsim-1.2.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/galsim-1.2.0.tar.gz
==> /Users/jlong/opt/scons/bin/scons BOOST_DIR=/Users/jlong/opt/boost FFTW_DIR=/Users/jlong/opt/fftw TMV_DIR=/Users/jlong/opt/tmv-cpp TMV_LINK=/Users/jlong/opt/tmv-cpp/share/tmv/tmv-link
scons: Reading SConscript files ...
SCons is version 2.3.5 using python version 2.7.10
Python is from /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7
Using the following (non-default) scons options:
   TMV_DIR = /Users/jlong/opt/tmv-cpp
   TMV_LINK = /Users/jlong/opt/tmv-cpp/share/tmv/tmv-link
   FFTW_DIR = /Users/jlong/opt/fftw
   BOOST_DIR = /Users/jlong/opt/boost
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /usr/bin/env python
Using default PYPREFIX =  /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Using compiler: /usr/bin/g++
compiler version: 4.2.1
Determined that a good number of jobs = 8
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.58.0
Checking for C++ header file TMV.h... yes
TMV version is 0.72
Using TMV_LINK file: /Users/jlong/opt/tmv-cpp/share/tmv/tmv-link
     -L/Users/jlong/homebrew/Cellar/tmv-cpp/0.72/lib -ltmv -llapack -lblas
Mac version is 10.10.4
XCode version is 6.4
Checking for correct TMV linkage... (this may take a little while)
Checking for correct TMV linkage... yes
Checking if we can build against Python... yes
Building for python version 2.7
Python libdir =  /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
Python libfile =  libpython2.7.a
Checking if we can build module using TMV... yes
Checking if we can build against NumPy... yes
Checking for PyFITS... yes
Checking if we can build against Boost.Python...
Unable to build a python loadable module with Boost.Python

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ

Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Formula
Tap: homebrew/homebrew-science
Path: /Users/jlong/homebrew/Library/Taps/homebrew/homebrew-science/galsim.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: cb441ffefd115d37765c4efabc5f1cb9d0fd79be
Last commit: 7 days ago
HOMEBREW_PREFIX: /Users/jlong
HOMEBREW_CELLAR: /Users/jlong/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
MacPorts/Fink: /sw/bin/fink
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/jlong/bin/python => /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/jlong/opt/ruby/bin/ruby => /Users/jlong/homebrew/Cellar/ruby/2.2.2/bin/ruby
Java: 1.8.0_51
==> ENV
CC: /usr/bin/clang
CXX: /usr/bin/clang++
OBJC: /usr/bin/clang
OBJCXX: /usr/bin/clang++
CFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CXXFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CPPFLAGS: -isystem/Users/jlong/include -F/Users/jlong/Frameworks
LDFLAGS: -L/Users/jlong/lib  -F/Users/jlong/Frameworks -Wl,-headerpad_max_install_names
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /Users/jlong
CMAKE_FRAMEWORK_PATH: /Users/jlong/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.10
PKG_CONFIG_LIBDIR: /Users/jlong/lib/pkgconfig:/Users/jlong/homebrew/Library/ENV/pkgconfig/10.10:/usr/lib/pkgconfig
PATH: /Users/jlong/opt/ruby/bin:/Users/jlong/bin:/usr/local/bin:/Applications/ST_sci/SM/bin:/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Users/jlong/homebrew/Library/ENV/scm
CPATH: /Users/jlong/include

Error: homebrew/science/galsim 1.2.0 did not build
Logs:
     /Users/jlong/Library/Logs/Homebrew/galsim/01.scons
     /Users/jlong/Library/Logs/Homebrew/galsim/config.log
```

**Comment by dpo** [comment]
Could you post again the output of `brew gist-logs galsim`?

**Comment by josePhoenix** [comment]
Here you go: https://gist.github.com/anonymous/769a31230a128cd9934d

**Comment by dpo** [comment]
It seems you have MacPorts installed. Have you tried moving it out of the way (just to rule out that possibility)?

Also, what does
```
otool -L $(brew --prefix boost-python)/lib/lib*.dylib
```
say?

**Comment by josePhoenix** [comment]
I'm afraid I can't remove MacPorts, since I don't have root on this machine (hence the unusual Homebrew prefix). I don't think that's the trouble, because the other formula linked in #2577 worked.

```
16:24:18 tanuki:~ jlong$ otool -L $(brew --prefix boost-python)/lib/lib*.dylib
/Users/jlong/opt/boost-python/lib/libboost_python-mt.dylib:
	/Users/jlong/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/Users/jlong/opt/boost-python/lib/libboost_python.dylib:
	/Users/jlong/lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by dpo** [comment]
It's not finding your boost-python library. Does the updated formula work?

**Comment by dpo** [comment]
@josePhoenix

**Comment by tdsmith** [comment]
:-1: for renaming; what problem does this solve?

**Comment by dpo** [comment]
https://github.com/Homebrew/homebrew-science/pull/2588#issuecomment-127651889

**Comment by josePhoenix** [comment]
9152c51 worked for me just now.

**Comment by dpo** [comment]
@tdsmith Any objections to merging this?

**Comment by tdsmith** [comment]
It used to be the case that we couldn't ever rename formulas without breaking upgrade. I think that may still be true in taps. @xucheng, do you know?

I would rather use share/"galsim" (vs pkgshare) rather than rename the formula.

Can we add aliases for formulas in taps?

**Comment by xu-cheng** [comment]
To rename a formula, please following https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Rename-A-Formula.md

However, current formula rename implementation has a few disadvantage. (For example, we cannot revert formula rename). So I'm :-1: to rename formula with only minor format change.

**Comment by xu-cheng** [comment]
> Can we add aliases for formulas in taps?

We doesn't support this yet. But I'd like to make it happening.

**Comment by josePhoenix** [comment]
Data point: I thought homebrew-science didn't have GalSim because I first tried `brew install galsim` and `brew search galsim` before checking their install instructions.

**Comment by dpo** [comment]
The rename proposal isn't arbitrary or minor (in my opinion), the current name is just inconsistent. Users have to brew `gal-sim` instead of `galsim`.

**Comment by xu-cheng** [comment]
Aliases now is supported in tap. You need create `Aliases` dir and put symlink inside. E.g.
```
+ foo.rb
|
+ Aliases/bar --> ../foo.rb

**Comment by dpo** [comment]
What are the cons of a rename? Aliases are convenient, but in this case, the name of the formula doesn't correspond to what upstream thinks the name of the package is (https://github.com/Homebrew/homebrew-science/pull/2588#issuecomment-127651889).

**Comment by iml** [comment]
Presumably someone with `gal-sim` installed would no longer receive updates if the formula is renamed. Not sure how this would work out if the file was renamed and an alias added `gal-sim -> galsim` vs keeping it as-is and a `galsim -> gal-sim` alias.

**Comment by dpo** [comment]
Good point. I actually prefer renaming the file and creating an alias `gal-sim -> galsim` for "backward compatibility".

**Comment by josePhoenix** [comment]
Coincidentally, today I've been asked to look at solutions for easily installing galsim on other researchers' computers. Since the changes to make this work without being in `/usr/local` are folded into this PR, I am eagerly awaiting its incorporation (with any changes to the name necessary) :smile:

**Comment by xu-cheng** [comment]
@dpo If you decide to rename the formula, you don't need to create the alias. Instead you should follow https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Rename-A-Formula.md

**Pull request closed without merging**
