### PR TITLE
adam 0.21.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by heuermh** [comment]
cc @fnothaft

Thank you, @ilovezfs!  I cut the ADAM release on Friday and was expecting to update the formula this morning, looks like you already got to it!

**Comment by fnothaft** [comment]
Just wanted to echo @heuermh! Thank you for updating the ADAM formula for us, @ilovezfs!

**Comment by sjackman** [comment]
@sjackman 🐧

**Pull request closed without merging**
