### PR TITLE
quast 2.3: Move from libexec to prefix

### PR DESCRIPTION
**Pull request by sjackman**
Add tag "bioinformatics"
Depend on "homebrew/python/matplotlib" for Mountain Lion and older
Install symlink from quast.py to quast
Run quast --test

### CODE REVIEW

**Comment by sjackman** [comment]
@mikemcquaid The bottles for Quast appear to have uploaded to Bintray by [BrewTestBot 16295](http://bot.brew.sh/job/Homebrew%20Bottles/16295/console), but the files don't appear at Bintray.
https://bintray.com/homebrew/bottles-science/quast/view#files
> There are no files yet for this package.
Thoughts?

**Comment by mikemcquaid** [comment]
You need to use `brew pull`, set the Bintray API parameters and get added to the `homebrew-science` team or newly published bottles will be autoremoved by Bintray after 24h unfortunately.

**Comment by mikemcquaid** [comment]
Let me know when you've got an account and what your username is and I'll add you.

**Comment by sjackman** [comment]
My Bintray username is [sjackman](https://bintray.com/sjackman). Thanks, Mike.

**Comment by mikemcquaid** [comment]
You've already been added, actually. You should be able to manually upload and publish through the web interface.

**Comment by sjackman** [comment]
Is Homebrew paying for a premium Bintray account, or is it being sponsored by someone?

**Comment by mikemcquaid** [comment]
Bintray is providing free hosting for us because they are lovely.

**Comment by sjackman** [comment]
Wicked. I created a [Linuxbrew organization on Bintray](https://bintray.com/linuxbrew/bottles). Would you ask them on my behalf to extend the same offer to Linuxbrew?

**Comment by sjackman** [comment]
Oh, and bottling Quast worked. Thanks again for your help.

**Comment by mikemcquaid** [comment]
@sjackman I'd suggest you get in contact with them directly. Glad Quast worked!

**Comment by dpo** [comment]
@mikemcquaid Would you please authorize me as well on Bintray? https://bintray.com/dpo

**Comment by mikemcquaid** [comment]
@dpo Done!

**Comment by sjackman** [comment]
@mikemcquaid I contacted Bintray, and they said that they'd be happy to sponsor Linuxbrew.

**Comment by mikemcquaid** [comment]
:tada:

**Pull request closed without merging**
