### PR TITLE
repeatmasker: revision for new bottles

### PR DESCRIPTION
**Pull request by iMichka**
The sha256 of the Linux bottles is wrong. Don't know what happened; maybe I made an error when uploading these. It happened when bintray had a lot of problems 10 days ago, so maybe something went wrong.

Rebuild a new fresh set of bottles.

### CODE REVIEW

**Comment by iMichka** [comment]
Okay so this is what is happening on mac.

- First time you `brew pull --bottle`:
```
Verifying bottles published on Bintray
Verifying bottle: repeatmasker-4.0.7_1.sierra.bottle.tar.gz
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-62-g3b92f69 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output repeatmasker-4.0.7_1.sierra.bottle.tar.gz https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  259M  100  259M    0     0  5496k      0  0:00:48  0:00:48 --:--:-- 5652k
```

- Everything is fine. If you `git reset --hard origin/master`, and `brew pull --bottle` again:
```
Verifying bottles published on Bintray
Verifying bottle: repeatmasker-4.0.7_1.sierra.bottle.tar.gz
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-62-g3b92f69 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output repeatmasker-4.0.7_1.sierra.bottle.tar.gz https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz
** Resuming transfer from byte position 272541698
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   206    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
curl download failed; retrying in 4 sec
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-62-g3b92f69 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output repeatmasker-4.0.7_1.sierra.bottle.tar.gz https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz
** Resuming transfer from byte position 272541698
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   206    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Failed to download repeatmasker bottle from https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz!
```

So, error 416. Not so nice ...

And of course if I use `brew pull-bottle`, to get the Linux bottle too:
```
Patch format detection failed.
fatal: Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.
Error: Kernel.exit
```

I think this is why there is a such a mess with all the shasums being wrong lately. We need to make the sha256 commits manually, and errors slip in.

@sjackman The workflow is currently quite painful for pulling Linux bottles on science :(

**Comment by iMichka** [comment]
First problem can be worked around by removing `--continue-at -` from the curl.rb file (cc @reitermarkus).

Second problem can be worked around by locally fixing linuxbrew/homebrew-developer with that patch:
https://github.com/Linuxbrew/homebrew-developer/pull/60

Hitting another error now:
```
Fetching patch (bottle commit)
Patch: https://github.com/LinuxbrewTestBot/homebrew-science/compare/Homebrew:master...pr-6166.patch
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-62-g3b92f69-dirty (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --output /Users/michkapopoff/Library/Caches/Homebrew/Homebrew:master...pr-6166.patch https://github.com/LinuxbrewTestBot/homebrew-science/compare/Homebrew:master...pr-6166.patch --silent
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --show-error --user-agent Homebrew/1.3.1-62-g3b92f69-dirty\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.12.6)\ curl/7.54.0 --fail --location --remote-time --output /Users/michkapopoff/Library/Caches/Homebrew/Homebrew:master...pr-6166.patch https://github.com/LinuxbrewTestBot/homebrew-science/compare/Homebrew:master...pr-6166.patch --silent
Error: Failure while executing: /usr/local/bin/brew pull-linux --bottle -v https://github.com/Homebrew/homebrew-science/pull/6166
```

**Comment by sjackman** [comment]
Using `brew` 1.3.1 rather than `master` on macOS works around this error. Using `master` on Linuxbrew should be fine. It'd be good to fix the root issue though. I believe the fix is to merge the unreleased Homebrew/master into Linuxbrew/master and merge Linuxbrew/homebrew-developer#60.
```sh
git -C $(brew --repo) checkout -B master 1.3.1
```

**Comment by reitermarkus** [comment]
Does this fix it? https://github.com/Homebrew/brew/pull/3075

**Comment by iMichka** [comment]
Mmh, I hit a different problem now I think (with and without your patch):

```
==> Verifying bottles published on Bintray
Verifying bottle: repeatmasker-4.0.7_1.sierra.bottle.tar.gz
Error: Failed to find published repeatmasker bottle at https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz (302 )!
```

when using `brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/6166`

**Comment by sjackman** [comment]
```
❯❯❯ curl -L https://homebrew.bintray.com/bottles-science/repeatmasker-4.0.7_1.sierra.bottle.tar.gz | file -
/dev/stdin: gzip compressed data, was "repeatmasker-bottle.tar", last modified: Wed Feb  1 21:01:58 2017, from Unix
```
The bottle exists and is published. I'm not sure why `brew pull --bottle` is failing.

**Comment by iMichka** [comment]
As the bottles are published (and I manually published the linux bottles), and the failure happened after the bottle commit is created, + a manually created bottle commit for Linux, I updated this as is. I'll keep an eye open on these problems; but I have no time to dive more into this for the moment.

**Pull request closed without merging**
