### PR TITLE
vips 7.42.3

### PR DESCRIPTION
**Pull request by dplarson**
Also add a test and use sha256.

### CODE REVIEW

**Comment by dplarson** [comment]
The Mountain Lion test failed on `brew doctor` (which I find weird). Not sure what to do...

```bash
==> brew doctor								 FAILED
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    gambit-scheme
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
```

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
It just seems like a random failure. Your formula built and all looks well. Thanks!

**Comment by dplarson** [comment]
:+1:

**Pull request closed without merging**
