### PR TITLE
Octave 4.0.2: transfig dependency

### PR DESCRIPTION
**Pull request by schoeps**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### Changes

added transfig depedency (fig2dev), This should fix the printing issues that some users have observed with qt backend.

### CODE REVIEW

**Comment by dpo** [comment]
Want to give a go with SuiteSparse 4.5.3?

**Comment by schoeps** [comment]
I can check locally. Is that the question? (fixing the linking w.r.t. major version numbers will take some time)

**Comment by dpo** [comment]
Yes, that is the question. Thanks!

**Comment by schoeps** [comment]
Ok, I just build Octave with suitesparse 4.5.3 from #3665. The tests give the same results as for 4.5.1, so upgrading should be save.

**Comment by dpo** [comment]
Excellent thank you. I just pulled #3665. I'll restart the `octave` build.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
