### PR TITLE
vcfanno 0.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
vcfanno.go:19:2: cannot find package "github.com/brentp/irelate/interfaces"
```
https://travis-ci.org/Homebrew/homebrew-science/builds/186637730#L1397

**Comment by ilovezfs** [comment]
@sjackman :penguin:

**Comment by sjackman** [comment]
🐧 https://github.com/Homebrew/homebrew-science/pull/5154

**Comment by ilovezfs** [comment]
:baby_bottle:

**Pull request closed without merging**
