### PR TITLE
samtools 1.5

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@sjackman is the audit for versioned aliases not working on Linuxbrew?

**Comment by sjackman** [comment]
```
Error: 2 problems in 1 formula
homebrew/science/samtools:
  * Formula has other versions so create a versioned alias:
      cd /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-science/Aliases
      ln -s ../samtools.rb samtools@1.5
  * Formula has invalid versioned aliases:
      homebrew/science/samtools@1.5
```
https://travis-ci.org/Homebrew/homebrew-science/builds/245400461#L1900

Seems that way, yes. I haven't noticed this problem before. I'll look into it.

**Comment by sjackman** [comment]
This `brew audit bug` is fixed in 1.2.2, which hasn't yet been merged into Linuxbrew. I'll give that a go today.
See https://github.com/Homebrew/brew/commit/cd8d7a8a44ccc79c08b111bfae8b01fc33302329
and https://github.com/Homebrew/brew/commit/aa81f5635648383b0245bc791edc3b9668a02829

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/brew/pull/410 to merge 1.2.2 into Linuxbrew/brew.

**Comment by iMichka** [comment]
1.2.2 has been merged, I re-triggered the Linux builds.

**Comment by sjackman** [comment]
The `samtools` 1.5 bottle for `x86_64_linux` was added to the formula, but wasn't published on Bintray.
```
Download failed: https://linuxbrew.bintray.com/bottles-science/samtools-1.5.x86_64_linux.bottle.tar.gz
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/251585728#L3930

The 1.5 version label exists on Bintray, so the bottle likely transferred at some point and then expired.

This bottle is still available on CircleCI, so I've uploaded it to Bintray.
https://circleci.com/gh/Homebrew/homebrew-science/5361#artifacts/containers/0
https://5361-4106792-gh.circle-artifacts.com/0/tmp/circle-artifacts.vfqgLtM/samtools-1.5.x86_64_linux.bottle.tar.gz

Just wanted to document it here, because it's a bit weird.

**Comment by iMichka** [comment]
Don't remember what happened here. It happens from time to time that a bottle is not published, can't explain why though.

**Comment by sjackman** [comment]
@tmozgach Can you check the ORCA build log for `Download failed` to check for missing bottles?

**Pull request closed without merging**
