### PR TITLE
gubbins 1.4.5 (update)

### PR DESCRIPTION
**Pull request by andrewjpage**
Minor version update to Gubbins and its dependancies

### CODE REVIEW

**Comment by dpo** [comment]
There's an error building fastML on 10.11:
```
g++  -O3 -Wall -Wno-sign-compare -I. -I../../libs/phylogeny -DLOG -ftemplate-depth-32  -c -o fastml.o fastml.cpp
In file included from fastml.cpp:1:
In file included from ./mainbb.h:4:
In file included from ./bb_options.h:13:
In file included from ../../libs/phylogeny/definitions.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:264:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:
/usr/include/unistd.h:508:6: error: conflicting types for 'getopt'
int      getopt(int, char * const [], const char *) __DARWIN_ALIAS(getopt);
         ^
../../libs/phylogeny/getopt.h:147:12: note: previous declaration is here
extern int getopt ();
           ^
```

**Comment by andrewjpage** [comment]
This pull request for fastml fixes the issue  
https://github.com/Homebrew/homebrew-science/pull/3031

**Comment by dpo** [comment]
I see. Sorry.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
