### PR TITLE
gmap-gsnap: make check fails on Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
`make check` fails on Linuxbrew on both CircleCI and TravisCI.
```
PASS: coords1.test
FAIL: align.test
PASS: iit.test
FAIL: setup1.test
```
https://travis-ci.org/Homebrew/homebrew-science/builds/200761726#L1151

**Comment by harper357** [comment]
I think this error might be related to issue #4584  . 
I did `brew install --keep-tmp GMAP-GSNAP` to look at the test-suite.log that is generated and
when I add the `depends_on "perl"`  it changes the test-suite.log from :
```
===========================================
   gmap 2017-01-14: tests/test-suite.log
===========================================

# TOTAL: 4
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: align
===========

./align.test: line 9: align.test.out: No such file or directory
diff: align.test.out: No such file or directory
FAIL align.test (exit status: 2) 

FAIL: coords1
=============

mkdir: cannot create directory ‘testSubDir’: File exists
Cannot write to file coords.chr17test at /tmp/gmap-gsnap-20170213-24975-u4fzsa/gmap-2017-01-14/util/fa_coords line 118.
Opening file /tmp/gmap-gsnap-20170213-24975-u4fzsa/gmap-2017-01-14/tests/ss.chr17test
  Processed short contigs (<1000000 nt): .diff: coords.chr17test: No such file or directory
FAIL coords1.test (exit status: 2)

FAIL: iit
=========

Finished reading FASTA file -- total entries: 3
Maximum coordinate: 40000
Total label length: 3 + 3 separators
Total annotation length: 80 + 3 separators
Saw 0 distinct divisions/chromosomes
Saw 3 distinct tags/types
No divs/chromosomes provided, so storing as IIT version 1
Error: can't open file iittest.iit
./iit.test: line 12: iit_get.out: No such file or directory
diff: iit_get.out: No such file or directory
./iit.test: line 15: iit_dump.out: No such file or directory
diff: iit_dump.out: No such file or directory
FAIL iit.test (exit status: 2)
```
to 
```
===========================================
   gmap 2017-01-14: tests/test-suite.log
===========================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: align
===========

./defs: line 23: cd: testSubDir: No such file or directory
Cannot make or change into testSubDir


FAIL align.test (exit status: 1)
```

But in the kept temp folder, there is testSubDir, so I am not sure why it can't change into that folder.

**Comment by sjackman** [comment]
Can you reproduce this error with the `linuxbrew/linuxbrew` docker image? I'd report this bug to the upstream author (http://research-pub.gene.com/gmap/) if you can.
```sh
docker run -it linuxbrew/linuxbrew
brew pull https://github.com/Homebrew/homebrew-science/pull/5110
brew install gmap-gsnap --keep-tmp -dv
```

**Comment by harper357** [comment]
I finally got some time to test this, and it looks like the error still happens on the docker image. From the test-suite.log:

```
===========================================
   gmap 2017-01-14: tests/test-suite.log
===========================================

# TOTAL: 4
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: align
===========

GMAP version 2017-01-14 called with args: /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/src/gmap.sse42 -A -g /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/tests/ss.chr17test /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/tests/ss.her2
Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17
Finished checking compiler assumptions
Starting alignment
Processed 1 queries in 0.08 seconds (12.50 queries/sec)
diff: align.test.out: No such file or directory
FAIL align.test (exit status: 2)

FAIL: coords1
=============

Cannot write to file coords.chr17test at /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/util/fa_coords line 118.
Opening file /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/tests/ss.chr17test
  Processed short contigs (<1000000 nt): .diff: coords.chr17test: No such file or directory
FAIL coords1.test (exit status: 2)

FAIL: setup1
============

Sorting chromosomes in chrom order.  To turn off or sort other ways, use the -s flag.
Creating files in directory ./chr17test
Running "/tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/src/fa_coords"     -o "./chr17test.coords" -f "./chr17test.sources"
sh: 0: getcwd() failed: No such file or directory
Cannot open file ./chr17test.sources at /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/src/fa_coords line 95.
"/tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/src/fa_coords"     -o "./chr17test.coords" -f "./chr17test.sources" failed with return code 512 at /tmp/gmap-gsnap-20170414-1907-1qr8c40/gmap-2017-01-14/util/gmap_build line 273.
diff: ./chr17test/chr17test.genomecomp: No such file or directory
Difference found between chr17test.genomecomp and setup.genomecomp.ok
FAIL setup1.test (exit status: 1)
```
When I change the formula to the current gmap/gsnap version, 2017-04-13, I get this on the docker image in test-suite.log:

```
===========================================
   gmap 2017-04-13: tests/test-suite.log
===========================================

# TOTAL: 4
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: align
===========

mkdir: cannot create directory  ^`^xtestSubDir ^`^y: File exists
GMAP version 2017-04-13 called with args: /tmp/gmap-gsnap-20170415-14925-19y9jw6/gmap-2017-04-13/src/gmap.sse42 -A -g /tmp/gmap-gsnap-20170415-14925$
Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17
Finished checking compiler assumptions
Starting alignment
Processed 1 queries in 0.05 seconds (20.00 queries/sec)
diff: align.test.out: No such file or directory
FAIL align.test (exit status: 2)

FAIL: setup1
============

Sorting chromosomes in chrom order.  To turn off or sort other ways, use the -s flag.
Creating files in directory ./chr17test
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
mkdir: cannot create directory  ^`^x./chr17test ^`^y: No such file or directory
sh: 0: getcwd() failed: No such file or directory
mkdir: cannot create directory  ^`^x./chr17test ^`^y: No such file or directory
sh: 0: getcwd() failed: No such file or directory
chmod: cannot access  ^`^x./chr17test/chr17test.maps ^`^y: No such file or directory
Could not create ./chr17test.sources at /tmp/gmap-gsnap-20170415-14925-19y9jw6/gmap-2017-04-13/util/gmap_build line 160.
diff: ./chr17test/chr17test.genomecomp: No such file or directory
Difference found between chr17test.genomecomp and setup.genomecomp.ok
FAIL setup1.test (exit status: 1)
```

I have emailed the program author, so maybe he can weigh in on the problem.

**Comment by harper357** [comment]
Update: I was playing around with this and may have made some headway. 

After trying `brew install gmap-gsnap --keep-tmp` I went into the tmp folder for the install and from  there I was able to run `make check` and everything passes. Then I ran `make install` and it properly install into the brew Cellar. 
 
Is there a way to make sure the formula is running `make check` in the correct directory?

**Comment by sjackman** [comment]
Perhaps try `ENV.deparallelize` before `make check`?

**Comment by harper357** [comment]
That looks like it fixed it with the docker image. Thanks for the help! 

I will try it out on everyday computer and make a pull request if it works.

**Comment by sjackman** [comment]
A pull request would be welcome. Thank you!

**Comment by harper357** [comment]
The pull request is #5435

**Comment by sjackman** [comment]
Superseded by PR #5435

**Comment by sjackman** [comment]
I've rebased this PR onto `master` at PR https://github.com/Homebrew/homebrew-science/pull/5655
This new PR retains your authorship, @harper357.

**Pull request closed without merging**
