### PR TITLE
Cutadapt 1.9 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
Cutadapt finds and removes adapter sequences, primers, poly-A tails and other types of unwanted sequence from your high-throughput sequencing reads.

Cleaning your data in this way is often required: Reads from small-RNA sequencing contain the 3’ sequencing adapter because the read is longer than the molecule that is sequenced. Amplicon reads start with a primer sequence. Poly-A tails are useful for pulling out RNA from your sample, but often you don’t want them to be in your reads.

Cutadapt helps with these trimming tasks by finding the adapter or primer sequences in an error-tolerant way. It can also modify and filter reads in various ways. Adapter sequences can contain IUPAC wildcard characters. Also, paired-end reads and even colorspace data is supported. If you want, you can also just demultiplex your input data, without removing adapter sequences at all.

Cutadapt comes with an extensive suite of automated tests and is available under the terms of the MIT license.

If you use cutadapt, please cite DOI:10.14806/ej.17.1.200 .

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman It seems the test failed due to overuse of a github API token on the Linux docker maybe?

```
==> brew style cutadapt
Successfully installed rainbow-2.0.0
Successfully installed ast-2.1.0
Successfully installed parser-2.2.3.0
Successfully installed powerpack-0.1.1
Successfully installed astrolabe-1.3.1
Successfully installed ruby-progressbar-1.7.5
Successfully installed tins-1.6.0
Successfully installed rubocop-0.35.1
8 gems installed
1 file inspected, no offenses detected
Error: GitHub API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 25 minutes 39 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: HOMEBREW_GITHUB_API_TOKEN
==> FAILED
```

**Comment by sjackman** [comment]
I'm not up to date with what's going on with the Travis testing. On the brew bot side, it succeeded on two Mac OS versions and failed on Mavericks.

**Comment by tseemann** [comment]
I had another failure with Mavericks too, something to do with string local / encoding....

**Comment by SuperYMS** [comment]
hi, it would be awesome to install cutadapt using brew. thanks.

**Comment by iMichka** [comment]
@SuperYMS Development has staled here, as there was no progress since 2015. This pull request is on my list of the requests that need to be closed. Would you like to pick this up and propose a formula? I can help you a little bit to make this work. Just submit a new pull request. I'm closing this here just to make clear that nobody is currently working on this.

**Comment by sjackman** [comment]
I'd also like to see `cutadapt` in Homebrew/science, and would appreciate someone picking up this PR.

**Comment by tseemann** [comment]
@sjackman it's still available in my tap `brew tap tseemann/bioinformatics-linux`, where i put all my homebrew-science failures :/

**Comment by sjackman** [comment]
@tmozgach may pick up this PR. Here's the repo Torsten mentioned: https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/cutadapt.rb

@tseemann Are there particular formulae in `tseemann/bioinformatics-linux` that you think would be appropriate for Homebrew/science (not Linux-only binaries), and that'd you'd like to see migrated?

**Comment by tmozgach** [comment]
@sjackman here you are! https://github.com/Homebrew/homebrew-science/pull/5961

**Comment by sjackman** [comment]
Thanks, Tanya!

**Pull request closed without merging**
