### PR TITLE
nextflow 0.15.1

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> Downloading http://www.nextflow.io/releases/v0.15.1/nextflow
Warning: Formula reports different SHA256: 32f3adbacbcbb3f36da3f9006a0836b686363b509f57d0f2b155a41e83131374
Downloaded to: /Library/Caches/Homebrew/nextflow-0.15.1
SHA1: 5cc081e6820605bfe5d1b9633ecb2cf728afc2f7
SHA256: c3671e83d68269724d817aa5b6dede8331587f4c87ec23d8d09cb08fc174c5ca
```

**Comment by pditommaso** [comment]
Yes, sorry. I've just updated it.

**Comment by sjackman** [comment]
Thanks for your contribution, Paolo.

**Comment by pditommaso** [comment]
Thanks to you !

**Pull request closed without merging**
