### PR TITLE
etsf_io: revision for netcdf

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Failed with:

```
Making check in tests/group_level
/Applications/Xcode.app/Contents/Developer/usr/bin/make  tests_init tests_write tests_read tests_copy
/usr/local/bin/gfortran -I../../src/low_level -I../../src/group_level -I/usr/local/opt/netcdf/include -g -O2 -I/usr/local/opt/netcdf/include  -c -o tests_init.o  tests_init.f90
/usr/local/bin/gfortran -I../../src/low_level -I../../src/group_level -I/usr/local/opt/netcdf/include -g -O2 -I/usr/local/opt/netcdf/include  -c -o tests_module.o  tests_module.f90
tests_module.f90:373:19:

     character(len = length), intent(in) :: string
                   1
Error: Scalar INTEGER expression expected at (1)
tests_module.f90:372:36:

   subroutine check_mem_str_0D(string, length, varname, lstat, error_data)
                                    1
Error: Symbol 'string' at (1) has no IMPLICIT type
tests_module.f90:130:80:

           call check_mem_str_0D(strings(1), dims(1), varname, lstat, error_data)
                                                                                1
Error: Type mismatch in argument 'string' at (1); passed CHARACTER(1) to UNKNOWN
make[2]: *** [tests_module.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

Any fortran gurus here? Though we have bottles, so we could push this as-is.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-science/pull/4999.

**Comment by ilovezfs** [comment]
This is a gcc 6 issue. It builds successfully with gfortran-5.

**Pull request closed without merging**
