### PR TITLE
RAPsearch 2.22 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
RAPSearch2: an even faster RAPSearch that supports multi-threading
RAPSearch stands for Reduced Alphabet based Protein similarity Search (more on RAPSearch)
What's improved in RAPSearch2
RAPSearch2 works faster than the original RAPSearch; uses less memory; and supports multi-threading!
Download RAPSearh2 from SourceForge or GitHub
Important notes:
be sure to set -z parameter if you want to use more than one thread.
if you are switching from RAPSearch to RAPSearch2, please make sure that you prepare a new index file for database search using prerapsearch that comes with the new RAPSearch2 package.
RAPSearch supposes that there is no '(' in the first split part of query id. Please remove it!
Sample input files: 4440037.3.dna.fa (a query file) and nogCOGdomN95.seq (a database of protein sequences); RAPSearch2 results
Contact: Yongan Zhao (yongzhao@indiana.edu) and Yuzhen Ye (yye@indiana.edu) (web)
Citations
Yongan Zhao, Haixu Tang and Yuzhen Ye. RAPSearch2: a fast and memory-efficient protein similarity search tool for next generation sequencing data. Bioinformatics 2012, 28 (1): 125-126
Yuzhen Ye, Jeong-Hyeon Choi and Haixu Tang. RAPSearch: a fast protein similarity search tool for short reads. BMC Bioinformatics 2011, 12:159
Last modified on June 28, 2014

### CODE REVIEW

**Comment by tseemann** [comment]
Any ideas on how I solve this issue?
Is is related to `boost --without-single` or `cx11` or `clang` ?
```
g++ -O3 -w  -o prerapsearch BuildHash.cpp HashSearch.o BlastStat.o Seg.o mergeUnit.o -I/usr/local/opt/boost/include -L/usr/local/opt/boost/lib -lboost_serialization -lpthread -lboost_thread -lboost_system -lboost_chrono
ld: library not found for -lboost_thread
```

**Comment by dpo** [comment]
It seems to be related to `boost --without-single`, but it's not clear why `boost` would have been installed that way.

**Comment by tseemann** [comment]
@dpo I figured out it needs `boost_thread-mt` library instead of `boost_thread` on Brew.

**Comment by tseemann** [comment]
@dpo are you able to pull this and bottle?

**Comment by dpo** [comment]
I am. Shall I pull and close?

**Comment by dpo** [comment]
@tseemann

**Comment by tseemann** [comment]
Thanks @dpo !   I seem to be able to find occasional time to update and write new formula, but then I move to other projects and never finish the job (and often have `--pull` and `bintray` issues) so I'm happy for anyone to help complete the task! thank you.

**Comment by dpo** [comment]
@tseemann It would be great if you could set aside some time to finalize your PRs. There are [currently 25 PRs that you created](https://github.com/Homebrew/homebrew-science/pulls/tseemann) out of about 100. I personally don't have the time to "complete the task" for someone else.

**Comment by tseemann** [comment]
@dpo my apologies for sounding demanding and rude. I did not mean to say you should finish them, I guess i was hoping if people had spare time they could help me get successful, passing requests like this one into the system and bottled. 

I have so many problems when I do the later stages, I don't know why, but bintray and other things always seem to go wrong. i spend a lot of time getting to this point, and then it all collapses. others seem to have a better handle of the final stages and less difficulty than me, that's all. many of the problems with the pull requests go back to Travis and all sorts of other problems out of my control. 

I am struggling to keep up with all the changes in the homebrew ecosystem.  like you, many of the formulae i write are of no benefit to me. if i think they won't pass here, i usually just put them in my own tap where I don't have to battle with OSX and Travis: https://github.com/tseemann/homebrew-bioinformatics-linux/

I have slowly been going back through my old pull requests trying to figure stuff out, but it invariable fails with some obscure travis or other error that has to do with the testing system. i often leave homebrew alone for months and then eventually come back hoping things are easier. and they are improving, but it's hard work as you know!

**Pull request closed without merging**
