### PR TITLE
open-mpi: migrate from core

### PR DESCRIPTION
**Pull request by ilovezfs**
Goes together with https://github.com/Homebrew/homebrew-core/pull/4274 and https://github.com/Homebrew/brew/pull/828.

### CODE REVIEW

**Comment by dpo** [comment]
What's the rationale? What about `mpich` and the `:mpi` dependency?

**Comment by ilovezfs** [comment]
@dpo recheck the PR ;)

**Comment by dpo** [comment]
Thanks. Is core happy for dependencies of core formulae to live in another tap? Any chance we could have real `:`-style requirements in science?

**Comment by ilovezfs** [comment]
@dpo as far as I know the "default_formula" mechanism won't break just because the formula is in a tap, but obviously that will need to be tested.

**Comment by ilovezfs** [comment]
@dpo see https://github.com/Homebrew/brew/pull/828.

**Comment by ilovezfs** [comment]
@dpo the rationale is that the revisions for
```
abinit
abyss
alpscore
bless
dealii
dida
elemental
exabayes
garli
getdp
gmsh
hypre
lammps
lis
meme
mumps
p4est
parmetis
pastix
petsc
ray
scalapack
scotch
scotch5
slepc
sundials
superlu_dist
trilinos
zoltan
```
all should have been part of the single open-mpi update PR (just as we do for llvm, gcc, boost, etc. in core), but weren't solely because open-mpi is in another tap, thereby breaking all of them in one swoop, and leaving everyone in the dark about whether they're going to build or not and leaving science to scramble to fix all the broken bottles.

**Comment by dpo** [comment]
At the very least, `zoltan` should have been marked as conflicting with `trilinos`.

**Pull request closed without merging**
