### PR TITLE
sratoolkit fix sha256 error for ncbi-vdb

### PR DESCRIPTION
**Pull request by cmdcolin**
The sha256 checksum was failing on ncbi-vdb and seemed to need updating. I manually checked that by downloading and running shasum -a 256 locally

### CODE REVIEW

**Comment by ilovezfs** [comment]
Please open an issue on their tracker asking why this happened and why a new tag was not created instead. As a matter of policy, we do not update checksums without understanding the situation first because upstream may have been hacked.

**Comment by cmdcolin** [comment]
Sounds good!

**Comment by cmdcolin** [comment]
Oh wait, why would it be an issue on their tracker? I guess we can cross reference with them but it seems a little confusng

**Comment by ilovezfs** [comment]
@cmdcolin because it's their tarball ...

**Comment by cmdcolin** [comment]
Looks like they can confirm the retagged tht led to the checksum difference

**Pull request merged**
