### PR TITLE
mlpack 2.2.5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by jonchang** [comment]
Bumped mlpack to 2.2.2 as it's now hosted on github.

audit:

```
  * Dependency armadillo should not use option with-hdf5
```

**Comment by iMichka** [comment]
@sjackman This is weird. The Linux build downloads the boost bottle. But when it installs boost, it tries to reinstall it from source, which fails. Already seen something like this?

**Comment by sjackman** [comment]
@iMichka Options are to blame. That's usually the case when something installs from source rather than bottle. `mlpack` has:
```ruby
  cxx11dep = MacOS.version < :mavericks ? ["c++11"] : []
  depends_on "armadillo" => ["with-hdf5"] + cxx11dep
  depends_on "boost" => cxx11dep
```
The following may work
```diff
-  cxx11dep = MacOS.version < :mavericks ? ["c++11"] : []
+  cxx11dep = OS.mac? && MacOS.version < :mavericks ? ["c++11"] : []
```

**Comment by iMichka** [comment]
@sjackman Options are bad :) Did not think about that in this context. I'll try to keep an eye open for these kind of problems in the future. Let's try your solution.

**Comment by iMichka** [comment]
> undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'

That did not work. I guess the only way out here is to have a c++11 boost bottle.

**Comment by iMichka** [comment]
>  I guess the only way out here is to have a c++11 boost bottle.

Mmh or to fix the c++11 compilation of boost. I'll have a look at this tomorrow. The mlpack compilation time is around 25 minutes on mac, so this may fit.

**Comment by jonchang** [comment]
I know it's possible to pass certain arguments for cmake builds to force using the non cxx11 abi. There's a formula that has an example of it, I'll try to look for it tomorrow.

**Comment by sjackman** [comment]
Linuxbrew uses GCC 4.8 and the old 4.x C++ ABI by default to build bottles.

**Comment by iMichka** [comment]
The Linux build will now be done with gcc5; boost bottles have been updated. Let's try this again.

**Comment by iMichka** [comment]
```
homebrew/science/mlpack:
  * C: 18: col 14: Use parentheses for ternary expressions with complex conditions.
  * C: 39: col 33: Only use parentheses for ternary expressions with complex conditions.
  * C: 40: col 35: Only use parentheses for ternary expressions with complex conditions.
  * Dependency armadillo does not define option "c++11"
==> FAILED
```

**Comment by iMichka** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/bin/mlpack_knn -r /home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv -n neighbors.csv -d distances.csv -k 5 -v
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/mlpack/test.01.mlpack_knn:
2017-08-31 20:48:40 +0000

/home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/bin/mlpack_knn
-r
/home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv
-n
neighbors.csv
-d
distances.csv
-k
5
-v

[INFO ] Loading '/home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv' as CSV data.  Size is 3 x 100000.
[INFO ] Loaded reference data from '/home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv' (3 x 100000).
[INFO ] Building reference tree...
[INFO ] Tree built.
[INFO ] Searching for 5 neighbors with dual-tree kd-tree search...
[INFO ] 1037944 node combinations were scored.
[INFO ] 3245406 base cases were calculated.
[INFO ] Search complete.
[INFO ] Saving CSV data to 'neighbors.csv'.
[INFO ] Saving CSV data to 'distances.csv'.
[INFO ] 
[INFO ] Execution parameters:
[INFO ]   algorithm: dual_tree
[INFO ]   distances_file: distances.csv
[INFO ]   epsilon: 0
[INFO ]   help: false
[INFO ]   info: ""
[INFO ]   input_model_file: ""
[INFO ]   k: 5
[INFO ]   leaf_size: 20
[INFO ]   naive: false
[INFO ]   neighbors_file: neighbors.csv
[INFO ]   output_model_file: ""
[INFO ]   query_file: ""
[INFO ]   random_basis: false
[INFO ]   reference_file: /home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv
[INFO ]   rho: 0.7
[INFO ]   seed: 0
[INFO ]   single_mode: false
[INFO ]   tau: 0
[INFO ]   tree_type: kd
[INFO ]   true_distances_file: ""
[INFO ]   true_neighbors_file: ""
[INFO ]   verbose: true
[INFO ]   version: false
[INFO ] 
[INFO ] Program timers:
[INFO ]   computing_neighbors: 0.152631s
[INFO ]   loading_data: 0.134747s
[INFO ]   saving_data: 0.292008s
[INFO ]   total_time: 0.628639s
[INFO ]   tree_building: 0.035719s
Error: homebrew/science/mlpack: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/bin/mlpack_knn -r /home/linuxbrew/.linuxbrew/Cellar/mlpack/2.2.0_2/share/mlpack/tests/data/GroupLens100k.csv -n neighbors.csv -d distances.csv -k 5 -v
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/mlpack.rb:55:in `block (2 levels) in <class:Mlpack>'
/usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/mlpack.rb:54:in `block in <class:Mlpack>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:36:in `block in <main>'
/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:35:in `<main>'
==> FAILED
```

Test is failing under Linux

**Comment by ilovezfs** [comment]
2.2.5 is now out.

**Pull request closed without merging**
