### PR TITLE
opengrm-thrax 1.2.0

### PR DESCRIPTION
**Pull request by stevenbedrick**
Updates the opengrm-thrax recipe to install the latest version of the Thrax library.

### CODE REVIEW

**Comment by stevenbedrick** [comment]
Turns out that there's a sandbox issue- the test case is trying to write to `#{share}/thrax/grammars` which isn't one of the whitelisted directories.

**Comment by dpo** [comment]
The solution is probably to `cp_r share/"thrax/grammars", testpath` and `cd` to that location before running the test.

**Comment by stevenbedrick** [comment]
Aha! Yes! That totally did the trick. Thanks!

**Comment by dpo** [comment]
Thank you!

**Pull request closed without merging**
