### PR TITLE
kaiju 1.5.0

### PR DESCRIPTION
**Pull request by HadrienG**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like the `test` block failed. Possibly a nonzero exit code when calling `kaiju -h`? You can try something like `assert_match version.to_s, shell_output("kaiju -h", 1)` assuming the exit status is 1.

**Comment by HadrienG** [comment]
Yes, `kaiju -h` returns `1` 😢 
I'll try to change the test. `shell_output("kaiju -h", 1)` might be a bad idea, I assume it will also throw `1` if it does not work. Maybe string matching to a part of the help message is better.

I'm a bit surprised, since in the previous version `kaiju -h` also returned `1` but that test passed. Did brew change something in the testing suite?

**Comment by ilovezfs** [comment]
>Did brew change something in the testing suite?

No. It likely means it was merged while failing last time.

**Comment by laserson** [comment]
bump.

**Comment by HadrienG** [comment]
I changed the test to `mkbwt -h` which returns `0`. I don't think it's a particularly good test but at least it passes.

**Comment by iMichka** [comment]
@HadrienG thanks for your contribution!

**Pull request closed without merging**
