### PR TITLE
Updated VarScan to 2.4.0

### PR DESCRIPTION
**Pull request by niemasd**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by niemasd** [comment]
We will be covering VarScan in the class I am teaching on Thursday, so I would appreciate it if the pull request could get merged before then if at all possible. Thanks for managing this awesome package manager! It's such a lifesaver, especially for Bioinformatics

**Comment by iMichka** [comment]
Hi. Why not upgrade to 2.4.3?

**Comment by niemasd** [comment]
Sorry, I didn't realize there was a 2.4.3. That would be even better.

**Comment by niemasd** [comment]
I created a new pull request for 2.4.3:

https://github.com/Homebrew/homebrew-science/pull/5393

**Pull request closed without merging**
