### PR TITLE
flexbar 2.7

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:
- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?
### New formula: have you
- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Looks like v3.0 is now released.  Using the same formula you created earlier and editing the URL and SHA worked on my system.
```
  url "https://github.com/seqan/flexbar/archive/v3.0.0.tar.gz"
  sha256 "60226d62d9617a7026bdae4b6f5f695ac2bc839b7d19e1d7d9ab63f85aa31a74"
  head "https://github.com/seqan/flexbar.git"
```

**Comment by jonchang** [comment]
@nextgenusfs feel free to open a pull request for this

**Comment by nextgenusfs** [comment]
I'd be happy to, if I could figure out how to only do a pull request on my latest commit.  seems like that should be much easier than what I'm reading....

**Comment by iMichka** [comment]
Closing this PR as it is superseded by #5264

**Pull request closed without merging**
