### PR TITLE
snap-aligner 1.0b18

### PR DESCRIPTION
**Pull request by tseemann**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### Notes

* Despite the "beta18" label it is years beyond what is in Brew currently.

### CODE REVIEW

**Comment by tseemann** [comment]
I'm not sure what this means:

```
Failed

brew-test-bot.sierra.audit homebrew/science/snap-aligner --online

Failing for the past 1 build (Since Failed#535 )
Took 12 sec.
Error Message

failed: brew audit homebrew/science/snap-aligner --online
Stacktrace

        ==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Successfully installed ast-2.3.0
Successfully installed parser-2.4.0.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.2.1
Successfully installed parallel-1.11.2
Successfully installed rubocop-0.49.1
8 gems installed
Error: Error running `rubocop --format json --force-exclusion --parallel --except FormulaAuditStrict --config /usr/local/Homebrew/Library/.rubocop.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/snap-aligner.rb`
```

**Comment by iMichka** [comment]
Fails on mac with:
> SNAPLib/AlignerContext.cpp:341:34: error: expected ')'
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, strBufLen),       // Aligntime is in ms
                                               ^
SNAPLib/AlignerContext.cpp:341:24: note: to match this '('
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, strBufLen),       // Aligntime is in ms
                                     ^
1 error generated.
make: *** [SNAPLib/AlignerContext.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by cmdcolin** [comment]
Looks like upstream https://github.com/amplab/snap/pull/71 is a fix but is blocking. Potentially could incorporate as a patch into formula

**Comment by iMichka** [comment]
@tseemann Could you add the patch to https://github.com/Homebrew/formula-patches, and apply it here?

**Pull request closed without merging**
