### PR TITLE
circlator: new formula (v0.14.2)

### PR DESCRIPTION
**Pull request by andrewjpage**
A tool for circularising genome assemblies. A publication is in progress.
https://github.com/sanger-pathogens/circlator

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/2536/version=yosemite/testReport/junit/brew-test-bot/yosemite/install___only_dependencies_Homebrew_science_circlator/
```
Error Message

failed: brew install --only-dependencies --verbose --build-bottle Homebrew/science/circlator
Stacktrace

        ==> Installing circlator from homebrew/homebrew-science
Error: Operation already in progress for numpy
Another active Homebrew process is already using numpy.
Please wait for it to finish or terminate it to continue.
```

**Comment by sjackman** [comment]
I haven't seen this particular error before.

**Comment by andrewjpage** [comment]
I ran the build  on Mountain Lion and it completed fine:
```
brew install --only-dependencies --verbose --build-bottle circlator.rb
```
This issue seems to be related:
https://github.com/Homebrew/homebrew/issues/17730
I would wonder if you kick off the test build again, would it work?

**Comment by sjackman** [comment]
Looks successful now. Can ignore this
```
==> audit problems
homebrew/science/circlator:
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
```

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Andrew.

**Pull request closed without merging**
