### PR TITLE
Update gmsh (+petsc and opencascade)

### PR DESCRIPTION
**Pull request by schoeps**
Allow gmsh to be compiled with petsc/slepc and opencascade to support real CAD geometries.

### CODE REVIEW

**Comment by schoeps** [comment]
Anyone tried to merge?

**Comment by dpo** [comment]
I did, sorry for the delay. First there's a problem to resolve with `opencascade`.

**Comment by schoeps** [comment]
I can have a look at. Is there a way to be informed which "install names" raised the error?

**Comment by dpo** [comment]
I'm not sure. `opencascade` doesn't even build for me.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
Thanks for your patience!

**Pull request closed without merging**
