### PR TITLE
pymol 1.8.6.0

### PR DESCRIPTION
**Pull request by fxcoudert**
- `tcl-tk` was migrated from dupes to core. Threads are enabled by default. X11 is not supported anymore
- Newer pymol version requires `msgpack`

### CODE REVIEW

**Comment by iMichka** [comment]
Don't :D 

See this 99 comment long pull request:
https://github.com/Homebrew/homebrew-science/pull/6066

**Comment by fxcoudert** [comment]
I know the PR, but it's not moved for 10 days and it is a heavy patch, not sure to be accepted upstream.

In the meantime, pymol is broken: https://github.com/Homebrew/homebrew-science/issues/6150

**Comment by ilovezfs** [comment]
@telamonian any thoughts here?

**Comment by iMichka** [comment]
I would propose
- To merge this as-is. Runtime will still be broken, but that is a different topic that can be fixed in the other PR
- Or remove pymol for the time being

**Comment by ilovezfs** [comment]
I'm confused. What's the benefit of upgrading the version if it's broken either way? Shouldn't we just do the version upgrade in the other PR?

**Pull request closed without merging**
