### PR TITLE
openblas: audits, compatibility symlinks

### PR DESCRIPTION
**Pull request by dpo**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?
- [X] Written a sensible test? (The best test is to compile and run a sample program.)
- [X] Removed the `revision` line, if any, when bumping the version number?
- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

- fix audits
- add libblas and liblapack symbolic links for compatibility with other
  BLAS/LAPACK implementations
- add test

### CODE REVIEW

**Comment by sjackman** [comment]
Can you split this PR into two commits: one for audit fixes and the other to add the symlinks?

**Comment by sjackman** [comment]
I have reservations about creating the library symlinks on Mac, because they conflict with the default Accelerate ones provided by the system. I think no library symlinks on Mac is the better. It could be an option with the default value of no symlinks on Mac.

**Comment by sjackman** [comment]
I forget that `openblas` is `keg_only :provided_by_osx` due to header file conflicts (no library conflicts). Ignore my above comments.

**Comment by dpo** [comment]
Seems this is good to go.

**Comment by sjackman** [comment]
:+1: Thanks, Dominique!

**Pull request closed without merging**
