### PR TITLE
Easel 0.2.snap20130225 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
EASEL is a sequence alignment library hidden inside HMMER and Infernal.
It comes with a bunch of "esl-*" tools which are very useful.

### CODE REVIEW

**Comment by tseemann** [comment]
I think @BrewTestBot is out to get me today:

```
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install ncurses

Run `brew missing` for more details.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
```

**Comment by tdsmith** [comment]
Should the hmmer formula install these? I see a note in the [hmmer docs](ftp://selab.janelia.org/pub/software/hmmer3/3.1b2/Userguide.pdf) that "the Easel API is not yet stable enough to decouple it from the applications that use it, like HMMER and Infernal."

**Comment by tseemann** [comment]
It gets bundled in HMMER and Infernal, so it isn't obvious which of those to install it from. I think it is better to have a separate package. The tools have been stable for many years, I've used them a lot. Not sure why Sean won't release the tools even if the C library API is not stable.

**Comment by tseemann** [comment]
@BrewTestBot test this please.

**Comment by iMichka** [comment]
We updated our "new formula" policy for homebrew-science:

> We will no longer accept new formula in homebrew-science, as this tap is being phased out. Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

I am closing this pull request, if you need any advice please feel free to comment below. Thanks!

**Pull request closed without merging**
