### PR TITLE
genewise: fix the problem with csh

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
```
cc -o genewise genewise.o geneparser21.o geneparameter.o genestats.o genewisehsp.o geneutil.o geneoutput.o threestatemodel.o genefrequency.o splicesitemodeler.o genewise4.o genewise6.o genestretch6.o genewise21.o geneloop21.o geneloop6.o genephase6.o gwlite.o gwlitemodel.o gwrap.o matchsum.o estwrap.o genewisemodel.o phasemodel.o cdparser.o genedisplay.o estwise3.o estslim3.o estloop3.o estfrag3.o estslimloop.o gwquickdb.o threestatedb.o pfamhmmer1db.o pwmdna.o wise2xhmmer2.o genewisemodeldb.o seqhit.o standardout.o geneparser4.o sw_wrap.o abc.o pba.o seqaligndisplay.o dbadisplay.o proteinsw.o estquick3.o  -L../base/ -L../dynlibsrc/ -L../HMMer2/ -lpthread `pkg-config glib-2.0 --libs` -lhmmer -ldyna_glib -ldyna_glib -ldyna_glib -ldyna -lwisebase  -lm
../dynlibsrc//libdyna_glib.a(subseqhash.o): In function `Wise2_free_subseqhash_ghash':
subseqhash.c:(.text+0x4c): undefined reference to `g_hash_table_foreach_remove'
```
https://travis-ci.org/Homebrew/homebrew-science/builds/261186656#L3017

**Comment by sjackman** [comment]
The link command line is currently
```
`pkg-config glib-2.0 --libs` -lhmmer -ldyna_glib -ldyna_glib -ldyna_glib -ldyna -lwisebase  -lm
```
that should probably be changed to
```
-lhmmer -ldyna_glib -ldyna -lwisebase  -lm `pkg-config glib-2.0 --libs` 
```
You can try editing the `Makefile`

**Comment by sjackman** [comment]
A simpler fix that may work is to add to the formula:
```ruby
# Fix undefined reference to g_hash_table_foreach_remove
fails_with :gcc => "4.8"
```

**Comment by tmozgach** [comment]
@sjackman thank you! Ready for merging!

**Comment by jonchang** [comment]
Circle timed out for some reason so I'm restarting that build.

**Comment by sjackman** [comment]
Success!

**Comment by jonchang** [comment]
Does this need a revision bump as well?

**Comment by sjackman** [comment]
Not really. I've merged this PR, and opened PR #6071 to bottle `genewise` for Linux with the same revision.

**Comment by sjackman** [comment]
Merged. Thanks again, Tanya!

**Pull request merged**
