### PR TITLE
flann: revision for hdf5

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Ignoring audits, I'm just bumping the revision.
> homebrew/science/flann:
  * The URL http://www.cs.ubc.ca/~mariusm/index.php/FLANN/FLANN could use HTTPS rather than HTTP
  * python modules should be vendored rather than use deprecated `depends_on "numpy" => :python`

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
Linux bottles did not make it to bintray, don't know why. Building again.

**Comment by jonchang** [comment]
I triggered a bottle reupload for Linux.

**Comment by jonchang** [comment]
Bottles succeeded on Linux, waiting on Mac builds...

**Comment by iMichka** [comment]
@ilovezfs Is the strategy I'm using here the right one? :) I need a small review. The audit failure is due to pcl, I'll bump that one in a separate PR later.

**Comment by ilovezfs** [comment]
No, you'll want to use a `numpy` resource block.

**Comment by iMichka** [comment]
@ilovezfs @tdsmith I had some time to experiment a little bit with the numpy venturing.

Now, if I have no numpy installed on my system, and use brewed python, and I try to import pyflann:
```
import pyflann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyflann/__init__.py", line 31, in <module>
    from pyflann.index import *
  File "/usr/local/lib/python2.7/site-packages/pyflann/index.py", line 30, in <module>
    from pyflann.flann_ctypes import (flannlib, FLANNParameters, allowed_types,
  File "/usr/local/lib/python2.7/site-packages/pyflann/flann_ctypes.py", line 29, in <module>
    from numpy import (float32, float64, uint8, int32, require)
ImportError: No module named numpy
```

So the way I wrote this seems not to work as expected.
Reading the doc, I see that I can also add this at the end: `venv.pip_install_and_link buildpath`
But then the build fails with:
```
/usr/local/Cellar/flann/1.9.1_4/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/flann-20170624-61862-s3afql/flann-1.9.1
Directory '/private/tmp/flann-20170624-61862-s3afql/flann-1.9.1' is not installable. File 'setup.py' not found.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/flann/1.9.1_4/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/flann/1.9.1_4/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/usr/local/Cellar/flann/1.9.1_4/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 276, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/local/Cellar/flann/1.9.1_4/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 201, in from_line
    "not found." % name
InstallationError: Directory '/private/tmp/flann-20170624-61862-s3afql/flann-1.9.1' is not installable. File 'setup.py' not found.
```

This makes sense because there is no `setup.py` file for flann itself.

I am not sure if I missed something in the documentation but I have a hard time understanding how vendoring of numpy is expected to work here.

**Comment by iMichka** [comment]
@ilovezfs Did you have time to look at this? I would like to merge this (the bots are all green), but I am worried that this is not the way vendoring is supposed to work.

**Comment by fxcoudert** [comment]
I think this was addressed during migration to core. Please file an issue against homebrew-core (and CC me) if there is an aspect I have not addressed.

**Pull request closed without merging**
