### PR TITLE
arpack 3.4.0 with cmake

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Actually, maybe the dependents don't need to be bumped. They appear to be linked against `libarpack.2.dylib`.

**Comment by ilovezfs** [comment]
@dpo That would be pleasant! BTW it looks like a CMake-based build is now available if you feel like converting it over.

**Comment by dpo** [comment]
I'll have a look.

**Comment by dpo** [comment]
Switching to the CMake build requires bumping the dependents.

**Comment by dpo** [comment]
The pkgconfig info file seems to be missing when installing with CMake: https://github.com/opencollab/arpack-ng/issues/44. That breaks `calculix-cxx` and `shogun`.

**Pull request closed without merging**
