### PR TITLE
ensembl-tools 82

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by heuermh** [comment]
There are a lot of failing and skipped tests due to missing dependencies. How did previous versions of this formula work?
```
...
# tabix and/or bgzip not found, skipping convert_cache tests
...
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC
...
could not find JSON perl module, skipping test
```

**Comment by tseemann** [comment]
@heuermh add `depends_on "htslib"` to get the bgzip and tabix commands.

**Comment by heuermh** [comment]
@tseemann Thank you, I'll give it a try.  Note that I'm working with linuxbrew via docker which may or may not have the same default perl libraries installed.  I assume the brew bot is doing something similar?

Meanwhile, I have made progress with this formula
https://github.com/chapmanb/homebrew-cbl/blob/master/vep.rb

with libarchive-zip-perl, libdbd-mysql-perl, and libjson-perl installed via apt-get
https://github.com/heuermh/docker-linuxbrew-bio/blob/master/vep/Dockerfile

**Comment by dpo** [comment]
Closing for lack of activity and conflicting files. Please open a new pull request if still interested.

**Comment by heuermh** [comment]
@dpo Good idea, I haven't looked at this in a while.

**Pull request closed without merging**
