### PR TITLE
r 3.3.0

### PR DESCRIPTION
**Pull request by erichare**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by tdsmith** [comment]
The formulas look great, thanks!

This looks like it'll be a bit of a project to pull; test-bot isn't building R first so everything else is dragging.

Other issues that want to be addressed:
* nonpareil tries to write directly to R's public site-library, which it should not be doing.
* poretools has an invalid checksum -- but actually no longer has R dependencies, so we should stop trying to install them.
* quake installs .R files to `bin`; is that right?

Thanks for your help; I don't think there's anything else you need to do. I'll use your commits and split it into a couple of PRs once we have the dependencies sorted out and pull one and then build the other; it'll be broken for a few minutes but hopefully nobody will notice.

**Comment by erichare** [comment]
Sounds great. Thank you very much!

**Comment by tdsmith** [comment]
Just to set expectations, my advancement exam is Thursday (!) and it's not likely that I'll work on this before then, if I know what's good for me

**Comment by rkrug** [comment]
I would suggest to switch to https downloads instead of the http.

**Comment by rkrug** [comment]
Would it be possible to pull the update of R and the other working recipies and to leave the recipies for poretools and nonpareil as is for the moment?

**Comment by yihui** [comment]
Yeah I think it is a good idea to download from https.

**Comment by tdsmith** [comment]
I'll do the https change; looks like both mirrors support it (good work, R-core!)

**Comment by tdsmith** [comment]
Also I found myself with some breathing room tonight so I'll spend some time on this; NB that you'll have to reinstall all your packages

**Comment by tdsmith** [comment]
Landed; thanks all!

**Comment by yihui** [comment]
Excellent. Good luck to your exam!

**Pull request closed without merging**
