### PR TITLE
med-file: New formula for Salome MED file 3.2.0

### PR DESCRIPTION
**Pull request by bblacey**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?
---
@sjackman, a new special checklist item for you ;)
- [x] Built formula locally on linuxbrew prior to submission

### CODE REVIEW

**Comment by iMichka** [comment]
@bblacey Thanks for your contribution. Were all your patches submitted upstream? We do not want to carry those around forever. Nice work fixing all these small details.

**Comment by bblacey** [comment]
Hi @iMichka, none of the patches are available upstream yet.  I am working with a Salome developer to ensure they are tracked and incorporated into a future MED file release.  We will have to carry them for some time but ideally not after the next MED-file release.

**Comment by sjackman** [comment]
> [x] Built formula locally on linuxbrew prior to submission

😂

**Comment by bblacey** [comment]
So what is the next step to merge this PR so the formula is available to the broader Homebrew community?

**Comment by iMichka** [comment]
I saw that the patches were submitted upstream. Perfect.

There is one step more, especially as the patch is quite big. Could you submit the patch here:
https://github.com/Homebrew/formula-patches

And then use it like this:
```
patch do
   url "https://raw.githubusercontent.com/Homebrew/formula-patches/...diff"
   sha256 "xxx"
end
```

Once this is done we can merge this. Thanks.

**Comment by bblacey** [comment]
Hi @iMichka - Got it.  As requested, I have submitted the patches to Homebrew/formula-patches.  Once the patches PR is merged to master, I will update the med-file formula to apply the patch resource and amend this PR commit accordingly.  Anything you can do to help ensure a timely merge will be greatly appreciated so we can wrap up this PR.  Thanks.

**Comment by ilovezfs** [comment]
```
  patch do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/720fedf/med-file/libc%2B%2B_and_python_bindings_fixes.diff"
    sha256 "4125238ca3623e682b766cf2d34fed17938007ad326ae3b158a9cd427c638054"
  end
```

**Comment by bblacey** [comment]
Thanks for the quick turn-around! 👍 Formula amended accordingly.

**Comment by bblacey** [comment]
The circleci failure looks like a BOT/infrastructure issue and not a formula issue as confirmed by a successful Travis-CI build.  Circle tried to checkout the formula on master and not the PR branch...

**Comment by iMichka** [comment]
Yes, we had some trouble with that lately.

Please rebase on master:
`git checkout master`
`git pull origin master`
`git checkout med-file`
`git rebase master`

That should update our circle.yml file, and the CI should run correctly. Sorry for the trouble.

**Comment by bblacey** [comment]
Ah, got it... Need to rebase.  I'm on it.

**Comment by bblacey** [comment]
All systems green - looks like we are good to go.  Thanks for your help.

**Comment by iMichka** [comment]
@bblacey Thanks for your contribution!

**Pull request closed without merging**
