### PR TITLE
igv 2.3.52

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1872/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_Homebrew_science_igv/
```
Error Message
failed: brew test --verbose Homebrew/science/igv

Testing igv
==> igv -b script
INFO [2015-05-07 11:39:13,456] [DirectoryManager.java:149]  IGV Directory: /Users/brew/igv
Error: igv: failed
<0> expected but was
<1>.
```

**Comment by sjackman** [comment]
Trying this hack:
```diff
--- a/igv.rb
+++ b/igv.rb
@@ -17,6 +17,6 @@ class Igv < Formula
 
   test do
     (testpath/"script").write "exit"
-    assert_match "IGV", shell_output("#{bin}/igv -b script")
+    assert_match "IGV", `#{bin}/igv -b script`
   end
 end
```

**Comment by sjackman** [comment]
The issue is likely that IGV returns a non-zero exit status in a headless (no GUI) environment.

**Comment by iml** [comment]
`shell_output("#{bin}/igv -b script", 1)` should work.

**Comment by sjackman** [comment]
Yes, but then `brew test igv` would fail on a desktop that's not headless, where `igv -b script` would return an exit status of zero.

**Pull request closed without merging**
