### PR TITLE
gnudatalanguage: Build a bottle for Linuxbrew: error: no matching function for call to ‘EnvT::AssureLongScalarPar(int, hid_t&)’

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
cd /tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/build/src && /usr/bin/g++-4.8   -DHAVE_CONFIG_H -I/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/src -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/include/GraphicsMagick -I/home/linuxbrew/.linuxbrew/Cellar/netcdf/4.4.1.1_3/include -I/home/linuxbrew/.linuxbrew/Cellar/hdf5/1.10.0-patch1/include -I/home/linuxbrew/.linuxbrew/opt/zlib/include -I/home/linuxbrew/.linuxbrew/opt/szip/include -I/home/linuxbrew/.linuxbrew/include/eigen3 -I/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7 -I/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/src/antlr -I/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/build  -Os -w -pipe -march=core2 -DNDEBUG   -fopenmp -o CMakeFiles/gdl.dir/hdf5_fun.cpp.o -c /tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/src/hdf5_fun.cpp
/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/src/hdf5_fun.cpp: In function ‘BaseGDL* lib::h5a_read_fun(EnvT*)’:
/tmp/gnudatalanguage-20170206-63233-soc160/gdl-0.9.7/src/hdf5_fun.cpp:490:37: error: no matching function for call to ‘EnvT::AssureLongScalarPar(int, hid_t&)’
     e->AssureLongScalarPar(0, h5a_id);
```
https://circleci.com/api/v1.1/project/github/Homebrew/homebrew-science/3212/output/29/0?file=true

**Comment by ilovezfs** [comment]
Looks like this may be https://sourceforge.net/p/gnudatalanguage/bugs/699/

**Comment by ilovezfs** [comment]
Debian has a patch for it.
```
Josephs-MacBook-Pro:debian joe$ ls patches/
bugfix-852682.patch				gdl-fun-fix
build-with-debian-antlr-instead-embedded-one	gdl-template.patch
create-shared-lib				hdf5-1.10.patch
debian-multiarch				series
fix-spelling-errors
Josephs-MacBook-Pro:debian joe$ cat patches/hdf5-1.10.patch 
Description: Support HDF5 1.10
Author: Gilles Filippini <pini@debian.org>
Bug-Debian: https://bugs.debian.org/841971

--- a/src/hdf5_fun.cpp
+++ b/src/hdf5_fun.cpp
@@ -404,8 +404,11 @@
     SizeT nParam=e->NParam(1);
     
     DLong h5a_id;
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5a_id);
+#else
     e->AssureLongScalarPar(0, h5a_id);
-    
+#endif
     DLong h5a_space_id;
     h5a_space_id = H5Aget_space( h5a_id );
     if (h5a_space_id < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
@@ -487,7 +490,11 @@
     hsize_t dims_out[MAXRANK];
 
     hid_t h5a_id;
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5a_id);
+#else
     e->AssureLongScalarPar(0, h5a_id);
+#endif
     
     hid_t h5s_id = H5Aget_space(h5a_id);
     if (h5s_id < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
@@ -601,7 +608,11 @@
     hsize_t dims_out[MAXRANK];
 
     hid_t h5d_id;
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5d_id);
+#else
     e->AssureLongScalarPar(0, h5d_id);
+#endif
 
     hid_t h5s_id = H5Dget_space(h5d_id);
     if (h5s_id < 0) {
@@ -766,7 +777,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5s_id;
-    e->AssureLongScalarPar( 0, h5s_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5s_id);
+#else
+    e->AssureLongScalarPar(0, h5s_id);
+#endif
     if (H5Sclose(h5s_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
   
@@ -775,7 +790,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5d_id;
-    e->AssureLongScalarPar( 0, h5d_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5d_id);
+#else
+    e->AssureLongScalarPar(0, h5d_id);
+#endif
     if (H5Dclose(h5d_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
   
@@ -784,7 +803,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5f_id;
-    e->AssureLongScalarPar( 0, h5f_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5f_id);
+#else
+    e->AssureLongScalarPar(0, h5f_id);
+#endif
     if (H5Fclose(h5f_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
 
@@ -793,7 +816,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5t_id;
-    e->AssureLongScalarPar( 0, h5t_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5t_id);
+#else
+    e->AssureLongScalarPar(0, h5t_id);
+#endif
     if (H5Tclose(h5t_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
 
@@ -802,7 +829,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5g_id;
-    e->AssureLongScalarPar( 0, h5g_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5g_id);
+#else
+    e->AssureLongScalarPar(0, h5g_id);
+#endif
     if (H5Gclose(h5g_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
 
@@ -811,7 +842,11 @@
   {
     SizeT nParam=e->NParam(1);
     DLong h5a_id;
-    e->AssureLongScalarPar( 0, h5a_id);
+#if (H5_VERS_MAJOR>1)||((H5_VERS_MAJOR==1)&&(H5_VERS_MINOR>=10))
+    e->AssureLongScalarPar(0, (DLong64&)h5a_id);
+#else
+    e->AssureLongScalarPar(0, h5a_id);
+#endif
     if (H5Aclose(h5a_id) < 0) { string msg; e->Throw(hdf5_error_message(msg)); }
   }
 
```

**Comment by ilovezfs** [comment]
https://mirrors.ocf.berkeley.edu/debian/pool/main/g/gnudatalanguage/gnudatalanguage_0.9.7-2.debian.tar.xz

**Comment by sjackman** [comment]
Thanks, Joe. I gisted the patch
https://gist.githubusercontent.com/sjackman/00fb95e10b7775d16924efb6faf462f6

**Comment by ilovezfs** [comment]
hmm looks like despite the keep-old the linuxbrew bottle is gnudatalanguage-0.9.7_1.x86_64_linux.bottle.tar.gz and there are no mac bottles.

**Comment by ilovezfs** [comment]
s/no/new/

**Comment by sjackman** [comment]
`gnudatalanguage-0.9.7_1.x86_64_linux.bottle.tar.gz` is the intended version for `revision 1` and no `rebuild`. The Homebrew Mac bottles get built, but I won't publish/merge them. They'll expire after seven days unpublished.

**Comment by sjackman** [comment]
Merged! Thanks for your help, Joe.

**Comment by ilovezfs** [comment]
:tada:

**Pull request closed without merging**
