### PR TITLE
quast 4.4 and DOI update

### PR DESCRIPTION
**Pull request by alexeigurevich**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by alexeigurevich** [comment]
Hi Shaun @sjackman, could you help us with this? 
All Mac tests reported a problem:
    Broken dylib links found:
      /usr/local/opt/gcc/lib/gcc/5/libstdc++.6.dylib
        /usr/local/lib/gcc/5/libgcc_s.1.dylib
        /usr/local/opt/gcc/lib/gcc/5/libgomp.1.dylib

It looks like they just found these broken links (in E-MEM binaries) and crashed without running ./quast.py --test actually. We can detect that E-MEM is not working and simply switch to MUMmer without errors and loss of functionality.

**Comment by sjackman** [comment]
> It looks like they just found these broken links (in E-MEM binaries)

I'd recommend not installing these `e-mem` binaries instead `depend_on "e-mem"`.

**Comment by alexeigurevich** [comment]
So, should we create a separate tar-ball without E-MEM binaries and put it somewhere? Or is it possible to use the full distribution (_quast-4.4.tar.gz_) somehow? E.g. download the full distribution, remove `quast-4.4/quast_lib/E-MEM-osx/` and run brew audit after that?

**Comment by sjackman** [comment]
Yes, you can continue to use the standard tarball. before the line
```ruby
prefix.install Dir["*"]
```
add
```ruby
rm "path/to/e-mem"
```
and also add
``` ruby
depends_on "e-mem"
```

Just to confirm, it will find and use the `e-mem` executable provided by brew in the `PATH`?

**Comment by alexeigurevich** [comment]
Thanks! I did the changes, hopefully it will be OK now (locally it is working for us).
Please take a look at the commit, maybe our mv/rmdir/mkdir/mv chain could be written in a more elegant way. We should remove binaries only but there are many of them so it is easier to remove the whole folder. However, QUAST need `nucmer` script in that folder: it runs it and use either embedded or external E-MEM binary. So, we need to recreate removed folder and put `nucmer` there.

| Just to confirm, it will find and use the e-mem executable provided by brew in the PATH?
Yes it should. But note that homebrew recipe  for E-MEM is linux only, so for Mac OSX we will use regular MUMmer anyway.

**Comment by alexeigurevich** [comment]
Finally we passed all the tests :)
Note: we released a slightly modified version 4.4.1 to make it possible (special homebrew edition). This version will be distributed from your university website, not from sourceforge.net as usual releases. 
Starting from the next release, these homebrew related changes will be added to the general tarball.

**Comment by sjackman** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
Triggered a rebuild of the bottles, which expired. (They last one week.)

**Comment by alexeigurevich** [comment]
Thanks!

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Homebrew-science, Alexi!

**Pull request closed without merging**
