### PR TITLE
graph-tool: bump revision for boost 1.60

### LINKED ISSUE #3237: graph-tool broken
I'm having trouble getting graph-tool working on my 'El Capitan' system.

First I tried a simple "brew install homebrew/science/graph-tool".  I'm using Homebrew python 2.7.11, numpy, scipy, etc...

```
$  python
Python 2.7.11 (default, Dec  5 2015, 14:44:53)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/graph_tool/__init__.py", line 105, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python2.7/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: __ZNK5boost9re_detail31cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
  Expected in: /usr/local/opt/boost/lib/libboost_regex.dylib
 in /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
>>>
```

When I look at that library, I don't see any obvious broken dependencies:

```
$  otool -L /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
/usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so:
	/usr/local/opt/boost/lib/libboost_iostreams.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost-python/lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_coroutine-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/cgal/lib/libCGAL.11.dylib (compatibility version 11.0.0, current version 11.0.1)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

I'm not sure what version "0.0.0" means, so next I tried force removing boost and putting it back.  That didn't help.

Then, after removing it all again, I tried building from source.  I decided to try this approach in case the missing library reference either resolved itself or became more obvious.

```
$  brew install --build-from-source boost boost-bcp boost-build boost-python homebrew/science/boost-compute
```

Boost installed just fine, but when I went to do graph-tool:

```
$  brew install --build-from-source homebrew/science/graph-tool
==> Installing graph-tool from homebrew/science
==> Installing dependencies for homebrew/science/graph-tool: autoconf, automake, intltool, swig, icon-naming-util
==> Installing homebrew/science/graph-tool dependency: autoconf
==> Downloading http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
==> Downloading from http://mirror.keystealth.org/gnu/autoconf/autoconf-2.69.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/autoconf/2.69 --with-lispdir=/usr/local/Cellar/autoconf/2.69/share/emacs/site
==> make install
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.0M, built in 6 seconds
==> Installing homebrew/science/graph-tool dependency: automake
==> Downloading http://ftpmirror.gnu.org/automake/automake-1.15.tar.xz
==> Downloading from http://ftp.wayne.edu/gnu/automake/automake-1.15.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/automake/1.15
==> make install
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M, built in 4 seconds
==> Installing homebrew/science/graph-tool dependency: intltool
==> Downloading https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
==> Downloading from https://launchpadlibrarian.net/199705878/intltool-0.51.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/intltool/0.51.0 --disable-silent-rules
==> make install
🍺  /usr/local/Cellar/intltool/0.51.0: 19 files, 184.4K, built in 4 seconds
==> Installing homebrew/science/graph-tool dependency: swig
==> Downloading https://downloads.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz
==> Downloading from http://iweb.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/swig/3.0.8
==> make
==> make install
🍺  /usr/local/Cellar/swig/3.0.8: 733 files, 5.2M, built in 1 minute 15 seconds
==> Installing homebrew/science/graph-tool dependency: icon-naming-utils
==> Downloading http://tango.freedesktop.org/releases/icon-naming-utils-0.8.90.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/icon-naming-utils/0.8.90
==> make install
🍺  /usr/local/Cellar/icon-naming-utils/0.8.90: 10 files, 80.5K, built in 4 seconds
==> Installing homebrew/science/graph-tool
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.skewed.de/graph-tool/graph-tool-2.12.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/graph-tool/2.12 PYTHON=python PYTHON_LDFLAGS=-undefin
==> make install
Last 15 lines from /Users/rick/Library/Logs/Homebrew/graph-tool/02.make:
namespace placeholders
          ^
/usr/local/include/boost/bind/placeholders.hpp:29:11: note: candidate found by name lookup is 'boost::placeholders'
namespace placeholders
          ^
8 errors generated.
make[3]: *** [graph_katz.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
6 errors generated.
8 errors generated.
make[3]: *** [graph_hits.lo] Error 1
make[3]: *** [graph_pagerank.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues
```

I went through the list of dependencies for the latest version of graph-tool from their website's build guide. [ https://graph-tool.skewed.de/download#compilation ]  It looked like I had them all.

I tried downloading it and building it with configure & make as described on that page, but I get the same placeholders error and it fails to build.

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes #3237.

### CODE REVIEW

**Comment by tdsmith** [comment]
@count0 It seems like graph-tool doesn't build against boost 1.60.0; you can see the error here: https://travis-ci.org/Homebrew/homebrew-science/jobs/103509668#L3167 -- let me know if I should file an issue against graph-tool.

**Comment by count0** [comment]
@tdsmith This has been fixed in git for a while. I will make a new release soon.

**Comment by tdsmith** [comment]
Awesome, thanks.

**Comment by tdsmith** [comment]
mooted by #3267.

**Pull request closed without merging**
