### PR TITLE
alpscore : update to 0.5.1

### PR DESCRIPTION
**Pull request by aeantipov**
The ALPSCore project, based on the ALPS (Algorithms and Libraries for Physics Simulations) project, provides generic algorithms and utilities for physics problems. It strives to increase software reuse in the physics community.

This release: Bugfixes and enhancements, mostly with accumulators.

For copyright see COPYRIGHT.txt. For licensing see LICENSE.txt. For acknowledgment in scientific publications see ACKNOWLEDGE.txt.

### CODE REVIEW

**Comment by dpo** [comment]
```
ALPSCore module : alps-accumulators

-- Building shared libraries
-- Compiler does not support MPI. Trying to find MPI
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Warning at common/cmake/ALPSEnableMPI.cmake:51 (message):
  MPI not found.
Call Stack (most recent call first):
  accumulators/CMakeLists.txt:25 (include)


CMake Error at /usr/local/Cellar/cmake/3.4.1/share/cmake/Modules/FindBoost.cmake:1247 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.59.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_mpi
```

**Comment by aeantipov** [comment]
Dominique, thanks. I'm not sure how to interpret it: in the Formula it is
```
depends_on :mpi => [:cc, :cxx, :recommended]
...
boost_options += ["with-mpi", "without-single"] if build.with? "mpi"
depends_on "boost" => boost_options
...
args << ("-DENABLE_MPI=" + ((build.with? "mpi") ? "ON" : "OFF"))
```
So boost::mpi should be there.

**Comment by dpo** [comment]
It might be related to the MPI glitches we're currently having.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
