### PR TITLE
PSPP 0.10.0

### PR DESCRIPTION
**Pull request by carcus88**

### CODE REVIEW

**Comment by dpo** [comment]
It seems like the formula should depend on `gtksourceview`: https://travis-ci.org/Homebrew/homebrew-science/jobs/119564873#L2224

**Comment by carcus88** [comment]
@dpo Do know what I need to do to fix this? Looks like its the sha1 issue but I set that in pspp.rb using
```shasum -a 256 pspp-0.10.0.tar.gz```

**Comment by dpo** [comment]
I think the issue is that you have a merge commit in your pull request. Try opening a fresh one.

**Comment by ilovezfs** [comment]
@carcus88 Current version is 0.10.2 now if you'd like to refresh this.

**Comment by carcus88** [comment]
Started a new one here https://github.com/Homebrew/homebrew-science/pull/3936

**Pull request closed without merging**
