### PR TITLE
Add MPICH support to MUMPS.

### PR DESCRIPTION
**Pull request by goxberry**
Add a conditional checking for the particular MPI implementation
installed (currently: open-mpi, mpich2), and then append flags
appropriate to that implementation.

### CODE REVIEW

**Comment by davydden** [comment]
@goxberry with regards to compile and link flags, aren't we safe if we compile with `mpic++`, `mpif90`, etc? I never used `MPICH` but this is my understanding of what those wrappers (also) do in case of `OpenMPI`.

**Comment by goxberry** [comment]
@davydden No. MPICH and OpenMPI both provide compiler wrappers called `mpicc`, etc., and each wraps compilers with different flags, plus each provides different options for their respective wrappers.

**Comment by davydden** [comment]
@goxberry sure, the flags are different. 

> Otherwise, that command should return the right compile flags for wrappers, which seems to be what is needed for the formula. The link flags for Open MPI should be taken from mpicc -showme:link.

I was referring to this part. IMHO one does not have to specify linking flags if things are compiled with wrappers. So no need to `mpicc -link_info`. 

Of course, that is a separate question from  `OpenMPI` vs `MPICH` consistency checks.

**Comment by goxberry** [comment]
@davydden Ideally, yes, the compiler wrappers work for builds and querying flags is unnecessary. IIRC, the compiler wrappers didn't "just work" when writing the hypre formula; they weren't detected by `configure`. There are many possible solutions; that one happened to be the most expedient and least surprising. Another option would be to substitute `mpicc` in for `clang` in `CC`, etc., which I think is fine as long as switching MPI implementations forces a rebuild of all formulas depending on MPI, and the effects of those substitutions are limited to formula building software with MPI. Better still would be to ensure that MPI wrappers are properly detected by `configure` instead of manual flag hacking or redirecting `CC`,  etc.

**Pull request closed without merging**
