### PR TITLE
Simbody 3.5.1 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
Simbody is a high-performance, open-source toolkit for science- and engineering-quality simulation of articulated mechanisms, including biomechanical structures such as human and animal skeletons, mechanical systems like robots, vehicles, and machines, and anything else that can be described as a set of rigid bodies interconnected by joints, influenced by forces and motions, and restricted by constraints. Simbody includes a multibody dynamics library for modeling motion in generalized/internal coordinates in O(n) time. This is sometimes called a Featherstone-style physics engine.

Release 3.5 focused primarily on infrastructure for and prototyping of rigid contact and impact, and the development of examples showing how to perform task space control using Simbody. These two projects were supported by our DARPA research subcontract with Open Source Robotics Foundation, and were integrated with Gazebo. Further development for rigid contact is required for smooth integration into Simbody; this is planned for Simbody 4.0 and only the bravest among you should attempt to use rigid contact before then. The task space control examples TaskSpaceControl-UR10 and TaskSpaceControl-Atlas can be found in the Simbody examples directory.

### CODE REVIEW

**Comment by alebcay** [comment]
CI tests failed with:
```
g++-4.9: internal compiler error: Killed (program cc1plus)
```
which may or may not be a simbody-specific issue.

**Comment by dpo** [comment]
There are audit warnings. Could you add a meaningful test, and a 'make check' if available?

**Comment by alebcay** [comment]
`make check` is unavailable, I will get around to adding a `test` block soon - it seems to install a library, though I'm not sure about the compiler flag that I need to use to get it linked correctly.

**Comment by dpo** [comment]
Any news?

**Comment by alebcay** [comment]
```
$ brew audit --strict ./simbody.rb
==> brew style simbody

1 file inspected, no offenses detected

==> audit problems
simbody:
 * A `test do` test block should be added

Error: 1 problems in 1 formulae
```

I've fixed the `sha256` sum - no idea why I had a `sha1` in the first place. Still pretty clueless about how to implement a usable `test ... do` block though.

**Comment by dpo** [comment]
Well, how do you use this stuff?

**Comment by alebcay** [comment]
It's supposed to already install the libraries and headers required in accessible places, but I get:

```
/var/folders/6z/dr13f9zs66g1mj3rc4d__n4m0000gn/T//c.cache/dir.93a7852143347ab6c1cffdb3cae54a573d139172/./ExamplePendulum.cpp(32): catastrophic error: cannot open source file "Simbody.h"
  #include "Simbody.h"
                      ^

compilation aborted for /var/folders/6z/dr13f9zs66g1mj3rc4d__n4m0000gn/T//c.cache/dir.93a7852143347ab6c1cffdb3cae54a573d139172/./ExamplePendulum.cpp (code 4
```

It can't seem to find the header. This is running an example that's included with the project, so I really don't know what's happening. Perhaps I need to look at the arguments for the `cmake` command again.

**Comment by dpo** [comment]
Could you add the source code for your test in a `test do` method? See, e.g., `armadillo.rb`.

**Comment by alebcay** [comment]
Well, I added a `test do` block. It still fails to compile though.

```
$ brew test -v ./simbody.rb
Testing simbody
==> /usr/bin/clang++ test.cpp -I/usr/local/Cellar/simbody/3.5.1/include -L/usr/local/Cellar/simbody/3.5.1/lib -o test
test.cpp:1:16: fatal error: 'Simbody.h' file not found
      #include "Simbody.h"
               ^
1 error generated.
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Error: simbody: failed
Failed executing: /usr/bin/clang++ test.cpp -I/usr/local/Cellar/simbody/3.5.1/include -L/usr/local/Cellar/simbody/3.5.1/lib -o test
/usr/local/Library/Homebrew/formula.rb:739:in `block in system'
/usr/local/Library/Homebrew/formula.rb:696:in `open'
/usr/local/Library/Homebrew/formula.rb:696:in `system'
/Volumes/Storage/Developer/homebrew-science/simbody.rb:49:in `block in <class:Simbody>'
/usr/local/Library/Homebrew/formula.rb:638:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:634:in `run_test'
/usr/local/Library/Homebrew/cmd/test.rb:38:in `block (2 levels) in test'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/cmd/test.rb:37:in `block in test'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `each'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `test'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by dpo** [comment]
This formula is in https://github.com/osrf/homebrew-simulation.

**Pull request closed without merging**
