### PR TITLE
libsequence 1.9.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
`analysis` is failing because it no longer tracks `libsequence` updates and API changes. I'm testing a patch that vendors `libsequence` into `analysis` and will create a pull request for that soon.

**Comment by jonchang** [comment]
#5457

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@sjackman any ideas how to fix the Travis failure?

**Comment by sjackman** [comment]
There is sometimes a `Details` link that shows the CI runs of a closed PR, but I don't see that here for some reason.

**Comment by ilovezfs** [comment]
It's there if you scroll up. https://travis-ci.org/Homebrew/homebrew-science/builds/224613744

**Comment by ilovezfs** [comment]
screen shot 2017-04-23 at 10 52 24 am

**Comment by sjackman** [comment]
Ah, great. Thanks, Jon. GitHub removed the text `Details`, so ⌘F didn't find it.

**Comment by ilovezfs** [comment]
No problem

**Comment by sjackman** [comment]
TravisCI
```
libtool: link: g++-5 -g -g -O2 -std=c++11 -o FastaConstructors FastaConstructors.o  -L../src/.libs -lboost_unit_test_framework /tmp/libsequence-20170422-17056-ohgk0d/libsequence-1.9.1/src/.libs/libsequence.a -ltbb -lz
FastaConstructors.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/home/linuxbrew/.linuxbrew/include/boost/test/tree/test_unit.hpp:249: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)'
```
https://travis-ci.org/Homebrew/homebrew-science/builds/224613744#L2118

**Comment by sjackman** [comment]
```ruby
  cxx11 = OS.linux? || MacOS.version > :mountain_lion ? [] : ["c++11"]
  depends_on "boost" => cxx11
```

It compiles fine on CircleCI with Ubuntu 14 Trusty with the host's GCC 4.8 because both `-std=c++98` and `-std=c++11` use the same ABI.

On TravisCI with Ubuntu 12 Precise with brewed GCC 5.3 it fails because `-std=c++98` and `-std=c++11` use different incompatible ABI.

I'll think about the solution to this problem. This PR https://github.com/Linuxbrew/brew/pull/334 will help.

**Comment by ilovezfs** [comment]
@sjackman possibly we should have boost build with c++11 as the default?

**Comment by sjackman** [comment]
> Possibly we should have boost build with c++11 as the default?

Seems reasonable to me. For Linuxbrew that means that everything that depends on Boost will also need to build with `ENV.cxx11`, at least as it's current configured. It could also be handled in `brew` by making ENV.cxx11` the default or by migrating to a GCC where it's the default.

Linuxbrew currently uses the old C++ ABI exclusively, because bottle are built with GCC 4.8 (unless the formula is marked as `fails_with :gcc => "4.8"` or `needs :cxx14`). We plan to migrate to the new C++ ABI, which should clear up these TravisCI C++ link failures. That migration will require rebuilding all the C++ bottles.

**Comment by sjackman** [comment]
Linuxbrew is currently designed for binary compatibility with Ubuntu 14.04 LTS (Trusty Tahr). Seems to make sense to move to Ubuntu 16.04 LTS (Xenial Xerus) assuming CircleCI provides that image. I'm curious which C++ ABI Xenial uses by default. They use GCC 5.3.1, like the current `gcc` formula in Linuxbrew.

**Comment by iMichka** [comment]
Homebrew has been known to support only the 3 last OS X versions, and I always found that a really good thing. Let's say this is sort of 3 year of support. Packages that don't build after 3 years get dropped. It's called darwinism :)

Compared to the 5 year Ubuntu LTS support, this is shorter. But if you want stable packages, just use the regular debian packages (or Fedora packages, whatever). With that scheme, Trusty is 3 years old, so can probably be dropped.

**Comment by sjackman** [comment]
When we migrate to CircleCI 2.0 we'll also migrate to Ubuntu 16 Xenial. The question is which C++ ABI they use by default. My inclination is to move to the new ABI.

**Pull request closed without merging**
