### PR TITLE
tbl2asn 24.2 (update) - urgent as previous version expired

### PR DESCRIPTION
**Pull request by tseemann**
NCBI releases this tool 

* unversioned
* makes the previous version stop working.

Awesome combo deal!

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman good to go!

**Comment by tdsmith** [comment]
Would you mind letting someone at NCBI know that a versioned URL would be really helpful?

**Comment by tdsmith** [comment]
(thanks for the PR!)

**Comment by tseemann** [comment]
@tdsmith There is going to be a big shake up at NCBI in terms of bioinformatics / open-source. Until then  there is nothing we can do. Many have tried for many years.

**Comment by tdsmith** [comment]
I almost said "I imagine there's history here..."

**Pull request closed without merging**
