### PR TITLE
Ococo 0.1.2.6

### PR DESCRIPTION
**Pull request by karel-brinda**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by sjackman** [comment]
Hi, Karel. You've included a merge commit in this PR. Please fix up this PR to include only your commit 42dd08db9378a9f571e80a03a32c8721bf14419f
```sh
git checkout master
git reset --hard origin/master # warning: this will discard any unsaved work
git cherry-pick 42dd08db9378a9f571e80a03a32c8721bf14419f
git push --force
```

**Comment by sjackman** [comment]
This tap Homebrew/science is being retired at the end of the year.

**Comment by karel-brinda** [comment]
@sjackman What's the replacement for the tap?

**Comment by sjackman** [comment]
You can submit this formula to https://github.com/Linuxbrew/homebrew-bio/ if you like.

**Comment by sjackman** [comment]
Sufficiently notable formula can be migrated to Homebrew/core. Homebrew/core requires that a GitHub repo have ≥ 50 stars, or ≥ 20 forks, or ≥ 20 watchers.

**Pull request closed without merging**
