### PR TITLE
gubbins: fix rewriting of matplotlib

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [ ] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [ ] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman is that not related error? 
```
Error: Failed to download resource "pillow"
```
Also, what about the following one?
```
Dependency fasttree should not use option with-double
```

**Comment by sjackman** [comment]
This PR looks good to me. Can you look into this error?

> Error: Failed to download resource "pillow"

It may first need a separate PR to fix `pillow`.

**Comment by tmozgach** [comment]
@sjackman  we fixed `pillow`, could you merge it?

**Comment by sjackman** [comment]
Please bump the `revision` and rebase this PR onto `master`.

**Comment by sjackman** [comment]
```
==> Verifying pillow-4.2.1_1.x86_64_linux.bottle.tar.gz checksum
Error: SHA256 mismatch
Expected: dad5cfdd59d7b081f13c0c33af1f103954c67b1dfad5b68d0526577777e0d895
Actual: a6f3379e4d23f2cba40660089290687a901ef8908a72dd1bd9ee6514e41c6203
Archive: /home/ubuntu/.cache/Homebrew/pillow-4.2.1_1.x86_64_linux.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
```

**Comment by sjackman** [comment]
This is weird…
```
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.6-55-g2139388 (Linux; x86_64 Ubuntu 14.04.4 LTS) curl/7.35.0 --fail --silent https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz -C 0 -o /home/ubuntu/.cache/Homebrew/zlib-1.2.11.x86_64_linux.bottle.tar.gz.incomplete
Downloaded to: /home/ubuntu/.cache/Homebrew/zlib-1.2.11.x86_64_linux.bottle.tar.gz
SHA256: 6f604280b9e056da163b81cef3076b2e39bbd2b8d3cc8c36d27c19c472c760a4
==> Verifying zlib-1.2.11.x86_64_linux.bottle.tar.gz checksum
==> FAILED
```

**Comment by sjackman** [comment]
Can you please rebase this PR onto `master`? That should I think resolve the `pillow` issue. Hopefully the `zlib` issue was transient.

**Comment by tmozgach** [comment]
@sjackman did it work now?

**Comment by sjackman** [comment]
`brew audit gubbins` failed
```
Error: 3 problems in 1 formula
homebrew/science/gubbins:
  * C: 24: col 21: Trailing whitespace detected.
  * C: 25: col 22: Trailing whitespace detected.
  * Dependency fasttree should not use option with-double
==> FAILED
```
You can ignore the `fasttree` issue.

**Comment by tmozgach** [comment]
@sjackman ready!

**Comment by sjackman** [comment]
Merged. Thanks, Tanya!

**Pull request closed without merging**
