### PR TITLE
Update links-scaffolder.rb

### PR DESCRIPTION
**Pull request by warrenlr**
new, improved, version of LINKS

### CODE REVIEW

**Comment by sjackman** [comment]
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1909/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_Homebrew_science_links_scaffolder/
```
Error Message
failed: brew test --verbose Homebrew/science/links-scaffolder

Testing links-scaffolder
==> /usr/local/Cellar/links-scaffolder/1.5/bin/LINKS
Can't locate Bloom/Faster.pm in @INC (you may need to install the Bloom::Faster module) (@INC contains: /usr/local/Cellar/links-scaffolder/1.5/bin/./lib/Bloom-Faster-1.7/bloom5-16-3/lib/site_perl/5.16.3/x86_64-linux /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/links-scaffolder/1.5/bin/LINKS line 33.
BEGIN failed--compilation aborted at /usr/local/Cellar/links-scaffolder/1.5/bin/LINKS line 33.
Error: links-scaffolder: failed
<255> expected but was
<2>.
```

**Comment by sjackman** [comment]
Hi, Rene. Is `Bloom::Faster` a new dependency of LINKS?

**Comment by warrenlr** [comment]
yes

it is included in the ./lib subfolder
and re-built for several PERl distributions


________________________________________

**Comment by sjackman** [comment]
Merged. Thanks, Rene.

**Comment by sjackman** [comment]
I added
```ruby
depends_on "Bloom::Faster" => :perl
```

**Pull request closed without merging**
