### PR TITLE
trans-abyss 1.5.5

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew readall --aliases homebrew/science
==> brew uses homebrew/science/trans-abyss
==> SKIPPING: homebrew/science/trans-abyss
Unsatisfied dependency: pysam
Homebrew does not provide special Python dependencies; install with:
  `pip install pysam`
Unsatisfied dependency: biopython
Homebrew does not provide special Python dependencies; install with:
  `pip install biopython`
Unsatisfied dependency: python-igraph
Homebrew does not provide special Python dependencies; install with:
  `pip install python-igraph`
==> brew fetch --retry homebrew/science/trans-abyss --build-bottle --force

```

**Comment by jonchang** [comment]
```
 $ brew test -v trans-abyss
Testing homebrew/science/trans-abyss
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160909-71181-1m9hrxw.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/trans-abyss.rb -v
==> /usr/local/Cellar/trans-abyss/1.5.5/bin/transabyss --help
usage: transabyss [-h] [--version] [--se PATH [PATH ...]]
                  [--pe PATH [PATH ...]] [--SS] [--outdir PATH] [--name STR]
                  [--stage {dbg,unitigs,contigs,references,junctions,final}]
                  [--length INT] [--cleanup {0,1,2,3}] [--threads INT]
                  [--mpi INT] [-k INT] [-c INT] [-e INT] [-E INT] [-q INT]
                  [-Q INT] [-n INT] [-s INT] [--gsim INT] [--indel INT]
                  [--island INT] [--useblat] [--pid FLOAT] [--walk FLOAT]
                  [--noref]

Assemble RNAseq with Trans-ABySS.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

Input:
  --se PATH [PATH ...]  single-end read files
  --pe PATH [PATH ...]  paired-end read files
  --SS                  input reads are strand-specific

Basic Options:
  --outdir PATH         output directory [/private/tmp/trans-abyss-
                        test-20160909-71182-1u4ecma/transabyss_1.5.5_assembly]
  --name STR            assembly name [transabyss] (ie. output assembly:
                        'transabyss-final.fa')
  --stage {dbg,unitigs,contigs,references,junctions,final}
                        run up to the specified stage [final]
  --length INT          minimum output sequence length [100]
  --cleanup {0,1,2,3}   level of clean-up of intermediate files [1]

ABySS Parameters:
  --threads INT         number of threads ('j' in abyss-pe) [1]
  --mpi INT             number of MPI processes ('np' in abyss-pe) [0]
  -k INT, --kmer INT    k-mer size [32]
  -c INT, --cov INT     minimum mean k-mer coverage of a unitig [2]
  -e INT, --eros INT    minimum erosion k-mer coverage [c]
  -E INT, --seros INT   minimum erosion k-mer coverage per strand [0]
  -q INT, --qends INT   minimum base quality on 5' and 3' ends of a read [3]
  -Q INT, --qall INT    minimum base quality throughout a read
  -n INT, --pairs INT   minimum number of pairs for building contigs [2]
  -s INT, --seed INT    minimum unitig size for building contigs [k]

Advanced Options:
  --gsim INT            maximum iterations of graph simplification [2]
  --indel INT           indel size tolerance [1]
  --island INT          minimum length of island unitigs [0]
  --useblat             use BLAT alignments to remove redundant sequences.
  --pid FLOAT           minimum percent sequence identity of redundant
                        sequences [0.95]
  --walk FLOAT          percentage of mean k-mer coverage of seed for path-
                        walking [0.05]
  --noref               do not include reference paths in final assembly

Written by Ka Ming Nip.
Copyright 2016 Canada's Michael Smith Genome Sciences Centre
Report bugs to <trans-abyss@googlegroups.com>
==> /usr/local/Cellar/trans-abyss/1.5.5/bin/transabyss-analyze --help
Failed to execute: /usr/local/Cellar/trans-abyss/1.5.5/bin/transabyss-analyze
==> Sandbox log
Sep  9 14:11:27 kernel[0]: Sandbox: Python(71192) deny(1) file-write-create /usr/local/Cellar/trans-abyss/1.5.5/utilities/fasta_utils.pyc
Sep  9 14:11:27 kernel[0]: Sandbox: Python(71192) deny(1) file-write-create /usr/local/Cellar/trans-abyss/1.5.5/utilities/sam_cid_extractor.pyc
Error: homebrew/science/trans-abyss: failed
Failed executing: /usr/local/Cellar/trans-abyss/1.5.5/bin/transabyss-analyze --help
/usr/local/Library/Homebrew/formula.rb:1608:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1545:in `open'
/usr/local/Library/Homebrew/formula.rb:1545:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/trans-abyss.rb:33:in `block in <class:TransAbyss>'
/usr/local/Library/Homebrew/formula.rb:1446:in `block (2 levels) in run_test'
/usr/local/Library/Homebrew/formula.rb:775:in `with_logging'
/usr/local/Library/Homebrew/formula.rb:1445:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1439:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by ilovezfs** [comment]
@jonchang PR refreshed.

**Comment by jonchang** [comment]
Looks like this is currently blocked by `abyss` failing to build, #4506.

**Comment by ilovezfs** [comment]
@jonchang #4506 shipped if you'd like to take this for a spin.

**Comment by jonchang** [comment]
Confirmed working. Thanks @ilovezfs!

**Pull request closed without merging**
