### PR TITLE
xmi-msim: revision for hdf5

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tschoonj it doesn't seem thrilled with the new URL (https settings confused maybe?)
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160912-15179-1yn1hyq.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/build.rb /usr/local/Library/Taps/homebrew/homebrew-science/xmi-msim.rb --build-bottle --verbose
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://xmi-msim.tomschoonjans.eu/xmimsim-5.0.tar.gz
==> Downloading from https://xmi-msim.tomschoonjans.eu/xmimsim-5.0.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://xmi-msim.tomschoonjans.eu/xmimsim-5.0.tar.gz -C 0 -o /Users/brew/Library/Caches/Homebrew/xmi-msim-5.0.tar.gz.incomplete --silent
Error: Failed to download resource "xmi-msim"
Download failed: http://xmi-msim.tomschoonjans.eu/xmimsim-5.0.tar.gz
==> FAILED
```

**Comment by ilovezfs** [comment]
odd - no trouble running it from the Homebrew Testing job, so trying again here ...

**Comment by zmwangx** [comment]
Wow you got some frigging big bottles here: https://bot.brew.sh/job/Homebrew%20Testing/1062/version=el_capitan/. Jamming up the build queue...

**Comment by ilovezfs** [comment]
@zmwangx the mystery is why this https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5843/ failed the first time. It's possible @tschoonj's machine was down.

**Comment by tschoonj** [comment]
I managed to obtain free SSL certificates for my Cloudfront subdomains, through Let' Encrypt.

They also seem to work fine here locally on my El Capitan laptop.

**Comment by ilovezfs** [comment]
@tschoonj cool! I'll update the URLs to use https then :)

**Comment by tschoonj** [comment]
Thanks, I will also file a PR for my two other Formulas `xrmc` and `xraylib`

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@tschoonj I think the bottles may be too big for bintray. It seems to be deliberately cutting off the connection at about 95%. Maybe this formula can be restructured so that the database is generated in `def post_install` after the bottle is poured, instead of being stored inside the bottle? Would that be possible or does that make no sense?

**Comment by tschoonj** [comment]
Sure that is certainly possible. The call to `xmimsim-db` then needs to go into a `post_install` block.

Shall I do that or would you like to give this a try?

**Comment by ilovezfs** [comment]
@tschoonj how's this?
```
diff --git a/xmi-msim.rb b/xmi-msim.rb
index 0714609..40a8084 100644
--- a/xmi-msim.rb
+++ b/xmi-msim.rb
@@ -3,7 +3,7 @@ class XmiMsim < Formula
   homepage "https://github.com/tschoonj/xmimsim"
   url "https://xmi-msim.tomschoonjans.eu/xmimsim-5.0.tar.gz"
   sha256 "3503b56bb36ec555dc941b958308fde9f4e550ba3de4af3b6913bc29c2c0c9f1"
-  revision 5
+  revision 6
 
   bottle do
     sha256 "16b9d9321218883a8e4b7250be0a513e1cab6da8dd70d7df360e02eb6bb992c8" => :el_capitan
@@ -46,12 +46,15 @@ class XmiMsim < Formula
                           "--disable-mac-integration",
                           "--disable-libnotify",
                           "--enable-opencl"
-    system "make"
-
-    # this next step can take a long time...
-    system "./bin/xmimsim-db"
     system "make", "install"
-    (share / "xmimsim").install "xmimsimdata.h5"
+  end
+
+  def post_install
+    ohai "Generating xmimsim-db – this may take a while"
+    mktemp do
+      system "#{bin}/xmimsim-db"
+      (share/"xmimsim").install "xmimsimdata.h5"
+    end
   end
 
   test do
```

**Comment by ilovezfs** [comment]
@tschoonj voilà: https://github.com/Homebrew/homebrew-science/pull/4299

this should also put a smile on @zmwangx's face

**Pull request closed without merging**
