### PR TITLE
Update salmon to v0.7.0

### PR DESCRIPTION
**Pull request by rob-p**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

cc @sjackman

### CODE REVIEW

**Comment by rob-p** [comment]
There seems to be a problem with (and only with Mavericks), though I feel like that is Mavericks' fault (has to do with non-standard compliant behavior about `max_align_t`, I think.

**Comment by sjackman** [comment]
The code that fails is a hack for `gcc`, so it could be disabled for `clang.`
```
/tmp/salmon-20160815-56369-11v446m/salmon-0.7.0/include/concurrentqueue.h:241:10: error: no type named 'max_align_t' in the global namespace; did you mean 'std::max_align_t'?
        typedef ::max_align_t max_align_t;      // GCC forgot to add it to std:: for a while
                ^~~~~~~~~~~~~
                std::max_align_t
```
https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5494/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_homebrew_science_salmon/

I'm happy merging this as is. We can fix Mavericks later if you're inclined.

**Comment by sjackman** [comment]
The preferred git commit log message is simply `salmon 0.7.0` to make search the git history for particular versions of software easier.

**Comment by rob-p** [comment]
I think that the problem is that clang (on mavericks only) defines the GCC symbol, and so falls into the path that it shouldn't.  The issue is that this is coming from the [concurrent queue](https://github.com/cameron314/concurrentqueue) library, which isn't maintained by me.

**Comment by rob-p** [comment]
Also can I "re-write" the history or some other git magic to change the commit message?

**Comment by sjackman** [comment]
You can fix up the commit log message with `git commit --amend`
I'll do that when I pull the PR, right now.

**Comment by sjackman** [comment]
Merged without a bottle for Mavericks (see above).

**Pull request closed without merging**
