### PR TITLE
libbi: fix perl deps, remove runtime test from build

### PR DESCRIPTION
**Pull request by sbfnk**
### Have you:

- [X] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [X] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [X] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [X] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [X] Not altered the `bottle` section?
- [X] Checked that the tests still pass?

Critical change:

1. Updated Test::Simple version, as the current link does no longer exist.

Improvements:

2. Changed the URLs of perl dependencies to be downloaded to https.
3. Removed run-time test `010_cpu.t` from build time; this would fail in superenv as the thrust header library, installed by the formula itself, is not yet linked at this stage and therefore inaccessible. Note that the test run by `010_cpu.t` is exactly the one specified in `test do`.
4. Tidied up environment variables. Most of these were only needed for the run-time test conducted at build time (see 3).

### CODE REVIEW

**Comment by sbfnk** [comment]
linuxbrew build failing as per https://github.com/Linuxbrew/homebrew-core/issues/3294

**Comment by rwhogg** [comment]
If all goes well, I'll hopefully be able to merge `hdf5` into Linuxbrew in a few hours (see https://github.com/Linuxbrew/homebrew-core/pull/3324). Then hopefully the Linux build should pass 🤞

Thanks for making this PR @sbfnk! I was about to open an issue for the missing Perl dependency.

(FYI: I don't have commit privileges for homebrew-science, so I can't merge this PR regardless of what happens to `hdf5`.)

**Comment by sbfnk** [comment]
Build still failing on linuxbrew, this time because of missing qrupdate. Will have to wait for https://github.com/Homebrew/homebrew-core/pull/15836/commits/9191317045fac8f990d04f5e71fe21925d8e77d6 to be merged into linuxbrew/core.

**Comment by sbfnk** [comment]
Updated this to disable bottling, thus preventing the error in https://github.com/Linuxbrew/homebrew-core/pull/3460. I think we can't use a bottle here because of the perl dependencies, but will be happy to stand corrected.

**Comment by sbfnk** [comment]
@BrewTestBot test this please

**Comment by sbfnk** [comment]
Will put a tidier version in a new pull request.

**Pull request closed without merging**
