### PR TITLE
kat: Use the brewed matplotlib numpy scipy for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
Why not vendor them?

**Comment by sjackman** [comment]
TravisCI
```
/home/linuxbrew/.linuxbrew/opt/boost/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
kat-plot_density.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
```
https://travis-ci.org/Homebrew/homebrew-science/builds/260302348#L3935

**Comment by sjackman** [comment]
I believe `kat` depends on `numpy` depends on `:fortran` provided by `gcc`.
`kat` then fails to compile with `gcc-5` which uses a different boost ABI than `gcc-4.8`.

**Comment by sjackman** [comment]
Jenkins
```
checking for python3... no
configure: WARNING: Cannot find python3 in your system path
```
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1043/version=sierra/testReport/junit/brew-test-bot/sierra/install_homebrew_science_kat/

**Comment by sjackman** [comment]
> Why not vendor them?

For me vendoring is a last resort. Why vendor them?

**Comment by sjackman** [comment]
Merged.

**Pull request closed without merging**
