### PR TITLE
graph-tool 2.9

### PR DESCRIPTION
**Pull request by tschoonj**
cairomm c++11 option no longer exists so it was removed here

### CODE REVIEW

**Comment by dpo** [comment]
I presume this supersedes #2792?

**Comment by dpo** [comment]
@xu-cheng  What does a status of "UNSTABLE" mean (yellow light)?

**Comment by tschoonj** [comment]
Yep mine is the more recent version. I also changed the cairomm dependency a bit

Op 2 okt. 2015 om 19:40 heeft Dominique <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I presume this supersedes #2792<https://github.com/Homebrew/homebrew-science/pull/2792>?

**Comment by dpo** [comment]
@tdsmith @xu-cheng I'm not clear on what an "UNSTABLE" status means on the build bot.

**Comment by xu-cheng** [comment]
Sorry no idea.

**Comment by tschoonj** [comment]
@dpo could you merge this one in please? 

Thanks!

**Comment by dpo** [comment]
@mikemcquaid What does a status of 'UNSTABLE' mean on the bot?

**Comment by mikemcquaid** [comment]
@dpo There was invalid XML in the output so Jenkins couldn't parse it. You can look at the logs to work out if it passedfailed.

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
