### PR TITLE
openmeeg: revision for hdf5

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
I looked at https://github.com/Homebrew/homebrew-science/issues/2545 yesterday, which is still an issue on 10.10. Adding `-framework Accelerate` to `CMAKE_CXX_FLAGS` gets past that issue, but then I ran into another problem where `FC.h` can't be found. I think that's a header generated by CMake for C/Fortran interoperability. Unfortunately, Fortran support seems broken in `openmeeg`; I wasn't able to have it discover the Fortran compiler.

See https://github.com/openmeeg/openmeeg/issues/139

**Comment by iMichka** [comment]
There seem to be a new version here: http://openmeeg.github.io (2.3.0).
Though it is not tagged on GitHub: https://github.com/openmeeg/openmeeg

The formula has been broken since at least July 2015. This does not really block the hdf5 migration, it's just that if this gets fixed on day, maybe the next failures could come through the hdf5 changes. No way to test that now, but as say, it does not prevent us to ship a newer hdf5.

**Comment by ilovezfs** [comment]
Closing this for now.

**Pull request closed without merging**
