### PR TITLE
Petsc 3.6 (updated)

### PR DESCRIPTION
**Pull request by davydden**
pull after https://github.com/Homebrew/homebrew-science/pull/2504

### CODE REVIEW

**Comment by davydden** [comment]
pull after https://github.com/Homebrew/homebrew-science/pull/2511

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot  test this please

**Pull request closed without merging**
