### PR TITLE
Update qhull.rb

### PR DESCRIPTION
**Pull request by schoeps**
make qhull compatible with recent clang, see https://trac.macports.org/ticket/47472

### CODE REVIEW

**Comment by dpo** [comment]
Thanks. Please squash your commits.

**Comment by schoeps** [comment]
done.

**Comment by schoeps** [comment]
@dpo qhull says: please merge my formula (and the ones of my sisters gmsh and getdp).

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by tseemann** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
