### PR TITLE
meme 4.10.1_3

### PR DESCRIPTION
**Pull request by saketkc**
Enable parallel, add doi, tag, desc

### CODE REVIEW

**Comment by tseemann** [comment]
``` 
 Error: 1 problem in 1 formula
homebrew/science/meme:
 * There are multiple conflicting ways to install MPI. Use an MPIRequirement:
  depends_on :mpi => [<lang list>]
Where <lang list> is a comma delimited list that can include:
  :cc, :cxx, :f77, :f90
```

**Comment by saketkc** [comment]
@tseemann Looks like you are a maintainer now? :-)
This is good to merge now.

**Comment by tseemann** [comment]
@saketkc Apparently submitting enough formulae to annoy @sjackman is the path to getting deputized :)

**Comment by tseemann** [comment]
==> audit problems
homebrew/science/meme:
 * `version`(line 9) should be put before `checksum`(line 8)

**Pull request closed without merging**
