### PR TITLE
opencv 2.4.11

### PR DESCRIPTION
**Pull request by kashif**

### CODE REVIEW

**Comment by iml** [comment]
I will look into this later but I'm a bit concerned that the bottle here appears to be less than half the size of the existing one.

**Comment by kashif** [comment]
true... one possible reason could be that it is not building for some architecture e.g. `x86_64`... I am also checking...

**Comment by iml** [comment]
@BrewTestBot test this please.

**Comment by tdsmith** [comment]
It would be nice to land this together with #2005.

**Comment by tdsmith** [comment]
Accepted as 98e9515. Thanks!

**Pull request closed without merging**
