### PR TITLE
simpleitk 0.9

### PR DESCRIPTION
**Pull request by iMichka**
Updated simpleITK to version 0.9

Description and sha256 are now defined. The PYTHON_INCLUDE_DIR also needs to be passed down to cmake, else simpleITK will not be linked against the right python.

Bug #2554 should be fixed with this; though the bug is not directly related but was due to a problem with swig 3.0.6.

### CODE REVIEW

**Comment by tdsmith** [comment]
Builds are failing; looks like this needs vtk specced as a dependency:

```
CMake Error at /usr/local/lib/cmake/ITK-4.8/Modules/ITKVtkGlue.cmake:9 (find_package):
  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:49 (include)
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:26 (itk_module_load)
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:70 (_itk_module_config_recurse)
  /usr/local/lib/cmake/ITK-4.8/ITKConfig.cmake:69 (itk_module_config)
  CMakeLists.txt:52 (find_package)
```

**Comment by iMichka** [comment]
```fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: can't write to output file (No space left on device)```

Seems the bot needs some cleanup or a bigger hard drive :)

**Comment by dpo** [comment]
Now there's a different (but probably related) error:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../../../lib/libSimpleITKBasicFilters5-0.9.a(length ) size too large (archive member extends past the end of the file)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: internal ranlib command failed
```

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
The El capitan build bot asks for:

```
Error: 1 problem in 1 formula
homebrew/science/simpleitk:
 * python modules have explicit framework links
These python extension modules were linked directly to a Python
framework binary. They should be linked with -undefined dynamic_lookup
instead of -lpython or -framework Python.
  /usr/local/Cellar/simpleitk/0.9.0/lib/python2.7/site-packages/SimpleITK/_SimpleITK.so
```

This is what we implemented for insighttoolkit:
https://github.com/Homebrew/homebrew-science/pull/2572

I know what needs to be done and I'll patch simpleITK to make it work.

The two other bots fail with:
```
CMake Error at /usr/local/Cellar/vtk/6.3.0/lib/cmake/vtk-6.3/vtkModuleAPI.cmake:120 (message):
  Requested modules not available:

    vtkRenderingFreeTypeOpenGL
Call Stack (most recent call first):
  /usr/local/lib/cmake/ITK-4.8/Modules/ITKVtkGlue.cmake:30 (vtk_module_config)
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:49 (include)
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:26 (itk_module_load)
  /usr/local/lib/cmake/ITK-4.8/ITKModuleAPI.cmake:70 (_itk_module_config_recurse)
  /usr/local/lib/cmake/ITK-4.8/ITKConfig.cmake:69 (itk_module_config)
  CMakeLists.txt:52 (find_package)
```

I'll rebuild on my side and look what is going on. Probably some dependency to enable/disable.

**Comment by dpo** [comment]
`vtk` was updated just a few days ago. It might be enough to kick off a new build when you're ready with the 10.11 patch.

**Comment by iMichka** [comment]
I changed the build strategy. It will now use the Superbuild setup from simpleITK, which is very nice:

- We do no more need the vtk dependency which was there for obscure reasons, probably due to the itk dependency ...
- We do no more need the itk dependency; the superbuild will build itk by itself in the build folder. This is important as simpleITK uses an itk version (currently itk 4.7.0) that may be different from the one which is provided in homebrew (itk 4.8.0 soon).
- SimpleITK needs Lua 5.1 to build; homebrew moved to Lua 5.2, which is not backward compatible with 5.1. The super build will use it's own Lua version.
- I enabled the system swig to speed up the build

All in all, the build lasted 51 min on my macbook pro, which opens the possibility to get bottles for simpleITK (if homebrew buildbots can cope with that :))

**Comment by dpo** [comment]
> We do no more need the itk dependency; the superbuild will build itk by itself in the build folder. This is important as simpleITK uses an itk version (currently itk 4.7.0) that may be different from the one which is provided in homebrew (itk 4.8.0 soon).

Are those two versions of `itk` going to conflict or otherwise overwrite files from one another?

**Comment by iMichka** [comment]
No, the setup.py will just install simpleITK:
```
michkapopoff$ cd /usr/local/Cellar/simpleitk/0.9.0/lib/python2.7/site-packages/SimpleITK 
michkapopoff$ ls
SimpleITK.py	SimpleITK.pyc	_SimpleITK.so	__init__.py	__init__.pyc
```

The built ITK will be deleted from the tmp folder.

It seems that the buildbots did not manage it. For the error with  -undefined dynamic_lookup, I'll need to do a patch in simpleITK and this will need a little bit of time. Can we temporarily bypass this ?

**Comment by dpo** [comment]
> The built ITK will be deleted from the tmp folder.

Yes, but does it get installed and does it potentially overwrite the ITK installed with `brew install insighttoolkit`?

The Python issue can be resolved later. I had to restart the bottle job though.

**Comment by iMichka** [comment]
No it won't conflict as it does not install ``ìnsighttoolkit```. Everything is wrapped in the _SimpleITK.so library.

Here is a log with the final install steps so you can see what is going on:
https://gist.github.com/iMichka/2e97cf218ff7bcb81fe6

**Comment by iMichka** [comment]
I pushed a new version with support for HEAD, because the path of the setup.py file has changed.

**Pull request closed without merging**
