### PR TITLE
Therion 5.3.16

### PR DESCRIPTION
**Pull request by un1x86**
New version 5.3.16
- Uses VTK6

### CODE REVIEW

**Comment by dpo** [comment]
@BrewTestBot test this please

**Comment by dpo** [comment]
@mikemcquaid I may be doing something wrong but it looks like a bottle isn't being built: `pr-1786` isn't a tag and `brew pull --bottle` fails:
````
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ Mac\ OS\ X\ 10.9.5) https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-1786.patch -o /Library/Caches/Homebrew/homebrew:master...pr-1786.patch
````

**Comment by mikemcquaid** [comment]
@dpo http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/938/version=yosemite/console

> ==> SKIPPING: therion
> A LaTeX distribution is required for Homebrew to install this formula.

The bot can't build things that require `:tex`.

**Comment by dpo** [comment]
Ah thanks. Sorry. Strange that the build is marked successful though.

**Pull request closed without merging**
