### PR TITLE
simulate-pcr: replace /usr/bin/perl with /usr/bin/env perl

### PR DESCRIPTION
**Pull request by tmozgach**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [ ] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [ ] Removed the `revision` line, if any, when bumping the version number?
- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [ ] Not altered the `bottle` section?
- [ ] Checked that the tests still pass?

### CODE REVIEW

**Comment by tmozgach** [comment]
@sjackman could you merge that?

**Comment by sjackman** [comment]
Replace change the commit log message to:
```
simulate-pcr: replace /usr/bin/perl with /usr/bin/env perl
```
(note the space ` ` after the colon `:`)

**Comment by sjackman** [comment]
```
  * perl modules should be vendored rather than use deprecated `depends_on "Bio::Perl" => :perl`
```
Let's ignore this audit error for now.
https://travis-ci.org/Homebrew/homebrew-science/builds/242227334#L1163

**Comment by tmozgach** [comment]
@sjackman Fixed! Ready for merging

**Comment by sjackman** [comment]
Merged! Thanks, Tanya. 👍

This formula isn't bottled because of `depends_on "Bio::Perl" => :perl`, so I replaced the `revision 1` with `bottle :unneeded`.

**Pull request closed without merging**
