### PR TITLE
netcdf: update version to 4.4.1.1

### PR DESCRIPTION
**Pull request by goxberry**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [ ] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by goxberry** [comment]
This pull request updates the versions of a couple libraries within the NetCDF formula, along with their SHA256 hashes.

I get one error from `brew audit --online --strict`:

```
  * Non-libraries were installed to "/usr/local/Cellar/netcdf/4.4.1.1/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/Cellar/netcdf/4.4.1.1/lib/libnetcdf.settings
```

This file lists the build settings determined from the `configure` script, and could probably be moved to a directory like `#{prefix}/pkgshare` without harm. The file was created in November of 2015, so it had to raise similar `brew-audit` errors in recent pull requests, yet those pull requests were accepted, so I left the file where it is.

**Comment by jonchang** [comment]
Hi @goxberry, thanks for the pull request. Could you please update the `revision` numbers of these dependent formulae? Once those linkage tests pass this should be good to go. 

```
abinit
cdo
dealii
etsf_io
getdp
gmt
gmt4
gnudatalanguage
moab
nccmp
ncview
radx
slepc
```

**Comment by goxberry** [comment]
@jonchang Rebased onto `master` and added revision bumps for each formula, one formula per commit. Let me know if the PR needs squashing or additional tweaks.

**Comment by jonchang** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
Ok, there's an issue with our bottling infrastructure so let's just get the new version merged and then work on the dependent bottles. I've reverted the revision changes (but they're saved on [my fork](https://github.com/Homebrew/homebrew-science/compare/master...jonchang:netcdf-revisions?expand=1) ). I will open a new pull request for the revisions once this pull request is merged.

**Comment by jonchang** [comment]
Thanks @goxberry!

**Pull request closed without merging**
