### PR TITLE
Bedops v2p4p21

### PR DESCRIPTION
**Pull request by alexpreynolds**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

### CODE REVIEW

**Comment by jonchang** [comment]
The executable isn't getting installed on macOS for some reason. 

```
cp applications/bed/sort-bed/bin/sort-bed bin/
cp: applications/bed/sort-bed/bin/sort-bed: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/bedops/bin/bedops bin/
cp: applications/bed/bedops/bin/bedops: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/closestfeats/bin/closest-features bin/
cp: applications/bed/closestfeats/bin/closest-features: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/bedmap/bin/bedmap bin/
cp: applications/bed/bedmap/bin/bedmap: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/bedextract/bin/bedextract bin/
cp: applications/bed/bedextract/bin/bedextract: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/starch/bin/starch bin/
cp: applications/bed/starch/bin/starch: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/starch/bin/unstarch bin/
cp: applications/bed/starch/bin/unstarch: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/starch/bin/starchcat bin/
cp: applications/bed/starch/bin/starchcat: No such file or directory
make: [install] Error 1 (ignored)
cp applications/bed/conversion/bin/convert2bed bin/
cp: applications/bed/conversion/bin/convert2bed: No such file or directory
make: [install] Error 1 (ignored)
```

**Comment by alexpreynolds** [comment]
There is some issue with the line `env :std` which is removed in commit 52b9c0251d09dedbaf4e8bed8e25af3728819be3 because it is identified as deprecated by `brew audit --strict --online <recipe>`. 

Can this deprecated call be replaced with something new? If so, I can put it back into the recipe, or simply put the deprecated call back if it is not an error, but a warning. Thanks for any advice.

**Comment by jonchang** [comment]
`env :std` is going to go away in the future so this formula will need to work without it. Linuxbrew still uses `env :std` on all formulae so that's why it still works on the Travis build. But it will go away on Linux in the future too.

**Comment by alexpreynolds** [comment]
How would I make this work without `env :std`? I'm not sure what it does or
why it is relevant to this recipe. Is its functionality replaced with a
newer call?

**Comment by jonchang** [comment]
`env :std` is deprecated and its functionality likely won't be replaced. Homebrew wraps all build tools and filters out many environment variables in order to provide a consistent set of flags and ensure that all e.g., include and library paths are properly added as arguments. This permits features like our binary bottles so that people don't have to recompile everything from source all the time.

**Comment by alexpreynolds** [comment]
How do people now write recipes, if customizations to the environment are
required for the build process? I'm not sure how to debug this recent
change to how recipes work, I guess. Is there another recipe I can use as a
template that has solved this problem?

**Pull request closed without merging**
