### PR TITLE
concorde: fix with-cplex build

### PR DESCRIPTION
**Pull request by Moisan**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [x] Written a sensible test? (The best test is to compile and run a sample program.)

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Added/bumped the `revision` number if the changes affect the precompiled bottles?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

The --with-cplex option was failing at build due a to missing `define` in the more recent versions of CPLEX (after CPLEX 9 I think). I fixed the issue by adding back the missing define in a concorde .h file. 

I also fixed the test call to use `#{bin}`.

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Has the patch been reported upstream? I'm OK to merge this as-is but I would prefer this gets fixed upstream if possible. Thanks.

**Comment by iMichka** [comment]
Ping @Moisan

**Comment by Moisan** [comment]
Hi, sorry the delay. I just wrote to William Cook at [the contact information given on the Concorde web page](http://www.math.uwaterloo.ca/tsp/concorde/contact/contact.htm) explaining the changes and asking if he wants to incorporate them.

**Comment by iMichka** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@Moisan Thanks for your contribution

**Pull request closed without merging**
