### PR TITLE
opencv 2.4.13

### PR DESCRIPTION
**Pull request by heinemml**
### Have you:

- [x] Followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md) document?
- [x] Checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-science/pulls) for the same update/change?
- [x] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [x] Built your formula locally prior to submission with `brew install <formula>`?

### Updates to existing formula: have you

- [x] Removed the `revision` line, if any, when bumping the version number?
- [x] Not altered the `bottle` section?
- [x] Checked that the tests still pass?

* bumped version
* fixed audit warnings in formula

### CODE REVIEW

**Comment by heinemml** [comment]
Okay, lots of strange errors. Does anyone an Idea what's going wrong here?

The linkages of butterflow are broken because the bottle is used which is linked against 
```
  /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib
  /usr/local/opt/ffmpeg/lib/libavformat.56.dylib
  /usr/local/opt/ffmpeg/lib/libavutil.54.dylib
```
But current ffmpeg version supplies version 57/55 of the libs. So building from sources works.

Even stranger, openalpr reports an error that it can't find `liblog4cplus-1.1.9.dylib`. If I try it on my System it links against `liblog4cplus-1.2.0.dylib`. And it is also poured from bottle! Are there different bottle versions?


Additionally the travis-ci build cancels after 10 minutes of "no output". On my macbook the opencv `make` step takes around 9m40s. So if the bot is a bit slower it is no surprise.

How do I go on from here?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Pulling despite the errors, as these are chicken and egg CI issues, unless all combined into one PR.

**Comment by ilovezfs** [comment]
@heinemml Thank you for your contribution to Homebrew Science! We really appreciate it. :bow:

**Pull request closed without merging**
