### PR TITLE
cufflinks: use current boost

### LINKED ISSUE #3076: Cufflinks won't load
diego-macbookpro:lib Diego$ cufflinks 
dyld: Symbol not found: __ZN5boost7archive21basic_binary_iarchiveINS0_15binary_iarchiveEE13load_overrideERNS0_15class_name_typeEi
  Referenced from: /usr/local/bin/cufflinks
  Expected in: libboost_serialization-mt.dylib
 in /usr/local/bin/cufflinks
Trace/BPT trap: 5

I keep getting this error every time I try to run cufflinks. This was installed using Homebrew. Someone please help. 

Thanks!

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes #3076.

### CODE REVIEW

**Comment by dpo** [comment]
See #2661.

**Comment by tdsmith** [comment]
Thanks for the link, Dominique. Why is this failing on Mavericks? :(

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
I guess I assert this is a C++ stdlib bug in Xcode 6.

**Pull request closed without merging**
